# -*- coding: utf-8 -*-
# Cartes de révision écrites à la main — BTS CRSA
FILIERE = "bts-crsa"
NIVEAU = "BTS CRSA"

CARTES = {}

# =====================================================================
CARTES["ch01"] = [
dict(t="n", o="§1 Énergie et puissance",
 r="Puissance et énergie : définitions et unités ?",
 v="<b>Puissance P</b> : énergie transférée <b>par unité de temps</b>, en <b>watts</b>.<br><b>Énergie E</b> : quantité totale transférée, en <b>joules</b>."),
dict(t="n", o="§1 Énergie et puissance",
 r="Relation entre E, P et Δt ? Quelles sont les deux combinaisons d'unités cohérentes ?",
 v="<b>E = P × Δt</b><br>P en W et Δt en <b>s</b> → E en <b>J</b>.<br>P en kW et Δt en <b>h</b> → E en <b>kWh</b>."),
dict(t="n", o="§1 Le kilowattheure est une énergie",
 r="Le kWh est-il une puissance ? Que vaut-il en joules ?",
 v="Non, c'est une <b>énergie</b> (puissance × durée). La plaque affiche des kW, la facture des kWh.<br><b>1 kWh = 3,6 MJ</b> = 3,6 × 10<sup>6</sup> J."),
dict(t="n", o="§2 Ordres de grandeur",
 r="Ordres de grandeur : capteur inductif, éclairage d'une travée, moteur de convoyeur, ligne de production, tranche nucléaire ?",
 v="Capteur : <b>~2 W</b> ; éclairage : <b>~150 W</b> ; convoyeur : <b>quelques kW</b> ; ligne : <b>~250 kW</b> ; tranche nucléaire : <b>~900 MW</b>.<br>Ils servent à juger un résultat."),
dict(t="n", o="§3 Le critère du renouvelable",
 r="Quand une ressource énergétique est-elle dite renouvelable ? Exemples ?",
 v="Quand elle <b>se reconstitue à l'échelle d'une vie humaine</b>.<br>Renouvelables : vent, soleil, eau. Non renouvelables : gaz, pétrole, charbon, uranium.<br>Le critère ne dit rien de la pollution ni du coût."),
dict(t="n", o="§4 Conservation de l'énergie",
 r="Bilan de puissance d'une machine (conservation de l'énergie) ?",
 v="<b>P<sub>a</sub> = P<sub>u</sub> + P<sub>p</sub></b><br>Tout ce qui entre ressort, en partie utile, en partie perdu."),
dict(t="n", o="§4 Conservation de l'énergie",
 r="Que sont réellement les « pertes » d'une machine ?",
 v="De l'énergie <b>bien réelle</b>, transférée sous une forme inutile — presque toujours de la <b>chaleur</b> (bobinages, circuit magnétique, roulements)."),
dict(t="n", o="§5 La chaîne d'énergie",
 r="Quelles sont les quatre fonctions de la chaîne d'énergie d'un système automatisé ?",
 v="<b>Alimenter</b> → <b>distribuer</b> → <b>convertir</b> → <b>transmettre</b>. Chacune correspond à un composant réel et a ses pertes."),
dict(t="n", o="§6 Le rendement",
 r="Rendement d'une machine : formule, unité, valeur possible ?",
 v="<b>η = P<sub>u</sub> / P<sub>a</sub></b><br><b>Sans unité</b>, <b>toujours inférieur à 1</b>."),
dict(t="n", o="§6 Le contrôle qui sauve la copie",
 r="Un rendement calculé dépasse 1. Quelles erreurs chercher ?",
 v="P<sub>u</sub> et P<sub>a</sub> <b>inversés</b> ; une <b>puissance confondue avec une énergie</b> ; une <b>conversion</b> oubliée."),
dict(t="n", o="§6 Les rendements se multiplient",
 r="Rendement total d'une chaîne de trois éléments ?",
 v="<b>η<sub>total</sub> = η<sub>1</sub> × η<sub>2</sub> × η<sub>3</sub></b>, toujours <b>inférieur au plus faible</b> des rendements."),
dict(t="n", o="§6 Remonter une chaîne",
 r="On connaît P<sub>u</sub> et η. Comment obtenir P<sub>a</sub> ?",
 v="On <b>divise</b> : <b>P<sub>a</sub> = P<sub>u</sub> / η</b>. Contrôle : P<sub>a</sub> doit être <b>plus grande</b> que P<sub>u</sub>."),
dict(t="n", o="§7 Efficacité",
 r="Définir l'efficacité e d'une machine. Qu'est-ce qui change par rapport au rendement ?",
 v="<b>e = P<sub>utile</sub> / P<sub>fournie</sub></b>. Au dénominateur, seulement l'énergie <b>apportée et payée</b> ; l'énergie prise gratuitement à l'environnement n'y figure pas."),
dict(t="n", o="§7 Pourquoi une efficacité peut dépasser 1",
 r="Une PAC d'efficacité 4 rend 4 kWh pour 1 kWh d'électricité. D'où viennent les 3 kWh ?",
 v="Ils sont <b>prélevés dans l'environnement extérieur</b> et transportés dedans. Rien n'est créé : la conservation <b>n'est pas violée</b>."),
dict(t="n", o="§7 Le réfrigérateur",
 r="Bilan d'une machine frigorifique (PAC, réfrigérateur) ?",
 v="<b>P<sub>chaud</sub> = P<sub>élec</sub> + P<sub>froid</sub></b><br>Ex. : 100 W absorbés, 200 W extraits → <b>300 W</b> rejetés dans la pièce."),
dict(t="n", o="§7 Deux efficacités pour une machine",
 r="Relation entre efficacité en mode chaud et en mode froid ? Pourquoi ?",
 v="<b>e<sub>chaud</sub> = e<sub>froid</sub> + 1</b>, car l'électricité du compresseur se retrouve aussi du côté chaud."),
dict(t="n", o="§7 Vocabulaire constructeur",
 r="Que désignent COP, EER, SCOP, SEER ?",
 v="Des <b>efficacités</b> : COP (chauffage), EER (froid), SCOP et SEER (moyennes saisonnières). Sans unité, elles peuvent dépasser 1."),
dict(t="n", o="§7 Une efficacité n'est pas une constante",
 r="De quoi dépend l'efficacité d'une pompe à chaleur ?",
 v="De l'<b>écart de température</b> entre sources froide et chaude : plus il est grand, plus <b>l'efficacité diminue</b>. Une valeur n'a de sens qu'avec ses deux températures."),
# --- méthodes
dict(t="m", o="§1 Du kilowatt au kilowattheure",
 r="Un appareil de 2 kW fonctionne 3 h. Comment donner l'énergie en kWh puis en J ?",
 v="1. kW et h → kWh : E = 2 × 3 = <b>6 kWh</b>.<br>2. En J : 6 × 3,6 × 10<sup>6</sup> = <b>2,16 × 10<sup>7</sup> J</b>.<br>3. Vérifier que le résultat est bien une énergie (pas des kW)."),
dict(t="m", o="§6 Calculer un rendement",
 r="Moteur : 1190 W absorbés, 731 W utiles. Comment trouver pertes et rendement ?",
 v="1. Pertes : P<sub>p</sub> = P<sub>a</sub> − P<sub>u</sub> = 1190 − 731 = <b>459 W</b>.<br>2. η = P<sub>u</sub> / P<sub>a</sub> = 731 / 1190 = <b>0,61</b>.<br>3. Vérifier η &lt; 1."),
dict(t="m", o="§6 Méthode — Remonter une chaîne",
 r="Comment remonter une chaîne d'énergie de la sortie jusqu'au réseau ?",
 v="1. <b>Partir de la sortie</b> (P<sub>u</sub>).<br>2. Remonter étage par étage en <b>divisant</b> : P<sub>entrée</sub> = P<sub>sortie</sub> / η.<br>3. Contrôler que la puissance <b>augmente</b> en remontant.<br>4. Recouper : P<sub>u</sub>/P<sub>réseau</sub> = produit des η."),
dict(t="m", o="§6 Méthode — Remonter une chaîne",
 r="Convoyeur 860 W ; réducteur 0,85, moteur 0,88, variateur 0,96. Puissance au réseau ?",
 v="860 / 0,85 = 1012 W → 1012 / 0,88 = 1150 W → 1150 / 0,96 = <b>1198 W</b>.<br>Contrôle : 860/1198 = 0,718 = 0,96 × 0,88 × 0,85."),
dict(t="m", o="§7 Méthode — Exploiter une efficacité",
 r="PAC : 12,0 kW à fournir, e = 3,8. Comment trouver la puissance électrique et la part prise dehors ?",
 v="1. Effet utile (chauffer) au numérateur, électricité au dénominateur.<br>2. P<sub>élec</sub> = P<sub>utile</sub> / e = 12,0 / 3,8 = <b>3,16 kW</b>.<br>3. Part prélevée dehors : 12,0 − 3,16 = <b>8,84 kW</b>.<br>4. Fermer le bilan : 3,16 + 8,84 = 12,0."),
]

# =====================================================================
CARTES["ch02"] = [
dict(t="n", o="§1 Produire l'énergie électrique",
 r="Quelle est la fin de chaîne commune à presque toutes les centrales ?",
 v="La source fait tourner une <b>turbine</b>, qui entraîne un <b>alternateur</b> (conversion mécanique → électrique)."),
dict(t="n", o="§1 Produire l'énergie électrique",
 r="Quels moyens produisent l'électricité sans pièce en mouvement ?",
 v="Le <b>photovoltaïque</b> et les <b>piles</b> (dont la pile à combustible)."),
dict(t="n", o="§1 Une éolienne",
 r="Conversions successives dans une éolienne, du vent au réseau ?",
 v="Énergie <b>cinétique</b> du vent → énergie <b>mécanique</b> de rotation (pales, arbre) → énergie <b>électrique</b> (alternateur)."),
dict(t="n", o="§2 Les convertisseurs statiques",
 r="Qu'est-ce qu'un convertisseur statique ?",
 v="Un appareil <b>sans pièce en mouvement</b> qui met en forme l'énergie électrique à l'aide de composants commandés."),
dict(t="n", o="§2 Les quatre noms",
 r="Nommer le convertisseur : AC → DC ; DC → AC ; DC → DC ; AC → AC.",
 v="AC → DC : <b>redresseur</b><br>DC → AC : <b>onduleur</b><br>DC → DC : <b>hacheur</b><br>AC → AC : <b>gradateur</b>"),
dict(t="n", o="§2 Ne pas les confondre",
 r="Redresseur et gradateur partent tous deux du réseau. Qu'est-ce qui les distingue ?",
 v="Redresseur : courant de <b>sens constant</b> (valeur moyenne non nulle), pour un moteur à courant continu ou une batterie.<br>Gradateur : <b>reste alternatif à 50 Hz</b>, découpe les alternances pour régler la puissance."),
dict(t="n", o="§2 Ne pas les confondre",
 r="Onduleur et gradateur fournissent de l'alternatif. Qu'est-ce qui les distingue ?",
 v="Gradateur : part du réseau et garde ses <b>50 Hz</b>.<br>Onduleur : part d'une source <b>continue</b> et fabrique l'alternatif à la <b>fréquence voulue</b> (d'où son rôle dans un variateur)."),
dict(t="n", o="§2 Le hacheur",
 r="Hacheur : que règle le rapport cyclique α ?",
 v="La valeur moyenne de la tension de sortie : <b>⟨u⟩ = α E</b>, donc la vitesse d'un moteur à courant continu."),
dict(t="n", o="§2 Le transformateur n'en fait pas partie",
 r="Pourquoi le transformateur n'est-il pas un convertisseur statique ?",
 v="Il reçoit et rend de l'<b>alternatif</b> : il ne change pas la <b>nature</b> du courant, seulement la <b>valeur</b> de la tension."),
dict(t="n", o="§2 Variateur de vitesse",
 r="Que contient le variateur de vitesse d'un moteur asynchrone alimenté par le réseau ?",
 v="<b>Deux convertisseurs</b> : un <b>redresseur</b> puis un <b>onduleur</b>. Changer la fréquence, c'est changer la vitesse."),
dict(t="n", o="§3 Convertisseurs électromécaniques",
 r="Citer les convertisseurs électromécaniques. Comment appelle-t-on la machine qui fonctionne dans l'autre sens ?",
 v="Moteur à <b>courant continu</b>, moteur <b>asynchrone</b>, moteur <b>synchrone</b> : électrique → mécanique.<br>Mécanique → électrique : <b>alternateur</b> (ou génératrice)."),
dict(t="n", o="§5 On ne stocke pas l'électricité",
 r="Sous quelles formes stocke-t-on l'énergie électrique ?",
 v="On la convertit en énergie <b>chimique</b> (batterie), <b>électrostatique</b> (condensateur), <b>mécanique</b> (volant), <b>hydraulique</b> (STEP), <b>électromagnétique</b> ou <b>thermique</b>, puis on refait le chemin inverse."),
dict(t="n", o="§5 L'ampère-heure n'est pas une énergie",
 r="Que représente l'indication « 40 Ah » d'une batterie ? Comment obtenir son énergie ?",
 v="Une <b>charge Q</b>, pas une énergie.<br><b>E = U × Q</b> : 24 V × 40 Ah = <b>960 Wh</b>."),
dict(t="n", o="§5 Stocker l'énergie",
 r="Énergie stockée par un condensateur de capacité C chargé sous U ?",
 v="<b>E = ½ C U²</b> (C en F, U en V, E en J). L'énergie varie comme le <b>carré</b> de la tension."),
dict(t="n", o="§6 Rendement d'un cycle de stockage",
 r="Pourquoi les pertes d'un stockage « comptent deux fois » ?",
 v="Il y a <b>deux conversions</b> (charge puis décharge) : les rendements se <b>multiplient</b>. 90 % dans chaque sens → 0,90 × 0,90 = <b>81 %</b> sur le cycle."),
dict(t="n", o="§6 À l'oral",
 r="Pourquoi choisir un supercondensateur plutôt qu'une batterie, alors qu'il stocke bien moins ?",
 v="Pour la <b>vitesse</b> : il rend son énergie en une fraction de seconde. On choisit un stockage sur l'<b>usage</b> — autonomie (batterie) ou <b>pic de puissance</b> (supercondensateur)."),
# --- méthodes
dict(t="m", o="§4 Méthode — Choisir un convertisseur",
 r="Comment choisir le convertisseur entre une source et une machine ?",
 v="1. <b>Source</b> : continue (batterie, PV) ou alternative (réseau) ?<br>2. <b>Machine</b> : MCC → continu ; asynchrone/synchrone → alternatif.<br>3. <b>Nommer</b> le convertisseur avec le tableau des quatre.<br>4. Vérifier s'il en faut <b>deux</b> (vitesse variable depuis le réseau : redresseur + onduleur)."),
dict(t="m", o="§4 Méthode — Choisir un convertisseur",
 r="Chariot : batterie 24 V et moteur asynchrone triphasé. Quel convertisseur ?",
 v="Source <b>continue</b>, machine <b>alternative</b> → un <b>onduleur</b>."),
dict(t="m", o="§5 Lire une plaque de batterie",
 r="Batterie 24 V, 40 Ah, récepteur de 240 W. Comment trouver l'énergie et l'autonomie ?",
 v="1. E = U × Q = 24 × 40 = <b>960 Wh</b> (× 3600 → 3,46 × 10<sup>6</sup> J).<br>2. Autonomie : Δt = E / P = 960 / 240 = <b>4,0 h</b>."),
dict(t="m", o="§6 Rendement d'un cycle",
 r="Comment calculer l'énergie récupérée après un cycle de stockage ?",
 v="1. Rendement du cycle : η<sub>cycle</sub> = η<sub>charge</sub> × η<sub>décharge</sub>.<br>2. E<sub>restituée</sub> = η<sub>cycle</sub> × E<sub>fournie à la charge</sub>.<br>3. Contrôle : E<sub>restituée</sub> &lt; E<sub>fournie</sub>."),
]

# =====================================================================
# ch00 placé en tête de collection (ordre d'affichage)
CARTES = {"ch00": None, **CARTES}
CARTES["ch00"] = [
dict(t="n", o="§1 Grandeur, valeur et unité",
 r="À quelle condition un résultat sort-il automatiquement dans la bonne unité ?",
 v="Avoir converti <b>toutes les données en unités SI avant de calculer</b>. Le tableau des unités dérivées se <b>consulte</b>, il ne s'apprend pas."),
dict(t="n", o="§1 La règle qui donne le signe",
 r="On convertit vers une unité plus <b>petite</b>. Le nombre augmente ou diminue ? Et l'exposant ?",
 v="Le découpage est plus fin, il en faut <b>davantage</b> : le nombre <b>augmente</b>, exposant <b>positif</b>.<br>Vers une unité plus grande : le nombre diminue, exposant négatif."),
dict(t="n", o="§1 Le piège du kilogramme",
 r="Sur quelle unité s'appliquent les préfixes pour une masse ?",
 v="Sur le <b>gramme</b>, jamais sur le kilogramme : le kg est la seule unité de base qui porte déjà un préfixe."),
dict(t="n", o="§2 Les puissances de dix",
 r="Que valent 10<sup>a</sup> × 10<sup>b</sup> et 10<sup>a</sup> / 10<sup>b</sup> ?",
 v="10<sup>a</sup> × 10<sup>b</sup> = <b>10<sup>a+b</sup></b><br>10<sup>a</sup> / 10<sup>b</sup> = <b>10<sup>a−b</sup></b>"),
dict(t="n", o="§2 L'écriture scientifique",
 r="Quelle est la forme d'une écriture scientifique ?",
 v="<b>N = a × 10<sup>n</sup></b> avec <b>1 ≤ a &lt; 10</b>.<br>45 × 10<sup>5</sup> ou 0,45 × 10<sup>7</sup> ne sont pas des écritures scientifiques."),
dict(t="n", o="§2 Même question que pour les conversions",
 r="Écriture scientifique : comment choisir le signe de l'exposant ?",
 v="Se demander si le nombre doit <b>grandir</b> (exposant <b>positif</b>) ou <b>rapetisser</b> (exposant <b>négatif</b>) pour revenir au nombre de départ."),
dict(t="n", o="§3 La règle du plus faible",
 r="Chiffres significatifs d'un produit ou quotient ? d'une somme ou différence ?",
 v="Produit, quotient : autant que la <b>donnée la moins précise</b>.<br>Somme, différence : le <b>rang du dernier chiffre significatif</b> (les décimales) commande.<br>On n'arrondit <b>qu'à la fin</b>."),
dict(t="n", o="§3 Pourquoi 1200 est ambigu",
 r="Combien de chiffres significatifs a 1200 ? Comment lever le doute ?",
 v="2, 3 ou 4 : on ne sait pas. Seule l'<b>écriture scientifique</b> le dit : 1,2 × 10<sup>3</sup> ; 1,20 × 10<sup>3</sup> ; 1,200 × 10<sup>3</sup>."),
dict(t="n", o="§3 Valeurs nominales",
 r="Compte-t-on les chiffres significatifs de « commande en 24 V » ou « réseau d'air à 6 bar » ?",
 v="Non : ce sont des valeurs <b>nominales</b> (noms de catégorie), pas des mesures."),
dict(t="n", o="§3 La soustraction détruit des chiffres",
 r="Pourquoi soustraire deux nombres voisins fait-il perdre de la précision ?",
 v="Le résultat garde le rang de la donnée la moins précise : 1,35 × 10<sup>5</sup> − 1,013 × 10<sup>5</sup> = <b>3,4 × 10<sup>4</sup> Pa</b>, seulement 2 chiffres significatifs."),
dict(t="n", o="§4 Convertir : compter les crans",
 r="Préfixes de kilo à milli, puis au-delà ? Que vaut un cran ?",
 v="Un cran = <b>un facteur 10</b>.<br>k, h, da, unité, d, c, m.<br>Puis par <b>3 crans</b> : M, G, T ; µ, n, p (« Mille Microbes Nagent Profondément »)."),
dict(t="n", o="§5 Le piège des unités composées",
 r="Que valent 1 cm² en m², et 1 L en m³ ?",
 v="<b>1 cm² = 10<sup>−4</sup> m²</b><br><b>1 L = 1 dm³ = 10<sup>−3</sup> m³</b>"),
dict(t="n", o="§5 Conversions du métier",
 r="1 bar en Pa ? 1 L/min en m³/s ? 1 tr/min en rad/s ? T (K) en fonction de θ (°C) ?",
 v="<b>1 bar = 10<sup>5</sup> Pa</b> ; <b>1 L/min = 1,67 × 10<sup>−5</sup> m³/s</b> ; <b>1 tr/min = 2π/60 rad/s</b> ; <b>T = θ + 273</b>."),
dict(t="n", o="§6 Durées",
 r="Combien valent 1,5 h et 2,25 h ? Comment passe-t-on des km/h aux m/s ?",
 v="1,5 h = <b>1 h 30 min</b> ; 2,25 h = <b>2 h 15 min</b>.<br>km/h → m/s : <b>diviser par 3,6</b>."),
dict(t="n", o="§7 Proportionnalité",
 r="Deux grandeurs sont proportionnelles si… ? Et sur un graphique ?",
 v="Leur <b>quotient est constant</b>.<br>Graphique : <b>droite passant par l'origine</b> — les deux conditions sont nécessaires."),
dict(t="n", o="§9 Lire une droite",
 r="Formule de la pente ? Avec quelle unité ? Quels points choisir ?",
 v="<b>a = (y<sub>2</sub> − y<sub>1</sub>) / (x<sub>2</sub> − x<sub>1</sub>)</b>, unité de y / unité de x, sur <b>deux points éloignés</b>."),
dict(t="n", o="§9 La règle de trois",
 r="Quand a-t-on le droit d'utiliser une règle de trois sur une droite ?",
 v="Seulement si la droite <b>passe par l'origine</b>. Avec une ordonnée à l'origine (décalage de capteur, tare), doubler x ne double pas y."),
dict(t="n", o="§10 Transformer une formule",
 r="Sur quel principe repose la transformation d'une formule ?",
 v="Faire <b>la même opération sur les deux membres</b>. Seule méthode qui marche aussi avec une somme."),
dict(t="n", o="§11 Trigonométrie",
 r="Dans un triangle rectangle, que valent cos α, sin α, tan α ?",
 v="<b>cos α = adjacent/hypoténuse</b> ; <b>sin α = opposé/hypoténuse</b> ; <b>tan α = opposé/adjacent</b>.<br>Vérifier le mode <b>degrés</b>."),
dict(t="n", o="§12 Comparer mesure et prévision",
 r="Comment juger l'accord entre une mesure et une prévision ?",
 v="Par l'<b>écart relatif</b> |mesure − prévision| / prévision × 100. En dessous de <b>5 %</b> : compatibles. Un écart de zéro doit inquiéter (calcul recopié)."),
# --- méthodes
dict(t="m", o="§2 Méthode 1",
 r="Comment écrire 4 500 000 Pa et 0,000072 m en écriture scientifique ?",
 v="1. Écrire le nombre entre 1 et 10 : 4,5 et 7,2.<br>2. Compter les rangs pour revenir au nombre : 6 en agrandissant, 5 en rapetissant.<br>3. <b>4,5 × 10<sup>6</sup> Pa</b> ; <b>7,2 × 10<sup>−5</sup> m</b>."),
dict(t="m", o="§3 Méthode 2",
 r="Vérin : S = 38,5 cm², p = 125 bar. Comment calculer F = p S au bon nombre de chiffres ?",
 v="1. SI : S = 38,5 × 10<sup>−4</sup> m² ; p = 1,25 × 10<sup>7</sup> Pa.<br>2. Calculer sans arrondir : 48 125 N.<br>3. 3 c.s. → <b>F = 4,81 × 10<sup>4</sup> N</b>.<br>4. Contrôler l'ordre de grandeur."),
dict(t="m", o="§6 Méthode 3",
 r="Moteur à 1450 tr/min, couple 141 N·m. Comment calculer la puissance ?",
 v="1. ω = 1450 × 2π/60 = <b>151,8 rad/s</b>.<br>2. P = C ω = 141 × 151,8 ≈ 21 400 W.<br>3. <b>P ≈ 21,4 kW</b> (moteur normalisé 22 kW).<br>Sans conversion : 9,55 fois trop."),
dict(t="m", o="§8 Méthode 4",
 r="6,0 m de flexible pèsent 5,4 kg. Comment trouver la masse de 14 m ?",
 v="1. Vérifier la proportionnalité.<br>2. <b>Passer à l'unité</b> : 1 m → 0,90 kg.<br>3. 14 × 0,90 = <b>12,6 kg</b>.<br>4. Contrôler."),
dict(t="m", o="§10 Méthode 5",
 r="Comment isoler Δθ dans Q = m c Δθ ?",
 v="1. Δθ est multiplié par m et c.<br>2. <b>Diviser les deux membres</b> par m c.<br>3. <b>Δθ = Q / (m c)</b>.<br>4. Contrôler l'unité."),
dict(t="m", o="§10 Quand la formule contient une somme",
 r="Comment isoler h dans p<sub>A</sub> = p<sub>B</sub> + ρ g h ?",
 v="1. <b>Déplacer le terme entier</b> : p<sub>A</sub> − p<sub>B</sub> = ρ g h.<br>2. <b>Diviser</b> par ρ g : h = (p<sub>A</sub> − p<sub>B</sub>)/(ρ g)."),
dict(t="m", o="§12 Méthode 6",
 r="Comment conclure sur une mesure comparée à une prévision ?",
 v="1. Calculer la valeur <b>prévue</b>.<br>2. Relever la valeur <b>mesurée</b> avec son unité.<br>3. Calculer l'<b>écart relatif</b> en %.<br>4. <b>Conclure par une phrase</b> (compatible ou non, et pourquoi)."),
]

# =====================================================================
CARTES["ch03"] = [
dict(t="n", o="§1 Chauffer sans changer d'état",
 r="Énergie pour échauffer une masse m sans changement d'état ? Que représente c ?",
 v="<b>Q = m c Δθ</b>. c, capacité thermique massique : énergie pour élever de 1 degré 1 kg du corps.<br>Eau : <b>c = 4185 J·kg<sup>−1</sup>·K<sup>−1</sup></b>."),
dict(t="n", o="§1 Le bilan d'un calorimètre",
 r="Comment écrire le bilan thermique dans une enceinte isolée ?",
 v="<b>Σ Q<sub>i</sub> = 0</b> (ce que l'un cède, l'autre le reçoit). La somme nulle évite les erreurs de signe."),
dict(t="n", o="§2 Les changements d'état",
 r="Énergie d'un changement d'état ? Chaleurs latentes de l'eau ?",
 v="<b>Q = m L</b> (L en J/kg).<br>Fusion : <b>3,34 × 10<sup>5</sup> J/kg</b> ; vaporisation : <b>2,26 × 10<sup>6</sup> J/kg</b> (7 fois plus)."),
dict(t="n", o="§2 Jamais les deux formules sur le même palier",
 r="Pourquoi ne peut-on pas utiliser m c Δθ pendant un changement d'état ?",
 v="La <b>température ne bouge pas</b> (Δθ = 0) : c'est <b>Q = m L</b> qui s'applique. Glace → eau chaude : deux étapes séparées."),
dict(t="n", o="§3 Le diagramme de phases",
 r="Comment lit-on le diagramme de phases de l'eau ? Que signifie un point sur une courbe ?",
 v="Température en <b>abscisse</b>, pression en <b>ordonnée</b> : on lit le domaine. Sur une courbe, <b>deux états coexistent</b>."),
dict(t="n", o="§3 100 °C n'est pas universel",
 r="L'eau bout-elle toujours à 100 °C ?",
 v="Non : seulement à la pression atmosphérique au niveau de la mer. <b>En altitude</b> (pression plus basse) elle bout <b>plus tôt</b> ; dans une chaudière sous pression, <b>plus tard</b>."),
dict(t="n", o="§4 Les trois modes de transfert",
 r="Conduction, convection, rayonnement : comment les reconnaître ?",
 v="<b>Conduction</b> : de proche en proche dans la matière.<br><b>Convection</b> : par déplacement d'un fluide.<br><b>Rayonnement</b> : par ondes, sans support (traverse le vide)."),
dict(t="n", o="§5 Le flux à travers une paroi",
 r="Flux thermique à travers une paroi de résistance surfacique R ? Nature du résultat ?",
 v="<b>φ = S × Δθ / R</b> (R en m²·K/W). φ est une <b>puissance</b> en W ; × durée → énergie."),
dict(t="n", o="§5 Les couches s'additionnent",
 r="Paroi multicouche : comment combiner les résistances ? Effet d'une grande résistance ?",
 v="<b>R<sub>tot</sub> = R<sub>1</sub> + R<sub>2</sub> + R<sub>3</sub></b>. Plus R est grande, <b>moins la chaleur passe</b>."),
dict(t="n", o="§5 Un écart ne se convertit pas",
 r="Faut-il ajouter 273 à un écart de température ?",
 v="<b>Non</b> : un écart vaut autant en K qu'en °C. Seule une température se convertit (T = θ + 273)."),
dict(t="n", o="§6 Les machines thermiques",
 r="Moteur thermique, machine frigorifique, pompe à chaleur : qu'est-ce qui les distingue ?",
 v="<b>Ce qu'on cherche</b> : du travail (moteur), refroidir la source froide (frigo), chauffer la source chaude (PAC). Frigo et PAC sont <b>la même machine</b>."),
dict(t="n", o="§6 La conservation décide de tout",
 r="Machine qui prend 4,5 kW à la source froide et absorbe 1,8 kW. Chaleur rejetée et efficacité de chauffage ?",
 v="Q<sub>chaud</sub> = 4,5 + 1,8 = <b>6,3 kW</b>.<br>e = 6,3/1,8 = <b>3,5</b> (&gt; 1 car la machine déplace de la chaleur)."),
# --- méthodes
dict(t="m", o="§2 Deux étapes, deux formules",
 r="Comment calculer l'énergie pour transformer 2,0 kg de glace à 0 °C en eau à 40 °C ?",
 v="1. Fusion : Q<sub>1</sub> = m L<sub>f</sub> = 2,0 × 3,34 × 10<sup>5</sup> = 6,68 × 10<sup>5</sup> J.<br>2. Échauffement : Q<sub>2</sub> = m c Δθ = 2,0 × 4185 × 40 = 3,35 × 10<sup>5</sup> J.<br>3. Q = Q<sub>1</sub> + Q<sub>2</sub> ≈ <b>1,0 × 10<sup>6</sup> J</b>."),
dict(t="m", o="§1 Le bilan d'un calorimètre",
 r="Comment trouver la température finale de deux corps mis en contact dans un calorimètre ?",
 v="1. Écrire Q<sub>i</sub> = m<sub>i</sub> c<sub>i</sub> (θ<sub>f</sub> − θ<sub>i</sub>) pour chaque corps.<br>2. Poser <b>Σ Q<sub>i</sub> = 0</b>.<br>3. Isoler θ<sub>f</sub>.<br>4. Vérifier : θ<sub>f</sub> entre les températures de départ."),
dict(t="m", o="§5 Méthode — Calculer une perte thermique",
 r="Bac à 70 °C, atelier à 18 °C, S = 12 m², couches 0,02 + 2,40 + 0,08 m²·K/W. Comment trouver la perte sur 8 h ?",
 v="1. R = 0,02 + 2,40 + 0,08 = <b>2,50</b> m²·K/W.<br>2. Δθ = 52 K (sans convertir).<br>3. φ = S Δθ / R = 12 × 52/2,50 = <b>250 W</b>.<br>4. Sur 8 h : 0,250 × 8 = <b>2,0 kWh</b>."),
]

# =====================================================================
CARTES["ch04"] = [
dict(t="n", o="§1 Le bilan des forces",
 r="Par quoi commence tout calcul de mécanique ? Comment savoir si une force existe ?",
 v="Par le <b>bilan des forces</b>. Une force est toujours <b>exercée par un corps identifiable</b> ; « force d'inertie » ou « d'élan » n'existent pas."),
dict(t="n", o="§2 Principe fondamental de la dynamique",
 r="Énoncer le PFD. Que fixe la somme des forces ?",
 v="<b>Σ F⃗ = m a⃗</b>. La somme des forces impose l'<b>accélération</b>, pas la vitesse."),
dict(t="n", o="§2 Le cas le plus utile",
 r="Solide immobile ou à vitesse constante : que vaut la somme des forces ?",
 v="a = 0, donc <b>Σ F⃗ = 0⃗</b> : la <b>même équation</b> dans les deux cas."),
dict(t="n", o="§2 Démarrer coûte plus cher",
 r="Pourquoi est-ce le démarrage qui dimensionne le moteur d'un chariot ?",
 v="Au démarrage il faut <b>F = m a + f</b> (accélérer + vaincre les frottements) ; lancé, seulement f."),
dict(t="n", o="§3 Le cas de la rotation",
 r="PFD en rotation ? Que deviennent masse, accélération et force ?",
 v="<b>Σ M = J ω̇</b>. Masse → moment d'inertie <b>J</b> (toujours donné) ; accélération → <b>ω̇</b> ; force → moment <b>M = F × d</b>."),
dict(t="n", o="§3 Le cas de la rotation",
 r="Dans quelle unité doit être ω ? Conversion depuis N (tr/min) ?",
 v="En <b>rad/s</b> : <b>ω = N × 2π / 60</b>."),
dict(t="n", o="§4 Le travail",
 r="Travail d'une force : formule et signe ?",
 v="<b>W = F d cos α</b>.<br>Positif : <b>moteur</b> ; négatif : <b>résistant</b> ; nul : force <b>perpendiculaire</b> au déplacement."),
dict(t="n", o="§4 La puissance",
 r="Trois écritures de la puissance mécanique ?",
 v="<b>P = W / Δt = F v = C ω</b>"),
dict(t="n", o="§5 Théorème de l'énergie cinétique",
 r="Énoncer le théorème de l'énergie cinétique. Énergie cinétique en translation et en rotation ?",
 v="<b>E<sub>c2</sub> − E<sub>c1</sub> = Σ W</b> (ignore la durée et la forme du trajet).<br>Translation : <b>½ m v²</b> ; rotation : <b>½ J ω²</b>."),
dict(t="n", o="§5 Le carré de la vitesse",
 r="Doubler la vitesse d'un chariot : effet sur la distance d'arrêt ?",
 v="Elle est <b>multipliée par 4</b> (E<sub>c</sub> en v²)."),
dict(t="n", o="§6 L'énergie mécanique",
 r="Quand l'énergie mécanique se conserve-t-elle ? Sinon, que vaut sa perte ?",
 v="<b>E<sub>m</sub> = E<sub>c</sub> + E<sub>p</sub></b> se conserve <b>sans frottement</b>. Sinon elle diminue, et la perte égale le <b>travail des frottements</b>."),
dict(t="n", o="§7 Choisir le bon outil",
 r="Quel outil pour une accélération ? une distance ou une force ? Quand utiliser la conservation ?",
 v="Accélération : <b>PFD</b>.<br>Distance ou force : <b>théorème de l'énergie cinétique</b>.<br>Conservation de E<sub>m</sub> : seulement <b>sans frottement</b>."),
# --- méthodes
dict(t="m", o="§2 Démarrer coûte plus cher que rouler",
 r="Chariot de 600 kg, frottements 180 N, accélération 0,40 m/s². Comment trouver la force de traction ?",
 v="1. Bilan des forces, axe du mouvement.<br>2. PFD : F − f = m a.<br>3. F = m a + f = 600 × 0,40 + 180 = <b>420 N</b>.<br>4. Une fois lancé : F = f = 180 N."),
dict(t="m", o="§5 Méthode — Distance de freinage",
 r="Chariot de 800 kg à 1,8 m/s freiné par 650 N. Comment trouver la distance d'arrêt ?",
 v="1. E<sub>c</sub> départ = ½ × 800 × 1,8² = 1296 J ; arrivée : 0.<br>2. Théorème : 0 − 1296 = W.<br>3. W = −F d.<br>4. d = 1296/650 = <b>2,0 m</b>."),
dict(t="m", o="§6 Mesurer un frottement",
 r="Comment déterminer une force de frottement à partir d'une perte d'énergie mécanique ?",
 v="1. Calculer E<sub>m</sub> au départ (m g h) et à l'arrivée (½ m v² mesurée).<br>2. Perte ΔE<sub>m</sub> = travail des frottements.<br>3. <b>f = |ΔE<sub>m</sub>| / d</b> (d = distance parcourue)."),
]

# =====================================================================
CARTES["ch05"] = [
dict(t="n", o="§1 Compressible ou incompressible",
 r="Qu'est-ce qu'un fluide incompressible ? Exemples ?",
 v="Un fluide dont la <b>masse volumique reste constante</b> quelle que soit la pression : tous les <b>liquides</b> en pratique ; <b>pas les gaz</b> (ni l'air comprimé)."),
dict(t="n", o="§2 La pression",
 r="Définition de la pression ? Unités ? 1 bar en Pa ?",
 v="<b>p = F / S</b> (Pa = N/m²).<br><b>1 bar = 10<sup>5</sup> Pa</b> ≈ 10 m d'eau."),
dict(t="n", o="§2 Pression absolue et relative",
 r="Différence entre pression absolue et pression relative ?",
 v="<b>Absolue</b> : comptée depuis le vide.<br><b>Relative</b> : comptée depuis la pression atmosphérique (0 à l'air libre) — celle des manomètres d'atelier."),
dict(t="n", o="§3 Principe fondamental de l'hydrostatique",
 r="Énoncer le principe fondamental de l'hydrostatique.",
 v="<b>p<sub>B</sub> − p<sub>A</sub> = ρ g h</b>, h différence d'altitude (B plus bas que A), résultat en Pa."),
dict(t="n", o="§3 Ce qui n'intervient pas",
 r="La pression au fond d'un récipient dépend-elle de sa forme ou du volume de liquide ?",
 v="<b>Non</b> : seule compte la <b>hauteur</b> de liquide."),
dict(t="n", o="§4 Les débits",
 r="Débit volumique et débit massique : formules et unités ?",
 v="<b>Q<sub>v</sub> = S × v</b> en m³/s.<br><b>Q<sub>m</sub> = ρ × Q<sub>v</sub></b> en kg/s.<br>1 m³/h = 2,78 × 10<sup>−4</sup> m³/s."),
dict(t="n", o="§5 L'équation de continuité",
 r="Énoncer l'équation de continuité. Si la section diminue ?",
 v="<b>S<sub>1</sub> v<sub>1</sub> = S<sub>2</sub> v<sub>2</sub></b> (le débit se conserve). Section plus petite → vitesse <b>plus grande</b>."),
dict(t="n", o="§5 Le piège du diamètre",
 r="Si le diamètre d'une conduite est divisé par 2, que devient la vitesse ?",
 v="Elle est <b>multipliée par 4</b> : S = π d²/4 varie comme le carré du diamètre."),
dict(t="n", o="§6 Le théorème de Bernoulli",
 r="Énoncer le théorème de Bernoulli. Conditions ?",
 v="<b>½ ρ v² + ρ g z + p = constante</b> le long d'un écoulement <b>permanent</b> de fluide <b>parfait incompressible</b>.<br>Termes de vitesse, d'altitude, de pression."),
dict(t="n", o="§7 La vidange",
 r="Vitesse de vidange d'un bac ouvert par un orifice à l'air libre ? Dépend-elle du liquide ?",
 v="<b>v = √(2 g h)</b>, <b>indépendante de ρ</b>. Le débit diminue quand h baisse : le débit initial est le maximum."),
dict(t="n", o="§8 Choisir le bon outil",
 r="Quel outil pour un fluide au repos ? Pour une vitesse en écoulement ? Pour une pression en écoulement ?",
 v="Au repos : <b>hydrostatique</b>.<br>Vitesse : <b>continuité</b>.<br>Pression : <b>Bernoulli</b>."),
# --- méthodes
dict(t="m", o="§2 L'erreur la plus coûteuse",
 r="Vérin de 63 mm de diamètre sous 120 bar. Comment calculer la force ?",
 v="1. S = π d²/4 = π × 0,063²/4 = 3,12 × 10<sup>−3</sup> m².<br>2. p = 120 × 10<sup>5</sup> Pa.<br>3. F = p S ≈ <b>37 kN</b>.<br>Oublier la conversion bar → Pa : facteur 100 000."),
dict(t="m", o="§3 Un bassin de traitement",
 r="Comment calculer la pression relative puis absolue sous 2,5 m d'eau ?",
 v="1. p<sub>rel</sub> = ρ g h = 1000 × 9,81 × 2,5 = <b>2,45 × 10<sup>4</sup> Pa</b> (0,25 bar).<br>2. p<sub>abs</sub> = p<sub>atm</sub> + p<sub>rel</sub> = 1,013 × 10<sup>5</sup> + 2,45 × 10<sup>4</sup> = <b>1,26 × 10<sup>5</sup> Pa</b>."),
dict(t="m", o="§6 Méthode — Appliquer Bernoulli",
 r="Comment appliquer le théorème de Bernoulli ?",
 v="1. <b>Choisir deux points</b> (le plus connu, celui de l'inconnue).<br>2. Écrire les <b>six termes</b>.<br>3. <b>Simplifier</b> : horizontal → ρgz disparaît ; air libre → p s'élimine ; grand bac → v ≈ 0.<br>4. Isoler l'inconnue."),
dict(t="m", o="§5 L'équation de continuité",
 r="Débit de 3,6 m³/h dans une conduite de 25 mm puis de 12,5 mm. Comment trouver les vitesses ?",
 v="1. Q<sub>v</sub> = 3,6/3600 = 1,0 × 10<sup>−3</sup> m³/s.<br>2. v<sub>1</sub> = Q<sub>v</sub>/S<sub>1</sub> avec S = π d²/4.<br>3. Diamètre ÷ 2 → <b>v<sub>2</sub> = 4 v<sub>1</sub></b>."),
]

# =====================================================================
CARTES["ch06"] = [
dict(t="n", o="§1 La viscosité",
 r="Que mesure la viscosité ? Viscosité dynamique et cinématique : symboles et unités ?",
 v="La <b>résistance du fluide à l'écoulement</b>.<br>Dynamique <b>μ</b> en Pa·s ; cinématique <b>ν = μ/ρ</b> en <b>m²/s</b>."),
dict(t="n", o="§1 Viscosité et température",
 r="Comment la viscosité d'une huile varie-t-elle avec la température ? Conséquence ?",
 v="Elle <b>augmente fortement à froid</b> (VG 46 : 5,5 fois plus visqueuse à 10 °C qu'à 40 °C). Un circuit hydraulique peine au démarrage : on préchauffe l'huile."),
dict(t="n", o="§2 Le nombre de Reynolds",
 r="Formule du nombre de Reynolds ? Unité ?",
 v="<b>Re = v d / ν</b>, <b>sans unité</b>."),
dict(t="n", o="§2 Les deux régimes",
 r="Quel régime pour Re &lt; 2000 ? Re &gt; 4000 ?",
 v="Re &lt; 2000 : <b>laminaire</b> (filets parallèles).<br>Re &gt; 4000 : <b>turbulent</b> (tourbillons)."),
dict(t="n", o="§3 Bernoulli corrigé",
 r="Où place-t-on le terme de pertes de charge dans Bernoulli ? Quel est son signe ?",
 v="Δp<sub>pertes</sub> est <b>toujours positif</b> et se place <b>du côté de l'arrivée</b> : le fluide perd de l'énergie en chemin."),
dict(t="n", o="§3 Deux familles de pertes",
 r="Pertes régulières et pertes singulières : différence ?",
 v="<b>Régulières</b> : le long des conduites droites (frottement sur les parois).<br><b>Singulières</b> : aux accidents (coude, vanne, rétrécissement, té). Elles s'additionnent."),
dict(t="n", o="§4 Les pertes régulières",
 r="Formule des pertes de charge régulières ? Que vaut λ en laminaire ?",
 v="<b>Δp = λ (L/D) ½ ρ v²</b>, λ sans unité.<br>Laminaire : <b>λ = 64 / Re</b> ; turbulent : abaque (donné)."),
dict(t="n", o="§5 Les pertes singulières",
 r="Formule des pertes de charge singulières ?",
 v="<b>Δp = (Σ K) ½ ρ v²</b>, coefficients K sans unité, donnés, qui <b>s'additionnent</b>."),
dict(t="n", o="§6 Le diamètre, levier principal",
 r="À débit imposé, en laminaire, comment la perte de charge dépend-elle de D et de L ?",
 v="Comme <b>1/D<sup>4</sup></b> et comme <b>L</b>. Le <b>diamètre</b> est le levier le plus efficace (+40 % de D → pertes ÷ 4)."),
dict(t="n", o="§6 Débit et pertes",
 r="Comment les pertes de charge suivent-elles le débit en laminaire ? en turbulent ?",
 v="Laminaire : comme le <b>débit</b>. Turbulent : comme son <b>carré</b>."),
dict(t="n", o="§7 La pompe",
 r="Que doit fournir une pompe ? Puissance hydraulique ?",
 v="La somme : <b>dénivelé + pertes régulières + pertes singulières</b>.<br><b>P<sub>hyd</sub> = Δp × Q<sub>v</sub></b> ; puissance absorbée = P<sub>hyd</sub> / η."),
# --- méthodes
dict(t="m", o="§4 Méthode — Perte de charge régulière",
 r="Comment calculer une perte de charge régulière ?",
 v="1. <b>Vitesse</b> : v = Q<sub>v</sub>/S (débit en m³/s).<br>2. <b>Reynolds</b> et <b>nommer le régime</b> (jamais facultatif).<br>3. <b>λ</b> : 64/Re en laminaire, abaque en turbulent.<br>4. Appliquer Δp = λ (L/D) ½ρv², convertir en bar."),
dict(t="m", o="§2 Deux fluides, deux régimes",
 r="Huile (ν = 46 × 10<sup>−6</sup> m²/s) à 0,85 m/s dans 12 mm. Comment trouver le régime ?",
 v="1. Convertir d = 0,012 m.<br>2. Re = v d / ν = 0,85 × 0,012 / 46 × 10<sup>−6</sup> ≈ <b>222</b>.<br>3. Re &lt; 2000 → <b>laminaire</b>."),
dict(t="m", o="§7 Méthode — Dimensionner une pompe",
 r="Comment dimensionner une pompe ?",
 v="1. <b>Additionner</b> dénivelé (ρgh), pertes régulières, pertes singulières → Δp<sub>pompe</sub>.<br>2. <b>P<sub>hyd</sub> = Δp × Q<sub>v</sub></b>.<br>3. Diviser par le <b>rendement</b>.<br>4. <b>Comparer les postes</b> pour savoir où agir."),
]

# =====================================================================
CARTES["ch07"] = [
dict(t="n", o="§1 Tension simple, tension composée",
 r="Tension simple V et tension composée U : entre quels conducteurs ? Relation ?",
 v="<b>V</b> : entre une <b>phase et le neutre</b>.<br><b>U</b> : entre <b>deux phases</b>.<br><b>U = √3 V</b> (réseau 230/400 V)."),
dict(t="n", o="§1 Un réseau se nomme par ses deux tensions",
 r="Comment lire l'indication « 230/400 V » d'un réseau ?",
 v="<b>Simple / composée</b> : V = 230 V, U = 400 V."),
dict(t="n", o="§2 Étoile ou triangle",
 r="Quelle tension voit un récepteur couplé en étoile ? en triangle ?",
 v="<b>Étoile</b> : la tension simple <b>V</b> (et J = I).<br><b>Triangle</b> : la tension composée <b>U</b> (et J = I/√3)."),
dict(t="n", o="§2 Courants",
 r="Différence entre courant de ligne I et courant de phase J ?",
 v="<b>I</b> circule dans le <b>câble d'alimentation</b> ; <b>J</b> dans le <b>récepteur</b>. Étoile : J = I ; triangle : J = I/√3."),
dict(t="n", o="§2 L'erreur de couplage",
 r="Que se passe-t-il si un récepteur prévu en étoile est couplé en triangle ?",
 v="Sa tension est × √3, sa puissance × <b>3</b> : il grille. Le couplage se vérifie <b>avant</b> la mise sous tension."),
dict(t="n", o="§3 Les trois puissances",
 r="Puissances active, réactive, apparente : unités et rôle ?",
 v="<b>P</b> (W) : celle qui <b>travaille</b> et qu'on paie.<br><b>Q</b> (var) : allers-retours sans travailler.<br><b>S</b> (VA) : celle que voient <b>câbles et disjoncteur</b>."),
dict(t="n", o="§3 Les trois puissances",
 r="Formules des puissances en triphasé équilibré ?",
 v="<b>S = √3 U I</b> ; <b>P = S cos φ</b> ; <b>Q = S sin φ</b> ; Q = P tan φ."),
dict(t="n", o="§3 Facteur de puissance",
 r="Que représente cos φ ? Valeurs typiques ?",
 v="<b>cos φ = P / S</b> : la fraction du courant qui travaille. <b>1</b> pour un résistif, ≈ <b>0,8</b> pour un moteur asynchrone en charge."),
dict(t="n", o="§3 On paie P, on dimensionne sur S",
 r="Pourquoi un mauvais facteur de puissance coûte-t-il cher ?",
 v="On <b>paie P</b>, mais câbles et disjoncteurs se <b>dimensionnent sur S</b> (le courant). Mauvais cos φ → plus de courant → installation plus chère."),
dict(t="n", o="§4 Le bilan de puissances",
 r="Bilan de plusieurs récepteurs : qu'est-ce qui s'additionne ?",
 v="<b>P</b> et <b>Q</b> s'additionnent ; <b>S ne s'additionne pas</b> : S = √(P² + Q²)."),
dict(t="n", o="§5 Méthode des deux wattmètres",
 r="Méthode des deux wattmètres : puissance active et déphasage ?",
 v="<b>P = W<sub>1</sub> + W<sub>2</sub></b>.<br><b>tan φ = √3 (W<sub>1</sub> − W<sub>2</sub>)/(W<sub>1</sub> + W<sub>2</sub>)</b>. W<sub>1</sub> = W<sub>2</sub> → charge résistive."),
dict(t="n", o="§5 Mesurer",
 r="Sur quelle position mettre le multimètre pour mesurer une tension du réseau ?",
 v="Sur <b>AC</b> : la tension est alternative de valeur moyenne nulle (en DC, ≈ 0)."),
dict(t="n", o="§6 Relever le facteur de puissance",
 r="Comment relève-t-on le facteur de puissance d'un atelier ? Que deviennent P et I ?",
 v="Par une <b>batterie de condensateurs en dérivation</b>. <b>P ne change pas</b>, I baisse (et les pertes en I²)."),
# --- méthodes
dict(t="m", o="§2 Méthode — Déterminer le couplage",
 r="Comment choisir le couplage d'un récepteur triphasé ?",
 v="1. Lire la <b>tension nominale d'un enroulement</b>.<br>2. Lire les <b>deux tensions du réseau</b>.<br>3. Choisir le couplage qui lui applique sa tension : <b>étoile si V</b>, <b>triangle si U</b>.<br>4. Rédiger la justification."),
dict(t="m", o="§2 Plaque moteur",
 r="Plaque moteur « 230/400 V » sur un réseau 230/400 V : quel couplage ?",
 v="Enroulement = 230 V. Le réseau a <b>U = 400 V</b> entre phases → <b>étoile</b> (chaque enroulement voit V = 230 V)."),
dict(t="m", o="§3 Méthode — De la puissance à l'intensité",
 r="Moteur : P = 4,50 kW, cos φ = 0,80, U = 400 V. Comment trouver I ?",
 v="1. S = P / cos φ = 4500/0,80 = <b>5625 VA</b>.<br>2. I = S / (√3 U) = 5625/693 = <b>8,12 A</b>.<br>3. Contrôle : ≈ 1,4 A par kVA sous 400 V."),
dict(t="m", o="§6 Méthode — Batterie de condensateurs",
 r="Comment dimensionner une batterie de condensateurs pour relever cos φ ?",
 v="1. <b>Q<sub>1</sub> = P tan φ<sub>1</sub></b> (actuel).<br>2. <b>Q<sub>2</sub> = P tan φ<sub>2</sub></b> (visé).<br>3. <b>Q<sub>C</sub> = Q<sub>1</sub> − Q<sub>2</sub></b>.<br>4. Triangle : <b>C = Q<sub>C</sub> / (3 ω U²)</b>.<br>5. Vérifier que P n'a pas changé."),
]

# =====================================================================
CARTES["ch08"] = [
dict(t="n", o="§1 Oxydant, réducteur",
 r="Définir un oxydant et un réducteur. Qui subit l'oxydation ?",
 v="<b>Oxydant</b> : capte des électrons (il subit une réduction).<br><b>Réducteur</b> : cède des électrons (il subit une <b>oxydation</b>)."),
dict(t="n", o="§1 Couple et demi-équation",
 r="Qu'est-ce qu'un couple oxydant/réducteur ? Exemple de demi-équation.",
 v="Un oxydant et le réducteur qu'il devient après avoir capté des électrons, noté <b>Ox/Red</b>.<br>Fe<sup>2+</sup> + 2 e<sup>−</sup> ⇌ Fe pour le couple Fe<sup>2+</sup>/Fe."),
dict(t="n", o="§2 L'échelle des potentiels",
 r="Comment lire l'échelle des potentiels standard E° ? Entre qui se fait la réaction spontanée ?",
 v="Potentiel <b>élevé</b> → oxydant <b>fort</b> ; potentiel <b>bas</b> → réducteur <b>fort</b>.<br>Réaction entre l'<b>oxydant du couple haut</b> et le <b>réducteur du couple bas</b>."),
dict(t="n", o="§3 La corrosion",
 r="Définir la corrosion. Quels sont les trois ingrédients de la corrosion du fer ?",
 v="La dégradation d'un métal par <b>oxydation</b> au contact de son environnement.<br>Il faut <b>le métal, l'eau et le dioxygène</b> : en supprimer un l'arrête."),
dict(t="n", o="§4 Protéger le métal",
 r="Protection passive et protection active : principe et exemples ?",
 v="<b>Passive</b> : <b>isole</b> le métal (revêtement, passivation, anodisation) ; inefficace si percée.<br><b>Active</b> : <b>sacrifie un métal plus réducteur</b> (galvanisation, anode sacrificielle) ; protège même après rayure."),
dict(t="n", o="§5 Acides, bases et pH",
 r="Solution acide, neutre, basique : quel pH ? Quand est-elle la plus corrosive ?",
 v="pH &lt; 7 <b>acide</b> ; = 7 <b>neutre</b> ; &gt; 7 <b>basique</b> (à 25 °C). Plus le pH <b>s'éloigne de 7</b>, plus elle est corrosive."),
dict(t="n", o="§5 Une échelle qui trompe",
 r="Un bain à pH 1 est-il un peu ou beaucoup plus acide qu'un bain à pH 2 ?",
 v="<b>10 fois plus</b> : l'échelle de pH est <b>logarithmique</b>."),
dict(t="n", o="§5 Choisir l'instrument",
 r="Papier pH ou pH-mètre : lequel choisir ?",
 v="<b>Papier pH</b> (± 1 unité) : pour trier. <b>pH-mètre étalonné</b> (± 0,05) : quand la décision se joue près d'une limite."),
dict(t="n", o="§6 FDS et pictogrammes",
 r="Que dit le pictogramme ? Que dit la fiche de données de sécurité (FDS) ?",
 v="<b>Pictogramme</b> : <b>quel danger</b> existe.<br><b>FDS</b> : <b>quoi faire</b> (précautions, stockage, secours, EPI). Une réponse complète cite les deux."),
dict(t="n", o="§7 Niveau d'intensité sonore",
 r="Formule du niveau d'intensité sonore ? Valeur de I<sub>0</sub> ? Appareil de mesure ?",
 v="<b>L = 10 log(I / I<sub>0</sub>)</b> en dB, <b>I<sub>0</sub> = 1,0 × 10<sup>−12</sup> W/m²</b>. Mesuré au <b>sonomètre</b>."),
dict(t="n", o="§7 Les décibels ne s'additionnent pas",
 r="Deux machines de 85 dB côte à côte donnent… ? Doubler la distance en champ libre ?",
 v="<b>88 dB</b> (doubler l'intensité ajoute 3 dB ; × 10 ajoute 10 dB).<br>Doubler la distance : <b>−6 dB</b>."),
dict(t="n", o="§7 Le risque acoustique",
 r="De quoi dépend le risque sonore ? Quels sont les trois seuils réglementaires ?",
 v="Du <b>niveau</b>, de la <b>durée</b> et de la <b>fréquence</b>.<br><b>80</b> dB(A) : protections mises à disposition ; <b>85</b> : port obligatoire ; <b>87</b> : valeur limite."),
dict(t="n", o="§7 La protection individuelle vient en dernier",
 r="Dans quel ordre agir contre le bruit ?",
 v="1. <b>À la source</b> (machine).<br>2. Sur la <b>propagation</b> (local).<br>3. Seulement ensuite sur l'<b>individu</b> (bouchons, casque)."),
# --- méthodes
dict(t="m", o="§2 Méthode — Identifier oxydant et réducteur",
 r="Pluie acide (H<sup>+</sup>/H<sub>2</sub> : 0,00 V) sur du fer (Fe<sup>2+</sup>/Fe : −0,44 V). Comment savoir si le fer est attaqué ?",
 v="1. Relever les deux potentiels.<br>2. Couple haut → oxydant (<b>H<sup>+</sup></b>) ; couple bas → réducteur (<b>Fe</b>).<br>3. Justifier : 0,00 &gt; −0,44, le fer est <b>attaqué</b>."),
dict(t="m", o="§3 Méthode — Écrire une équation d'oxydoréduction",
 r="Comment écrire l'équation d'une réaction d'oxydoréduction ?",
 v="1. Identifier les deux couples (potentiels).<br>2. Écrire l'oxydation et la réduction.<br>3. <b>Égaliser les électrons</b> (multiplier).<br>4. Additionner : les électrons disparaissent.<br>5. Contrôler éléments et charges."),
dict(t="m", o="§4 Méthode — Anode sacrificielle",
 r="Comment choisir le métal d'une anode sacrificielle pour protéger de l'acier ?",
 v="1. Potentiel du fer : −0,44 V.<br>2. Ne garder que les métaux de potentiel <b>inférieur</b> (meilleurs réducteurs).<br>3. Choisir le praticable (<b>zinc, magnésium</b>).<br>4. Justifier en comparant au moins deux métaux."),
dict(t="m", o="§7 Méthode — Évaluer un risque sonore",
 r="Comment évaluer le risque sonore à un poste de travail ?",
 v="1. <b>Mesurer</b> L au sonomètre au poste.<br>2. Ajouter <b>+3 dB</b> par source identique.<br>3. Ramener à 8 h : <b>L<sub>ex</sub> = L + 10 log(T / 8 h)</b>.<br>4. Comparer aux seuils 80/85/87 dB(A) et énoncer l'obligation."),
]

# =====================================================================
CARTES["ch09"] = [
dict(t="n", o="§1 Ce que le transformateur ne fait pas",
 r="Le transformateur redresse-t-il ? Change-t-il la fréquence ?",
 v="<b>Non et non</b> : sa sortie reste <b>alternative</b>, il ne lisse rien, la fréquence reste celle du réseau (50 Hz). Il change seulement la <b>tension</b>."),
dict(t="n", o="§2 Le principe",
 r="De quoi est fait un transformateur ? Comment l'énergie passe-t-elle du primaire au secondaire ?",
 v="Un <b>circuit magnétique</b> en tôles feuilletées et deux enroulements (<b>primaire</b> N<sub>1</sub>, <b>secondaire</b> N<sub>2</sub>), jamais reliés : l'énergie passe par le <b>flux magnétique commun</b> (isolement galvanique)."),
dict(t="n", o="§2 Pourquoi l'alternatif",
 r="Que se passe-t-il si l'on alimente un transformateur en continu ?",
 v="Le flux est constant : <b>aucune tension au secondaire</b>, et le primaire, réduit à sa résistance, <b>grille</b>."),
dict(t="n", o="§3 Le transformateur parfait",
 r="Rapport de transformation du transformateur parfait ?",
 v="<b>m = U<sub>2</sub>/U<sub>1</sub> = N<sub>2</sub>/N<sub>1</sub> = I<sub>1</sub>/I<sub>2</sub></b> (sans unité). Le rapport des courants est <b>inversé</b>."),
dict(t="n", o="§3 Abaisseur ou élévateur",
 r="Comment savoir si un transformateur est abaisseur ou élévateur ?",
 v="<b>m &lt; 1</b> : <b>abaisseur</b> (U<sub>2</sub> &lt; U<sub>1</sub>) ; <b>m &gt; 1</b> : <b>élévateur</b>. Toujours justifier."),
dict(t="n", o="§4 Conservation de la puissance",
 r="Que conserve un transformateur parfait ?",
 v="La puissance apparente : <b>S<sub>1</sub> = S<sub>2</sub></b>, soit <b>U<sub>1</sub> I<sub>1</sub> = U<sub>2</sub> I<sub>2</sub></b>. Élever la tension abaisse le courant dans le même rapport."),
dict(t="n", o="§5 Des VA, pas des watts",
 r="Pourquoi la plaque d'un transformateur donne-t-elle S en VA et pas P en W ?",
 v="L'échauffement dépend du <b>courant</b>, donc de <b>S = U I</b>. Dépasser S fait chauffer le transformateur, même si la charge consomme peu de watts."),
dict(t="n", o="§6 Oscilloscope et voltmètre",
 r="Que montre l'oscilloscope et qu'affiche le voltmètre au secondaire ?",
 v="Oscilloscope : <b>U<sub>2max</sub></b>. Voltmètre (sur AC) : <b>U<sub>2</sub> efficace = U<sub>2max</sub>/√2</b>. Valeur moyenne nulle."),
dict(t="n", o="§7 Le transformateur réel",
 r="Quelles pertes dans un transformateur réel ? Rendement typique ?",
 v="<b>Pertes fer</b> (circuit magnétique) et <b>pertes cuivre</b> (enroulements). <b>η = P<sub>2</sub>/P<sub>1</sub> &gt; 95 %</b>. En charge, U<sub>2</sub> chute de quelques %."),
# --- méthodes
dict(t="m", o="§3 Méthode — Déterminer m",
 r="Plaque « 230 V / 24 V ». Comment trouver m et conclure ?",
 v="1. Primaire = côté source (230 V).<br>2. m = U<sub>2</sub>/U<sub>1</sub> = 24/230 = <b>0,104</b>.<br>3. m &lt; 1 → <b>abaisseur</b> (justifier).<br>4. Contrôle : tension ÷ 10, courant × 10."),
dict(t="m", o="§5 Méthode — Courants nominaux",
 r="Plaque « 230 V / 24 V — 24 VA ». Comment trouver les courants nominaux ?",
 v="1. S = 24 VA des deux côtés.<br>2. I<sub>2N</sub> = S/U<sub>2</sub> = <b>1,00 A</b>.<br>3. I<sub>1N</sub> = S/U<sub>1</sub> = <b>0,104 A</b>.<br>4. Contrôle : I<sub>1</sub>/I<sub>2</sub> = m."),
dict(t="m", o="§6 Méthode — Oscillogramme de u2",
 r="20 V/div, 5 ms/div ; amplitude 1,7 div, motif sur 4 div. Comment trouver U<sub>2max</sub>, f et U<sub>2</sub> ?",
 v="1. U<sub>2max</sub> = 1,7 × 20 = <b>34 V</b>.<br>2. T = 4 × 5 = 20 ms → <b>f = 50 Hz</b>.<br>3. U<sub>2</sub> = 34/√2 = <b>24 V</b>."),
dict(t="m", o="§7 Méthode — Mesurer m",
 r="Comment mesurer le rapport de transformation ?",
 v="1. <b>Secondaire ouvert</b> (rien de branché).<br>2. Alimenter le primaire, mesurer U<sub>1</sub>.<br>3. Mesurer U<sub>20</sub> à vide.<br>4. <b>m = U<sub>20</sub>/U<sub>1</sub></b>, comparer à la plaque (quelques %)."),
]

# =====================================================================
CARTES["ch10"] = [
dict(t="n", o="§1 Redresser",
 r="Que signifie « redresser » une tension ? Redressé veut-il dire constant ?",
 v="Transformer une tension alternative en une tension qui <b>garde toujours le même signe</b>. <b>Non</b> : elle ondule encore (arches) ; il faut ensuite la lisser."),
dict(t="n", o="§2 La diode",
 r="Comment se comporte une diode parfaite passante ? bloquée ? Qui décide de son état ?",
 v="Courant dans <b>un seul sens</b>. Passante : un <b>fil</b> ; bloquée : un <b>interrupteur ouvert</b>. C'est le <b>circuit</b> qui décide."),
dict(t="n", o="§3 Le pont de Graetz",
 r="Comment conduisent les diodes d'un pont de Graetz (PD2) ? Conséquence sur u<sub>s</sub> ?",
 v="<b>Deux par deux, en diagonale</b>. Le courant entre toujours par la même borne de la charge : <b>u<sub>s</sub> ne change jamais de signe</b>."),
dict(t="n", o="§4 Fréquence de sortie",
 r="Fréquence de la tension redressée double alternance ?",
 v="<b>f<sub>s</sub> = 2 f<sub>e</sub></b> : 100 Hz pour un réseau à 50 Hz."),
dict(t="n", o="§4 La valeur moyenne",
 r="Valeur moyenne en sortie d'un pont de diodes ? Piège ?",
 v="<b>⟨u<sub>s</sub>⟩ = 2 U<sub>max</sub> / π ≈ 0,637 U<sub>max</sub></b>.<br>Piège : une tension de transformateur donnée est <b>efficace</b> → U<sub>max</sub> = U √2."),
dict(t="n", o="§4 Mesurer",
 r="Sur quelle position mesurer la valeur moyenne d'une tension redressée ?",
 v="Sur <b>DC</b>. En AC, l'appareil retire la composante continue et ne mesure que l'ondulation."),
dict(t="n", o="§5 Lisser",
 r="Lissage : comment monte-t-on le condensateur ? la bobine ? Que lisse chacun ?",
 v="<b>Condensateur en parallèle</b> sur la charge : lisse la <b>tension</b>.<br><b>Bobine en série</b> : lisse le <b>courant</b>.<br>Plus C ou L est grand, plus l'ondulation est faible."),
dict(t="n", o="§6 Retard à l'amorçage",
 r="Qu'est-ce que le retard à l'amorçage α d'un thyristor ? Comment le lire ?",
 v="L'angle entre le début théorique de conduction et l'impulsion de gâchette.<br><b>α = 360° × Δt / T</b>."),
dict(t="n", o="§6 Ponts commandés",
 r="Valeur moyenne d'un pont mixte et d'un pont tout thyristor ? Hypothèse ?",
 v="Mixte : <b>(U<sub>max</sub>/π)(1 + cos α)</b>.<br>Tout thyristor : <b>(2 U<sub>max</sub>/π) cos α</b>.<br>Hypothèse : courant <b>parfaitement lissé</b> (bobine en série)."),
dict(t="n", o="§7 Le spectre",
 r="Sur le spectre d'une tension redressée, que représente la raie à 0 Hz ?",
 v="La <b>valeur moyenne</b>. Les autres raies (surtout 100 Hz) décrivent l'ondulation."),
dict(t="n", o="§7 Côté réseau",
 r="Pourquoi un redresseur pollue-t-il le réseau ? Particularité du pont triphasé PD3 ?",
 v="Il appelle un courant <b>non sinusoïdal</b> (à-coups) → <b>harmoniques</b>. Le PD3 ne produit <b>aucun harmonique de rang 3</b> (ceux qui chauffent le neutre)."),
# --- méthodes
dict(t="m", o="§4 Méthode — Valeur moyenne d'un pont",
 r="Transformateur 230 V/24 V suivi d'un pont de Graetz. Comment trouver ⟨u<sub>s</sub>⟩ ?",
 v="1. 24 V est une valeur <b>efficace</b>.<br>2. U<sub>max</sub> = 24 √2 = <b>34 V</b>.<br>3. ⟨u<sub>s</sub>⟩ = 2 × 34/π = <b>21,6 V</b>.<br>4. Contrôle : ≈ 64 % de U<sub>max</sub>, inférieur à 24 V."),
dict(t="m", o="§6 Méthode — Pont commandé",
 r="Pont tout thyristor, U<sub>max</sub> = 34 V, 50 Hz, conduction 3,33 ms après le zéro. Comment trouver ⟨u<sub>s</sub>⟩ ?",
 v="1. α = 360 × 3,33/20 = <b>60°</b>.<br>2. Identifier le pont (4 thyristors).<br>3. ⟨u<sub>s</sub>⟩ = (2 × 34/π) cos 60° = <b>10,8 V</b>.<br>4. Vérifier : α plus grand → tension plus faible."),
dict(t="m", o="§5 Lisser",
 r="Tension lissée entre 40 V et 44 V. Comment trouver l'ondulation et le taux d'ondulation ?",
 v="1. <b>Δu = 44 − 40 = 4 V</b>.<br>2. Valeur moyenne ≈ 42 V.<br>3. Taux = Δu / ⟨u⟩ = 4/42 ≈ <b>9,5 %</b>."),
dict(t="m", o="§7 Lire une valeur moyenne sur un spectre",
 r="Comment obtenir la valeur moyenne d'un signal à partir de son spectre ?",
 v="1. Relever l'amplitude de la <b>raie à 0 Hz</b> : c'est ⟨u⟩.<br>2. Pour vérifier : recalculer 2U<sub>max</sub>/π.<br>3. Comparer par un <b>écart relatif</b> et conclure."),
]

# =====================================================================
CARTES["ch11"] = [
dict(t="n", o="§1 Les deux convertisseurs",
 r="Que convertissent un hacheur et un onduleur ?",
 v="<b>Hacheur</b> : continu → <b>continu réglable</b>.<br><b>Onduleur</b> : continu → <b>alternatif</b>."),
dict(t="n", o="§1 Le variateur de vitesse",
 r="Pourquoi un variateur redresse-t-il puis ondule-t-il la tension du réseau ?",
 v="Pour obtenir une <b>autre fréquence que 50 Hz</b> : c'est le seul moyen de faire varier la vitesse d'un moteur alternatif."),
dict(t="n", o="§2 L'interrupteur commandé",
 r="Comment se comporte un transistor utilisé en commutation ?",
 v="Deux états seulement : <b>passant</b> = fil ; <b>bloqué</b> = interrupteur ouvert."),
dict(t="n", o="§3 La diode de roue libre",
 r="Rôle de la diode de roue libre d'un hacheur ? Peut-elle conduire en même temps que l'interrupteur ?",
 v="Elle <b>entretient le courant</b> de la bobine quand l'interrupteur s'ouvre (évite la surtension). <b>Jamais en même temps</b> : sinon court-circuit de la source."),
dict(t="n", o="§3 Le rapport cyclique",
 r="Définir le rapport cyclique α. Valeur moyenne en sortie d'un hacheur série ?",
 v="La <b>fraction de la période</b> pendant laquelle l'interrupteur est fermé (0 ≤ α ≤ 1, sans unité).<br><b>⟨u<sub>s</sub>⟩ = α U</b> : la tension est toujours <b>abaissée</b>."),
dict(t="n", o="§4 L'ondulation du courant",
 r="Qu'est-ce que la conduction continue ? Comment réduire l'ondulation Δi ?",
 v="Le courant oscille autour de sa moyenne <b>sans s'annuler</b>.<br>Réduire Δi : <b>augmenter L</b> ou <b>augmenter la fréquence de découpage</b>."),
dict(t="n", o="§5 L'onduleur en pont",
 r="Quelle règle absolue pour les interrupteurs d'un bras d'onduleur ?",
 v="<b>Jamais les deux interrupteurs d'un même bras fermés ensemble</b> (court-circuit de la source) : temps mort entre les deux."),
dict(t="n", o="§5 Commande symétrique",
 r="Onduleur en commande symétrique : forme, valeur moyenne, valeur efficace de la sortie ?",
 v="Un <b>créneau ±U</b> ; valeur moyenne <b>nulle</b> ; valeur efficace <b>exactement U</b>."),
dict(t="n", o="§6 La MLI",
 r="Qu'apporte la commande MLI par rapport à la commande symétrique ?",
 v="Même fondamental, mais les <b>harmoniques sont repoussés vers la fréquence de découpage</b>, où l'inductance du moteur les filtre."),
dict(t="n", o="§7 Le sens du transfert",
 r="Comment savoir sur des chronogrammes si le pont fonctionne en onduleur ou en redresseur ?",
 v="u et i de <b>même signe</b> : p &gt; 0, énergie vers la charge → <b>onduleur</b>.<br>De <b>signes opposés</b> : p &lt; 0, énergie vers la source → <b>redresseur</b> (freinage par récupération)."),
# --- méthodes
dict(t="m", o="§3 Méthode — Chronogramme de hacheur",
 r="10 V/div, 10 µs/div : palier haut 4,8 div, durée 3,0 div, motif 5,0 div. Comment trouver U, f, α et ⟨u<sub>s</sub>⟩ ?",
 v="1. U = 4,8 × 10 = <b>48 V</b>.<br>2. T = 50 µs → <b>f = 20 kHz</b>.<br>3. α = 3,0/5,0 = <b>0,60</b> (en divisions).<br>4. ⟨u<sub>s</sub>⟩ = 0,60 × 48 = <b>28,8 V</b>."),
dict(t="m", o="§4 L'ondulation du courant",
 r="Comment calculer l'ondulation du courant d'un hacheur avec la relation fournie ?",
 v="1. Relever α, U, L, f (en unités SI).<br>2. Δi = α(1 − α) U / (L f).<br>3. Ex. : 0,60 × 0,40 × 48 / (2,0 × 10<sup>−3</sup> × 20 × 10<sup>3</sup>) = <b>0,29 A</b>.<br>4. Comparer au courant moyen."),
dict(t="m", o="§5 Méthode — Tracer la sortie d'un onduleur",
 r="Comment tracer la tension de sortie d'un onduleur en pont ?",
 v="1. K<sub>1</sub>, K<sub>3</sub> fermés : charge reliée au + à gauche → <b>u<sub>c</sub> = +U</b>.<br>2. K<sub>2</sub>, K<sub>4</sub> fermés : liaisons inversées → <b>u<sub>c</sub> = −U</b>.<br>3. Tracer le créneau.<br>4. Vérifier : changement de signe, alternances égales."),
dict(t="m", o="§7 Méthode — Sens du transfert",
 r="Comment lire le sens du transfert d'énergie sur des chronogrammes u et i ?",
 v="1. Superposer u<sub>c</sub> et i.<br>2. Repérer les intervalles de <b>même signe</b> (onduleur).<br>3. Repérer ceux de <b>signes opposés</b> (redresseur).<br>4. Conclure sur le fonctionnement dominant (durées)."),
]

# =====================================================================
CARTES["ch12"] = [
dict(t="n", o="§1 Conversion réalisée",
 r="Que convertit un moteur à courant continu ? Grandeurs d'entrée et de sortie ?",
 v="Énergie <b>électrique → mécanique</b>. Entrée : U et I. Sortie : couple <b>T<sub>u</sub></b> et vitesse <b>Ω</b>."),
dict(t="n", o="§1 Inducteur et induit",
 r="Rôle de l'inducteur et de l'induit ?",
 v="<b>Inducteur</b> : crée le champ magnétique (souvent des aimants permanents).<br><b>Induit</b> : porte le courant utile."),
dict(t="n", o="§2 Modèle de l'induit",
 r="Modèle électrique de l'induit ? Que vaut E à l'arrêt ?",
 v="<b>U = E + R I</b> (E force électromotrice). À l'arrêt, <b>E = 0</b>."),
dict(t="n", o="§3 Relations de couplage",
 r="Les deux relations de couplage du moteur à courant continu ?",
 v="<b>E = k Ω</b> et <b>T<sub>em</sub> = k I</b>, avec le même k. D'où <b>E I = T<sub>em</sub> Ω</b>.<br>Ω en rad/s : Ω = 2π n / 60."),
dict(t="n", o="§4 Le démarrage",
 r="Courant de démarrage d'un moteur à courant continu ? Comment l'éviter ?",
 v="E = 0, donc <b>I<sub>d</sub> = U / R</b> (souvent &gt; 10 fois le nominal). On monte la tension <b>progressivement</b> (hacheur, α croissant)."),
dict(t="n", o="§5 Couple utile et électromagnétique",
 r="Comparer le couple utile T<sub>u</sub> et le couple électromagnétique T<sub>em</sub>.",
 v="<b>T<sub>u</sub> &lt; T<sub>em</sub></b> : une partie du couple sert à vaincre les frottements. T<sub>u</sub> = P<sub>u</sub>/Ω."),
dict(t="n", o="§5 Rendement",
 r="Rendement typique d'un moteur à courant continu ?",
 v="Autour de <b>90 %</b>. Une valeur très différente doit faire relire le calcul."),
dict(t="n", o="§6 Caractéristique mécanique",
 r="Forme de la caractéristique mécanique T(Ω) ? Qu'est-ce que le point de fonctionnement ?",
 v="Une <b>droite descendante</b>. Le point de fonctionnement est l'<b>intersection</b> avec la caractéristique de la charge."),
dict(t="n", o="§6 Régler la vitesse",
 r="Comment régler la vitesse d'un moteur à courant continu ? l'inverser ?",
 v="Régler : agir sur la <b>tension d'induit</b> (le courant est fixé par la charge).<br>Inverser : <b>permuter les bornes</b> de l'induit."),
dict(t="n", o="§7 Le réducteur",
 r="Moteur à 90 % suivi d'un réducteur à 85 % : rendement global ?",
 v="Les rendements se <b>multiplient</b> : 0,90 × 0,85 = <b>77 %</b>."),
dict(t="n", o="§7 Ses limites",
 r="Points faibles du moteur à courant continu ?",
 v="L'<b>usure des balais</b> et des <b>pertes au rotor</b> difficiles à évacuer. On lui préfère les machines alternatives."),
# --- méthodes
dict(t="m", o="§3 Exemple de référence",
 r="U = 48 V, I = 12 A, R = 0,25 Ω, n = 1500 tr/min. Comment trouver E, k et T<sub>em</sub> ?",
 v="1. E = U − R I = 48 − 3 = <b>45 V</b>.<br>2. Ω = 2π × 1500/60 = <b>157 rad/s</b>.<br>3. k = E/Ω = <b>0,286 V·s/rad</b>.<br>4. T<sub>em</sub> = k I = <b>3,44 N·m</b>."),
dict(t="m", o="§5 Méthode — Bilan des puissances",
 r="Comment établir le bilan des puissances d'un moteur à courant continu ?",
 v="1. <b>P<sub>a</sub> = U I</b>.<br>2. Retirer <b>p<sub>J</sub> = R I²</b> → P<sub>em</sub>.<br>3. Contrôler <b>P<sub>em</sub> = E I</b>.<br>4. Retirer pertes fer et mécaniques → <b>P<sub>u</sub></b>.<br>5. <b>η = P<sub>u</sub>/P<sub>a</sub></b> ; T<sub>u</sub> = P<sub>u</sub>/Ω."),
dict(t="m", o="§6 Méthode — Point de fonctionnement",
 r="Comment déterminer le point de fonctionnement moteur + charge ?",
 v="1. Tracer la caractéristique du <b>moteur</b> T(Ω).<br>2. Tracer celle de la <b>charge</b> sur le même graphe.<br>3. Lire l'<b>intersection</b>.<br>4. Convertir : n = 60 Ω/2π."),
]

# =====================================================================
CARTES["ch13"] = [
dict(t="n", o="§1 Le champ tournant",
 r="Que créent trois bobines à 120° alimentées en triphasé ?",
 v="Un <b>champ magnétique unique qui tourne</b>, qui entraîne le rotor sans contact."),
dict(t="n", o="§1 Vitesse de synchronisme",
 r="Vitesse de synchronisme ? De quoi dépend-elle ?",
 v="<b>n<sub>s</sub> = 60 f / p</b> (tr/min), p = nombre de <b>paires</b> de pôles. Elle ne dépend que de f et p.<br>À 50 Hz : 3000, 1500, 1000… tr/min."),
dict(t="n", o="§1 Deux pièges",
 r="Moteur « 4 pôles » sur 50 Hz : que vaut p ? n<sub>s</sub> ?",
 v="<b>p = 2</b> (paires de pôles) ; n<sub>s</sub> = 60 × 50/2 = <b>1500 tr/min</b>."),
dict(t="n", o="§2 Le glissement",
 r="Définir le glissement. Valeur pour une machine synchrone ? asynchrone ?",
 v="<b>g = (n<sub>s</sub> − n) / n<sub>s</sub></b>.<br>Synchrone : <b>g = 0</b> (rotor accroché).<br>Asynchrone : <b>quelques %</b>."),
dict(t="n", o="§2 Pourquoi le glissement",
 r="Pourquoi une machine asynchrone doit-elle glisser ?",
 v="Sans retard sur le champ, <b>aucun courant n'est induit</b> au rotor, donc <b>aucun couple</b>."),
dict(t="n", o="§3 Couplage du stator",
 r="Plaque 230/400 V : quelle tension supporte un enroulement ? Couplage sur réseau 400 V ? Plaque 400/690 V ?",
 v="La plus petite : <b>230 V</b> → sur réseau 400 V, <b>étoile</b>.<br>Plaque 400/690 V : enroulement 400 V → <b>triangle</b>."),
dict(t="n", o="§4 Bilan des puissances",
 r="Puissance absorbée et puissance utile d'un moteur asynchrone ? Rendement typique ?",
 v="<b>P<sub>a</sub> = √3 U I cos φ</b> ; <b>P<sub>u</sub> = T<sub>u</sub> Ω</b> (Ω en rad/s).<br>η = P<sub>u</sub>/P<sub>a</sub>, entre <b>80 et 95 %</b>."),
dict(t="n", o="§4 Les trois vitesses",
 r="Quelles sont les trois vitesses d'un exercice sur machine asynchrone ?",
 v="<b>n<sub>s</sub></b> : champ (tr/min) ; <b>n</b> : rotor (tr/min) ; <b>Ω</b> : rotor (rad/s). Le couple se calcule avec <b>Ω</b>."),
dict(t="n", o="§5 Caractéristique mécanique",
 r="Forme de la caractéristique mécanique d'une machine asynchrone ? Conséquence ?",
 v="Une <b>droite très raide</b>, presque verticale : sur le réseau 50 Hz, elle tourne à vitesse <b>pratiquement constante</b>."),
dict(t="n", o="§6 U/f constant",
 r="Comment régler la vitesse d'un moteur asynchrone ? Pourquoi garder U/f constant ?",
 v="En changeant la <b>fréquence</b> (variateur) donc n<sub>s</sub>. U/f constant conserve le <b>flux</b>, donc le <b>couple</b>. Les caractéristiques sont des <b>droites parallèles</b>."),
dict(t="n", o="§7 La machine synchrone",
 r="La machine synchrone est-elle réversible ? Peut-elle démarrer seule sur le réseau ?",
 v="<b>Réversible</b> : alternateur si on l'entraîne, moteur si on l'alimente (n = n<sub>s</sub>).<br><b>Ne démarre pas seule</b> : il faut un variateur qui monte la fréquence depuis zéro."),
# --- méthodes
dict(t="m", o="§2 Méthode — Synchrone ou asynchrone",
 r="Plaque : 1440 tr/min, 50 Hz. Comment justifier que la machine est asynchrone ?",
 v="1. Lire n = 1440 tr/min.<br>2. Vitesses de synchronisme possibles : 3000, 1500, 1000…<br>3. 1440 est <b>légèrement inférieure</b> à 1500.<br>4. Conclure : <b>asynchrone</b>, g = (1500 − 1440)/1500 = 4 %."),
dict(t="m", o="§3 Méthode — Couplage",
 r="Comment déterminer le couplage d'un moteur sur un réseau ?",
 v="1. Plus petite tension de la plaque = tension d'un <b>enroulement</b>.<br>2. Tension composée du réseau.<br>3. Enroulement = V → <b>étoile</b> ; = U → <b>triangle</b>.<br>4. <b>Justifier</b>."),
dict(t="m", o="§4 Méthode — Bilan et rendement",
 r="Moteur 4 kW, η = 87 %, cos φ = 0,82, 400 V, 1440 tr/min. Comment trouver I et T<sub>u</sub> ?",
 v="1. P<sub>a</sub> = 4000/0,87 = 4,60 kW.<br>2. I = P<sub>a</sub> / (√3 × 400 × 0,82) = <b>8,1 A</b>.<br>3. Ω = 2π × 1440/60 = 150,8 rad/s.<br>4. T<sub>u</sub> = 4000/150,8 = <b>26,5 N·m</b>."),
dict(t="m", o="§5 Méthode — Point de fonctionnement",
 r="Comment tracer la caractéristique d'un moteur asynchrone et trouver le point de fonctionnement ?",
 v="1. Deux points : <b>(n<sub>s</sub> ; 0)</b> et le <b>point nominal</b>.<br>2. Tracer la charge sur le même graphe.<br>3. Lire l'<b>intersection</b>.<br>4. En déduire ce qui est demandé (vitesse de translation…)."),
]

# =====================================================================
CARTES["ch14"] = [
dict(t="n", o="Introduction",
 r="Que fait un capteur ?",
 v="Il <b>traduit</b> une grandeur physique en une grandeur <b>électrique</b>. Il ne mesure pas : il convertit. C'est le premier maillon de la chaîne de mesure."),
dict(t="n", o="§1 Grandeurs d'entrée et de sortie",
 r="Grandeur d'entrée et grandeur de sortie d'un capteur : de quelle nature ?",
 v="<b>Entrée</b> : la grandeur <b>physique</b> mesurée (température, force…).<br><b>Sortie</b> : <b>toujours électrique</b> (résistance, tension, courant, charge)."),
dict(t="n", o="§2 Capteur passif, capteur actif",
 r="Quand un capteur est-il passif ? actif ?",
 v="<b>Passif</b> : la sortie est une <b>impédance</b> (résistance…) ; il faut une alimentation extérieure.<br><b>Actif</b> : il délivre une <b>tension, un courant ou une charge</b> (générateur)."),
dict(t="n", o="§3 Nature du signal",
 r="Quels sont les trois types de signal de sortie ? Ce classement dépend-il d'actif/passif ?",
 v="<b>Analogique</b>, <b>logique</b> (deux états), <b>numérique</b> (nombre codé). Classement <b>indépendant</b> d'actif/passif (Pt100 : passive et analogique)."),
dict(t="n", o="§4 Sensibilité",
 r="Définir la sensibilité d'un capteur. Son unité ?",
 v="La <b>pente</b> de la caractéristique statique : <b>s = ΔS / ΔE</b>. Unité <b>déduite du quotient</b> (Ω/°C pour une Pt100)."),
dict(t="n", o="§4 Étendue et linéarité",
 r="Qu'est-ce que l'étendue de mesure ? Quand un capteur est-il linéaire ?",
 v="<b>Étendue</b> : l'intervalle sur lequel le capteur est garanti.<br><b>Linéaire</b> : caractéristique = <b>droite</b>, sensibilité constante."),
dict(t="n", o="§4 La Pt100",
 r="Loi de la sonde Pt100 ? Sensibilité ?",
 v="<b>R = R<sub>0</sub>(1 + α θ)</b>, R<sub>0</sub> = 100 Ω à 0 °C, α = 3,85 × 10<sup>−3</sup> °C<sup>−1</sup>.<br>s = R<sub>0</sub> α = <b>0,385 Ω/°C</b>. Passive, analogique."),
dict(t="n", o="§5 Temps de réponse à 5 %",
 r="Définir le temps de réponse à 5 % d'un capteur. Piège ?",
 v="Le temps pour atteindre <b>95 % de la variation</b> finale après un échelon. Piège : 95 % de la variation, <b>pas de la valeur finale</b>."),
dict(t="n", o="§6 Quelques capteurs",
 r="Jauge d'extensométrie : loi ? Thermocouple et piézoélectrique : actifs ou passifs ?",
 v="Jauge : <b>ΔR/R<sub>0</sub> = k ΔL/L<sub>0</sub></b>, passive.<br>Thermocouple, piézoélectrique : <b>actifs</b>."),
# --- méthodes
dict(t="m", o="§1 Méthode — Entrée et sortie",
 r="Comment préciser les grandeurs d'entrée et de sortie d'un capteur ?",
 v="1. Ce que le capteur <b>surveille</b> → entrée (physique).<br>2. Ce qu'il <b>délivre</b> → sortie (électrique).<br>3. Donner les <b>unités</b>.<br>4. Ne pas confondre avec la sortie du conditionneur."),
dict(t="m", o="§2 Méthode — Actif ou passif",
 r="Comment justifier qu'un capteur est actif ou passif ?",
 v="Regarder la <b>nature de la sortie</b> :<br>• résistance, capacité, inductance → <b>passif</b> (rien sans alimentation) ;<br>• tension, courant, charge → <b>actif</b> (générateur)."),
dict(t="m", o="§5 Méthode — Temps de réponse",
 r="Comment déterminer graphiquement t<sub>r</sub>(5 %) ?",
 v="1. Valeur <b>initiale</b> et <b>finale</b>.<br>2. Variation Δ = finale − initiale.<br>3. Seuil = initiale + <b>0,95 Δ</b>.<br>4. Horizontale au seuil → intersection → lire t. <b>Laisser les traits de construction.</b>"),
dict(t="m", o="§7 Méthode — Justifier un choix de capteur",
 r="Comment justifier le choix d'un capteur à partir d'une documentation ?",
 v="1. Relever l'<b>exigence</b> de l'énoncé.<br>2. Relever la <b>caractéristique</b> correspondante.<br>3. <b>Comparer chiffres à l'appui</b> (étendue, sensibilité, linéarité, temps de réponse).<br>4. <b>Conclure</b> : convient / ne convient pas car…"),
]

# =====================================================================
CARTES["ch15"] = [
dict(t="n", o="§1 Chronogramme",
 r="La fréquence se lit-elle sur un chronogramme ?",
 v="Non : on lit la <b>période T</b> et on calcule <b>f = 1/T</b> (attention ms → s)."),
dict(t="n", o="§2 Continue et alternative",
 r="De quoi se compose tout signal périodique ?",
 v="D'une <b>composante continue</b> (sa valeur moyenne) + une <b>composante alternative</b> (de valeur moyenne nulle)."),
dict(t="n", o="§3 La valeur moyenne",
 r="Définir la valeur moyenne d'un signal périodique. Raccourci si le motif est symétrique ?",
 v="L'<b>aire algébrique</b> sous la courbe sur une période, divisée par la période. Motif symétrique : c'est l'<b>axe de symétrie</b>.<br>Créneau : ⟨u⟩ = α U<sub>max</sub>."),
dict(t="n", o="§4 La valeur efficace",
 r="Énoncer la définition de la valeur efficace.",
 v="La valeur de la <b>tension continue</b> qui dissiperait <b>la même puissance</b> dans la même résistance."),
dict(t="n", o="§4 La valeur efficace",
 r="U<sub>eff</sub> = U<sub>max</sub>/√2 : est-ce valable pour tout signal ?",
 v="<b>Non</b> : seulement pour un signal <b>sinusoïdal</b>. Faux pour un créneau."),
dict(t="n", o="§4 Relation générale",
 r="Relation entre valeur efficace totale, valeur moyenne et valeur efficace de la composante alternative ?",
 v="<b>U<sub>eff</sub>² = ⟨u⟩² + U<sub>eff,alt</sub>²</b> (valable pour tout signal périodique)."),
dict(t="n", o="§5 Fondamental et harmoniques",
 r="Qu'est-ce que le fondamental ? les harmoniques ?",
 v="<b>Fondamental</b> : sinusoïde de fréquence <b>f<sub>1</sub></b> = celle du signal.<br><b>Harmoniques</b> : fréquences <b>f<sub>n</sub> = n × f<sub>1</sub></b>."),
dict(t="n", o="§5 Le spectre",
 r="Sur un spectre d'amplitude, que représente la raie à 0 Hz ? la première raie non nulle ?",
 v="Raie à 0 Hz : la <b>composante continue</b> (valeur moyenne).<br>Première raie non nulle : le <b>fondamental</b>."),
dict(t="n", o="§6 Mesurer",
 r="Quelle position du voltmètre pour une valeur moyenne ? pour la vraie valeur efficace ?",
 v="Valeur moyenne : <b>DC</b>.<br>Valeur efficace vraie : <b>AC+DC</b> sur un voltmètre <b>TRMS</b> (AC suffit sans composante continue)."),
# --- méthodes
dict(t="m", o="§3 Méthode — Valeur moyenne",
 r="Comment déterminer une valeur moyenne sur un chronogramme ?",
 v="1. Repérer une <b>période</b>.<br>2. Chercher une <b>symétrie</b> horizontale (axe = valeur moyenne).<br>3. Sinon, découper en rectangles/triangles, aires algébriques ÷ T.<br>4. Contrôler : entre u<sub>min</sub> et u<sub>max</sub>."),
dict(t="m", o="§4 Relation générale",
 r="⟨u⟩ = 12 V et composante alternative de valeur efficace 5,66 V. Comment trouver U<sub>eff</sub> ?",
 v="1. U<sub>eff</sub>² = ⟨u⟩² + U<sub>eff,alt</sub>².<br>2. = 12² + 5,66² = 176.<br>3. U<sub>eff</sub> = √176 = <b>13,3 V</b>."),
dict(t="m", o="§5 Méthode — Exploiter un spectre",
 r="Comment exploiter un spectre d'amplitude ?",
 v="1. Raie à <b>0 Hz</b> : valeur moyenne.<br>2. <b>Fondamental</b> : première raie non nulle.<br>3. <b>Rang</b> d'un harmonique = f / f<sub>1</sub> (250 Hz avec f<sub>1</sub> = 50 Hz → rang 5).<br>4. Lire les amplitudes (vérifier l'unité de l'axe)."),
dict(t="m", o="§6 Méthode — Réglage du voltmètre",
 r="Comment répondre à « indiquer le réglage du voltmètre » ?",
 v="1. Grandeur demandée : moyenne ou efficace ?<br>2. Moyenne → <b>DC</b>.<br>3. Efficace vraie → <b>AC+DC</b>, appareil <b>TRMS</b>.<br>4. Nommer l'appareil <b>et</b> sa position."),
]

# =====================================================================
CARTES["ch16"] = [
dict(t="n", o="Introduction",
 r="Qu'est-ce que le conditionnement ? Quels sont les trois problèmes qu'il règle ?",
 v="L'ensemble des étages qui rendent exploitable la sortie brute d'un capteur. La sortie n'est <b>pas une tension</b> ; elle est <b>trop faible</b> ; il faut en tirer une <b>décision</b>. Un étage par problème."),
dict(t="n", o="§1 Le diviseur de tension",
 r="Formule du diviseur de tension avec un capteur résistif R(θ) en série avec R<sub>1</sub> ?",
 v="<b>u = E × R(θ) / (R<sub>1</sub> + R(θ))</b> (tension prise aux bornes du capteur). Contrôle : u &lt; E."),
dict(t="n", o="§2 Le pont de Wheatstone",
 r="Qu'est-ce qu'un pont de Wheatstone ? Quand est-il équilibré ?",
 v="La <b>différence de deux diviseurs de tension</b> : le décalage disparaît. <b>Équilibré</b> quand la tension de sortie est <b>nulle</b>."),
dict(t="n", o="§2 Diviseur ou pont",
 r="Quand choisir un pont plutôt qu'un diviseur ?",
 v="Quand la variation est <b>minuscule</b> devant la valeur au repos (jauge, ≈ 1/1000) → <b>pont</b>. Variation de quelques dizaines de % (Pt100) → <b>diviseur</b>."),
dict(t="n", o="§3 L'amplification",
 r="Définir le coefficient d'amplification A. Unité ? Signe pour un inverseur ?",
 v="<b>A = Δu<sub>s</sub> / Δu<sub>e</sub></b>, pente de la partie linéaire, <b>sans unité</b>. Pente descendante → <b>inverseur</b>, A &lt; 0."),
dict(t="n", o="§3 La saturation",
 r="Qu'est-ce que la saturation d'un amplificateur ? Conséquence sur le choix de A ?",
 v="Sa sortie reste <b>bloquée</b> quelle que soit l'entrée : il ne mesure plus rien. On choisit A pour que la pleine échelle du capteur arrive <b>juste avant</b> la saturation."),
dict(t="n", o="§4 Le comparateur simple",
 r="Que fait un comparateur simple ? Nature de sa sortie ?",
 v="Il compare la tension d'entrée à un <b>seuil</b> et bascule. Sortie à <b>deux valeurs</b> : signal <b>logique</b>."),
dict(t="n", o="§5 Le comparateur à hystérésis",
 r="Qu'est-ce qu'un comparateur à hystérésis (trigger de Schmitt) ?",
 v="Un comparateur à <b>deux seuils</b> distincts (montée et descente). Entre les deux, la sortie <b>conserve son état</b>."),
dict(t="n", o="§6 La chaîne type",
 r="Quelle est la chaîne de conditionnement type ?",
 v="Capteur → <b>diviseur</b> → <b>soustracteur</b> → <b>amplificateur</b> → <b>comparateur</b>."),
# --- méthodes
dict(t="m", o="§1 Méthode — Diviseur de tension",
 r="Comment exploiter un diviseur de tension avec un capteur ?",
 v="1. Repérer les deux résistances en série, identifier le <b>capteur</b>.<br>2. u = E × R<sub>capteur</sub> / R<sub>totale</sub>.<br>3. Calculer R du capteur à la valeur demandée (loi du capteur).<br>4. Vérifier <b>0 &lt; u &lt; E</b>."),
dict(t="m", o="§3 Méthode — Caractéristique de transfert",
 r="Comment exploiter la caractéristique de transfert d'un amplificateur ?",
 v="1. Repérer la <b>partie linéaire</b> et les <b>paliers de saturation</b>.<br>2. Pente sur deux points éloignés → A.<br>3. <b>Signe</b> : montante = non inverseur, descendante = inverseur.<br>4. Lire le <b>domaine d'utilisation</b> en entrée."),
dict(t="m", o="§5 Méthode — Justifier l'hystérésis",
 r="Comment justifier le choix d'un comparateur à hystérésis ?",
 v="1. <b>Défaut</b> du simple : près du seuil, le bruit fait basculer plusieurs fois.<br>2. <b>Conséquence</b> : relais qui claque, usure, clignotement.<br>3. <b>Remède</b> : deux seuils, zone insensible au bruit.<br>4. <b>Compromis</b> : plus de seuil unique."),
]

# =====================================================================
CARTES["ch17"] = [
dict(t="n", o="§1 Pourquoi filtrer",
 r="Que fait un filtre ? À quelle condition peut-il séparer deux signaux ?",
 v="Il <b>trie les composantes selon leur fréquence</b>. Il ne sépare deux signaux que si leurs <b>fréquences diffèrent</b>."),
dict(t="n", o="§1 Le gabarit",
 r="Quel type de filtre si l'utile est en bas du spectre ? en haut ? au milieu ?",
 v="En bas : <b>passe-bas</b> ; en haut : <b>passe-haut</b> ; encadré : <b>passe-bande</b>. Fréquence de coupure <b>entre</b> les groupes de raies."),
dict(t="n", o="§2 Le gain en décibels",
 r="Formule du gain en décibels ? Formule inverse ?",
 v="<b>G = 20 log(u<sub>s</sub>/u<sub>e</sub>)</b> ; <b>u<sub>s</sub>/u<sub>e</sub> = 10<sup>G/20</sup></b>.<br>Repères : −3 dB → 0,71 ; −20 dB → 0,10. G &lt; 0 : atténuation."),
dict(t="n", o="§3 Fréquence de coupure",
 r="Définir la fréquence de coupure d'un filtre. Qu'est-ce que la bande passante ?",
 v="f<sub>c</sub> : le gain a chuté de <b>3 dB</b> sous le palier (amplitude ÷ √2).<br>Bande passante : fréquences où G &gt; −3 dB (passe-bas : de 0 à f<sub>c</sub>)."),
dict(t="n", o="§3 Axe logarithmique",
 r="Quel piège sur l'axe des fréquences d'un diagramme de Bode ?",
 v="Il est <b>logarithmique</b> : chaque intervalle = × 10. Entre 10 et 100 Hz, le milieu vaut ≈ <b>32 Hz</b>, pas 55."),
dict(t="n", o="§4 Spectre de sortie",
 r="Un filtre peut-il créer ou déplacer une fréquence ?",
 v="<b>Non</b> : mêmes raies aux mêmes fréquences ; seules leurs <b>hauteurs</b> changent."),
dict(t="n", o="§5 Quantum d'un CAN",
 r="Définir le quantum (résolution) d'un CAN. Formule ?",
 v="La plus petite variation de tension distinguée : <b>q = PE / 2<sup>n</sup></b> (PE pleine échelle, n bits)."),
dict(t="n", o="§5 Améliorer la résolution",
 r="Quels sont les deux leviers pour améliorer la résolution d'un CAN ?",
 v="<b>Ajouter des bits</b> (chaque bit divise q par 2) ou <b>réduire la pleine échelle</b>. Inutile au-delà de la précision du capteur."),
dict(t="n", o="§6 Échantillonneur bloqueur",
 r="Rôle de l'échantillonneur bloqueur ?",
 v="Il <b>maintient la tension constante</b> pendant la conversion, pour que le nombre corresponde à un <b>instant précis</b>."),
dict(t="n", o="§7 Le CNA",
 r="Que fait un CNA ? Tension de sortie ? Caractéristiques à lire sur sa documentation ?",
 v="Il transforme un nombre N en tension <b>u = q × N</b> (par paliers).<br>Doc : <b>résolution</b>, <b>non-linéarité</b>, <b>temps de conversion</b>."),
# --- méthodes
dict(t="m", o="§1 Méthode — Choisir le gabarit",
 r="Comment choisir le gabarit d'un filtre ?",
 v="1. Lire le <b>spectre d'entrée</b>.<br>2. Repérer raies <b>utiles</b> et raies à éliminer.<br>3. En déduire passe-bas, passe-haut ou passe-bande.<br>4. Placer f<sub>c</sub> <b>entre</b> les deux groupes."),
dict(t="m", o="§3 Méthode — f<sub>c</sub> à −3 dB",
 r="Comment déterminer graphiquement la fréquence de coupure sur un diagramme de Bode ?",
 v="1. Gain du <b>palier</b>.<br>2. Descendre de <b>3 dB</b>, tracer l'horizontale.<br>3. Intersection avec la courbe, descendre sur l'axe.<br>4. Lire (échelle <b>log</b>).<br>5. <b>Laisser les traits</b>."),
dict(t="m", o="§4 Méthode — Spectre de sortie",
 r="Comment construire le spectre de sortie d'un filtre ?",
 v="1. Pour chaque raie d'entrée :<br>2. Lire le gain G du filtre à sa fréquence.<br>3. Rapport = 10<sup>G/20</sup>.<br>4. Nouvelle amplitude = amplitude × rapport, <b>même fréquence</b>."),
dict(t="m", o="§5 Exemple — Quantum",
 r="CAN 12 bits, pleine échelle 10,0 V, chaîne à 0,10 V/°C. Comment trouver la résolution en °C ?",
 v="1. q = 10,0 / 2<sup>12</sup> = 10,0/4096 = <b>2,44 mV</b>.<br>2. En °C : 2,44 × 10<sup>−3</sup> / 0,10 = <b>0,024 °C</b>."),
]

# =====================================================================
CARTES["ch18"] = [
dict(t="n", o="§1 La chaîne de transmission",
 r="Quels sont les cinq maillons d'une chaîne de transmission ? Que subit le signal sur le canal ?",
 v="<b>Source</b> → <b>émetteur</b> (codage) → <b>canal</b> → <b>récepteur</b> (décodage) → <b>destinataire</b>. Le canal ajoute <b>atténuation et parasites</b>."),
dict(t="n", o="§2 Les types de transmission",
 r="Transmission analogique et numérique : différence ? Laquelle résiste mieux aux parasites ?",
 v="<b>Analogique</b> : une grandeur varie continûment (4-20 mA).<br><b>Numérique</b> : suite de bits. Le <b>numérique</b> résiste mieux : deux niveaux à distinguer."),
dict(t="n", o="§3 Indice de réfraction",
 r="Définir l'indice de réfraction. Unité ? Valeur minimale ?",
 v="<b>n = c / v</b> (c = 3,00 × 10<sup>8</sup> m/s). <b>Sans unité</b>, <b>≥ 1</b>. Verre n = 1,50 → v = 2,00 × 10<sup>8</sup> m/s."),
dict(t="n", o="§4 Réflexion et réfraction",
 r="Lois de la réflexion et de la réfraction ? Par rapport à quoi mesure-t-on les angles ?",
 v="Réflexion : <b>r = i<sub>1</sub></b>.<br>Réfraction : <b>n<sub>1</sub> sin i<sub>1</sub> = n<sub>2</sub> sin i<sub>2</sub></b>.<br>Angles mesurés par rapport à la <b>normale</b>."),
dict(t="n", o="§4 Réfraction",
 r="En passant dans un milieu d'indice plus grand, le rayon se rapproche ou s'écarte de la normale ?",
 v="Il se <b>rapproche</b> de la normale."),
dict(t="n", o="§5 La réflexion totale",
 r="Angle limite ? Quand y a-t-il réflexion totale ?",
 v="<b>sin i<sub>lim</sub> = n<sub>2</sub> / n<sub>1</sub></b>, seulement vers un milieu d'indice <b>plus faible</b>. Incidence &gt; i<sub>lim</sub> → <b>réflexion totale</b>."),
dict(t="n", o="§6 La fibre optique",
 r="Comment une fibre optique guide-t-elle la lumière ? Condition sur les indices ?",
 v="Par <b>réflexions totales successives</b> à la frontière cœur-gaine : <b>n<sub>cœur</sub> &gt; n<sub>gaine</sub></b>."),
dict(t="n", o="§6 Ouverture numérique",
 r="Ouverture numérique d'une fibre ?",
 v="<b>sin θ<sub>max</sub> = √(n<sub>1</sub>² − n<sub>2</sub>²)</b> : seuls les rayons entrant avec θ ≤ θ<sub>max</sub> sont guidés."),
dict(t="n", o="§6 L'atténuation",
 r="Atténuation d'une fibre : formule ? Rapport de puissance ?",
 v="<b>A = α × L</b> (dB) ; <b>P<sub>s</sub>/P<sub>e</sub> = 10<sup>−A/10</sup></b>. En puissance : 10 log (pas 20). 3 dB = moitié de la puissance."),
dict(t="n", o="§6 Atouts de la fibre",
 r="Atouts de la fibre optique en milieu industriel ?",
 v="<b>Insensible aux parasites</b> électromagnétiques, débit très élevé, grandes distances, <b>isolation électrique</b>."),
dict(t="n", o="§7 La transmission numérique",
 r="Débit binaire et durée d'un bit ? Que contient une trame série ?",
 v="<b>D</b> en bit/s ; <b>T<sub>b</sub> = 1/D</b>.<br>Trame : <b>start</b> (0), 8 bits de données (poids faible en premier), <b>parité</b> éventuelle, <b>stop</b> (1)."),
dict(t="n", o="§7 Débit et distance",
 r="Comment varient débit et distance d'une liaison (RS-485) ?",
 v="En <b>sens contraire</b> : 10 Mbit/s sur quelques mètres, ≈ 100 kbit/s sur 1200 m."),
# --- méthodes
dict(t="m", o="§1 Méthode — Identifier les maillons",
 r="Transmetteur 4-20 mA sur une cuve, paire de fils, entrée automate. Comment identifier les maillons ?",
 v="1. <b>Source</b> : le niveau.<br>2. <b>Émetteur</b> : le transmetteur (code en courant).<br>3. <b>Canal</b> : la paire de fils.<br>4. <b>Récepteur</b> : l'entrée analogique.<br>5. <b>Destinataire</b> : l'automate et l'opérateur."),
dict(t="m", o="§4 Méthode — Angle de réfraction",
 r="Rayon air → verre (n = 1,50) sous 40°. Comment trouver l'angle de réfraction ?",
 v="1. n<sub>1</sub> sin i<sub>1</sub> = n<sub>2</sub> sin i<sub>2</sub>.<br>2. sin i<sub>2</sub> = 1,00 × sin 40° / 1,50 = 0,429.<br>3. sin<sup>−1</sup> (calculatrice en <b>degrés</b>) : <b>i<sub>2</sub> = 25,4°</b>.<br>4. i<sub>2</sub> &lt; i<sub>1</sub> : cohérent."),
dict(t="m", o="§5 Méthode — Réflexion totale",
 r="Rayon verre (1,50) → air sous 55°. Comment prévoir s'il y a réflexion totale ?",
 v="1. Vers un indice plus faible : possible.<br>2. sin i<sub>lim</sub> = 1,00/1,50 → <b>i<sub>lim</sub> = 41,8°</b>.<br>3. 55° &gt; 41,8° → <b>réflexion totale</b>."),
dict(t="m", o="§7 Méthode — Durée de transmission",
 r="9600 bit/s, trames de 11 bits, 120 octets. Comment calculer la durée de transmission ?",
 v="1. T<sub>b</sub> = 1/9600 = 104 µs.<br>2. Trame : 11 × 104 µs = 1,15 ms.<br>3. Total : 120 × 1,15 = <b>138 ms</b>.<br>4. Débit utile : 9600 × 8/11 ≈ 6980 bit/s."),
]

# =====================================================================
CARTES["ch19"] = [
dict(t="n", o="§1 Réponse indicielle",
 r="Qu'est-ce que la réponse indicielle d'un système ? Quels sont ses deux régimes ?",
 v="La réponse de la sortie à un <b>échelon</b> d'entrée. Un <b>régime transitoire</b> (la sortie évolue) puis un <b>régime permanent</b> (elle ne varie plus)."),
dict(t="n", o="§1 Transmittance statique",
 r="Définir la transmittance statique K. Unité ?",
 v="<b>K = Δs / Δe</b> en régime permanent. Unité : celle de la sortie / celle de l'entrée."),
dict(t="n", o="§2 Le premier ordre",
 r="Premier ordre : que vaut la sortie à t = τ ? Temps de réponse à 5 % ? Dépassement ?",
 v="À t = τ : <b>63 %</b> de la variation. <b>t<sub>5%</sub> = 3τ</b>. <b>Aucun dépassement</b>.<br>Ex. : four, charge d'un condensateur, montée en vitesse d'un moteur."),
dict(t="n", o="§3 Le second ordre",
 r="Second ordre : rôle du coefficient d'amortissement m ? Meilleur compromis ?",
 v="Plus m est <b>petit</b>, plus la réponse <b>oscille et dépasse</b>. m ≥ 1 : apériodique mais lente. Compromis : <b>m ≈ 0,7</b>."),
dict(t="n", o="§3 Dépassement",
 r="Formule du dépassement D ? Où lire le temps de réponse à 5 % ?",
 v="<b>D = (s<sub>max</sub> − s<sub>∞</sub>) / (s<sub>∞</sub> − s<sub>0</sub>)</b>.<br>t<sub>5%</sub> : au <b>dernier</b> passage dans la bande ± 5 %."),
dict(t="n", o="§4 Réponse en fréquence du 1er ordre",
 r="Fréquence de coupure d'un premier ordre ? Lien avec τ ?",
 v="Gain baissé de <b>3 dB</b> ; <b>f<sub>c</sub> = 1 / (2π τ)</b>. Système rapide (petit τ) → f<sub>c</sub> élevée."),
dict(t="n", o="§5 La résonance",
 r="Qu'est-ce que la résonance d'un second ordre peu amorti ? Effet de m ?",
 v="Le gain passe par un <b>maximum</b> près de la fréquence propre f<sub>0</sub>. Plus m est petit, plus le pic est <b>haut et étroit</b>."),
dict(t="n", o="§5 Fréquences propres",
 r="Fréquence propre d'un système masse-ressort ? d'un circuit LC ?",
 v="Masse-ressort : <b>f<sub>0</sub> = (1/2π) √(k/m)</b>.<br>LC : <b>f<sub>0</sub> = 1 / (2π √(LC))</b>."),
dict(t="n", o="§6 Se protéger d'une résonance",
 r="Quels sont les trois leviers contre une résonance dangereuse ?",
 v="<b>Éloigner</b> la fréquence d'excitation de f<sub>0</sub> (vitesse, raideur, masse) ; <b>amortir</b> ; <b>traverser vite</b> la zone critique au démarrage."),
# --- méthodes
dict(t="m", o="§2 Méthode — Premier ordre",
 r="Four : échelon 0 → 3,0 kW, température 20 → 80 °C, 57,8 °C à 12 min. Comment trouver K, τ, t<sub>5%</sub> ?",
 v="1. K = 60/3,0 = <b>20 °C/kW</b>.<br>2. 63 % de la variation : 20 + 0,63 × 60 = 57,8 °C → <b>τ = 12 min</b>.<br>3. <b>t<sub>5%</sub> = 3τ = 36 min</b>."),
dict(t="m", o="§3 Méthode — Second ordre",
 r="Consigne 0 → 5 V, position 0 → 200 mm, maximum 236 mm. Comment trouver K et D ?",
 v="1. K = 200/5 = <b>40 mm/V</b>.<br>2. D = (236 − 200)/(200 − 0) = <b>18 %</b>.<br>3. t<sub>5%</sub> : dernier passage dans [190 ; 210] mm."),
dict(t="m", o="§5 Méthode — Risque de résonance",
 r="Moteur de 40 kg sur plots (k = 1,6 × 10<sup>6</sup> N/m), 1900 tr/min. Comment repérer un risque de résonance ?",
 v="1. f<sub>0</sub> = (1/2π) √(k/m) = <b>31,8 Hz</b>.<br>2. Excitation : 1900/60 = <b>31,7 Hz</b>.<br>3. Égales → <b>résonance</b> : changer les plots ou la vitesse."),
]

# =====================================================================
CARTES["ch20"] = [
dict(t="n", o="§1 Boucle ouverte, boucle fermée",
 r="Différence entre boucle ouverte et boucle fermée ?",
 v="<b>Ouverte</b> : commande fixée d'avance, aucune correction des perturbations.<br><b>Fermée</b> : un capteur mesure la sortie, on la compare à la consigne, l'<b>écart fixe la commande</b>."),
dict(t="n", o="§1 Intérêt de la boucle fermée",
 r="Intérêt et prix d'un système bouclé ?",
 v="Intérêt : <b>compenser les perturbations</b> et <b>suivre la consigne</b>. Prix : un capteur et un <b>risque d'instabilité</b>."),
dict(t="n", o="§2 Le schéma blocs",
 r="Éléments d'un schéma blocs de régulation ? Que calcule le comparateur ?",
 v="<b>Consigne</b> w ; <b>comparateur</b> : erreur <b>ε = w − m</b> ; <b>chaîne directe</b> (correcteur, actionneur, procédé) → sortie y ; <b>chaîne de retour</b> (capteur) → mesure m."),
dict(t="n", o="§3 Critères de performance",
 r="Quels sont les critères de performance d'une boucle ?",
 v="<b>Stabilité</b>, <b>précision</b> (erreur statique ε<sub>∞</sub> = consigne − sortie en régime permanent), <b>rapidité</b> (t<sub>5%</sub>), <b>dépassement</b>."),
dict(t="n", o="§3 Instabilité",
 r="Que se passe-t-il pour un système instable ?",
 v="Ses <b>oscillations grandissent</b> jusqu'à une butée, une protection ou une casse : le défaut le plus grave."),
dict(t="n", o="§4 Le correcteur PI",
 r="Correcteur PI : rôle de l'action proportionnelle ? de l'action intégrale ?",
 v="<b>Proportionnelle</b> (K<sub>p</sub>) : la <b>rapidité</b>.<br><b>Intégrale</b> (T<sub>i</sub>) : <b>annule l'erreur statique</b>.<br>Forcer l'une ou l'autre → instabilité : réglage = compromis."),
dict(t="n", o="§5 Régulation tout ou rien",
 r="Régulation TOR avec hystérésis : comportement ? Effet d'une hystérésis plus large ?",
 v="La grandeur <b>oscille en permanence</b> entre seuil bas et seuil haut. Hystérésis plus large : oscillations <b>plus amples</b> mais <b>moins de commutations</b> (moins d'usure)."),
# --- méthodes
dict(t="m", o="§2 Méthode — Identifier les blocs",
 r="Régulation de niveau d'une cuve (capteur de pression, automate, pompe, soutirage). Comment identifier les blocs ?",
 v="1. <b>Sortie</b> : le niveau ; <b>consigne</b> : le niveau demandé.<br>2. <b>Retour</b> : capteur de pression.<br>3. <b>Comparateur, correcteur</b> : automate.<br>4. <b>Actionneur</b> : pompe + variateur ; <b>procédé</b> : la cuve.<br>5. <b>Perturbation</b> : le soutirage."),
dict(t="m", o="§3 Méthode — Performances d'une boucle",
 r="Consigne 1500 tr/min ; max 1650, finale 1440, dans ± 5 % à 2,5 s. Comment lire les performances ?",
 v="1. Se stabilise → <b>stable</b>.<br>2. ε<sub>∞</sub> = 1500 − 1440 = <b>60 tr/min</b> (4 %).<br>3. D = (1650 − 1440)/1440 = <b>15 %</b>.<br>4. <b>t<sub>5%</sub> = 2,5 s</b>."),
dict(t="m", o="§5 Méthode — Thermostat",
 r="Consigne 60 °C, hystérésis 4 °C, montée 2 °C/min, descente 1 °C/min. Comment prévoir le fonctionnement ?",
 v="1. Seuils : arrêt à <b>62 °C</b>, reprise à <b>58 °C</b>.<br>2. Chauffe 4/2 = 2 min ; arrêt 4/1 = 4 min → cycle de <b>6 min</b>.<br>3. 10 cycles/h → <b>20 manœuvres</b>.<br>4. Hystérésis doublée : 2 fois moins de manœuvres."),
]
