# -*- coding: utf-8 -*-
# Cartes de révision écrites à la main — BTS Électrotechnique
FILIERE = "bts-et"
NIVEAU = "BTS ET"

CARTES = {}

# =====================================================================
# Cours 1 — Énergie interne et transferts thermiques
CARTES["c01"] = [
dict(t="n", o="§1 Les deux échelles",
 r="Relation entre température absolue T et température Celsius θ ? Que représente 0 K ?",
 v="<b>T (K) = θ (°C) + 273</b><br>0 K = −273 °C : le <b>zéro absolu</b>, arrêt de l'agitation microscopique (inatteignable)."),
dict(t="n", o="§1 Un écart n'est pas une température",
 r="Un écart de 40 °C vaut combien de kelvins ? Quelle formule du chapitre exige T en kelvins ?",
 v="<b>40 K</b> : le décalage de 273 disparaît dans la soustraction.<br>Seule la <b>loi de Stefan</b> exige la température absolue en K."),
dict(t="n", o="§1 Trois capteurs industriels",
 r="Pt100, thermocouple, CTN : principe et usage de chacun ?",
 v="<b>Pt100</b> : résistance du platine qui varie — linéaire, précise (régulation).<br><b>Thermocouple</b> : tension au contact de deux métaux — jusqu'à 1300 °C.<br><b>CTN</b> : résistance qui chute quand θ monte — non linéaire, pour les seuils."),
dict(t="n", o="§2 Énergie interne",
 r="Qu'est-ce que l'énergie interne U d'un système ? Que traduit la température ?",
 v="La <b>somme des énergies de ses constituants microscopiques</b>. La température en est la traduction macroscopique (agitation des particules)."),
dict(t="n", o="§2 Les deux façons de transférer de l'énergie",
 r="Sous quelles formes un système échange-t-il de l'énergie avec l'extérieur ?",
 v="Uniquement par <b>travail</b> ou par <b>chaleur</b>. Il n'y a pas de troisième voie."),
dict(t="n", o="§3 E = P × t",
 r="Énergie consommée par un appareil de puissance P pendant t ? Unités ?",
 v="<b>E = P × t</b> : E en J, P en W, t en <b>s</b>.<br>(P en kW et t en h → kWh ; 1 kWh = 3,6 MJ.) On ne mélange jamais les deux systèmes."),
dict(t="n", o="§3 Q et E sont la même grandeur",
 r="Pourquoi note-t-on Q l'énergie reçue par un corps chauffé ?",
 v="Q est une <b>énergie, en joules</b>, comme E. La lettre indique seulement le chemin : un <b>transfert thermique</b> (chaleur), pas un travail."),
dict(t="n", o="§4 Capacité thermique massique",
 r="Définir la capacité thermique massique c. Unité ?",
 v="L'énergie nécessaire pour élever de <b>1 degré</b> la température de <b>1 kg</b> du corps. En <b>J·kg<sup>−1</sup>·K<sup>−1</sup></b>."),
dict(t="n", o="§4 Échauffer un corps",
 r="Énergie pour échauffer une masse m de θ<sub>i</sub> à θ<sub>f</sub> ? Valeur de c pour l'eau ?",
 v="<b>Q = m c Δθ = m c (θ<sub>f</sub> − θ<sub>i</sub>)</b><br>Eau : <b>c ≈ 4185 J·kg<sup>−1</sup>·K<sup>−1</sup></b>."),
dict(t="n", o="§4 Le signe porte l'information",
 r="Que signifie Q &lt; 0 dans Q = m c Δθ ?",
 v="Le corps a <b>cédé</b> de l'énergie (il s'est refroidi). On ne corrige pas le signe, on le lit."),
dict(t="n", o="§5 Chaleur latente",
 r="Définir la chaleur latente L. Énergie pour changer d'état une masse m ?",
 v="L'énergie pour faire changer d'état <b>1 kg</b> de corps, <b>à température constante</b>, en J/kg.<br><b>Q = m L</b>"),
dict(t="n", o="§5 Lire une courbe de chauffe",
 r="Sur une courbe de chauffe θ(t), que représentent les pentes et les paliers ?",
 v="<b>Pentes</b> : la température monte, Q = m c Δθ.<br><b>Paliers</b> : changement d'état, Q = m L, la température ne bouge pas."),
dict(t="n", o="§6 Les trois modes de transfert",
 r="Conduction, convection, rayonnement : définition et exemple sur une armoire ?",
 v="<b>Conduction</b> : de proche en proche dans la matière (la tôle chauffe).<br><b>Convection</b> : par déplacement d'un fluide (le ventilateur).<br><b>Rayonnement</b> : sans support, par ondes électromagnétiques (caméra thermique)."),
dict(t="n", o="§7 Flux thermique",
 r="Flux thermique à travers une paroi plane : formule et unités ?",
 v="<b>Φ = λ S (θ<sub>1</sub> − θ<sub>2</sub>) / e = Δθ / R<sub>th</sub></b><br>Φ en W, λ en W·m<sup>−1</sup>·K<sup>−1</sup>, S en m², e en m."),
dict(t="n", o="§7 Résistance thermique",
 r="Résistance thermique d'une paroi ? Comment se combinent plusieurs couches ?",
 v="<b>R<sub>th</sub> = e / (λ S)</b>, en K/W.<br>Couches superposées : les résistances <b>s'ajoutent en série</b>, le flux est le même dans toutes."),
dict(t="n", o="§7 L'analogie électrique",
 r="Dans l'analogie thermique/électrique, à quoi correspondent le flux et l'écart de température ?",
 v="Flux Φ ↔ <b>courant</b> ; écart Δθ ↔ <b>tension</b> ; R<sub>th</sub> ↔ résistance."),
dict(t="n", o="§7 Isoler une armoire qui chauffe",
 r="Faut-il isoler une armoire électrique dont les équipements chauffent ?",
 v="<b>Non</b> : l'isolant empêche aussi la chaleur de <b>sortir</b>. Avec une source interne, isoler aggrave l'échauffement."),
dict(t="n", o="§8 Loi de Stefan",
 r="Puissance rayonnée (émise) par une surface : formule ?",
 v="<b>P = ε σ S T<sup>4</sup></b>, σ = 5,67 × 10<sup>−8</sup> W·m<sup>−2</sup>·K<sup>−4</sup>, ε émissivité (0 à 1), <b>T en kelvins</b>.<br>Doubler T multiplie P par 16."),
dict(t="n", o="§8 Le corps noir",
 r="Qu'est-ce qu'un corps noir ?",
 v="La surface idéale qui <b>absorbe tout</b> ce qu'elle reçoit. C'est aussi le <b>meilleur émetteur</b> à température égale : <b>ε = 1</b>."),
dict(t="n", o="§8 Ce que mesure une caméra thermique",
 r="Que mesure réellement une caméra thermique ? Que faut-il lui fournir ?",
 v="Un <b>rayonnement</b>, pas une température. Il faut lui donner l'<b>émissivité</b> de la surface (cuivre brillant ε ≈ 0,05 : pastille mate)."),
dict(t="n", o="§8 Bilan et rendement",
 r="Bilan énergétique d'un convertisseur ? Sous quelle forme se retrouvent les pertes ?",
 v="<b>W<sub>a</sub> = W<sub>u</sub> + W<sub>p</sub></b>, <b>η = W<sub>u</sub> / W<sub>a</sub></b>. Les pertes sont <b>intégralement thermiques</b> (95 % sur 100 kW → 5 kW à évacuer)."),
# --- méthodes
dict(t="m", o="§4 Méthode — Dimensionner un préparateur d'eau chaude",
 r="Comment trouver la puissance pour chauffer 200 L d'eau de 12 à 60 °C en 2 h ?",
 v="1. Masse : 200 L d'eau → <b>200 kg</b>.<br>2. Q = m c Δθ = 200 × 4185 × 48 = <b>4,02 × 10<sup>7</sup> J</b>.<br>3. P = Q / t = 4,02 × 10<sup>7</sup> / 7200 = <b>5580 W</b>.<br>4. Choisir 6 kW normalisé, vérifier I = 6000/230 = 26 A."),
dict(t="m", o="§5 Courbe de chauffe",
 r="Comment calculer l'énergie pour chauffer puis vaporiser une masse d'eau ?",
 v="1. Chauffage jusqu'à 100 °C : Q<sub>1</sub> = m c (100 − θ<sub>i</sub>).<br>2. Palier : Q<sub>2</sub> = m L<sub>v</sub> (L<sub>v</sub> = 2257 kJ/kg).<br>3. Q = Q<sub>1</sub> + Q<sub>2</sub>, en joules."),
dict(t="m", o="§7 Méthode — Chiffrer la déperdition d'une armoire",
 r="Comment calculer le flux perdu à travers une paroi tôle + isolant ?",
 v="1. R<sub>1</sub> = e<sub>1</sub> / (λ<sub>1</sub> S) pour la tôle.<br>2. R<sub>2</sub> = e<sub>2</sub> / (λ<sub>2</sub> S) pour l'isolant.<br>3. <b>R<sub>th</sub> = R<sub>1</sub> + R<sub>2</sub></b> (série).<br>4. <b>Φ = Δθ / R<sub>th</sub></b>.<br>5. Comparer à la puissance dissipée → ventilation nécessaire ?"),
dict(t="m", o="§8 Loi de Stefan",
 r="Comment calculer la puissance rayonnée par une surface à 60 °C ?",
 v="1. Convertir en kelvins : T = 60 + 273 = <b>333 K</b>.<br>2. Relever ε et S (en m²).<br>3. P = ε σ S T<sup>4</sup>.<br>Laisser T en °C fausse le résultat d'un facteur ~950."),
dict(t="m", o="§8 Thermographie",
 r="Comment mesurer correctement un point chaud à la caméra thermique ?",
 v="1. <b>Régler l'émissivité</b> de la surface (pastille mate si métal brillant).<br>2. Comparer le point suspect à une <b>référence sur la même surface</b>.<br>3. Conclure sur l'<b>écart</b> plutôt que sur une valeur absolue."),
]

# =====================================================================
# TP 1 — Lois générales de l'électricité en régime continu
CARTES["tp01"] = [
dict(t="n", o="§0 Convention d'écriture",
 r="Pourquoi note-t-on U, I, P en majuscules dans ce chapitre ?",
 v="On est en <b>régime continu</b> : les grandeurs ne varient pas. Les minuscules u, i, p sont réservées aux <b>valeurs instantanées</b> d'une grandeur variable."),
dict(t="n", o="§1 Courant électrique",
 r="Qu'est-ce que le courant électrique ? Que mesure son intensité ?",
 v="Un <b>déplacement d'ensemble de porteurs de charge</b>. L'intensité est la charge qui traverse une section par unité de temps : <b>I = Q / t</b>, en A."),
dict(t="n", o="§1 Potentiel et tension",
 r="Relation entre la tension U<sub>AB</sub> et les potentiels ? Qu'est-ce que la masse ?",
 v="<b>U<sub>AB</sub> = V<sub>A</sub> − V<sub>B</sub></b>.<br>La <b>masse</b> est le point de référence dont on fixe le potentiel à <b>0 V</b>."),
dict(t="n", o="§1 Pourquoi cela compte dès le premier TP",
 r="Pourquoi utiliser une sonde différentielle avec l'oscilloscope ?",
 v="Les masses des appareils sont reliées par la <b>terre</b> : deux voies sur deux « bas » différents créent un <b>court-circuit</b>. La sonde différentielle mesure entre deux points quelconques."),
dict(t="n", o="§1 Deux grandeurs, deux branchements",
 r="Comment se branchent l'ampèremètre et le voltmètre ?",
 v="Ampèremètre : <b>en série</b> (le courant traverse).<br>Voltmètre : <b>en dérivation</b>, aux bornes du dipôle."),
dict(t="n", o="§2 Deux règles de fléchage",
 r="Où place-t-on la flèche d'un courant ? d'une tension ? Vers où pointe celle de U<sub>AB</sub> ?",
 v="Courant : <b>sur le fil</b>. Tension : <b>à côté du dipôle</b>.<br>U<sub>AB</sub> pointe vers <b>A</b> (sa première lettre)."),
dict(t="n", o="§2 Les deux conventions",
 r="Conventions récepteur et générateur : sens des flèches de U et I ?",
 v="<b>Récepteur</b> : flèches <b>opposées</b>.<br><b>Générateur</b> : flèches <b>dans le même sens</b>."),
dict(t="n", o="§2 P = U I",
 r="En convention récepteur, que signifie P = U I &gt; 0 ? et P &lt; 0 ?",
 v="P &gt; 0 : le dipôle <b>reçoit</b> de la puissance.<br>P &lt; 0 : il en <b>fournit</b> (ex. moteur qui freine en génératrice).<br>En convention générateur, c'est l'inverse."),
dict(t="n", o="§2 Ce que révèle un signe négatif",
 r="On trouve I = −2,5 A. Que faire ?",
 v="Rien à corriger : le courant circule <b>en sens inverse de la flèche</b> choisie. On garde la valeur et on l'interprète."),
dict(t="n", o="§3 Loi des nœuds",
 r="Énoncer la loi des nœuds.",
 v="En un nœud, la <b>somme des courants qui entrent = somme des courants qui sortent</b>. La charge se conserve."),
dict(t="n", o="§3 Relation de Chasles",
 r="Relation de Chasles pour les tensions ? Tension entre deux points reliés par un fil ?",
 v="<b>U<sub>AC</sub> = U<sub>AB</sub> + U<sub>BC</sub></b><br>Deux points reliés par un fil sont au <b>même potentiel</b> : tension nulle."),
dict(t="n", o="§3 Loi des mailles",
 r="Énoncer la loi des mailles et la règle des signes.",
 v="Sur un tour complet : <b>Σ U = 0</b>.<br>Tension <b>+</b> si sa flèche est dans le sens de parcours, <b>−</b> sinon.<br>Sur une boucle simple : E = U<sub>1</sub> + U<sub>2</sub> + …"),
dict(t="n", o="§4 Série et parallèle",
 r="Quand deux dipôles sont-ils en série ? en parallèle ?",
 v="En <b>série</b> : traversés par <b>le même courant</b>.<br>En <b>parallèle</b> : soumis à <b>la même tension</b>."),
dict(t="n", o="§4 Associer des dipôles",
 r="Résistance équivalente en série ? en parallèle ?",
 v="Série : <b>R<sub>eq</sub> = R<sub>1</sub> + R<sub>2</sub></b><br>Parallèle : <b>1/R<sub>eq</sub> = 1/R<sub>1</sub> + 1/R<sub>2</sub></b> (deux résistances : R<sub>1</sub>R<sub>2</sub>/(R<sub>1</sub>+R<sub>2</sub>)), toujours plus petite que la plus petite."),
dict(t="n", o="§5 Le diviseur de tension",
 r="Formule du diviseur de tension ? À quelle condition est-elle valable ?",
 v="<b>U<sub>2</sub> = U × R<sub>2</sub> / (R<sub>1</sub> + R<sub>2</sub>)</b><br>Seulement si <b>aucun courant ne sort du point milieu</b> (diviseur à vide)."),
dict(t="n", o="§5 Le rhéostat",
 r="Rhéostat câblé sur 2 bornes ou sur 3 bornes : quel usage ?",
 v="<b>2 bornes</b> (extrémité + curseur) : <b>résistance réglable</b> (rhéostat), règle un courant.<br><b>3 bornes</b> : <b>diviseur de tension réglable</b> (potentiomètre), règle une tension : U<sub>S</sub> = U<sub>E</sub> × R<sub>CB</sub>/R<sub>AB</sub>."),
dict(t="n", o="§6 Résistance d'un conducteur",
 r="Résistance d'un conducteur de longueur ℓ et de section S ? Résistivité du cuivre ?",
 v="<b>R = ρ ℓ / S</b> (ρ en Ω·m, ℓ en m, S en m²).<br>Cuivre : <b>1,8 × 10<sup>−8</sup> Ω·m</b> ; aluminium : 2,8 × 10<sup>−8</sup> Ω·m."),
dict(t="n", o="§6 La conversion qui coûte le plus de points",
 r="1 mm² = ? m²",
 v="<b>1 mm² = 10<sup>−6</sup> m²</b> (et non 10<sup>−3</sup>) : une surface se convertit au carré."),
dict(t="n", o="§7 Puissance et énergie",
 r="Puissance d'un dipôle en continu ? Énergie sur une durée t ?",
 v="<b>P = U I</b> (débit d'énergie, en W).<br><b>W = P × t</b> (quantité transférée, en J). Le compteur facture des kWh : 1 kWh = 3,6 MJ."),
dict(t="n", o="§7 L'effet Joule",
 r="Puissance dissipée par effet Joule ? Que se passe-t-il si l'on divise le courant par 2 ?",
 v="<b>P<sub>J</sub> = R I²</b> (chaleur).<br>Les pertes varient comme le <b>carré du courant</b> : I / 2 → pertes / <b>4</b>."),
dict(t="n", o="§8 Les trois vérifications",
 r="Quelles sont les trois vérifications sur le multimètre avant la mise sous tension ?",
 v="1. La <b>fonction</b> (tension/courant, continu/alternatif).<br>2. Les <b>bornes</b> (celle du courant est distincte).<br>3. Le <b>calibre</b>, au-dessus de la valeur attendue puis resserré."),
dict(t="n", o="§8 L'erreur qui détruit le matériel",
 r="Que se passe-t-il si l'on branche un ampèremètre en dérivation sur une source ?",
 v="Sa résistance est quasi nulle : c'est un <b>court-circuit franc</b> (fusible, appareil, opérateur exposés). C'est la seule erreur de branchement dangereuse."),
dict(t="n", o="§8 Boîtes à décades",
 r="Boîte à décades réglée sur 100 Ω : quel courant admissible commande ?",
 v="Celui de la <b>décade la plus contraignante parmi celles affichées</b> (décades en série) : ici ×100 → <b>70 mA</b>. On calcule le courant <b>avant</b> la mise sous tension."),
dict(t="n", o="§8 Valeur efficace vraie",
 r="Définir la valeur efficace d'un courant périodique. Que signifie TRMS ?",
 v="La valeur du <b>courant continu</b> qui dissiperait <b>la même puissance</b> dans la même résistance.<br>Un appareil <b>TRMS</b> la mesure quelle que soit la forme d'onde."),
# --- méthodes
dict(t="m", o="§3 Méthode — Écrire une loi des mailles",
 r="Comment écrire une loi des mailles sans erreur de signe ?",
 v="1. Choisir un <b>point de départ</b> et un <b>sens de parcours</b>, les dessiner.<br>2. Avancer dipôle après dipôle : <b>+U</b> si la flèche est dans le sens de parcours, <b>−U</b> sinon.<br>3. Revenu au départ : somme = 0."),
dict(t="m", o="§3 Méthode — Résoudre un circuit à une maille",
 r="E = 24 V alimente R<sub>1</sub> = 100 Ω et R<sub>2</sub> = 200 Ω en série. Comment trouver I, U<sub>1</sub>, U<sub>2</sub> ?",
 v="1. Orienter I, flécher U<sub>1</sub>, U<sub>2</sub> en convention récepteur.<br>2. Maille : E = (R<sub>1</sub> + R<sub>2</sub>) I.<br>3. I = 24 / 300 = <b>80 mA</b>.<br>4. U<sub>1</sub> = <b>8 V</b>, U<sub>2</sub> = <b>16 V</b>.<br>5. Vérifier : 8 + 16 = 24."),
dict(t="m", o="§5 Méthode — Régler une tension au rhéostat",
 r="Rhéostat 33 Ω sous 15 V, curseur à 40 % de la piste depuis B. Comment trouver U<sub>S</sub> et vérifier le matériel ?",
 v="1. R<sub>CB</sub> = 0,40 × 33 = 13,2 Ω.<br>2. U<sub>S</sub> = 15 × 13,2/33 = <b>6,0 V</b>.<br>3. Courant dans la piste : 15/33 = 0,45 A &lt; courant admissible de la plaque.<br>4. Valable seulement sans charge sur le curseur."),
dict(t="m", o="§7 Méthode — Ce que coûte une canalisation",
 r="Câble cuivre 60 m, 10 mm², 25 A, 2000 h/an. Comment chiffrer les pertes annuelles ?",
 v="1. R = ρ ℓ / S = 1,8 × 10<sup>−8</sup> × 60 / 10 × 10<sup>−6</sup> = <b>0,108 Ω</b>.<br>2. P<sub>J</sub> = R I² = 0,108 × 25² = <b>67,5 W</b>.<br>3. W = 0,0675 kW × 2000 h = <b>135 kWh</b>.<br>4. Coût = W × prix du kWh."),
dict(t="m", o="§8 Mesurer sans casser",
 r="Comment passer d'une mesure de tension à une mesure de courant au multimètre TRG803 ?",
 v="1. Couper l'alimentation.<br>2. Tourner le commutateur sur <b>A</b>.<br>3. <b>Déplacer le cordon</b> de V vers µA mA ou 10 A MAX.<br>4. Insérer l'appareil <b>en série</b>, calibre au-dessus de la valeur attendue."),
]

# =====================================================================
# TP 2 — Dipôles passifs et actifs
CARTES["tp02"] = [
dict(t="n", o="§1 La caractéristique",
 r="Qu'est-ce que la caractéristique d'un dipôle ? De quoi dépend-elle ?",
 v="La courbe du <b>courant en fonction de la tension</b> (ou l'inverse). Elle ne dépend <b>que du dipôle</b>, jamais du circuit."),
dict(t="n", o="§1 Passif ou actif",
 r="Comment reconnaître sur sa caractéristique un dipôle passif ? actif ?",
 v="<b>Passif</b> : la caractéristique <b>passe par l'origine</b>.<br><b>Actif</b> : elle <b>ne passe pas par l'origine</b> (tension imposée à courant nul)."),
dict(t="n", o="§1 Actif ne veut pas dire générateur",
 r="Un dipôle actif fournit-il toujours de la puissance ?",
 v="Non : une batterie en charge est active mais <b>reçoit</b>. C'est le <b>signe de U I</b> dans la convention choisie qui dit le sens du transfert."),
dict(t="n", o="§2 Dipôle ohmique",
 r="Quand un dipôle est-il ohmique ? Relations utiles ?",
 v="Caractéristique = <b>droite passant par l'origine</b>.<br><b>U = R I</b> ; <b>P = U I = R I² = U² / R</b>"),
dict(t="n", o="§2 Dipôle ohmique",
 r="Comment déterminer R à partir d'une caractéristique I(U) relevée ?",
 v="Par la <b>pente</b> (elle vaut <b>1/R</b>), et non par un seul point : cela moyenne les erreurs de mesure."),
dict(t="n", o="§2 Une résistance porte deux valeurs",
 r="Quelles sont les deux valeurs qui caractérisent une résistance ?",
 v="Sa <b>valeur ohmique</b> et sa <b>puissance admissible</b>. Ex. : 47 Ω sous 12 V dissipe 3,1 W, trop pour une 0,25 W ou 2 W."),
dict(t="n", o="§3 Les dipôles non linéaires",
 r="Diode, lampe à filament, varistance : comportement de chacune ?",
 v="<b>Diode</b> : conduit dans <b>un seul sens</b>, au-delà de ~0,6 V (silicium).<br><b>Lampe</b> : R <b>augmente avec la température</b>.<br><b>Varistance</b> : isolante puis brutalement conductrice — <b>limiteur de surtension</b>."),
dict(t="n", o="§3 U/I n'a plus de sens global",
 r="Pourquoi « la résistance d'une lampe » n'a-t-il pas de sens sans précision ?",
 v="R = U/I <b>change d'un point à l'autre</b> : à froid, une lampe a environ <b>1/10</b> de sa résistance à chaud — d'où la pointe de courant à l'allumage."),
dict(t="n", o="§4 Le condensateur",
 r="Relations du condensateur (convention récepteur) ?",
 v="<b>q = C u</b> ; <b>i = C du/dt</b> ; énergie <b>W = ½ C u²</b><br>C en farads (F)."),
dict(t="n", o="§4 Le condensateur",
 r="Quelle grandeur ne peut pas varier brutalement aux bornes d'un condensateur ? Pourquoi ?",
 v="La <b>tension</b> : une variation brutale demanderait un courant infini (i = C du/dt)."),
dict(t="n", o="§4 Un condensateur chargé reste dangereux",
 r="Pourquoi attendre avant d'intervenir sur un variateur coupé ?",
 v="Les condensateurs du bus continu gardent <b>½ C u²</b> et plusieurs centaines de volts pendant des minutes. On attend le temps de décharge, puis on <b>vérifie l'absence de tension</b>."),
dict(t="n", o="§5 La bobine",
 r="Relations de la bobine (convention récepteur) ? Quelle grandeur ne peut pas varier brutalement ?",
 v="<b>u = L di/dt</b> ; énergie <b>W = ½ L i²</b> (L en henrys).<br>C'est le <b>courant</b> qui ne peut pas varier brutalement."),
dict(t="n", o="§5 La surtension d'ouverture",
 r="Pourquoi place-t-on une diode de roue libre aux bornes d'une bobine commandée en continu ?",
 v="Couper brutalement le courant crée une <b>très forte tension</b> (u = L di/dt) : l'arc du contacteur. La diode de roue libre l'évite."),
dict(t="n", o="§5 Régime continu établi",
 r="En régime continu établi, comment se comportent un condensateur et une bobine ?",
 v="Condensateur : <b>interrupteur ouvert</b> (i = 0).<br>Bobine : <b>fil</b> (u = 0)."),
dict(t="n", o="§6 Modèle de Thévenin",
 r="Modèle d'une source réelle ? Équation de sa caractéristique ?",
 v="Une f.é.m. <b>E</b> en série avec une résistance interne <b>r</b> :<br><b>U = E − r I</b>"),
dict(t="n", o="§6 Modèle de Thévenin",
 r="Sur la caractéristique U(I) d'une source, où lit-on E et r ?",
 v="<b>E</b> : la tension <b>à vide</b> (I = 0), ordonnée à l'origine.<br><b>r</b> : la <b>pente</b> de la droite, au signe près."),
dict(t="n", o="§7 Point de fonctionnement",
 r="Qu'est-ce que le point de fonctionnement d'un circuit source + récepteur ?",
 v="Les deux dipôles ont <b>la même tension et le même courant</b> : c'est l'<b>intersection de leurs deux caractéristiques</b>."),
dict(t="n", o="§7 Le module photovoltaïque",
 r="Pourquoi le point de fonctionnement d'un module photovoltaïque ne se trouve-t-il que graphiquement ?",
 v="Sa caractéristique <b>n'est pas une droite</b> : courant presque constant (≈ I<sub>cc</sub>) puis effondrement près de la tension à vide. Le court-circuit y est sans danger."),
dict(t="n", o="§7 Rendement d'une source",
 r="Rendement d'une source de Thévenin ? Où passent les pertes ?",
 v="<b>η = U / E</b>. Elle génère E I, fournit U I et dissipe <b>r I²</b> en interne. Le rendement <b>baisse</b> quand le courant augmente."),
# --- méthodes
dict(t="m", o="§2 Partie A du TP",
 r="Comment déterminer R d'un dipôle à partir d'un relevé de caractéristique ?",
 v="1. Relever plusieurs couples (U ; I).<br>2. Tracer <b>I en fonction de U</b>.<br>3. Vérifier : droite <b>passant par l'origine</b> → ohmique.<br>4. Pente sur deux points éloignés = <b>1/R</b>, d'où R."),
dict(t="m", o="§6 Méthode — Déterminer E et r",
 r="Batterie : 12,6 V à vide, 11,4 V sous 30 A. Comment trouver E et r ?",
 v="1. <b>E = 12,6 V</b> (mesure à courant nul).<br>2. Chute : E − U = 1,2 V.<br>3. <b>r = 1,2 / 30 = 40 mΩ</b>.<br>4. Interpréter : 5 à 10 mΩ pour une batterie neuve → vieillissement."),
dict(t="m", o="§7 Méthode — Deux voies vers le même point",
 r="E = 24 V, r = 0,8 Ω alimente R = 5,2 Ω. Comment trouver le point de fonctionnement ?",
 v="<b>Algébrique</b> : maille E = r I + R I → I = 24 / 6,0 = <b>4,0 A</b> ; U = 5,2 × 4,0 = <b>20,8 V</b>.<br><b>Graphique</b> : intersection de U = 24 − 0,8 I et U = 5,2 I (seule voie si le récepteur n'est pas linéaire)."),
dict(t="m", o="§7 Rendement d'une source",
 r="Comment calculer le rendement d'une source et ses pertes internes ?",
 v="1. Mesurer E (à vide) et U (en charge).<br>2. <b>η = U / E</b>.<br>3. Pertes internes : <b>r I²</b> (ou (E − U) × I)."),
]

# =====================================================================
# Chapitres ajoutés ensuite (ordre d'affichage rétabli à la fin du fichier)

CARTES["ch00"] = [
dict(t="n", o="§1 L'unité est un découpage",
 r="On passe d'une unité à une unité plus petite : le nombre augmente ou diminue ? Pourquoi ?",
 v="Il <b>augmente</b> : un découpage plus fin demande davantage de morceaux.<br>Unité plus grande → il en faut moins → le nombre diminue. C'est ce qui donne le <b>signe de l'exposant</b>."),
dict(t="n", o="§1 Le piège du kilogramme",
 r="Sur quelle unité s'appliquent les préfixes de masse ?",
 v="Sur le <b>gramme</b>, jamais sur le kilogramme (pas de « kilokilogramme »). C'est la seule unité de base dont le nom porte déjà un préfixe."),
dict(t="n", o="§2 Écriture scientifique",
 r="Forme de l'écriture scientifique ? Que signifie un exposant négatif ?",
 v="<b>N = a × 10<sup>n</sup></b> avec <b>1 ≤ a &lt; 10</b>.<br>Exposant négatif = nombre <b>plus petit que 1</b> (pas un nombre négatif) : 10<sup>−3</sup> = 0,001."),
dict(t="n", o="§2 Calculer avec les puissances de dix",
 r="10<sup>a</sup> × 10<sup>b</sup> = ? et 10<sup>a</sup> / 10<sup>b</sup> = ?",
 v="10<sup>a</sup> × 10<sup>b</sup> = <b>10<sup>a+b</sup></b><br>10<sup>a</sup> / 10<sup>b</sup> = <b>10<sup>a−b</sup></b>"),
dict(t="m", o="§2 Méthode 1 — Écriture scientifique",
 r="Écrire 45 000 W puis 0,000 33 F en écriture scientifique : la démarche ?",
 v="1. Écrire le nombre entre 1 et 10 : 4,5 et 3,3.<br>2. Compter les rangs pour retomber sur le nombre de départ : 4 rangs dans les deux cas.<br>3. A-t-on <b>agrandi</b> (exposant +) ou <b>rapetissé</b> (exposant −) ?<br>→ <b>4,5 × 10<sup>4</sup> W</b> et <b>3,3 × 10<sup>−4</sup> F</b>. Contrôle avec la touche EXP."),
dict(t="n", o="§2 L'ordre de grandeur",
 r="Qu'est-ce que l'ordre de grandeur d'un nombre ? À quoi sert-il ?",
 v="La <b>puissance de dix la plus proche</b>. Il sert au contrôle rapide : un câble d'atelier fait ~10<sup>−2</sup> Ω ; une calculatrice qui annonce 41 Ω signale une erreur de trois rangs."),
dict(t="n", o="§3 La règle du plus faible",
 r="Combien de chiffres significatifs garder pour un produit/quotient ? Pour une somme/différence ?",
 v="Produit ou quotient : autant que la <b>donnée la moins précise</b>.<br>Somme ou différence : c'est le <b>nombre de décimales</b> qui commande."),
dict(t="n", o="§3 Pourquoi 1200 est ambigu",
 r="Combien de chiffres significatifs a « 1200 » ? Comment lever le doute ?",
 v="2, 3 ou 4 — on ne peut pas savoir. Seule l'<b>écriture scientifique</b> tranche : 1,2×10<sup>3</sup> (2 c.s.), 1,20×10<sup>3</sup> (3), 1,200×10<sup>3</sup> (4)."),
dict(t="n", o="§3 Valeurs nominales",
 r="Faut-il compter les chiffres significatifs de 230 V, 400 V, 50 Hz, 25 mm² ?",
 v="<b>Non</b> : ce sont des valeurs <b>nominales</b>, des noms de catégories, pas des mesures. La question ne se pose que pour des valeurs mesurées ou calculées."),
dict(t="m", o="§3 Méthode 2 — Arrondir un résultat",
 r="U = 231 V, I = 12,6 A : donner S = U I correctement. La démarche ?",
 v="1. Calculer <b>sans arrondir</b> : 2910,6.<br>2. Compter les c.s. des données : 3 et 3.<br>3. Arrondir au plus faible : <b>S = 2,91 × 10<sup>3</sup> VA</b>.<br>4. Contrôler : ~3 kVA, un départ de prises. Plausible.<br>On garde tous les chiffres jusqu'au bout ; recopier la calculatrice est une faute."),
dict(t="n", o="§4 Convertir : compter les crans",
 r="Que vaut un cran sur la réglette des préfixes ? Quelles deux questions pose une conversion ?",
 v="Un cran = un <b>facteur 10</b> (de k à m un par un ; au-delà, M, G, T et µ, n, p vont de 3 en 3).<br>1. <b>Combien de crans ?</b> → le chiffre de l'exposant.<br>2. <b>Découpage plus fin ou plus gros ?</b> → le signe."),
dict(t="n", o="§4 La règle d'or",
 r="Que faire avant tout calcul numérique ?",
 v="Convertir <b>toutes</b> les grandeurs en <b>unités SI</b> (m, m², s, F…). Le résultat sort alors directement dans l'unité SI."),
dict(t="n", o="§5 Le piège des unités composées",
 r="1 mm² = ? m². Et 95 mm² ?",
 v="<b>1 mm² = 10<sup>−6</sup> m²</b> (chaque cran compte deux fois : un millionième, pas un millième).<br>95 mm² = <b>9,5 × 10<sup>−5</sup> m²</b>."),
dict(t="m", o="§5 Méthode 3 — Conversion puis calcul",
 r="Résistance d'un câble cuivre de 125 m et 35 mm² (ρ = 1,8×10<sup>−8</sup> Ω·m) : la démarche ?",
 v="1. Tout en SI : S = 35×10<sup>−6</sup> = 3,5×10<sup>−5</sup> m².<br>2. R = ρ L / S = 1,8×10<sup>−8</sup> × 125 / 3,5×10<sup>−5</sup> = 6,43×10<sup>−2</sup> Ω.<br>3. ρ a 2 c.s. → <b>R = 64 mΩ</b>.<br>4. Contrôle : quelques dizaines de mΩ pour un câble d'atelier."),
dict(t="n", o="§6 Les durées se comptent par 60",
 r="Que vaut 1,5 h ? et 2,25 h ?",
 v="La partie décimale est une <b>fraction d'heure</b> : 0,5 h = 30 min.<br>1,5 h = <b>1 h 30 min</b> (pas 1 h 50) ; 2,25 h = <b>2 h 15 min</b>."),
dict(t="n", o="§6 Le kilowattheure",
 r="1 kWh = combien de joules ? Pourquoi ?",
 v="<b>1 kWh = 1000 W × 3600 s = 3,6 × 10<sup>6</sup> J = 3,6 MJ</b>.<br>Unité du compteur et de la facture ; le joule est celle des formules."),
dict(t="m", o="§6 Méthode 4 — D'un régime à une puissance",
 r="Moteur : N = 1450 tr/min, C = 141 N·m. Puissance mécanique ? La démarche ?",
 v="1. Convertir : <b>ω = N × 2π/60</b> = 151,8 rad/s.<br>2. P = C ω = 141 × 151,8 ≈ 21 400 W → <b>P = 21,4 kW</b>.<br>3. Contrôle : moteur normalisé de 22 kW, cohérent.<br>Oublier la conversion donne un résultat 60/2π ≈ 9,55 fois trop grand."),
dict(t="n", o="§7 Grandeurs proportionnelles",
 r="Quand deux grandeurs sont-elles proportionnelles ? Comment le vérifier ?",
 v="Quand on passe de l'une à l'autre en multipliant <b>toujours par le même nombre</b> : leur <b>quotient est constant</b>.<br>Graphiquement : une <b>droite passant par l'origine</b>."),
dict(t="n", o="§7 Une droite ne suffit pas",
 r="« C'est une droite, donc c'est proportionnel » : vrai ou faux ? Exemples ?",
 v="<b>Faux</b> : il faut aussi passer par l'<b>origine</b>.<br>Proportionnels : U = R I, Φ = B S. Non proportionnels : U = E − r I, diode, pompe.<br>P<sub>J</sub> = 3 R I² est proportionnel à <b>I²</b> : doubler I multiplie les pertes par 4."),
dict(t="m", o="§8 Méthode 5 — Quatrième proportionnelle",
 r="6,0 m de câble font 54 mΩ. Combien pour 14 m ? La démarche ?",
 v="1. Vérifier la proportionnalité : R = ρL/S passe par l'origine.<br>2. <b>Passer à l'unité</b> : 1,0 m → 54 / 6,0 = 9,0 mΩ.<br>3. Multiplier : 14 × 9,0 = 126 mΩ → <b>1,3 × 10<sup>2</sup> mΩ</b> (2 c.s.).<br>4. Contrôler : un peu plus du double des deux côtés."),
dict(t="m", o="§9 Lire une pente",
 r="Comment lire correctement la pente d'une droite expérimentale ?",
 v="1. Tracer la droite qui passe <b>au mieux entre les points</b>.<br>2. Prendre <b>deux points éloignés sur la droite</b> (pas deux mesures voisines).<br>3. a = Δy / Δx, avec <b>l'unité du quotient des axes</b> : V/A = Ω."),
dict(t="n", o="§9 L'ordonnée à l'origine",
 r="Une droite a une ordonnée à l'origine non nulle : défaut de tracé ? Que lit-on sur U = E − r I ?",
 v="Non, c'est une <b>information</b> (f.é.m., décalage, tare) — et la règle de trois devient interdite.<br>Sur U = E − r I : ordonnée à l'origine = <b>E</b>, pente = <b>−r</b>."),
dict(t="n", o="§10 Transformer une formule",
 r="Quel est le seul principe pour isoler une grandeur ? Les deux gestes qui en découlent ?",
 v="Faire <b>la même opération sur les deux membres</b>.<br>Ce qui multiplie d'un côté <b>divise</b> de l'autre ; ce qui s'ajoute d'un côté <b>se retranche</b> de l'autre."),
dict(t="m", o="§10 Méthode 6 — Isoler une grandeur",
 r="De Q<sub>C</sub> = 3 C ω U², tirer C et le calculer pour 25,6 kvar sous 400 V, 50 Hz.",
 v="1. C est multiplié par 3, ω, U² → <b>C = Q<sub>C</sub> / (3 ω U²)</b>.<br>2. SI : Q<sub>C</sub> = 2,56×10<sup>4</sup> var ; ω = 2π×50 = 314 rad/s.<br>3. C = 2,56×10<sup>4</sup> / (3×314×400²) = <b>170 µF</b>.<br>4. Contrôle : dizaines à centaines de µF par phase, plausible."),
dict(t="n", o="§10 Deux pièges en isolant",
 r="Comment extraire U de Q<sub>C</sub> = 3CωU² ? Et r de U = E − r I ?",
 v="Un carré s'enlève par une <b>racine</b> : U = √(Q<sub>C</sub> / 3Cω).<br>Avec une somme, déplacer d'abord le terme entier : r I = E − U, puis <b>r = (E − U) / I</b>."),
dict(t="n", o="§11 Le triangle des puissances",
 r="Dans le triangle des puissances, qui est l'adjacent, l'opposé, l'hypoténuse ? Relations ?",
 v="P adjacent, Q opposé, S hypoténuse.<br><b>cos φ = P/S</b>, <b>tan φ = Q/P</b>, <b>S² = P² + Q²</b>."),
dict(t="m", o="§11 Méthode 7 — Du cosinus à la tangente",
 r="cos φ = 0,72 : obtenir tan φ. La démarche et le piège ?",
 v="1. φ = arccos(0,72) = 43,9°.<br>2. tan φ = <b>0,964</b>.<br>3. Contrôle : cos médiocre → tan proche de 1 ou plus.<br>Piège : calculatrice en <b>DEG</b>, sinon on obtient 0,766 rad sans s'en rendre compte."),
dict(t="m", o="§12 Méthode 8 — Conclure sur une mesure",
 r="Comment comparer une mesure à une prévision ?",
 v="1. Calculer la valeur <b>prévue</b>.<br>2. Relever la valeur <b>mesurée</b> avec son unité.<br>3. Écart relatif = |mesure − prévision| / prévision × 100.<br>4. <b>Conclure par une phrase</b> : en dessous de <b>5 %</b>, compatible.<br>Ex. 1585 W pour 1587 W prévus → 0,13 %."),
dict(t="n", o="§12 Un écart nul doit inquiéter",
 r="La mesure tombe exactement sur la prévision : bonne nouvelle ?",
 v="Plutôt un signal d'alerte : en général on a <b>recopié le calcul</b> au lieu de lire l'appareil. Quelques dixièmes de pourcent signent une mesure réelle."),
dict(t="n", o="§13 Contrôler l'ordre de grandeur",
 r="Pourquoi le contrôle d'ordre de grandeur est-il indispensable ?",
 v="Une erreur de <b>conversion</b> donne un résultat de la bonne forme, décalé d'un facteur 1000 ou 10<sup>6</sup> : rien ne l'indique. Seul le contrôle de plausibilité l'attrape (câble ≠ 41 Ω, rendement &lt; 1…)."),
]

CARTES["c02"] = [
dict(t="n", o="§1 Le champ magnétique",
 r="Qu'est-ce que le champ magnétique B ? Unité ?",
 v="Une grandeur <b>vectorielle</b> définie en chaque point : direction, sens, valeur. En <b>teslas (T)</b>."),
dict(t="n", o="§1 Les lignes de champ",
 r="Qu'est-ce qu'une ligne de champ ? Par où sort-elle d'un aimant ? Peut-elle en croiser une autre ?",
 v="Une courbe <b>tangente en tout point à B</b>. Elle sort par le pôle <b>nord</b> et rentre par le pôle <b>sud</b>.<br>Deux lignes <b>ne se croisent jamais</b> : en un point, le champ n'a qu'une direction."),
dict(t="n", o="§1 Ordres de grandeur",
 r="Ordres de grandeur du champ : Terre, haut-parleur, entrefer de machine, IRM ?",
 v="Terre <b>50 µT</b> ; haut-parleur <b>0,1 T</b> ; entrefer de machine <b>0,8 à 1 T</b> ; IRM <b>3 T</b>."),
dict(t="n", o="§2 Champ d'un solénoïde",
 r="Champ à l'intérieur d'un solénoïde long ? De quoi dépend-il ?",
 v="<b>B = µ<sub>0</sub> n I = µ<sub>0</sub> (N/ℓ) I</b>, uniforme et selon l'axe.<br>µ<sub>0</sub> = 4π×10<sup>−7</sup> H/m ; n en spires <b>par mètre</b>.<br>Dépend seulement de la densité de spires et du courant (ni du diamètre, ni de la section du fil)."),
dict(t="m", o="§2 N n'est pas n",
 r="Calculer B pour 1200 spires sur 30 cm, I = 4,0 A. Le piège ?",
 v="1. <b>n = N/ℓ</b> avec ℓ en m : n = 1200 / 0,30 = 4000 spires/m.<br>2. B = 1,257×10<sup>−6</sup> × 4000 × 4,0 = <b>20 mT</b>.<br>Piège : diviser par 30 au lieu de 0,30 → erreur d'un facteur 100.<br>(20 mT c'est peu : il faudra un noyau de fer.)"),
dict(t="n", o="§3 Le flux (hors programme)",
 r="Le flux magnétique est-il exigible au BTS ET ? Que faut-il en retenir ?",
 v="<b>Non</b>, hors programme. À retenir : plus le champ est fort, la surface grande et bien face au champ, plus il y a de lignes qui la traversent — et c'est la <b>variation</b> de ce nombre de lignes qui produit une tension."),
dict(t="n", o="§4 Loi de Lenz",
 r="Énoncer la loi de Lenz.",
 v="Le courant induit a des effets qui <b>s'opposent à la cause qui lui a donné naissance</b>.<br>Approcher un aimant : le courant induit crée un champ qui s'oppose à l'augmentation ; l'éloigner : il s'inverse."),
dict(t="n", o="§4 Pourquoi la loi de Lenz",
 r="Pourquoi la loi de Lenz n'est-elle pas une simple convention ?",
 v="Si le courant induit renforçait la cause, le moindre mouvement s'amplifierait et fournirait de l'énergie indéfiniment : c'est une conséquence de la <b>conservation de l'énergie</b>."),
dict(t="n", o="§4 Freinage par courants de Foucault",
 r="Principe du ralentisseur électromagnétique des poids lourds ?",
 v="Un disque métallique tourne devant un aimant : des <b>courants induits</b> apparaissent dans sa masse et, par Lenz, s'opposent au mouvement. Freinage <b>sans contact ni usure</b>, uniquement en mouvement."),
dict(t="n", o="§5 Ce qui fait grandir la tension induite (exigible)",
 r="De quoi dépend la f.é.m. induite dans une bobine ?",
 v="Il faut que le champ <b>varie</b>. Elle est d'autant plus grande que :<br>• la variation est <b>rapide</b> ;<br>• les spires sont <b>nombreuses</b> ;<br>• le champ est <b>fort</b> ;<br>• la <b>surface</b> des spires est grande ;<br>• un <b>noyau de fer</b> canalise le champ.<br>Champ constant → aucune tension."),
dict(t="n", o="§5 Une tension, tout simplement",
 r="Qu'est-ce qu'une f.é.m. induite ? Comment la mesure-t-on ?",
 v="Une <b>tension</b>, en <b>volts</b>, mesurée au <b>voltmètre</b>. La lettre e indique seulement qu'elle vient d'un dispositif qui la produit. I = e/R et P = e I s'appliquent sans changement."),
dict(t="n", o="§5 La spire tournante",
 r="Spire tournant à vitesse constante dans un champ uniforme : forme de la f.é.m. ? Quand est-elle maximale ?",
 v="<b>Sinusoïdale</b>. Maximale quand le flux varie le plus vite (spire <b>dans le plan du champ</b>), <b>nulle quand le flux est maximal</b>."),
dict(t="n", o="§6 Force de Laplace",
 r="Force sur un conducteur de longueur ℓ parcouru par I dans un champ B ? Quand est-elle maximale ?",
 v="<b>F = B I ℓ sin α</b>, α angle entre conducteur et champ.<br>Maximale si perpendiculaires, nulle si parallèles. Direction ⟂ au conducteur et au champ ; sens par la règle des trois doigts de la main droite."),
dict(t="n", o="§6 Les deux sens de conversion",
 r="Quelle conversion assure la force de Laplace ? et la f.é.m. induite ?",
 v="Laplace : électrique → <b>mécanique</b> (moteur).<br>F.é.m. induite : mécanique → <b>électrique</b> (génératrice).<br>La <b>même machine</b> assure les deux sens."),
dict(t="n", o="§7 Matériau ferromagnétique",
 r="Qu'est-ce qu'un matériau ferromagnétique ? Exemples ? Effet dans une bobine ?",
 v="Il <b>canalise et renforce</b> le champ : fer, nickel, cobalt et alliages (tôles Fe-Si, ferrites, NdFeB).<br>Dans une bobine : <b>B = µ<sub>r</sub> µ<sub>0</sub> n I</b>, µ<sub>r</sub> de plusieurs milliers."),
dict(t="n", o="§7 Saturation, rémanence, démagnétisation",
 r="Définir saturation, champ rémanent B<sub>r</sub> et intensité de démagnétisation I<sub>d</sub>.",
 v="<b>Saturation</b> : B plafonne (1,5 à 2 T pour les tôles).<br><b>B<sub>r</sub></b> : champ qui reste quand le courant revient à zéro.<br><b>I<sub>d</sub></b> : courant de <b>sens inverse</b> qui annule ce champ."),
dict(t="n", o="§7 Doux ou dur",
 r="Matériau doux / matériau dur : forme du cycle et usages ?",
 v="<b>Doux</b> : cycle <b>étroit</b>, s'aimante et se désaimante facilement, peu de pertes → transformateurs, moteurs, électroaimants.<br><b>Dur</b> : cycle <b>large</b>, garde l'aimantation → aimants permanents."),
dict(t="m", o="§7 Exploiter un cycle B(I)",
 r="Sur un cycle B(I), où lire B<sub>r</sub>, I<sub>d</sub> et la saturation ? Comment conclure doux/dur ?",
 v="• B<sub>r</sub> : ordonnée du cycle pour <b>I = 0</b>.<br>• I<sub>d</sub> : abscisse où le cycle coupe <b>B = 0</b> (courant négatif).<br>• Saturation : zone où B ne croît presque plus.<br>Cycle étroit (I<sub>d</sub> faible) → doux ; cycle large → dur."),
dict(t="n", o="§7 Les pertes fer",
 r="Quelles sont les deux pertes fer ? Comment les limite-t-on ?",
 v="<b>Hystérésis</b> : énergie perdue par cycle ∝ <b>aire du cycle</b> (∝ f) → matériau doux.<br><b>Courants de Foucault</b> : courants induits dans la masse (∝ f²) → <b>feuilleter</b> le circuit en tôles isolées."),
dict(t="n", o="§8 Champ électrique",
 r="Champ électrique entre deux plaques parallèles ? Unité ? Exemple 230 V sur 1 mm ?",
 v="<b>E = U / d</b>, uniforme, en <b>V/m</b>.<br>230 V sur 1 mm → <b>230 kV/m</b> : plus les conducteurs sont proches, plus le champ est fort."),
dict(t="n", o="§8 Rigidité diélectrique",
 r="Qu'est-ce que la rigidité diélectrique ? Valeur pour l'air sec ?",
 v="Le <b>champ maximal</b> au-delà duquel l'isolant cesse d'isoler : c'est le <b>claquage</b> (champ disruptif).<br>Air sec : <b>3 kV/mm</b> (3 MV/m) ; huile et isolants de câbles : dizaines de kV/mm. L'air humide claque plus tôt."),
dict(t="m", o="§8 Distance minimale avant claquage",
 r="Deux jeux de barres à 20 kV l'un de l'autre, dans l'air sec : distance minimale ?",
 v="1. E<sub>d</sub> = 3 kV/mm (unités cohérentes avec U en kV).<br>2. <b>d = U / E<sub>d</sub></b> = 20 / 3 = <b>6,7 mm</b>.<br>3. Conclure : en dessous, l'air claque ; les distances réelles prennent une large marge."),
dict(t="n", o="§8 L'arc à l'ouverture",
 r="Pourquoi un arc apparaît-il quand un contacteur s'ouvre en charge ? Comment l'éteint-on ?",
 v="Les contacts ne sont d'abord séparés que de quelques centièmes de mm : même sous 400 V, <b>E = U/d dépasse la rigidité de l'air</b>, qui devient conducteur.<br>Les chambres de coupure <b>allongent et refroidissent</b> l'arc."),
]

CARTES["c03"] = [
dict(t="n", o="§1 Combustion",
 r="Qu'est-ce qu'une combustion ?",
 v="Une <b>réaction chimique</b> entre un <b>combustible</b> et un <b>comburant</b> (presque toujours le dioxygène de l'air), qui libère de l'énergie : chaleur, souvent lumière."),
dict(t="n", o="§1 Le triangle du feu",
 r="Quels sont les trois côtés du triangle du feu ? Comment éteindre un feu ?",
 v="<b>Combustible</b>, <b>comburant</b>, <b>énergie d'activation</b>.<br>On en supprime <b>un seul</b> : couper le gaz, étouffer, refroidir."),
dict(t="n", o="§1 L'énergie d'activation en électrotechnique",
 r="D'où vient souvent l'énergie d'activation dans une installation électrique ?",
 v="D'un <b>arc</b> à l'ouverture d'un contact, d'une étincelle, ou d'une <b>borne mal serrée</b> dont la résistance de contact dissipe R I² en un point minuscule. Le serrage au couple prescrit prévient l'incendie."),
dict(t="m", o="§2 Lire une formule chimique",
 r="Que contient C<sub>3</sub>H<sub>8</sub> ? et 2 H<sub>2</sub>O ?",
 v="La lettre donne l'atome, l'<b>indice</b> le nombre dans une molécule (pas d'indice = 1).<br>C<sub>3</sub>H<sub>8</sub> : 3 C et 8 H.<br>Le nombre <b>devant</b> compte les molécules : 2 H<sub>2</sub>O = 4 H et 2 O."),
dict(t="n", o="§2 Les hydrocarbures",
 r="Qu'est-ce qu'un hydrocarbure ? Formules du méthane, du propane, du butane ?",
 v="Une molécule faite <b>seulement de C et de H</b>.<br>Méthane <b>CH<sub>4</sub></b>, propane <b>C<sub>3</sub>H<sub>8</sub></b>, butane <b>C<sub>4</sub>H<sub>10</sub></b>."),
dict(t="n", o="§3 Conservation des atomes",
 r="Que deviennent les atomes au cours d'une réaction chimique ?",
 v="Ils ne sont <b>ni créés ni détruits</b> : ils changent de partenaires. Mêmes atomes, en même nombre, avant et après."),
dict(t="n", o="§3 Combustion complète du méthane",
 r="Équation de la combustion complète du méthane ?",
 v="<b>CH<sub>4</sub> + 2 O<sub>2</sub> → CO<sub>2</sub> + 2 H<sub>2</sub>O</b><br>Le carbone devient CO<sub>2</sub>, l'hydrogène devient H<sub>2</sub>O."),
dict(t="m", o="§3 Équilibrer une combustion",
 r="Équilibrer la combustion du propane C<sub>3</sub>H<sub>8</sub>. Dans quel ordre ?",
 v="Ordre : <b>C, puis H, puis O en dernier</b>.<br>C : 3 CO<sub>2</sub>. H : 8/2 = 4 H<sub>2</sub>O. O à droite : 6 + 4 = 10 → 5 O<sub>2</sub>.<br><b>C<sub>3</sub>H<sub>8</sub> + 5 O<sub>2</sub> → 3 CO<sub>2</sub> + 4 H<sub>2</sub>O</b>"),
dict(t="m", o="§3 Le cas de la demi-molécule",
 r="Pour le butane, on trouve 6,5 O<sub>2</sub>. Que faire ?",
 v="<b>Tout multiplier par 2</b> :<br><b>2 C<sub>4</sub>H<sub>10</sub> + 13 O<sub>2</sub> → 8 CO<sub>2</sub> + 10 H<sub>2</sub>O</b>"),
dict(t="n", o="§4 Combustion incomplète",
 r="Quand une combustion est-elle incomplète ? Que produit-elle ?",
 v="Quand le <b>dioxygène manque</b> : il se forme du <b>monoxyde de carbone CO</b>, parfois de la suie (carbone).<br>Ex. 2 CH<sub>4</sub> + 3 O<sub>2</sub> → 2 CO + 4 H<sub>2</sub>O."),
dict(t="n", o="§4 Le monoxyde de carbone tue",
 r="Pourquoi le CO est-il dangereux ? Quelles précautions ?",
 v="<b>Incolore, inodore</b>, il se fixe dans le sang à la place du dioxygène ; quelques centaines de ppm suffisent.<br>Jamais de groupe électrogène en local fermé ; détecteurs de CO."),
dict(t="n", o="§4 Assez d'air, mais pas trop",
 r="Pourquoi fournir assez d'air ? Et pourquoi pas un grand excès ?",
 v="Manque d'air : combustion incomplète, <b>dangereuse</b> (CO) et <b>coûteuse</b> (énergie non libérée).<br>Grand excès : refroidit la flamme et emporte de la chaleur par la cheminée. Réglage à l'analyseur de fumées."),
dict(t="n", o="§5 Mole et masse molaire",
 r="Qu'est-ce qu'une mole ? une masse molaire ? Valeurs pour C, H, O ?",
 v="Mole : paquet de <b>6,02 × 10<sup>23</sup></b> molécules.<br>Masse molaire M : masse d'une mole, en g/mol, somme des atomes : <b>C = 12, H = 1, O = 16</b>."),
dict(t="n", o="§5 Quantité de matière et volume",
 r="Relations entre n, m, M et entre V, n, V<sub>m</sub> ?",
 v="<b>n = m / M</b><br><b>V = n × V<sub>m</sub></b>, V<sub>m</sub> = 24 L/mol à 20 °C (le même pour tous les gaz)."),
dict(t="n", o="§5 Ce que dit l'équation",
 r="Comment lire CH<sub>4</sub> + 2 O<sub>2</sub> → CO<sub>2</sub> + 2 H<sub>2</sub>O en moles ? en volumes ?",
 v="Les nombres sont des <b>proportions de moles</b> : 1 mol de méthane réagit avec 2 mol de O<sub>2</sub>.<br>Même volume molaire pour tous les gaz → aussi <b>1 L de méthane pour 2 L de O<sub>2</sub></b>."),
dict(t="m", o="§5 Bilan de matière",
 r="Que consomme et que produit la combustion de 1 kg de méthane ?",
 v="1. n = 1000 / 16 = <b>62,5 mol</b>.<br>2. Proportions : 125 mol O<sub>2</sub>, 62,5 mol CO<sub>2</sub>, 125 mol H<sub>2</sub>O.<br>3. m = n × M : O<sub>2</sub> <b>4,00 kg</b> ; CO<sub>2</sub> <b>2,75 kg</b> ; H<sub>2</sub>O <b>2,25 kg</b>.<br>4. Contrôle : 1 + 4 = 2,75 + 2,25 (la masse se conserve)."),
dict(t="m", o="§5 L'air nécessaire",
 r="Quel volume d'air pour brûler 1 m³ de méthane ?",
 v="1. Équation : 1 m³ CH<sub>4</sub> demande <b>2 m³ de O<sub>2</sub></b>.<br>2. L'air n'a que <b>21 %</b> de O<sub>2</sub> : 2 / 0,21 ≈ <b>9,5 m³ d'air</b>.<br>C'est ce qui dimensionne les entrées d'air d'une chaufferie."),
dict(t="n", o="§6 Pouvoir calorifique",
 r="Qu'est-ce que le pouvoir calorifique ? Énergie libérée par une masse m ?",
 v="L'énergie libérée par la combustion <b>complète de 1 kg</b> (ou 1 m³ pour un gaz), en MJ/kg ou kWh/kg.<br><b>E = m × PCI</b>"),
dict(t="n", o="§6 PCI ou PCS",
 r="Différence entre PCI et PCS ? Pourquoi une chaudière à condensation dépasse 100 % ?",
 v="Le <b>PCS</b> compte l'énergie rendue par la <b>condensation de la vapeur d'eau</b> des fumées, le <b>PCI</b> non (méthane : PCS ≈ PCI + 11 %).<br>La chaudière à condensation récupère une partie de cet écart : rapporté au PCI, son rendement peut dépasser 100 %."),
dict(t="n", o="§6 Conversions utiles",
 r="Méthane : 50 MJ/kg = ? kWh/kg. Énergie d'1 m³ de gaz naturel ? d'1 L de gazole ?",
 v="1 kWh = 3,6 MJ → 50 / 3,6 = <b>13,9 kWh/kg</b>.<br>Gaz naturel ≈ <b>10 kWh/m³</b> (PCS) ; gazole ≈ <b>10 kWh/L</b>."),
dict(t="n", o="§7 Rendement d'une installation à combustion",
 r="Rendement d'une installation à combustion ? Ordres de grandeur ?",
 v="<b>η = W<sub>utile</sub> / (m × PCI)</b><br>Chaudière 90–105 % (sur PCI) ; groupe électrogène <b>30–40 %</b> ; centrale thermique 35–60 %."),
dict(t="n", o="§7 Le groupe sous-chargé",
 r="Pourquoi choisir un groupe électrogène au plus juste ?",
 v="Son rendement <b>chute loin de la puissance nominale</b> : à 25 % de charge, il consomme près de 50 % de gazole de plus par kWh qu'à pleine charge."),
dict(t="n", o="§7 Le CO2 émis",
 r="De quoi dépend la masse de CO<sub>2</sub> rejetée ? Valeurs pour le méthane et le gazole ?",
 v="Elle est <b>proportionnelle à la masse de combustible brûlé</b> (conservation des atomes) : <b>2,75 kg</b>/kg de méthane, <b>3,1 kg</b>/kg de gazole.<br>≈ 0,20 kg/kWh de chaleur au gaz ; ≈ 0,7 kg/kWh électrique au diesel."),
dict(t="m", o="§7 Une heure de secours",
 r="Groupe 100 kW pendant 1 h, η = 37 %, PCI gazole 11,8 kWh/kg : gazole et CO<sub>2</sub> ?",
 v="1. Énergie chimique : 100 / 0,37 = <b>270 kWh</b>.<br>2. Gazole : 270 / 11,8 = <b>23 kg</b> (≈ 27 L).<br>3. CO<sub>2</sub> : 23 × 3,1 = <b>71 kg</b>."),
dict(t="n", o="§8 Feu sur une installation électrique",
 r="Que faire face à un feu dans une armoire électrique ?",
 v="<b>Couper l'alimentation</b> d'abord. Sous tension, seul l'<b>extincteur à CO<sub>2</sub></b> convient (ne conduit pas, aucun résidu). Jamais d'eau en jet."),
dict(t="n", o="§8 Limites d'explosivité",
 r="Quand un mélange gaz–air peut-il exploser ?",
 v="Seulement si sa concentration est comprise entre la <b>LIE</b> (limite inférieure) et la <b>LSE</b> (limite supérieure). En dessous : trop pauvre ; au-dessus : trop riche."),
]

CARTES["tp03"] = [
dict(t="n", o="Convention d'écriture",
 r="Que désignent u(t) en minuscule et U en majuscule ? « u = 230 V » est-il correct ?",
 v="Minuscule : valeur <b>instantanée</b>, qui change à chaque instant. Majuscule : <b>valeur efficace</b>, un nombre fixe.<br>« u = 230 V » est une faute : c'est <b>U</b> qui vaut 230 V."),
dict(t="n", o="§1 Grandeur sinusoïdale",
 r="Écriture d'une tension sinusoïdale ? Relations entre T, f et ω ?",
 v="<b>u(t) = U<sub>max</sub> sin(ωt)</b><br><b>f = 1/T</b> et <b>ω = 2πf</b> (rad/s)."),
dict(t="n", o="§1 Le réseau",
 r="Réseau à 50 Hz : période ? pulsation ?",
 v="<b>T = 20 ms</b>, <b>ω = 2π × 50 = 314 rad/s</b>. La tension passe par zéro 100 fois par seconde."),
dict(t="n", o="§1 Valeur moyenne",
 r="Valeur moyenne d'une grandeur sinusoïdale ? Conséquence pour le voltmètre ?",
 v="<b>Nulle</b> : les deux alternances ont la même aire. Un voltmètre en position <b>DC</b> afficherait zéro sur le réseau : il faut la position <b>AC</b>."),
dict(t="n", o="§2 Valeur efficace",
 r="Définition de la valeur efficace ? Relation avec U<sub>max</sub> ?",
 v="La valeur de la <b>tension continue qui produirait le même échauffement</b> dans la même résistance.<br><b>U = U<sub>max</sub> / √2</b> — en sinusoïdal <b>uniquement</b>."),
dict(t="n", o="§2 Le facteur √2 n'est pas universel",
 r="Valeur efficace d'un carré ? d'un triangle ? Quel appareil pour un signal quelconque ?",
 v="Carré : U = U<sub>max</sub> ; triangle : U = U<sub>max</sub>/√3.<br>Signal quelconque (variateur, découpage) : seul un appareil <b>TRMS</b> mesure la vraie valeur efficace ; un non-TRMS se trompe souvent de plus de 10 %."),
dict(t="n", o="§2 Ce que mesure chaque appareil",
 r="Que lit-on à l'oscilloscope ? au multimètre en AC ? Que sont 230 V et 16 A sur une plaque ?",
 v="Oscilloscope : la forme et <b>U<sub>max</sub></b>.<br>Multimètre AC : la <b>valeur efficace U</b>.<br>Les valeurs de plaque sont des <b>valeurs efficaces</b>."),
dict(t="n", o="§3 Le déphasage",
 r="Définition et formule du déphasage ?",
 v="Le décalage entre deux sinusoïdes de même fréquence, rapporté à la période (une période = 360°).<br><b>φ = 360° × Δt / T</b>"),
dict(t="m", o="§3 Mesurer un déphasage à l'oscilloscope",
 r="Comment mesurer un déphasage sur un oscillogramme ?",
 v="1. Repérer un passage par zéro <b>dans le même sens</b> sur chaque courbe.<br>2. Mesurer Δt entre les deux et la période T.<br>3. φ = 360 Δt / T.<br>4. Est <b>en avance celle qui passe par zéro la première</b>.<br>Ex. T = 20 ms, i 2 ms après u → φ = 36°, courant en retard."),
dict(t="n", o="§3 Signe du déphasage",
 r="Que signifie φ &gt; 0 ? φ &lt; 0 ?",
 v="φ est le déphasage de u par rapport à i.<br><b>φ &gt; 0</b> : tension en avance sur le courant → circuit <b>inductif</b>.<br><b>φ &lt; 0</b> : tension en retard → circuit <b>capacitif</b>."),
dict(t="n", o="§4 Vecteur de Fresnel",
 r="Qu'associe-t-on à une grandeur sinusoïdale dans la représentation de Fresnel ?",
 v="Un vecteur dont la <b>longueur est la valeur efficace</b> et dont l'<b>angle</b> avec la référence est le <b>déphasage</b>."),
dict(t="n", o="§4 Pourquoi Fresnel",
 r="Peut-on additionner les valeurs efficaces de deux tensions déphasées ?",
 v="<b>Non</b>. On additionne leurs <b>vecteurs de Fresnel</b> : c'est la seule addition autorisée."),
dict(t="n", o="§5 Impédance",
 r="Définition de l'impédance ? Impédance et déphasage de R, L, C ?",
 v="<b>Z = U / I</b> (valeurs efficaces), en Ω.<br>Résistance : <b>R</b>, 0°.<br>Bobine : <b>Lω</b>, +90°.<br>Condensateur : <b>1/(Cω)</b>, −90°."),
dict(t="n", o="§5 La bobine réelle",
 r="Comment modélise-t-on une bobine réelle ? Que se passe-t-il si on l'alimente en continu ?",
 v="<b>r en série avec L</b> : Z &gt; r et déphasage entre 0° et 90°.<br>En continu, seule r limite le courant : une bobine prévue pour 24 V alternatif <b>grille</b> sous 24 V continu."),
dict(t="m", o="§6 Construire un Fresnel série",
 r="Circuit série R, L, C : comment construire le diagramme de Fresnel ?",
 v="1. <b>I horizontal</b> en référence (commun à tous les dipôles en série).<br>2. Bout à bout : U<sub>R</sub> en phase, U<sub>L</sub> à +90°, U<sub>C</sub> à −90°.<br>3. U joint l'origine à l'extrémité du dernier vecteur.<br>4. <b>U = √(U<sub>R</sub>² + (U<sub>L</sub> − U<sub>C</sub>)²)</b>, <b>tan φ = (U<sub>L</sub> − U<sub>C</sub>)/U<sub>R</sub></b>."),
dict(t="n", o="§6 Triangle des impédances",
 r="Impédance d'un circuit R–L série ? Exemple R = 40 Ω, Lω = 30 Ω ?",
 v="<b>Z = √(R² + X²)</b>, X = Lω (bobine) ou −1/(Cω) (condensateur).<br>40 et 30 Ω → <b>Z = 50 Ω</b>, φ = 36,9°."),
dict(t="n", o="§7 Les trois puissances",
 r="Expressions de P, Q, S en monophasé sinusoïdal ? Relation entre elles ?",
 v="<b>P = U I cos φ</b> (W), <b>Q = U I sin φ</b> (var), <b>S = U I</b> (VA).<br><b>S² = P² + Q²</b>"),
dict(t="n", o="§7 Facteur de puissance",
 r="Qu'est-ce que le facteur de puissance ? Que vaut-il en sinusoïdal ?",
 v="<b>k = P / S</b>, la part de la puissance transportée réellement utilisée. En sinusoïdal : <b>cos φ</b>."),
dict(t="n", o="§7 La puissance de chaque dipôle",
 r="P et Q pour une résistance, une bobine idéale, un condensateur ?",
 v="Résistance : P = R I², <b>Q = 0</b>.<br>Bobine : <b>P = 0</b>, Q = Lω I² <b>&gt; 0</b> (consomme du réactif).<br>Condensateur : <b>P = 0</b>, Q = −I²/(Cω) <b>&lt; 0</b> (fournit du réactif)."),
dict(t="m", o="§7 Un moteur monophasé",
 r="Moteur 1,5 kW sous 230 V, cos φ = 0,80 : S, I, Q ?",
 v="S = P / cos φ = <b>1875 VA</b> ; I = S / U = <b>8,15 A</b> ; Q = √(S² − P²) = <b>1125 var</b>.<br>Un radiateur de même puissance ne tirerait que 6,52 A."),
dict(t="n", o="§8 Théorème de Boucherot",
 r="Qu'est-ce qui s'additionne dans une installation ? Qu'est-ce qui ne s'additionne pas ?",
 v="Les puissances <b>actives</b> s'additionnent, les puissances <b>réactives</b> aussi (avec leur signe).<br>Les puissances <b>apparentes</b> et les <b>courants</b> ne s'additionnent pas."),
dict(t="m", o="§8 Faire un bilan de puissance",
 r="Comment faire le bilan de puissance d'une installation ?",
 v="1. Pour chaque récepteur : P absorbée (P<sub>u</sub>/η pour un moteur), puis <b>Q = P tan φ</b>.<br>2. Additionner les P, puis les Q.<br>3. <b>S = √(P² + Q²)</b>, cos φ = P/S, I = S/U.<br>Présenter un tableau, une ligne par récepteur (forme attendue à l'E4)."),
dict(t="n", o="§9 Pourquoi relever le facteur de puissance",
 r="Pourquoi un mauvais facteur de puissance coûte-t-il ? Quel est le principe du relèvement ?",
 v="Courant plus grand que nécessaire : câbles qui chauffent, abonnement en kVA plus élevé, réactif facturé.<br>Un <b>condensateur en parallèle</b> fournit sur place une partie du réactif : P inchangée, Q, S et I diminuent."),
dict(t="m", o="§9 Dimensionner le condensateur",
 r="5,0 kW sous 230 V, cos φ = 0,70 à relever à 0,95 : capacité ?",
 v="1. tan φ = 1,020 ; tan φ' = 0,329.<br>2. <b>Q<sub>C</sub> = P (tan φ − tan φ')</b> = 5000 × 0,691 = 3456 var.<br>3. <b>C = Q<sub>C</sub> / (U² ω)</b> = 3456 / (230² × 314) = <b>208 µF</b>.<br>4. Contrôle : I passe de 31,1 A à 22,9 A."),
]

CARTES["tp04"] = [
dict(t="n", o="§1 Le réseau triphasé",
 r="Que distribue un réseau triphasé ? Qu'est-ce qu'une tension simple ?",
 v="Trois phases <b>L1, L2, L3</b> et souvent un <b>neutre N</b>.<br>Tension simple : entre <b>une phase et le neutre</b> (v<sub>1</sub>, v<sub>2</sub>, v<sub>3</sub>)."),
dict(t="n", o="§1 Système triphasé équilibré",
 r="Caractéristiques d'un système triphasé équilibré de tensions ?",
 v="Même <b>valeur efficace V</b>, même fréquence, décalées d'<b>un tiers de période (120°)</b>. Leur somme est <b>nulle</b> à chaque instant."),
dict(t="n", o="§2 Tension composée",
 r="Qu'est-ce qu'une tension composée ? Relation avec la tension simple ? Valeurs du réseau ?",
 v="Tension <b>entre deux phases</b> : u<sub>12</sub> = v<sub>1</sub> − v<sub>2</sub>.<br><b>U = V√3</b> : V = 230 V, <b>U = 400 V</b> (réseau « 230/400 V »)."),
dict(t="n", o="§2 Le piège de la soustraction",
 r="Pourquoi u<sub>12</sub> ne vaut-il pas 230 − 230 = 0 V ?",
 v="Les tensions simples <b>ne sont pas en phase</b> (120°) : la différence se construit avec <b>Fresnel</b>. U = V√3 relie des valeurs efficaces."),
dict(t="n", o="§3 Étoile et triangle",
 r="Couplage étoile / triangle : tension aux bornes d'un élément ? Relation entre I (ligne) et J (élément) ?",
 v="<b>Étoile</b> : chaque élément sous <b>V</b>, <b>I = J</b>.<br><b>Triangle</b> : chaque élément sous <b>U</b>, <b>I = J√3</b>."),
dict(t="m", o="§3 Trois résistances en étoile puis en triangle",
 r="Trois résistances de 100 Ω sur le 230/400 V : courants en étoile et en triangle ?",
 v="Étoile : J = I = 230/100 = <b>2,3 A</b>.<br>Triangle : J = 400/100 = 4,0 A, I = 4,0√3 = <b>6,9 A</b>.<br>Le triangle absorbe <b>3 fois plus</b> de puissance (√3 fois plus de tension par élément)."),
dict(t="n", o="§3 Le neutre",
 r="Récepteur équilibré : quel courant circule dans le neutre ? Pourquoi ?",
 v="<b>Aucun</b> : les trois courants de ligne ont même valeur, sont décalés de 120°, et leur somme est nulle."),
dict(t="m", o="§4 Choisir le couplage d'un moteur",
 r="Comment choisir le couplage d'un moteur à partir de sa plaque ?",
 v="1. La <b>plus petite</b> tension de la plaque est celle que supporte <b>un enroulement</b>.<br>2. Lire la tension composée U du réseau.<br>3. Enroulement prévu pour U → <b>triangle</b> ; pour U/√3 → <b>étoile</b>.<br>Ex. « 400 V Δ / 690 V Y » sur 400 V → triangle ; « 230/400 V » sur 400 V → étoile."),
dict(t="n", o="§4 L'erreur de couplage",
 r="Que se passe-t-il si un moteur « 230/400 V » est couplé en triangle sur le 400 V ?",
 v="Chaque enroulement reçoit <b>√3 fois</b> sa tension nominale : il chauffe et <b>grille</b> en quelques minutes."),
dict(t="n", o="§5 Puissances en triphasé",
 r="P, Q, S d'un récepteur triphasé équilibré (grandeurs de ligne) ?",
 v="<b>P = √3 U I cos φ</b> ; <b>Q = √3 U I sin φ</b> ; <b>S = √3 U I</b>.<br>Valables dans les deux couplages ; Boucherot s'applique."),
dict(t="n", o="§5 Quel déphasage φ ?",
 r="Dans P = √3 U I cos φ, entre quelles grandeurs est mesuré φ ?",
 v="Entre la <b>tension et le courant d'un même élément</b>, pas entre U et I de ligne."),
dict(t="m", o="§5 Un moteur sur le 400 V",
 r="Moteur sur 400 V : I = 8,2 A, cos φ = 0,82. P, S, Q ?",
 v="P = √3 × 400 × 8,2 × 0,82 = <b>4,66 kW</b><br>S = √3 × 400 × 8,2 = <b>5,68 kVA</b><br>Q = √(S² − P²) = <b>3,25 kvar</b>"),
dict(t="n", o="§6 La méthode des deux wattmètres",
 r="Méthode des deux wattmètres : P et Q à partir des lectures P<sub>1</sub> et P<sub>2</sub> ?",
 v="<b>P = P<sub>1</sub> + P<sub>2</sub></b><br><b>Q = √3 (P<sub>1</sub> − P<sub>2</sub>)</b><br>Lectures prises <b>avec leur signe</b> (sans neutre, récepteur équilibré)."),
dict(t="n", o="§6 Une lecture négative",
 r="Un des deux wattmètres affiche une valeur négative : erreur ?",
 v="Non : quand <b>cos φ &lt; 0,5</b>, P<sub>2</sub> devient négatif. On le compte <b>avec son signe</b>."),
dict(t="m", o="§6 Exploiter les deux lectures",
 r="P<sub>1</sub> = 3200 W et P<sub>2</sub> = 1400 W : P, Q, cos φ ?",
 v="1. P = 3200 + 1400 = <b>4600 W</b>.<br>2. Q = √3 × (3200 − 1400) = <b>3118 var</b>.<br>3. tan φ = Q/P = 0,678 → <b>cos φ = 0,83</b>."),
]

CARTES["tp05"] = [
dict(t="n", o="§1 Constitution et principe",
 r="Comment est constitué un transformateur ? Comment une tension apparaît-elle au secondaire ?",
 v="Deux enroulements (<b>primaire</b>, <b>secondaire</b>) sur un même <b>circuit magnétique en tôles feuilletées</b>.<br>Le primaire alimenté en alternatif crée un champ <b>variable</b> qui traverse le secondaire : une tension y est induite."),
dict(t="n", o="§1 Alternatif seulement",
 r="Un transformateur fonctionne-t-il en continu ? Quel autre rôle assure-t-il ?",
 v="<b>Non</b> : en continu, le champ est constant et n'induit rien.<br>Aucun fil ne relie les deux enroulements : il assure l'<b>isolement galvanique</b>."),
dict(t="n", o="§2 Rapport de transformation",
 r="Rapport de transformation d'un transformateur parfait ? Abaisseur ou élévateur ?",
 v="<b>m = N<sub>2</sub>/N<sub>1</sub> = U<sub>2</sub>/U<sub>1</sub> = I<sub>1</sub>/I<sub>2</sub></b><br>m &lt; 1 : <b>abaisseur</b> ; m &gt; 1 : <b>élévateur</b>."),
dict(t="n", o="§2 Le transformateur parfait",
 r="Que dit la conservation de la puissance pour un transformateur parfait ?",
 v="<b>S<sub>1</sub> = S<sub>2</sub></b> : U<sub>1</sub> I<sub>1</sub> = U<sub>2</sub> I<sub>2</sub>. Ce qu'il gagne en tension, il le perd en courant."),
dict(t="m", o="§2 Un transformateur de commande",
 r="Transformateur 230 V / 24 V débitant 4,0 A : courant primaire ?",
 v="1. m = 24 / 230 = <b>0,104</b>.<br>2. I<sub>1</sub> = m × I<sub>2</sub> = 4,0 × 0,104 = <b>0,42 A</b>."),
dict(t="n", o="§3 Lire une plaque signalétique",
 r="Que porte la plaque d'un transformateur ? Comment en déduire I<sub>2n</sub> ? Pourquoi en VA ?",
 v="S<sub>n</sub> (VA), U<sub>1n</sub>, et U<sub>20</sub> <b>à vide</b>.<br><b>I<sub>2n</sub> = S<sub>n</sub> / U<sub>20</sub></b>.<br>En <b>VA</b> car il chauffe selon le <b>courant</b>, quel que soit le cos φ."),
dict(t="n", o="§4 Les deux pertes",
 r="Quelles sont les deux sortes de pertes d'un transformateur réel ? De quoi dépendent-elles ?",
 v="<b>Pertes fer</b> (circuit magnétique) : fixes à tension donnée.<br><b>Pertes cuivre</b> (effet Joule dans les enroulements) : <b>P<sub>J</sub> = R<sub>s</sub> I<sub>2</sub>²</b>, croissent comme le carré du courant."),
dict(t="n", o="§5 Essai à vide",
 r="Essai à vide : conditions ? Que mesure-t-on ?",
 v="Primaire sous <b>tension nominale</b>, secondaire <b>ouvert</b>.<br>Flux nominal, courant très faible → <b>P<sub>10</sub> ≈ P<sub>fer</sub></b>. Donne aussi <b>m = U<sub>20</sub>/U<sub>1</sub></b>."),
dict(t="n", o="§5 Essai en court-circuit",
 r="Essai en court-circuit : conditions ? Que mesure-t-on ?",
 v="Secondaire en <b>court-circuit</b>, primaire sous tension <b>très réduite</b>, montée jusqu'à I<sub>2</sub> = I<sub>2n</sub>.<br>Courant nominal, flux négligeable → <b>P<sub>1cc</sub> ≈ P<sub>J</sub></b> au courant nominal."),
dict(t="n", o="§5 Sécurité de l'essai en court-circuit",
 r="Pourquoi l'essai en court-circuit part-il toujours de zéro ?",
 v="Sous la tension nominale, un secondaire en court-circuit <b>détruit le transformateur</b>. On monte à l'<b>alternostat</b> depuis 0 et on ne dépasse jamais quelques % de U<sub>1n</sub>."),
dict(t="m", o="§5 Exploiter les deux essais",
 r="500 VA, 230/48 V. À vide : U<sub>20</sub> = 50,0 V, P<sub>10</sub> = 18 W. CC : U<sub>1cc</sub> = 13,8 V, P<sub>1cc</sub> = 26 W à I<sub>2n</sub> = 10,4 A. Exploiter.",
 v="1. m = 50,0 / 230 = 0,217.<br>2. P<sub>fer</sub> = 18 W ; P<sub>J</sub> = 26 W au nominal.<br>3. <b>R<sub>s</sub> = P<sub>1cc</sub> / I<sub>2n</sub>²</b> = 26 / 10,4² = 0,24 Ω.<br>4. <b>Z<sub>s</sub> = m U<sub>1cc</sub> / I<sub>2n</sub></b> = 0,29 Ω ; <b>X<sub>s</sub> = √(Z<sub>s</sub>² − R<sub>s</sub>²)</b> = 0,16 Ω."),
dict(t="n", o="§6 Modèle vu du secondaire",
 r="Vu du secondaire, à quoi équivaut un transformateur en charge ?",
 v="À une source <b>U<sub>20</sub></b> en série avec <b>R<sub>s</sub></b> et <b>X<sub>s</sub></b>. En charge, U<sub>2</sub> &lt; U<sub>20</sub>."),
dict(t="n", o="§6 Formule de Kapp",
 r="Chute de tension en charge (formule approchée de Kapp) ? Quand est-elle forte ?",
 v="<b>ΔU<sub>2</sub> = U<sub>20</sub> − U<sub>2</sub> ≈ R<sub>s</sub> I<sub>2</sub> cos φ<sub>2</sub> + X<sub>s</sub> I<sub>2</sub> sin φ<sub>2</sub></b><br>D'autant plus forte que le courant est grand et la charge <b>inductive</b>."),
dict(t="m", o="§6 Tension en charge",
 r="R<sub>s</sub> = 0,24 Ω, X<sub>s</sub> = 0,16 Ω, U<sub>20</sub> = 50,0 V, I<sub>2</sub> = 10,4 A, cos φ<sub>2</sub> = 0,80 : U<sub>2</sub> ?",
 v="1. sin φ<sub>2</sub> = 0,60.<br>2. ΔU<sub>2</sub> = 0,24 × 10,4 × 0,80 + 0,16 × 10,4 × 0,60 = <b>3,0 V</b>.<br>3. U<sub>2</sub> = 50,0 − 3,0 = <b>47,0 V</b>."),
dict(t="n", o="§7 Rendement",
 r="Rendement d'un transformateur ? Quand est-il maximal ? À vide ?",
 v="<b>η = P<sub>2</sub> / (P<sub>2</sub> + P<sub>fer</sub> + P<sub>J</sub>)</b><br>Maximal quand <b>P<sub>J</sub> = P<sub>fer</sub></b>. À vide, η = 0 : il consomme ses pertes fer sans rien fournir."),
dict(t="n", o="§8 Transformateur triphasé de distribution",
 r="Couplage usuel d'un transformateur de distribution (Dyn) ? Pourquoi ?",
 v="<b>Triangle au primaire</b>, <b>étoile avec neutre au secondaire</b>.<br>La HT n'a pas besoin de neutre ; la BT en fournit un pour les récepteurs monophasés. Le rapport des tensions composées n'est plus le rapport des spires."),
]

CARTES["tp06"] = [
dict(t="n", o="§1 La diode",
 r="Dans quel sens une diode conduit-elle ? Tension de seuil ? Modèle idéal ?",
 v="De l'<b>anode vers la cathode</b> uniquement. Passante : seuil ≈ <b>0,7 V</b> (silicium) ; bloquée : <b>aucun courant</b>.<br>Idéale : un fil quand elle conduit, un interrupteur ouvert sinon."),
dict(t="n", o="§2 Redressement simple alternance",
 r="Redressement simple alternance : valeur moyenne ? Fréquence d'ondulation ? Limite ?",
 v="<b>⟨u⟩ = U<sub>max</sub> / π</b> avec U<sub>max</sub> = U√2.<br>Ondulation à <b>50 Hz</b> (une bosse par période).<br>La moitié de l'énergie est perdue : petites puissances seulement."),
dict(t="m", o="§2 Simple alternance sous 12 V",
 r="Secondaire de 12 V, simple alternance, diode idéale : valeur moyenne ?",
 v="1. U<sub>max</sub> = 12√2 = <b>17,0 V</b>.<br>2. ⟨u⟩ = 17,0 / π = <b>5,4 V</b>."),
dict(t="m", o="§3 Suivre le courant dans le pont de Graëtz",
 r="Comment suivre le trajet du courant dans un pont de diodes ?",
 v="1. Repérer la borne du secondaire au potentiel <b>le plus haut</b>.<br>2. En partir : une seule diode s'ouvre (anode → cathode) vers le haut de la charge.<br>3. Traverser la charge de haut en bas, revenir à l'autre borne par la seule diode qui l'accepte.<br>4. Alternance suivante : les <b>deux autres diodes</b>, et la charge est traversée <b>dans le même sens</b>."),
dict(t="n", o="§3 Pont de Graëtz",
 r="Pont de Graëtz : valeur moyenne ? Fréquence d'ondulation ? Combien de diodes conduisent ?",
 v="<b>⟨u⟩ = 2 U<sub>max</sub> / π</b>.<br>Ondulation à <b>100 Hz</b> (deux fois le réseau).<br><b>Deux diodes</b> conduisent à chaque instant : ≈ 1,4 V de seuil perdus."),
dict(t="m", o="§3 Graëtz sous 12 V",
 r="Même secondaire de 12 V, pont de Graëtz : valeur moyenne ?",
 v="⟨u⟩ = 2 × 17,0 / π = <b>10,8 V</b> (diodes idéales), ≈ <b>9,9 V</b> en retirant les 1,4 V de seuil."),
dict(t="n", o="§3 Le pont n'est pas réversible",
 r="Un pont de diodes peut-il renvoyer de l'énergie au réseau ?",
 v="<b>Non</b> : l'énergie ne va que du réseau vers la charge. Pour freiner en renvoyant l'énergie, il faut des <b>thyristors</b> (année 2)."),
dict(t="n", o="§4 Mesurer une tension redressée",
 r="Que lit un voltmètre en DC sur une tension redressée ? en AC ? Comment observer la forme ?",
 v="DC : la <b>valeur moyenne</b>.<br>AC : l'efficace de la seule partie alternative (sauf <b>TRMS AC+DC</b>).<br>Forme : oscilloscope en <b>couplage DC</b>, via un <b>module d'isolement</b> ou une sonde différentielle."),
dict(t="n", o="§5 Le filtrage capacitif",
 r="Rôle du condensateur en parallèle sur la charge ? Ondulation résiduelle ?",
 v="Il se charge à chaque sommet puis fournit le courant quand la tension redescend : sortie presque continue, proche de U<sub>max</sub>.<br><b>ΔU ≈ I / (f<sub>ond</sub> C)</b> : diminue si C augmente, augmente avec le courant."),
dict(t="m", o="§5 Dimensionner un condensateur de filtrage",
 r="Derrière un pont (12 V), une carte absorbe 0,50 A ; ondulation ≤ 1,5 V. Capacité ?",
 v="1. f<sub>ond</sub> = <b>100 Hz</b> (pont).<br>2. <b>C ≥ I / (f<sub>ond</sub> ΔU)</b> = 0,50 / (100 × 1,5) = 3,3 × 10<sup>−3</sup> F = 3300 µF.<br>3. Valeur normalisée <b>supérieure</b> : 4700 µF → ΔU ≈ 1,1 V."),
dict(t="n", o="§5 Le condensateur chimique",
 r="Deux précautions pour un condensateur chimique de filtrage ?",
 v="Il est <b>polarisé</b> : à l'envers, il chauffe et peut exploser.<br>Sa <b>tension de service</b> doit dépasser U<sub>max</sub>."),
dict(t="n", o="§6 La chaîne de conversion",
 r="Constitution d'une alimentation continue classique ? Conséquence côté réseau ?",
 v="<b>Transformateur → pont de diodes → condensateur</b>.<br>Le condensateur ne se recharge qu'aux sommets : le réseau fournit le courant par <b>brèves pointes</b>, <b>non sinusoïdal</b>."),
]

CARTES["tp07"] = [
dict(t="n", o="§1 Décomposition de Fourier",
 r="Comment se décompose un signal périodique de fréquence f ? Qu'est-ce que le fondamental ? un harmonique de rang n ?",
 v="Valeur moyenne + sinusoïdes de fréquences f, 2f, 3f…<br><b>Fondamental</b> : la composante à f.<br><b>Harmonique de rang n</b> : à n·f (rang 3 sur le réseau : <b>150 Hz</b>)."),
dict(t="n", o="§2 Le spectre",
 r="Que représente le spectre d'un courant ? Quels rangs pour un signal à alternances symétriques ?",
 v="La <b>valeur efficace de chaque harmonique</b> en fonction de son rang.<br>Alternances positive et négative symétriques → rangs <b>impairs</b> seulement."),
dict(t="n", o="§3 Valeur efficace d'un signal déformé",
 r="Valeur efficace totale à partir des harmoniques ?",
 v="<b>I² = I<sub>1</sub>² + I<sub>2</sub>² + I<sub>3</sub>² + …</b> (somme des carrés, pas des valeurs)."),
dict(t="n", o="§3 Taux de distorsion harmonique",
 r="Définition du THD ? Que vaut-il pour un courant sinusoïdal ?",
 v="<b>THD = √(I<sub>2</sub>² + I<sub>3</sub>² + …) / I<sub>1</sub></b> : les harmoniques comparés au fondamental.<br>Courant sinusoïdal : THD <b>nul</b>."),
dict(t="m", o="§3 Exploiter un spectre",
 r="I<sub>1</sub> = 0,50 A, I<sub>3</sub> = 0,40 A, I<sub>5</sub> = 0,25 A, I<sub>7</sub> = 0,12 A : I et THD ?",
 v="1. I = √(0,50² + 0,40² + 0,25² + 0,12²) = <b>0,70 A</b>.<br>2. THD = √(0,40² + 0,25² + 0,12²) / 0,50 = <b>97 %</b>.<br>3. Les harmoniques pèsent presque autant que le fondamental."),
dict(t="n", o="§4 Puissances en non sinusoïdal",
 r="Tension sinusoïdale, courant déformé : quelle partie du courant porte P et Q ? Que vaut S ?",
 v="Seul le <b>fondamental</b> : <b>P = V I<sub>1</sub> cos φ<sub>1</sub></b>, <b>Q = V I<sub>1</sub> sin φ<sub>1</sub></b>.<br>Mais <b>S = V I</b> avec le courant total."),
dict(t="n", o="§4 Puissance déformante",
 r="Qu'est-ce que la puissance déformante D ? Comment se compare F = P/S à cos φ<sub>1</sub> ?",
 v="L'écart dû aux harmoniques : <b>S² = P² + Q² + D²</b> (D en var).<br>Le facteur de puissance <b>F = P/S est plus petit que cos φ<sub>1</sub></b>."),
dict(t="m", o="§4 Calculer les puissances",
 r="Même alimentation sous 230 V, cos φ<sub>1</sub> = 0,98 (I<sub>1</sub> = 0,50 A, I = 0,70 A) : P, Q, S, D, F ?",
 v="1. P = 230 × 0,50 × 0,98 = <b>113 W</b> ; Q = 230 × 0,50 × 0,20 = <b>23 var</b>.<br>2. S = 230 × 0,70 = <b>160 VA</b>.<br>3. D = √(S² − P² − Q²) ≈ <b>112 var</b>.<br>4. F = 113 / 160 = <b>0,70</b>, alors que cos φ<sub>1</sub> = 0,98."),
dict(t="n", o="§4 Le condensateur ne corrige pas D",
 r="Un condensateur de compensation corrige-t-il la puissance déformante ?",
 v="<b>Non</b>, il ne corrige que <b>Q</b>. Pire, il peut <b>résonner</b> avec l'inductance du réseau à la fréquence d'un harmonique."),
dict(t="n", o="§5 Origine et conséquences des harmoniques",
 r="D'où viennent les harmoniques ? Quelles conséquences ?",
 v="Des récepteurs <b>non linéaires</b> : redresseurs à condensateur (alimentations, variateurs, chargeurs), LED, fluorescent.<br>Conséquences : <b>échauffements</b> (câbles, transformateurs), déclenchements intempestifs, perturbations, <b>surcharge du neutre</b>."),
dict(t="n", o="§6 Le courant dans le neutre",
 r="En triphasé équilibré, pourquoi le neutre peut-il être surchargé ? Ordre de grandeur ?",
 v="Les fondamentaux s'annulent, mais les harmoniques de <b>rang 3 et multiples</b> sont <b>en phase</b> sur les trois phases et s'additionnent : <b>I<sub>N</sub> ≈ 3 I<sub>3</sub></b>.<br>Le neutre peut dépasser le courant de phase : à dimensionner en conséquence."),
dict(t="m", o="§6 Vingt ordinateurs par phase",
 r="20 alimentations par phase (I = 0,70 A, I<sub>3</sub> = 0,40 A chacune) : courant de phase et de neutre ?",
 v="Phase : 20 × 0,70 = <b>14 A</b>.<br>Neutre : 3 × 20 × 0,40 = <b>24 A</b>, presque deux fois plus qu'une phase."),
]

_ORDRE = ["ch00", "c01", "c02", "c03", "tp01", "tp02", "tp03", "tp04", "tp05", "tp06", "tp07"]
CARTES = {k: CARTES[k] for k in _ORDRE if k in CARTES}
