# -*- coding: utf-8 -*-
# Cartes de révision écrites à la main — 1re STI2D
# t : "n" = notion à connaître, "m" = méthode (savoir-faire)
# o : paragraphe du cours d'où vient la carte
FILIERE = "1sti2d"
NIVEAU = "1re STI2D"

CARTES = {}

# =====================================================================
CARTES["ch00"] = [
dict(t="n", o="§1 Grandeur, valeur et unité",
 r="Pourquoi « la pièce fait 25 » n'est-il pas un résultat ?",
 v="Il manque l'<b>unité</b> : 25 mm et 25 cm ne décrivent pas le même objet. Un résultat comporte toujours <b>une valeur et une unité</b>."),
dict(t="n", o="§1 Grandeur, valeur et unité",
 r="Choisir une unité, c'est quoi ?",
 v="C'est décider en <b>combien de morceaux on découpe</b> la grandeur. Mesurer, c'est ensuite <b>compter ces morceaux</b>."),
dict(t="n", o="§1 La règle qui donne le signe",
 r="On convertit vers une unité plus <b>petite</b>. Le nombre augmente ou diminue ? Et l'exposant ?",
 v="Le découpage est plus fin, il faut <b>davantage</b> de morceaux : le nombre <b>augmente</b>, l'exposant est <b>positif</b>.<br>Vers une unité plus grande : le nombre diminue, exposant négatif."),
dict(t="n", o="§2 Les puissances de 10",
 r="Que valent 10<sup>a</sup> × 10<sup>b</sup> et 10<sup>a</sup> / 10<sup>b</sup> ?",
 v="10<sup>a</sup> × 10<sup>b</sup> = <b>10<sup>a+b</sup></b><br>10<sup>a</sup> / 10<sup>b</sup> = <b>10<sup>a−b</sup></b>"),
dict(t="n", o="§2 Les puissances de 10",
 r="Que signifie un exposant négatif, par exemple 10<sup>−3</sup> ?",
 v="Un nombre <b>plus petit que 1</b> : 10<sup>−3</sup> = 1/1000 = 0,001. Ce n'est <b>pas</b> un nombre négatif."),
dict(t="n", o="§2 L'ordre de grandeur",
 r="Qu'est-ce que l'ordre de grandeur d'un nombre, et à quoi sert-il ?",
 v="C'est la <b>puissance de 10 la plus proche</b> (un cheveu : 10<sup>−4</sup> m). Il sert à <b>contrôler un résultat</b> avant de le recopier."),
dict(t="n", o="§3 Convertir : compter les crans",
 r="Sur la réglette des préfixes, que vaut un cran ?",
 v="Un cran = <b>un facteur 10</b>."),
dict(t="n", o="§3 Retenir l'ordre des préfixes",
 r="Donner, dans l'ordre, les préfixes de kilo à milli.",
 v="<b>k</b>ilo, <b>h</b>ecto, <b>da</b> (déca), <b>u</b>nité, <b>d</b>éci, <b>c</b>enti, <b>m</b>illi — un cran entre chaque."),
dict(t="n", o="§3 Retenir l'ordre des préfixes",
 r="Quels préfixes viennent au-delà de kilo, et après milli ? Combien de crans entre eux ?",
 v="On avance de <b>3 crans</b> à la fois.<br>Au-delà de kilo : <b>M</b>éga (10<sup>6</sup>), <b>G</b>iga (10<sup>9</sup>), <b>T</b>éra (10<sup>12</sup>).<br>Après milli : <b>µ</b> micro (10<sup>−6</sup>), <b>n</b> nano (10<sup>−9</sup>), <b>p</b> pico (10<sup>−12</sup>) — « Mille Microbes Nagent Profondément »."),
dict(t="n", o="§3 Le piège des unités composées",
 r="Que valent 1 cm² en m², et 1 L en m³ ?",
 v="1 cm² = (10<sup>−2</sup> m)² = <b>10<sup>−4</sup> m²</b><br>1 L = 1 dm³ = (10<sup>−1</sup> m)³ = <b>10<sup>−3</sup> m³</b><br>Sur une aire, la puissance de 10 s'élève au carré ; sur un volume, au cube."),
dict(t="n", o="§3 La règle d'or du calcul",
 r="Que fait-on avant tout calcul numérique en physique ?",
 v="On convertit <b>toutes</b> les grandeurs en <b>unités SI</b> (m, kg, s…). Le résultat sort alors dans l'unité SI."),
dict(t="n", o="§4 Les durées",
 r="Combien valent 1,5 h et 2,25 h en heures et minutes ?",
 v="La partie décimale est une fraction d'heure, × 60 :<br>1,5 h = <b>1 h 30 min</b> ; 2,25 h = <b>2 h 15 min</b>."),
dict(t="n", o="§4 Les durées",
 r="Comment passe-t-on des km/h aux m/s ?",
 v="On <b>divise par 3,6</b> (et on multiplie par 3,6 dans l'autre sens).<br>Exemple : 108 km/h = 30 m/s."),
dict(t="n", o="§5 Proportionnalité",
 r="À quelle condition deux grandeurs sont-elles proportionnelles ?",
 v="Leur <b>quotient est constant</b> : on passe de l'une à l'autre en multipliant toujours par le même nombre (coefficient de proportionnalité)."),
dict(t="n", o="§5 Une droite ne suffit pas",
 r="Comment reconnaît-on la proportionnalité sur un graphique ?",
 v="Une <b>droite</b> qui <b>passe par l'origine</b>. Les deux conditions sont nécessaires."),
dict(t="n", o="§7 Transformer une formule",
 r="Sur quel principe repose la transformation d'une formule ?",
 v="Une égalité reste vraie si l'on fait <b>la même opération sur ses deux membres</b> (ajouter, soustraire, multiplier, diviser par un même nombre non nul)."),
# --- méthodes
dict(t="m", o="§3 Méthode 1",
 r="Comment convertir 680 nm en mètres ?",
 v="1. <b>Compter les crans</b> de nano à l'unité : 9 crans (3 + 3 + 3).<br>2. <b>Choisir le signe</b> : le mètre est un découpage plus gros, le nombre diminue → exposant <b>négatif</b>.<br>3. <b>Écrire</b> : λ = 680 × 10<sup>−9</sup> m."),
dict(t="m", o="§3 Unités composées",
 r="Comment convertir une aire de 2,5 mm² en m² ?",
 v="1. Crans entre mm et m : <b>3</b>, vers une unité plus grosse → 10<sup>−3</sup>.<br>2. C'est une aire : on élève <b>une seule fois</b> au carré → (10<sup>−3</sup>)² = 10<sup>−6</sup>.<br>3. S = 2,5 × 10<sup>−6</sup> m²."),
dict(t="m", o="§4 Méthode 2",
 r="Comment convertir 1 h 45 min 20 s en secondes ?",
 v="1. Convertir chaque part : 1 h = 3600 s ; 45 min = 45 × 60 = 2700 s ; reste 20 s.<br>2. Additionner : Δt = 3600 + 2700 + 20 = <b>6320 s</b>."),
dict(t="m", o="§5 Proportionnel ou pas ?",
 r="Comment vérifier qu'un tableau de mesures traduit une proportionnalité ?",
 v="1. Calculer le <b>quotient</b> des deux grandeurs pour <b>chaque</b> couple de valeurs.<br>2. S'il est <b>constant</b> → proportionnalité ; sinon, non.<br>3. Sur le graphique : droite <b>et</b> origine."),
dict(t="m", o="§6 Méthode 3",
 r="6,0 m de câble pèsent 54 g. Comment trouver la masse de 14 m ?",
 v="1. Vérifier que c'est proportionnel (câble homogène).<br>2. <b>Passer à l'unité</b> : 1 m pèse 54 / 6,0 = 9,0 g.<br>3. <b>Multiplier</b> : 14 × 9,0 = <b>126 g</b>.<br>4. Contrôler : un peu plus du double, des deux côtés."),
dict(t="m", o="§7 Méthode 4",
 r="Comment isoler Δθ dans Q = m × c × Δθ ?",
 v="1. Repérer ce qui gêne : Δθ est multiplié par m et par c.<br>2. <b>Diviser les deux membres</b> par m × c.<br>3. Écrire : <b>Δθ = Q / (m × c)</b>.<br>4. Contrôler par les unités."),
dict(t="m", o="§7 Quand la formule contient une somme",
 r="Comment isoler R dans E − R × I = U ?",
 v="1. D'abord <b>déplacer le terme entier</b> : E − U = R × I.<br>2. Puis <b>diviser</b> les deux membres par I : <b>R = (E − U) / I</b>.<br>Le produit en croix ne marche pas tant qu'une somme reste."),
]

# =====================================================================
CARTES["ch01"] = [
dict(t="n", o="§1 Mesurer, c'est comparer",
 r="Quels sont les trois éléments d'un résultat de mesure ?",
 v="Une <b>valeur</b>, une <b>incertitude</b> et une <b>unité</b> :<br>d = (25,020 ± 0,008) mm."),
dict(t="n", o="§1 Le système international",
 r="Citer les sept unités de base du SI.",
 v="<b>mètre</b> (m), <b>kilogramme</b> (kg), <b>seconde</b> (s), <b>ampère</b> (A), <b>kelvin</b> (K), <b>mole</b> (mol), <b>candela</b> (cd). Les autres unités (N, V, J…) en dérivent."),
dict(t="n", o="§2 Justesse et fidélité",
 r="Qu'est-ce que la justesse d'une série de mesures ? Quel type d'erreur la dégrade ?",
 v="L'écart entre la <b>moyenne</b> des mesures et la <b>valeur vraie</b>. Elle est dégradée par une <b>erreur systématique</b> (zéro décalé, appareil mal réglé)."),
dict(t="n", o="§2 Justesse et fidélité",
 r="Qu'est-ce que la fidélité d'une série de mesures ? Quel type d'erreur la dégrade ?",
 v="Le <b>regroupement</b> des mesures entre elles. Elle est dégradée par les <b>erreurs aléatoires</b> (lecture, vibrations, opérateur)."),
dict(t="n", o="§2 Deux remèdes différents",
 r="Répéter les mesures corrige-t-il un défaut de justesse ?",
 v="<b>Non, jamais.</b> Répéter et moyenner réduit les erreurs <b>aléatoires</b> (fidélité). Un défaut de justesse se corrige en <b>réglant ou étalonnant</b> l'instrument."),
dict(t="n", o="§2 Justesse et fidélité",
 r="Des mesures très groupées mais toutes décalées de la valeur vraie sont…",
 v="<b>fidèles mais pas justes</b>."),
dict(t="n", o="§3 Les chiffres significatifs",
 r="Quels zéros comptent comme chiffres significatifs ? Combien en a 0,0250 ?",
 v="Les zéros <b>de tête</b> ne comptent pas, les zéros <b>à droite</b> comptent.<br>0,0250 a <b>3</b> chiffres significatifs."),
dict(t="n", o="§3 Les chiffres significatifs",
 r="Combien de chiffres garde-t-on au résultat d'un produit ou d'un quotient ? d'une somme ?",
 v="Produit, quotient : le <b>plus petit nombre de chiffres significatifs</b> des données.<br>Somme, différence : le <b>plus petit nombre de décimales</b>."),
dict(t="n", o="§4 Une série de mesures se disperse",
 r="Pourquoi l'histogramme d'une série de mesures a-t-il une forme de cloche ?",
 v="C'est la signature des <b>erreurs aléatoires</b> : elles jouent autant dans un sens que dans l'autre. C'est pour cela que la <b>moyenne</b> les compense."),
dict(t="n", o="§5 De la dispersion à l'incertitude",
 r="Que mesure l'écart-type s ? et l'incertitude-type u ?",
 v="<b>s</b> : la dispersion <b>des mesures</b>.<br><b>u</b> : le doute qui reste <b>sur la moyenne</b>."),
dict(t="n", o="§5 Incertitude de type A",
 r="Incertitude-type sur la moyenne de n mesures : formule ?",
 v="<b>u = s / √n</b><br>s : écart-type, n : nombre de mesures (évaluation de type A)."),
dict(t="n", o="§5 Multiplier les mesures",
 r="Par combien multiplier le nombre de mesures pour diviser l'incertitude-type par 2 ?",
 v="Par <b>4</b>, car u varie en 1/√n."),
dict(t="n", o="§6 Une seule mesure",
 r="Incertitude-type d'une mesure unique : formule ? Que vaut a ?",
 v="<b>u = a / √3</b> (type B), a = demi-largeur de l'intervalle.<br>Précision annoncée ± a → on prend a.<br>Instrument gradué de pas d → a = d / 2."),
dict(t="n", o="§6 Type A ou type B",
 r="Quand utilise-t-on u = s/√n et quand u = a/√3 ?",
 v="<b>Plusieurs mesures</b> → on exploite leur dispersion : u = s/√n (type A).<br><b>Une seule mesure</b> → on exploite l'instrument : u = a/√3 (type B)."),
dict(t="n", o="§7 Écrire le résultat",
 r="Quelles sont les deux règles d'écriture d'un résultat, dans l'ordre ?",
 v="1. Arrondir l'incertitude à <b>un seul chiffre significatif</b>.<br>2. Arrondir la valeur à la <b>même décimale</b>."),
dict(t="n", o="§8 Comparer un résultat",
 r="Écart normalisé E<sub>n</sub> : formule et critère ?",
 v="<b>E<sub>n</sub> = |m − m<sub>ref</sub>| / √(u² + u<sub>ref</sub>²)</b><br>Si E<sub>n</sub> &lt; 2 : résultats <b>compatibles</b>."),
dict(t="n", o="§8 Représenter des mesures",
 r="Quand un modèle tracé sur des points expérimentaux est-il validé ?",
 v="Quand il passe par <b>toutes les barres d'incertitude</b> — inutile qu'il passe exactement par les points."),
# --- méthodes
dict(t="m", o="§3 Méthode 1",
 r="Une plaque mesure 12,4 cm sur 3,0 cm. Comment écrire son aire ?",
 v="1. Chiffres significatifs des données : 12,4 → 3 ; 3,0 → 2.<br>2. Calculer sans arrondir : 37,2.<br>3. Produit : on garde le plus petit, <b>2</b>.<br>4. S = <b>37 cm²</b>."),
dict(t="m", o="§5 Méthode 2",
 r="Comment exploiter une série de n mesures pour donner le résultat ?",
 v="1. Calculer la <b>moyenne</b> m et l'<b>écart-type</b> s (calculatrice).<br>2. Calculer <b>u = s / √n</b>.<br>3. Arrondir u à 1 chiffre significatif, puis m à la même décimale.<br>4. Écrire x = (m ± u) unité."),
dict(t="m", o="§6 Méthode 4",
 r="Thermomètre : on lit 37,2 °C, notice ± 0,5 °C. Comment écrire le résultat ?",
 v="1. Mesure unique → type B ; a = 0,5 °C.<br>2. u = a / √3 = 0,5 / 1,732 = 0,29 °C.<br>3. Arrondir u à 1 chiffre : 0,3.<br>4. θ = <b>(37,2 ± 0,3) °C</b>."),
dict(t="m", o="§7 Écrire le résultat",
 r="Calcul : m = 25,0200 mm et u = 0,00816 mm. Comment écrire le résultat ?",
 v="1. u à un chiffre significatif : 0,00816 → <b>0,008</b>.<br>2. m à la même décimale : 25,0200 → <b>25,020</b>.<br>3. d = (25,020 ± 0,008) mm."),
dict(t="m", o="§8 Méthode 3",
 r="Comment décider si une mesure est compatible avec une valeur de référence ?",
 v="1. Calculer l'<b>écart</b> |m − m<sub>ref</sub>|.<br>2. Calculer l'incertitude de l'écart √(u² + u<sub>ref</sub>²).<br>3. Former <b>E<sub>n</sub></b> = écart / incertitude.<br>4. E<sub>n</sub> &lt; 2 → compatibles (les intervalles se recouvrent)."),
]

# =====================================================================
CARTES["ch02"] = [
dict(t="n", o="§1 L'énergie change de forme",
 r="Qu'est-ce que l'énergie ? Quelle est son unité ?",
 v="La grandeur qui mesure la capacité d'un système à <b>provoquer un changement</b> (mettre en mouvement, chauffer, éclairer…). Unité : le <b>joule (J)</b>, quelle que soit la forme."),
dict(t="n", o="§1 Conservation de l'énergie",
 r="Énoncer le principe de conservation de l'énergie.",
 v="L'énergie <b>ne se crée pas et ne disparaît pas</b> : elle se <b>convertit</b> d'une forme à une autre et se <b>transfère</b> d'un système à un autre."),
dict(t="n", o="§1 Les formes de l'énergie",
 r="Sous quelle forme est l'énergie d'une batterie chargée ? d'un volant lancé ? d'une masse en hauteur ? du rayonnement solaire ?",
 v="Batterie : <b>chimique</b> ; volant : <b>cinétique</b> ; masse en hauteur : <b>potentielle</b> ; Soleil : <b>rayonnante</b>."),
dict(t="n", o="§2 La puissance",
 r="Définir la puissance. Unités ?",
 v="L'énergie transférée <b>par unité de temps</b> : <b>P = E / Δt</b><br>P en watts (W), E en joules (J), Δt en secondes (s). 1 W = 1 J/s."),
dict(t="n", o="§2 La formule à connaître par cœur",
 r="Relation entre énergie, puissance et durée (la forme qui sert à calculer) ?",
 v="<b>E = P × Δt</b>"),
dict(t="n", o="§2 Ne pas confondre",
 r="Qu'est-ce qui figure sur la plaque d'un appareil ? sur la facture ?",
 v="Plaque : la <b>puissance</b> (indépendante de la durée d'usage).<br>Facture : l'<b>énergie</b>, qui dépend de la puissance <b>et</b> de la durée."),
dict(t="n", o="§3 Joule, wattheure, kilowattheure",
 r="Que valent 1 Wh et 1 kWh en joules ?",
 v="1 Wh = 1 W × 3600 s = <b>3600 J</b><br>1 kWh = <b>3,6 × 10<sup>6</sup> J</b><br>Autant de joules dans un Wh que de secondes dans une heure."),
dict(t="n", o="§3 Joule, wattheure, kilowattheure",
 r="Avec P en W et Δt en heures, dans quelle unité sort E = P × Δt ?",
 v="En <b>wattheures (Wh)</b>. Avec P en kW : en kWh."),
dict(t="n", o="§4 La chaîne énergétique",
 r="Dans une chaîne énergétique, que représentent la batterie, le moteur et les flèches ?",
 v="Batterie (ou réseau) : <b>réservoir</b> ; moteur : <b>convertisseur</b> ; flèches : <b>transferts</b>, avec la forme d'énergie écrite dessus."),
dict(t="n", o="§4 La chaîne énergétique",
 r="Sous quelle forme se font presque toujours les pertes ? Comment les représente-t-on ?",
 v="Sous forme <b>thermique</b> (frottements, échauffement des bobinages). Par une <b>flèche qui sort vers le bas</b> de chaque convertisseur."),
dict(t="n", o="§5 Le rendement",
 r="Définition du rendement η ? Unité ?",
 v="<b>η = E<sub>utile</sub> / E<sub>absorbée</sub> = P<sub>utile</sub> / P<sub>absorbée</sub></b><br><b>Sans unité</b>, entre 0 et 1, souvent en %."),
dict(t="n", o="§5 Le rendement",
 r="On trouve un rendement de 1,25. Qu'en conclure ?",
 v="C'est <b>forcément une erreur</b> (ou utile et absorbé inversés) : le convertisseur créerait de l'énergie, contraire à la conservation."),
dict(t="n", o="§6 Rendement d'une chaîne",
 r="Comment obtient-on le rendement global d'une chaîne de convertisseurs ?",
 v="On <b>multiplie</b> les rendements : <b>η<sub>global</sub> = η<sub>1</sub> × η<sub>2</sub> × … × η<sub>n</sub></b>"),
dict(t="n", o="§6 Le maillon faible",
 r="Dans une chaîne, quel convertisseur faut-il améliorer en premier ? Pourquoi ?",
 v="Le <b>plus mauvais</b>. Le rendement global est toujours <b>plus petit que le plus faible des maillons</b>."),
dict(t="n", o="§7 Économiser l'énergie",
 r="Sur quels leviers agir pour consommer moins d'énergie ?",
 v="Puisque E = P × Δt : réduire la <b>puissance</b> (appareil de meilleur rendement, LED) ou la <b>durée</b> (éteindre, temporiser, automatiser)."),
# --- méthodes
dict(t="m", o="§3 Méthode 1",
 r="Une LED de 9,0 W reste allumée 3,0 h. Comment calculer l'énergie en Wh, kWh et J ?",
 v="1. P en W et Δt en h → E en Wh.<br>2. E = 9,0 × 3,0 = <b>27 Wh</b>.<br>3. En kWh : <b>0,027 kWh</b>.<br>4. En J : 27 × 3600 = <b>9,7 × 10<sup>4</sup> J</b>."),
dict(t="m", o="§4 Méthode 2",
 r="Comment construire la chaîne énergétique d'un appareil ?",
 v="1. Identifier le <b>réservoir</b> de départ.<br>2. Placer les <b>convertisseurs</b> dans l'ordre.<br>3. Nommer la forme d'énergie sur chaque <b>flèche de transfert</b>.<br>4. Ajouter les <b>pertes</b> (flèche vers le bas) sous chaque convertisseur."),
dict(t="m", o="§5 Méthode 3",
 r="Un moteur absorbe 1500 W et fournit 1275 W. Comment trouver son rendement et ses pertes ?",
 v="1. Utile = 1275 W (ce qu'on veut) ; absorbé = 1500 W (ce qu'on paie).<br>2. η = 1275 / 1500 = <b>0,85</b> (85 %).<br>3. Pertes = 1500 − 1275 = <b>225 W</b>.<br>4. Vérifier η &lt; 1."),
dict(t="m", o="§6 Rendements d'une chaîne",
 r="Moteur η<sub>1</sub> = 0,88 puis compresseur η<sub>2</sub> = 0,65, 6,6 kWh consommés. Comment trouver l'énergie utile ?",
 v="1. η = 0,88 × 0,65 = <b>0,57</b>.<br>2. E<sub>utile</sub> = η × E<sub>absorbée</sub> = 0,57 × 6,6 = <b>3,8 kWh</b>.<br>3. Pertes : 6,6 − 3,8 = 2,8 kWh."),
]

# =====================================================================
CARTES["ch03"] = [
dict(t="n", o="§1 Intensité et tension",
 r="L'intensité : comment la note-t-on sur un schéma ? unité ? appareil et branchement ?",
 v="Une <b>flèche sur le fil</b>. En <b>ampères (A)</b>. Ampèremètre branché <b>en série</b>."),
dict(t="n", o="§1 Intensité et tension",
 r="La tension : comment la note-t-on sur un schéma ? unité ? appareil et branchement ?",
 v="Une <b>flèche à côté du dipôle</b>. En <b>volts (V)</b>. Voltmètre branché <b>en dérivation</b>."),
dict(t="n", o="§1 Le piège classique",
 r="L'intensité se rapporte à … ; la tension se rapporte à …",
 v="L'intensité : à <b>un fil</b>.<br>La tension : à <b>deux points</b>."),
dict(t="n", o="§1 Le sens de branchement",
 r="Multimètre en voltmètre : que mesure-t-il ? Comment le brancher pour lire U<sub>AB</sub> ?",
 v="Il affiche <b>V<sub>HI</sub> − V<sub>LO</sub></b>.<br>Pour U<sub>AB</sub> : <b>HI en A</b>, <b>LO (COM) en B</b>."),
dict(t="n", o="§1 Le sens de branchement",
 r="Le multimètre affiche une valeur négative. Est-ce une erreur ?",
 v="Non : le fléchage choisi est <b>l'inverse du sens réel</b>. L'appareil affiche une valeur <b>signée</b>."),
dict(t="n", o="§2 La loi des nœuds",
 r="Qu'est-ce qu'un nœud ?",
 v="Un point du circuit où <b>au moins trois fils</b> se rejoignent."),
dict(t="n", o="§2 La loi des nœuds",
 r="Énoncer la loi des nœuds.",
 v="En un nœud : <b>Σ I<sub>entrant</sub> = Σ I<sub>sortant</sub></b>. Les charges ne s'accumulent pas et ne disparaissent pas."),
dict(t="n", o="§2 Conséquences",
 r="Que devient l'intensité en série ? en dérivation ?",
 v="En <b>série</b> (aucun nœud) : la <b>même partout</b>.<br>En <b>dérivation</b> : le courant principal se <b>partage</b> entre les branches."),
dict(t="n", o="§3 Les deux conventions",
 r="Convention récepteur : sens des flèches de U et I ? Pour quels dipôles ?",
 v="Flèches de <b>sens contraires</b>. Pour les dipôles qui <b>reçoivent</b> de l'énergie : résistance, lampe, moteur."),
dict(t="n", o="§3 Les deux conventions",
 r="Convention générateur : sens des flèches de U et I ? Pour quels dipôles ?",
 v="Flèches de <b>même sens</b>. Pour les dipôles qui <b>fournissent</b> de l'énergie : pile, batterie, alternateur."),
dict(t="n", o="§3 Méthode pratique",
 r="Dans quel ordre flèche-t-on un circuit ?",
 v="1. On flèche d'abord <b>le courant</b> (sens au choix).<br>2. On en <b>déduit</b> le sens de chaque tension selon que le dipôle reçoit ou fournit. Jamais l'inverse."),
dict(t="n", o="§3 Un même dipôle peut changer de convention",
 r="Une batterie de voiture se flèche-t-elle toujours en convention générateur ?",
 v="Non : <b>générateur</b> quand elle démarre le moteur, <b>récepteur</b> quand l'alternateur la recharge. La convention décrit une situation, pas le composant."),
dict(t="n", o="§4 La loi des mailles",
 r="Qu'est-ce qu'une maille ?",
 v="Un <b>chemin fermé</b> du circuit : on revient au point de départ sans emprunter deux fois la même branche."),
dict(t="n", o="§4 Repérer les mailles",
 r="Combien de mailles dans un circuit : générateur + deux branches en dérivation ?",
 v="<b>Trois</b> : générateur + branche 1, générateur + branche 2, et la boucle des deux branches (sans générateur, mais c'est une maille)."),
dict(t="n", o="§4 Une histoire de dénivelé",
 r="Relation entre la tension U<sub>AB</sub> et les potentiels ? Vers où pointe sa flèche ?",
 v="<b>U<sub>AB</sub> = V<sub>A</sub> − V<sub>B</sub></b> : un dénivelé de potentiel. La flèche pointe <b>vers A</b>."),
dict(t="n", o="§4 La loi des mailles",
 r="Énoncer la loi des mailles.",
 v="Sur un tour complet d'une maille : <b>Σ U = 0</b>. Tension comptée <b>+</b> si sa flèche est dans le sens de parcours, <b>−</b> sinon."),
dict(t="n", o="§4 La loi des mailles",
 r="Sur une boucle simple (générateur E et récepteurs), comment se réarrange la loi des mailles ?",
 v="<b>E = U<sub>1</sub> + U<sub>2</sub> + …</b> : la tension du générateur se répartit entre les récepteurs."),
dict(t="n", o="Bilan",
 r="Deux dipôles en dérivation ont-ils la même tension ? Et la tension aux bornes d'un fil ?",
 v="En dérivation : <b>la même tension</b>.<br>Aux bornes d'un fil de liaison : <b>environ 0 V</b> (U = R I avec R ≈ 0)."),
# --- méthodes
dict(t="m", o="§3 Méthode pratique",
 r="Comment flécher entièrement un circuit à un générateur et deux résistances ?",
 v="1. Flécher <b>le courant</b> sur chaque branche.<br>2. Générateur : flèche de U <b>dans le même sens</b> que I.<br>3. Résistances : flèche de U <b>en sens contraire</b> de I."),
dict(t="m", o="§4 Méthode 1",
 r="Générateur 12 V, R<sub>1</sub> et R<sub>2</sub> en série, U<sub>1</sub> = 7,2 V. Comment trouver U<sub>2</sub> ?",
 v="1. Repérer la maille, flécher les tensions.<br>2. Loi des mailles : E = U<sub>1</sub> + U<sub>2</sub>.<br>3. U<sub>2</sub> = 12 − 7,2 = <b>4,8 V</b>.<br>4. Vérifier : 7,2 + 4,8 = 12."),
dict(t="m", o="§4 Méthode 1",
 r="I<sub>1</sub> = 0,45 A entre dans un nœud, I<sub>2</sub> = 0,30 A en sort. Comment trouver I<sub>3</sub> ?",
 v="1. Repérer le nœud, flécher : I<sub>1</sub> entre, I<sub>2</sub> et I<sub>3</sub> sortent.<br>2. Loi des nœuds : I<sub>1</sub> = I<sub>2</sub> + I<sub>3</sub>.<br>3. I<sub>3</sub> = 0,45 − 0,30 = <b>0,15 A</b>."),
dict(t="m", o="§1 Mesurer avec le multimètre",
 r="Comment brancher le multimètre pour mesurer l'intensité dans une branche ?",
 v="1. Ouvrir le circuit dans la branche.<br>2. Insérer l'appareil <b>en série</b> : le courant <b>entre par 10A</b> et <b>sort par LO (COM)</b>.<br>3. Sélecteur en A continu, puis lire la valeur signée."),
]

# =====================================================================
CARTES["ch04"] = [
dict(t="n", o="§1 Pourquoi le secteur est sinusoïdal",
 r="Donner trois raisons pour lesquelles le courant du secteur est sinusoïdal.",
 v="1. Un <b>alternateur</b> (bobine qui tourne dans un champ) produit naturellement une tension sinusoïdale.<br>2. Seul un courant <b>variable</b> traverse un <b>transformateur</b>.<br>3. Transporter sous <b>haute tension</b> donne une faible intensité, donc peu de pertes."),
dict(t="n", o="§2 Période et fréquence",
 r="Définir la période T et la fréquence f d'un signal périodique.",
 v="<b>T</b> : la <b>durée d'un seul motif</b>, en secondes.<br><b>f</b> : le <b>nombre de motifs par seconde</b>, en hertz (Hz)."),
dict(t="n", o="§2 Période et fréquence",
 r="Relation entre f et T ? Unités ?",
 v="<b>f = 1 / T</b> — f en Hz, T en s."),
dict(t="n", o="§2 Période et fréquence",
 r="Période et fréquence du secteur européen ?",
 v="<b>f = 50 Hz</b>, <b>T = 20 ms</b>."),
dict(t="n", o="§3 La valeur moyenne",
 r="Comment définit-on la valeur moyenne ⟨u⟩ d'un signal périodique ?",
 v="C'est l'<b>aire algébrique</b> entre la courbe et l'axe des temps sur <b>une période</b>, divisée par la période. Aires au-dessus : +, au-dessous : −."),
dict(t="n", o="§3 La valeur moyenne",
 r="Que vaut la valeur moyenne d'une sinusoïde ? Que montre un voltmètre en position continue sur une prise ?",
 v="<b>Zéro</b> : les deux alternances ont des aires opposées. Le voltmètre en continu (qui mesure la valeur moyenne) affiche <b>0</b>."),
dict(t="n", o="§4 La valeur efficace",
 r="Définir la valeur efficace d'une tension périodique.",
 v="La valeur de la tension <b>continue</b> qui produirait dans la même résistance <b>le même échauffement</b>.<br>Calcul : <b>carré → moyenne → racine</b>."),
dict(t="n", o="§4 La valeur efficace",
 r="Relation entre valeur efficace et valeur maximale ? Pour quel signal ?",
 v="<b>U<sub>eff</sub> = U<sub>max</sub> / √2</b> — pour une <b>sinusoïde seulement</b>."),
dict(t="n", o="§4 Quel voltmètre affiche quoi ?",
 r="Quel voltmètre donne la bonne valeur efficace d'un signal non sinusoïdal (variateur, découpage) ?",
 v="Seul un voltmètre <b>TRUE RMS</b>, qui fait réellement « carré, moyenne, racine ». Un voltmètre ordinaire suppose le signal sinusoïdal et se trompe."),
dict(t="n", o="§4 Contrôle",
 r="Entre quelles valeurs se situe toujours la valeur efficace ?",
 v="Elle est <b>positive</b>, comprise entre la <b>valeur moyenne</b> et la <b>valeur maximale</b>."),
# --- méthodes
dict(t="m", o="§2 Méthode 1",
 r="Comment déterminer T et f sur un oscillogramme ?",
 v="1. Repérer un <b>motif complet</b> : deux points identiques consécutifs (deux maximums).<br>2. Lire sa durée : c'est <b>T</b> (convertir en s).<br>3. <b>f = 1/T</b> (ex. 20 ms → 50 Hz).<br>4. Contrôler l'ordre de grandeur."),
dict(t="m", o="§4 Méthode 2",
 r="Signal : 8 V pendant 3 ms puis −4 V pendant 2 ms. Comment trouver sa valeur moyenne ?",
 v="1. T = 3 + 2 = 5 ms.<br>2. Aires algébriques : ⟨u⟩ = (8 × 3 + (−4) × 2) / 5.<br>3. ⟨u⟩ = 16 / 5 = <b>3,2 V</b>."),
dict(t="m", o="§4 Méthode 2",
 r="Même signal (8 V pendant 3 ms, −4 V pendant 2 ms). Comment trouver sa valeur efficace ?",
 v="1. <b>Carré</b> : 64 pendant 3 ms, 16 pendant 2 ms.<br>2. <b>Moyenne</b> du carré : (64 × 3 + 16 × 2) / 5 = 44,8 V².<br>3. <b>Racine</b> : U<sub>eff</sub> = √44,8 = <b>6,7 V</b>.<br>4. Contrôle : entre 3,2 V et 8 V."),
dict(t="m", o="§4 Valeur efficace d'une sinusoïde",
 r="Le secteur a une valeur efficace de 230 V. Comment trouver sa valeur maximale ?",
 v="1. Signal sinusoïdal → U<sub>eff</sub> = U<sub>max</sub>/√2.<br>2. Isoler : U<sub>max</sub> = U<sub>eff</sub> × √2.<br>3. U<sub>max</sub> = 230 × 1,414 = <b>325 V</b>."),
]

# =====================================================================
CARTES["ch05"] = [
dict(t="n", o="§1 La loi d'Ohm",
 r="Énoncer la loi d'Ohm. Unités ?",
 v="Pour un conducteur ohmique, U est <b>proportionnelle</b> à I : <b>U = R × I</b><br>U en V, R en Ω, I en A."),
dict(t="n", o="§1 La loi d'Ohm",
 r="Si l'on double la tension aux bornes d'une résistance, que deviennent R et I ?",
 v="<b>R ne change pas</b> (caractéristique du composant : matière, longueur, section). <b>I double</b>."),
dict(t="n", o="§2 La puissance électrique",
 r="Puissance électrique reçue par un dipôle quelconque ?",
 v="<b>P = U × I</b> (P en W, U en V, I en A). Valable pour <b>tout dipôle</b> : moteur, lampe, chargeur…"),
dict(t="n", o="§2 Trois écritures, une seule puissance",
 r="Quelles autres écritures de P pour une résistance ? Pour quel dipôle valent-elles ?",
 v="<b>P = R I²</b> et <b>P = U² / R</b>, obtenues avec la loi d'Ohm. Seulement pour un <b>conducteur ohmique</b>."),
dict(t="n", o="§3 Le signe de la puissance",
 r="Dipôle fléché en convention récepteur : que signifie P = U I &gt; 0 ? P &lt; 0 ?",
 v="<b>P &gt; 0</b> : le dipôle <b>reçoit</b> de l'énergie.<br><b>P &lt; 0</b> : il en <b>fournit</b>.<br>Une résistance donne toujours P &gt; 0."),
dict(t="n", o="§4 L'effet Joule",
 r="Puissance dissipée par effet Joule ? Si l'intensité double ?",
 v="<b>P<sub>J</sub> = R × I²</b>. I double → pertes × <b>4</b> (I triple → × 9)."),
dict(t="n", o="§4 L'effet Joule",
 r="L'effet Joule est-il un défaut ou un but ? Exemples.",
 v="Les deux : <b>défaut</b> dans un câble (énergie gaspillée), <b>but recherché</b> dans un radiateur, une plaque, un grille-pain, un fer à souder."),
dict(t="n", o="§5 Les pertes dans une ligne",
 r="Pertes et chute de tension dans une ligne de résistance R<sub>ligne</sub> parcourue par I ?",
 v="Pertes : <b>R<sub>ligne</sub> × I²</b><br>Chute de tension : <b>R<sub>ligne</sub> × I</b> (aller + retour)."),
dict(t="n", o="§5 Le rôle de la section",
 r="Comment la résistance d'un câble dépend-elle de sa section ?",
 v="Elle est <b>inversement proportionnelle</b> à la section : section plus grande → résistance et pertes plus faibles."),
dict(t="n", o="§6 Pourquoi la haute tension",
 r="Pourquoi transporte-t-on l'électricité sous haute tension ?",
 v="À puissance fixée, augmenter U <b>diminue I</b> (I = P/U). Or les pertes varient en <b>I²</b> : elles chutent énormément."),
dict(t="n", o="§6 La chaîne de distribution",
 r="Quels sont les niveaux de tension, de la ligne nationale à la prise ?",
 v="<b>400 kV</b> (pays) → <b>90 kV</b> (région) → <b>20 kV</b> (ville) → <b>230 V</b> (prise), avec un <b>transformateur</b> à chaque étage."),
dict(t="n", o="§7 Énergie et facture",
 r="Énergie consommée ? 1 kWh en joules ?",
 v="<b>E = P × Δt</b> ; P en W et Δt en h → Wh ; en s → J.<br><b>1 kWh = 3,6 × 10<sup>6</sup> J</b>."),
dict(t="n", o="§9 Ce qui blesse, c'est l'intensité",
 r="Seuils de danger du courant alternatif 50 Hz dans le corps ?",
 v="<b>0,5 mA</b> perception ; <b>10 mA</b> tétanisation ; <b>30 mA</b> paralysie respiratoire ; <b>75 mA</b> fibrillation cardiaque.<br>Ce qui blesse : l'<b>intensité</b> et la <b>durée</b>."),
dict(t="n", o="§9 Le corps humain",
 r="Résistance du corps humain, peau sèche et mouillée ? Tensions limites de sécurité ?",
 v="≈ <b>5000 Ω</b> sec, ≈ <b>1000 Ω</b> mouillé.<br>Tension limite : <b>50 V</b> en local sec, <b>25 V</b> en local humide."),
dict(t="n", o="§10 Deux protections complémentaires",
 r="Que protège le disjoncteur magnétothermique ? le disjoncteur différentiel ?",
 v="<b>Magnétothermique</b> : surveille l'intensité (surcharge, court-circuit) → protège le <b>câble</b>.<br><b>Différentiel</b> : compare courant aller et retour → protège les <b>personnes</b>."),
dict(t="n", o="§10 Deux protections complémentaires",
 r="Pourquoi le différentiel domestique est-il réglé à 30 mA ?",
 v="C'est le <b>seuil de paralysie respiratoire</b>. Il coupe en moins de 30 ms."),
# --- méthodes
dict(t="m", o="§2 Méthode 1",
 r="Plaque chauffante 2000 W sous 230 V. Comment trouver I puis R ?",
 v="1. P et U connues → P = U I : I = P/U = 2000/230 = <b>8,7 A</b>.<br>2. R = U/I = 230/8,7 = <b>26,4 Ω</b>.<br>3. Vérifier : U²/R = 230²/26,4 ≈ 2000 W."),
dict(t="m", o="§5 Méthode 2",
 r="Ligne de 0,48 Ω (aller-retour) parcourue par 16 A. Comment chiffrer pertes et chute de tension ?",
 v="1. Pertes : P<sub>J</sub> = R I² = 0,48 × 16² = <b>122 W</b>.<br>2. Chute : R I = 0,48 × 16 = <b>7,6 V</b> → 222 V au lieu de 230 V.<br>3. Énergie perdue : E = P<sub>J</sub> × Δt, puis le coût."),
dict(t="m", o="§6 Pourquoi la haute tension",
 r="Comment montrer l'intérêt de la haute tension pour transporter 100 kW sur 0,50 Ω ?",
 v="1. I = P/U : 435 A sous 230 V, 5,0 A sous 20 kV.<br>2. Pertes R I² : <b>94,5 kW</b> sous 230 V, <b>12,5 W</b> sous 20 kV.<br>3. Conclure : U × k → pertes ÷ k²."),
dict(t="m", o="§8 Méthode 3",
 r="Moteur : 1500 W absorbés, 1275 W utiles. Comment faire son bilan de puissance ?",
 v="1. Utile = 1275 W ; absorbée = 1500 W.<br>2. Pertes = 1500 − 1275 = <b>225 W</b> (effet Joule).<br>3. η = 1275/1500 = <b>0,85</b>.<br>4. Vérifier η &lt; 1."),
dict(t="m", o="§9 Méthode 4",
 r="Contact avec 230 V. Comment chiffrer le risque peau sèche / peau mouillée ?",
 v="1. Loi d'Ohm I = U/R.<br>2. Sèche (5000 Ω) : 230/5000 = <b>46 mA</b> &gt; 30 mA.<br>3. Mouillée (1000 Ω) : <b>230 mA</b> &gt; 75 mA (fibrillation).<br>4. Comparer aux seuils et conclure."),
]

# =====================================================================
CARTES["ch06"] = [
dict(t="n", o="§1 Référentiel et trajectoire",
 r="Qu'est-ce qu'un référentiel ? une trajectoire ?",
 v="<b>Référentiel</b> : l'objet (muni d'une horloge) par rapport auquel on décrit le mouvement.<br><b>Trajectoire</b> : ensemble des positions successives d'un point, dans un référentiel donné."),
dict(t="n", o="§1 La règle absolue",
 r="Par quoi commence toujours la description d'un mouvement ?",
 v="« <b>Dans le référentiel…</b> » (en STI2D, presque toujours <b>terrestre</b>). Sans référentiel, une vitesse n'a pas de sens."),
dict(t="n", o="§2 Translation",
 r="Quand un solide est-il en translation ? Quelles sont les trois translations ?",
 v="Il garde toujours la <b>même orientation</b>.<br><b>Rectiligne</b> (ascenseur), <b>circulaire</b> (nacelle de grande roue), <b>curviligne</b>."),
dict(t="n", o="§2 Le modèle du point matériel",
 r="Qu'est-ce que le modèle du point matériel ? Quand est-il valable ?",
 v="On remplace le solide par un point placé au <b>centre de masse</b>, portant toute sa masse. Valable seulement en <b>translation</b> (pas pour une roue qui tourne)."),
dict(t="n", o="§3.1 La vitesse moyenne",
 r="Vitesse moyenne : formule et unités ? Conversion km/h → m/s ?",
 v="<b>v = d / Δt</b> (v en m/s, d en m, Δt en s).<br>km/h → m/s : <b>diviser par 3,6</b>."),
dict(t="n", o="§3.2 Vitesse instantanée",
 r="Qu'est-ce que la vitesse instantanée ? Comment la lire sur la courbe x(t) ?",
 v="La limite de la vitesse moyenne quand Δt → 0 : <b>v = dx/dt</b>, la <b>dérivée</b> de la position.<br>Graphiquement : la <b>pente de la tangente</b> à x(t)."),
dict(t="n", o="§3.3 L'accélération",
 r="Définir l'accélération. Unité ?",
 v="La rapidité de variation de la vitesse : <b>a = dv/dt</b>, en <b>m/s²</b>."),
dict(t="n", o="§3.3 L'accélération",
 r="Que signifie a &gt; 0, a = 0, a &lt; 0 ?",
 v="a &gt; 0 : <b>accéléré</b> ; a = 0 : <b>uniforme</b> (vitesse constante) ; a &lt; 0 : <b>freiné</b>.<br>a = 0 ne veut pas dire « à l'arrêt »."),
dict(t="n", o="§3.3 Chronophotographie",
 r="Comment lire le régime d'un mouvement sur une chronophotographie ?",
 v="Par les <b>espacements</b> : constants → uniforme ; croissants → accéléré ; décroissants → freiné."),
dict(t="n", o="§3.4 Calculer par dérivation",
 r="Dérivées de t², de t et d'une constante ?",
 v="(t²)' = <b>2t</b> ; (t)' = <b>1</b> ; (constante)' = <b>0</b>."),
dict(t="n", o="§4 Trois mouvements",
 r="Rectiligne uniforme, rectiligne uniformément varié, circulaire uniforme : que dire de a ?",
 v="Rectiligne uniforme : <b>a = 0</b>.<br>Uniformément varié : <b>a constante non nulle</b> (démarrage, chute libre).<br>Circulaire uniforme : <b>a ≠ 0</b> car la <b>direction</b> de la vitesse change."),
# --- méthodes
dict(t="m", o="§3 Méthode 1",
 r="Positions relevées toutes les 0,20 s : 0 ; 0,15 ; 0,40 ; 0,75 m. Comment trouver le type de mouvement et a ?",
 v="1. Vitesses moyennes Δx/Δt : 0,75 ; 1,25 ; 1,75 m/s.<br>2. Elles augmentent → <b>accéléré</b>.<br>3. a = Δv/Δt = 0,50/0,20 = <b>2,5 m/s²</b>.<br>4. Même valeur partout → uniformément accéléré."),
dict(t="m", o="§3 Méthode 2",
 r="x(t) = 6,35 t² + 26 t + 156. Comment obtenir v(t) et a(t) ?",
 v="1. Dériver terme à terme : <b>v(t) = 12,70 t + 26</b>.<br>2. Dériver encore : <b>a = 12,70 m/s²</b> (constante).<br>3. Remplacer t pour une valeur : v(2,0) = 51,4 m/s."),
dict(t="m", o="§3.1 La vitesse moyenne",
 r="Comment calculer la vitesse moyenne d'un trajet donné en km et en minutes, en m/s ?",
 v="1. Convertir d en <b>m</b> et Δt en <b>s</b>.<br>2. v = d / Δt.<br>3. Contrôler l'ordre de grandeur (× 3,6 → km/h)."),
]

# =====================================================================
CARTES["ch07"] = [
dict(t="n", o="§1.1 Actions de contact et à distance",
 r="Qu'est-ce qu'une force ? Quelles sont les deux familles d'actions ?",
 v="Le modèle d'une <b>action mécanique</b> d'un objet sur un autre.<br>Actions de <b>contact</b> (main, support, ressort, air) et actions <b>à distance</b> (poids, forces magnétiques et électriques)."),
dict(t="n", o="§1.2 Les quatre caractéristiques",
 r="Quelles sont les quatre caractéristiques d'une force ?",
 v="<b>Point d'application</b>, <b>direction</b>, <b>sens</b>, <b>norme</b> (intensité) en <b>newtons (N)</b>."),
dict(t="n", o="§1.3 Où placer le point d'application",
 r="Où placer le point d'application d'une action à distance ? d'une action de contact ?",
 v="À distance (le <b>poids</b>) : au <b>centre de gravité G</b>.<br>De contact : <b>sur la zone de contact</b> (milieu de la surface d'appui, point d'accroche de la corde…)."),
dict(t="n", o="§1.3 Le contrôle qui ne trompe pas",
 r="Quelle question permet de vérifier chaque flèche d'un schéma de forces ?",
 v="« <b>Qu'est-ce qui touche l'objet à cet endroit ?</b> » Rien → c'est le poids, depuis G. Un objet → la flèche part du point de contact. Sinon : flèche à supprimer."),
dict(t="n", o="§1.4 Le poids",
 r="Caractéristiques du poids d'un objet de masse m ?",
 v="<b>P = m × g</b> (g ≈ 9,81 N/kg), <b>vertical</b>, vers le <b>bas</b>, appliqué en <b>G</b>."),
dict(t="n", o="§1.4 Les quatre forces au programme",
 r="Force d'un support, force élastique, frottement fluide : que retenir ?",
 v="<b>Support</b> : empêche de traverser ; perpendiculaire au plan sans frottement.<br><b>Ressort</b> : <b>F = k × Δℓ</b> (k en N/m), ramène vers l'équilibre.<br><b>Frottement fluide</b> : s'oppose au mouvement, croît avec la vitesse."),
dict(t="n", o="§1.4 Masse et poids",
 r="Différence entre masse et poids ?",
 v="<b>Masse</b> m en kg : quantité de matière, la même partout.<br><b>Poids</b> P en N : une force, qui dépend du lieu (g varie)."),
dict(t="n", o="§2.1 La résultante",
 r="Qu'est-ce que la résultante des forces ? Deux forces de 10 N opposées donnent… ?",
 v="La <b>somme vectorielle</b> Σ F des forces. Deux forces de 10 N opposées : résultante <b>nulle</b> (pas 20 N)."),
dict(t="n", o="§2.2 Principe d'inertie",
 r="Énoncer le principe d'inertie.",
 v="Résultante des forces <b>nulle</b> ⇔ le solide est <b>immobile</b> ou en <b>translation rectiligne uniforme</b>."),
dict(t="n", o="§2.2 L'idée à retenir",
 r="Faut-il une force pour entretenir un mouvement à vitesse constante ?",
 v="<b>Non</b> : une force sert à <b>changer</b> le mouvement. La traction d'une voiture à vitesse constante ne fait que <b>compenser les frottements</b>."),
dict(t="n", o="§2.2 Résolution graphique",
 r="Résultante nulle : comment se disposent les vecteurs forces mis tête à queue ?",
 v="Ils forment une <b>boucle fermée</b> (un triangle pour trois forces), ce qui permet de trouver les forces inconnues."),
dict(t="n", o="§3 Relier forces et mouvement",
 r="On observe un objet à vitesse constante. Que peut-on en déduire sur les forces ?",
 v="Elles se <b>compensent</b> (résultante nulle) : on peut calculer les forces inconnues. C'est le sens le plus utilisé en exercice."),
# --- méthodes
dict(t="m", o="§1 Méthode 1",
 r="Comment faire le bilan des forces d'un livre de 800 g posé sur une table ?",
 v="1. Système (le livre), référentiel terrestre.<br>2. Inventaire : poids P (à distance), réaction R de la table (contact).<br>3. Caractériser : P vertical vers le bas en G ; R vertical vers le haut au milieu du contact.<br>4. P = m g = 0,800 × 9,81 = <b>7,85 N</b> ; immobile → R = P."),
dict(t="m", o="§3 Méthode 2",
 r="Voiture de 1200 kg à vitesse constante, frottements 480 N. Comment trouver traction et réaction de la route ?",
 v="1. Vitesse constante en ligne droite → résultante <b>nulle</b>.<br>2. Bilan : P, R, traction F, frottements f.<br>3. Horizontalement : <b>F = f = 480 N</b>.<br>4. Verticalement : R = P = m g = <b>1,18 × 10<sup>4</sup> N</b>."),
dict(t="m", o="§3 Trois forces : le plan incliné",
 r="Caisse immobile sur une pente d'angle α. Comment trouver le frottement f et la réaction normale R<sub>N</sub> ?",
 v="1. Bilan : P (vertical), R<sub>N</sub> (⊥ au plan), f (le long de la pente).<br>2. Résultante nulle → <b>triangle fermé</b>.<br>3. Trigonométrie : <b>f = P sin α</b> ; <b>R<sub>N</sub> = P cos α</b>."),
]

# =====================================================================
CARTES["ch08"] = [
dict(t="n", o="§1 Travail d'une force",
 r="Travail d'une force constante : formule et unité ?",
 v="<b>W = F × d × cos α</b>, α = angle entre la force et le déplacement. En <b>joules (J)</b>. C'est le produit scalaire F⃗ · d⃗."),
dict(t="n", o="§2 Moteur, résistant ou nul",
 r="Quand le travail d'une force est-il moteur, résistant, nul ?",
 v="<b>Moteur</b> W &gt; 0 : accélère.<br><b>Résistant</b> W &lt; 0 : freine.<br><b>Nul</b> : force <b>perpendiculaire</b> au déplacement (cos 90° = 0)."),
dict(t="n", o="§2 Le travail du poids",
 r="Travail du poids sur une dénivelée h ? De quoi dépend-il ?",
 v="<b>−m g h</b> à la montée (résistant), <b>+m g h</b> à la descente (moteur), 0 à l'horizontale.<br>Il ne dépend <b>pas du chemin suivi</b>, seulement de la dénivelée."),
dict(t="n", o="§3 Puissance moyenne",
 r="Puissance moyenne d'une force ? Et à vitesse constante ?",
 v="<b>P = W / Δt</b> (en W).<br>À vitesse constante : <b>P = F × v</b>."),
dict(t="n", o="§4 Énergie cinétique",
 r="Énergie cinétique d'un solide en translation ? Unités ?",
 v="<b>E<sub>c</sub> = ½ m v²</b> — m en kg, v en <b>m/s</b>, E<sub>c</sub> en J."),
dict(t="n", o="§4 Énergie cinétique",
 r="Si la vitesse double, que devient l'énergie cinétique ?",
 v="Elle est <b>multipliée par 4</b> (v au carré)."),
dict(t="n", o="§5 Théorème de l'énergie cinétique",
 r="Énoncer le théorème de l'énergie cinétique.",
 v="<b>E<sub>c</sub>(B) − E<sub>c</sub>(A) = Σ W</b> : la variation d'énergie cinétique égale la somme des travaux des forces."),
dict(t="n", o="§6 Énergies potentielles",
 r="Énergie potentielle de pesanteur ? Énergie potentielle élastique ?",
 v="<b>E<sub>pp</sub> = m g h</b> (h mesurée depuis une <b>référence</b> à annoncer).<br><b>E<sub>pe</sub> = ½ k x²</b> (ressort de raideur k, déformé de x)."),
dict(t="n", o="§7 Énergie mécanique",
 r="Définir l'énergie mécanique. Quand se conserve-t-elle ?",
 v="<b>E<sub>m</sub> = E<sub>c</sub> + E<sub>p</sub></b>. Elle est <b>constante sans frottement</b> ; avec frottements elle diminue, <b>dissipée en chaleur</b>."),
dict(t="n", o="§7 Énergie mécanique",
 r="Vitesse en bas d'une chute de hauteur h sans frottement ?",
 v="½ m v² = m g h → <b>v = √(2 g h)</b> (≈ 6,3 m/s pour 2,0 m), quelle que soit la forme du parcours."),
# --- méthodes
dict(t="m", o="§2 Méthode 1",
 r="Force de 800 N inclinée de 30° sur un déplacement de 15 m. Comment calculer son travail ?",
 v="1. Repérer F = 800 N, d = 15 m, α = 30°.<br>2. W = F d cos α = 800 × 15 × 0,866.<br>3. W ≈ <b>1,04 × 10<sup>4</sup> J</b>, positif → <b>moteur</b>."),
dict(t="m", o="§3 Méthode 2",
 r="Monte-charge : 250 kg élevés de 12 m en 30 s. Comment trouver sa puissance ?",
 v="1. Travail contre le poids : W = m g h = 250 × 9,81 × 12 = <b>2,94 × 10<sup>4</sup> J</b>.<br>2. P = W/Δt = 2,94 × 10<sup>4</sup>/30 = <b>981 W</b>.<br>3. Interpréter : ≈ 1 kW."),
dict(t="m", o="§5 Méthode 3",
 r="Voiture de 1200 kg à 90 km/h, force de freinage 6000 N. Comment trouver la distance d'arrêt ?",
 v="1. v = 90/3,6 = 25 m/s ; E<sub>c</sub> = ½ × 1200 × 25² = 3,75 × 10<sup>5</sup> J.<br>2. Théorème : 0 − E<sub>c</sub> = −F × d.<br>3. d = 3,75 × 10<sup>5</sup>/6000 = <b>62,5 m</b>."),
dict(t="m", o="§7 Méthode 4",
 r="Comment faire un bilan d'énergie mécanique ?",
 v="1. <b>Choisir et annoncer la référence</b> des altitudes.<br>2. Calculer E<sub>m</sub> initiale = E<sub>c</sub> + E<sub>p</sub>.<br>3. Sans frottement : E<sub>m</sub> finale = E<sub>m</sub> initiale → l'inconnue.<br>4. Vérifier la cohérence (v positive, h inférieure au départ)."),
]

# =====================================================================
CARTES["ch09"] = [
dict(t="n", o="§1 La température",
 r="Que traduit la température d'un corps ?",
 v="L'<b>agitation</b> de ses constituants microscopiques : plus ils bougent vite, plus la température est élevée."),
dict(t="n", o="§1 Les deux échelles",
 r="Relation entre T (K) et θ (°C) ? Qu'est-ce que le zéro absolu ?",
 v="<b>T = θ + 273,15</b>.<br>Le zéro absolu (0 K = −273,15 °C) est la température la plus basse possible, où l'agitation cesse."),
dict(t="n", o="§1 Les deux échelles",
 r="Un écart de 1 °C vaut combien de kelvins ?",
 v="<b>1 K</b> : les deux échelles ont le même pas, elles sont seulement décalées."),
dict(t="n", o="§1 Mesurer une température",
 r="Citer trois types de thermomètres.",
 v="À <b>dilatation</b> de liquide ; à <b>résistance</b> (sonde Pt100, R augmente avec T) ; <b>infrarouge</b> (sans contact)."),
dict(t="n", o="§2 L'énergie interne",
 r="Qu'est-ce que l'énergie interne U d'un système ?",
 v="La somme de l'énergie <b>cinétique d'agitation</b> et de l'énergie <b>potentielle d'interaction</b> de ses constituants microscopiques, en J."),
dict(t="n", o="§3 Capacité thermique massique",
 r="Définir la capacité thermique massique c. Unité ? Valeur pour l'eau ?",
 v="L'énergie pour élever de <b>1 K</b> la température de <b>1 kg</b> du matériau, en <b>J·kg<sup>−1</sup>·K<sup>−1</sup></b>.<br>Eau : <b>4180</b> (très élevée)."),
dict(t="n", o="§3 Chauffer sans changer d'état",
 r="Variation d'énergie interne d'un corps chauffé sans changement d'état ?",
 v="<b>ΔU = m c Δθ</b> avec Δθ = θ<sub>final</sub> − θ<sub>initial</sub>.<br>ΔU &gt; 0 s'il se réchauffe, &lt; 0 s'il se refroidit."),
dict(t="n", o="§4 Changement d'état",
 r="Définir l'énergie massique de changement d'état L. Énergie pour faire changer d'état une masse m ?",
 v="L'énergie pour faire changer d'état <b>1 kg</b> à <b>température constante</b>, en J/kg.<br><b>Q = m L</b>"),
dict(t="n", o="§4 Changement d'état",
 r="Énergies massiques de fusion et de vaporisation de l'eau ?",
 v="Fusion : <b>L<sub>f</sub> = 334 kJ/kg</b>.<br>Vaporisation : <b>L<sub>v</sub> = 2260 kJ/kg</b> (≈ 7 fois plus)."),
dict(t="n", o="§4 Courbe de chauffe",
 r="Sur une courbe de chauffe, quelle formule pour les pentes ? pour les paliers ?",
 v="Pentes (la température monte) : <b>m c Δθ</b>.<br>Paliers (changement d'état, θ constante) : <b>m L</b>.<br>Problème complet : on additionne les étapes."),
dict(t="n", o="§5 L'équilibre thermique",
 r="Dans quel sens se fait spontanément un transfert thermique ? Quand s'arrête-t-il ?",
 v="Du <b>corps chaud vers le corps froid</b>, jusqu'à ce qu'ils aient la <b>même température</b> : l'équilibre thermique."),
dict(t="n", o="§6 Les trois modes de transfert",
 r="Conduction, convection, rayonnement : définir et donner un exemple.",
 v="<b>Conduction</b> : de proche en proche dans un solide (manche de casserole).<br><b>Convection</b> : mouvement d'un fluide (air chaud d'un radiateur).<br><b>Rayonnement</b> : par ondes, sans contact, même dans le vide (Soleil)."),
dict(t="n", o="§6 La chaleur",
 r="Un corps « contient-il » de la chaleur ?",
 v="Non : la <b>chaleur</b> est un <b>transfert</b> d'énergie d'un corps à un autre. Un corps possède de l'<b>énergie interne</b>."),
# --- méthodes
dict(t="m", o="§3 Méthode 1",
 r="Comment calculer l'énergie pour porter 200 kg d'eau de 15 °C à 60 °C ?",
 v="1. m = 200 kg ; c = 4180 J·kg<sup>−1</sup>·K<sup>−1</sup>.<br>2. Δθ = 60 − 15 = 45 K.<br>3. ΔU = m c Δθ = 200 × 4180 × 45 = <b>3,76 × 10<sup>7</sup> J</b> (≈ 10,4 kWh)."),
dict(t="m", o="§4 Méthode 2",
 r="Comment calculer l'énergie pour faire fondre un glaçon de 34 g à 0 °C ?",
 v="1. Changement d'état : fusion, L<sub>f</sub> = 334 kJ/kg.<br>2. m = 0,034 kg.<br>3. Q = m L = 0,034 × 334 000 = <b>1,14 × 10<sup>4</sup> J</b>.<br>Pas de m c Δθ pendant le palier."),
dict(t="m", o="§5 Méthode 3",
 r="200 g d'eau à 80 °C versés dans 300 g d'eau à 20 °C. Comment trouver la température finale ?",
 v="1. Système isolé : énergie cédée = énergie reçue.<br>2. m<sub>1</sub>c(T<sub>f</sub> − θ<sub>1</sub>) + m<sub>2</sub>c(T<sub>f</sub> − θ<sub>2</sub>) = 0.<br>3. Même c : T<sub>f</sub> = (200×80 + 300×20)/500 = <b>44 °C</b>.<br>4. Vérifier : entre 20 et 80 °C."),
dict(t="m", o="§4 Courbe de chauffe",
 r="Comment calculer l'énergie pour transformer de la glace à −10 °C en eau à 20 °C ?",
 v="1. Glace de −10 à 0 °C : m c<sub>glace</sub> Δθ.<br>2. Fusion à 0 °C : m L<sub>f</sub>.<br>3. Eau de 0 à 20 °C : m c<sub>eau</sub> Δθ.<br>4. <b>Additionner</b> les trois énergies."),
]

# =====================================================================
CARTES["ch10"] = [
dict(t="n", o="§1 Le système chimique",
 r="Qu'est-ce que le système chimique ? l'effet thermique d'une transformation ?",
 v="<b>Système</b> : les espèces qui réagissent (réactifs) et qui se forment (produits).<br><b>Effet thermique</b> : le transfert thermique Q qui accompagne la transformation."),
dict(t="n", o="§2 Exothermique ou endothermique",
 r="Transformation exothermique : que fait le système ? l'entourage ? son énergie ?",
 v="Le système <b>cède</b> de l'énergie, l'entourage <b>se réchauffe</b>, l'énergie du système <b>diminue</b>. Toutes les combustions sont exothermiques."),
dict(t="n", o="§2 Exothermique ou endothermique",
 r="Transformation endothermique : que fait le système ? l'entourage ? son énergie ?",
 v="Le système <b>reçoit</b> de l'énergie, l'entourage <b>se refroidit</b>, l'énergie du système <b>augmente</b> (poche de froid instantané)."),
dict(t="n", o="§3 Le triangle du feu",
 r="Quels sont les trois côtés du triangle du feu ?",
 v="<b>Combustible</b> (ce qui brûle) + <b>comburant</b> (O<sub>2</sub> de l'air) + <b>énergie d'activation</b> (apport pour amorcer)."),
dict(t="n", o="§3 Combustion complète",
 r="Produits d'une combustion complète ? Équation de la combustion du méthane ?",
 v="<b>CO<sub>2</sub> et H<sub>2</sub>O</b>.<br><b>CH<sub>4</sub> + 2 O<sub>2</sub> → CO<sub>2</sub> + 2 H<sub>2</sub>O</b>"),
dict(t="n", o="§3 Combustion incomplète",
 r="Quand une combustion est-elle incomplète ? Que produit-elle en plus ?",
 v="Quand il <b>manque du dioxygène</b>. Elle produit en plus du <b>monoxyde de carbone CO</b> et des <b>suies</b>."),
dict(t="n", o="§4 Énergie d'activation",
 r="Pourquoi une combustion s'auto-entretient-elle ? Quand s'arrête-t-elle ?",
 v="L'énergie libérée porte le combustible voisin à sa température d'inflammation. Elle s'arrête dès qu'<b>un côté du triangle disparaît</b>."),
dict(t="n", o="§5 Pouvoir calorifique",
 r="Définir le pouvoir calorifique. Énergie libérée par une masse m ?",
 v="L'énergie libérée par la combustion complète de <b>1 kg</b> (ou 1 L) de combustible, en MJ/kg.<br><b>E = PC × m</b>"),
dict(t="n", o="§5 Ordres de grandeur",
 r="Pouvoirs calorifiques du bois, de l'éthanol, de l'essence, du gaz naturel, du dihydrogène ?",
 v="Bois ≈ <b>15</b> ; éthanol ≈ <b>27</b> ; essence/gazole ≈ <b>43-44</b> ; gaz naturel ≈ <b>50</b> ; H<sub>2</sub> ≈ <b>120</b> MJ/kg."),
dict(t="n", o="§5 Conversions",
 r="1 kWh en MJ ? 1 kcal en kJ ?",
 v="<b>1 kWh = 3,6 MJ</b> ; <b>1 kcal ≈ 4,18 kJ</b>."),
dict(t="n", o="§7 Dangers",
 r="Pourquoi le monoxyde de carbone est-il dangereux ? Comment s'en protéger ?",
 v="Il est <b>incolore, inodore et toxique</b> (combustion incomplète). Protection : <b>détecteur de CO</b>, ventilation, entretien des appareils."),
dict(t="n", o="§7 Dangers",
 r="Quel extincteur pour un feu de solides ? pour un feu d'huile ou électrique ?",
 v="Solides : <b>eau</b>. Huile, liquides, gaz, feu électrique : <b>CO<sub>2</sub></b> ou <b>poudre</b> — <b>jamais d'eau</b>."),
# --- méthodes
dict(t="m", o="§3 Méthode 1",
 r="Comment analyser une combustion (exemple : chalumeau à acétylène) ?",
 v="1. <b>Système</b> : réactifs → produits.<br>2. <b>Combustible</b> (acétylène) et <b>comburant</b> (O<sub>2</sub>).<br>3. <b>Énergie d'activation</b> (étincelle).<br>4. <b>Effet thermique</b> : dégage de la chaleur → exothermique."),
dict(t="m", o="§5 Méthode 2",
 r="Plein de 50 L d'essence (ρ = 0,750 kg/L, PC = 42,7 MJ/kg). Comment trouver l'énergie libérée ?",
 v="1. Masse : m = ρ V = 0,750 × 50 = 37,5 kg.<br>2. E = PC × m = 42,7 × 37,5 = <b>1,6 × 10<sup>3</sup> MJ</b>.<br>3. En kWh : 1,6 × 10<sup>3</sup>/3,6 ≈ <b>445 kWh</b>."),
dict(t="m", o="§6 Méthode 3",
 r="Comment déterminer un pouvoir calorifique par calorimétrie ?",
 v="1. Chauffer une masse d'eau connue : Δθ.<br>2. Q = m<sub>eau</sub> c Δθ.<br>3. Peser le combustible consommé Δm.<br>4. <b>PC = Q / Δm</b> ; résultat sous-estimé (pertes vers l'air et le récipient)."),
dict(t="m", o="§7 Dangers",
 r="Que faire en cas d'odeur de gaz ?",
 v="1. <b>Aérer</b>.<br>2. <b>Couper le gaz</b> au compteur.<br>3. <b>Aucune flamme ni étincelle</b> (pas d'interrupteur)."),
]

# =====================================================================
CARTES["ch11"] = [
dict(t="n", o="§2 L'irradiance",
 r="Définir l'irradiance. Unité ? Appareil de mesure ?",
 v="La puissance lumineuse reçue par unité de surface : <b>E = P / S</b>, en <b>W/m²</b>. Mesurée au <b>pyranomètre</b>."),
dict(t="n", o="§2 Attention à la notation",
 r="Dans ce chapitre, que désigne la lettre E ? Comment ne pas se tromper ?",
 v="L'<b>irradiance</b> (W/m²), pas une énergie (J). On regarde toujours l'<b>unité</b>."),
dict(t="n", o="§2 Ordres de grandeur",
 r="Irradiance du Soleil au sol par ciel dégagé ?",
 v="<b>E ≈ 1000 W/m²</b>, la valeur de référence des calculs."),
dict(t="n", o="§3 La puissance reçue",
 r="Puissance lumineuse reçue par une surface S ?",
 v="<b>P = E × S</b> : proportionnelle à la surface."),
dict(t="n", o="§3 L'effet de l'orientation",
 r="Pourquoi l'irradiance diminue-t-elle quand les rayons arrivent obliquement ?",
 v="La même puissance se répartit sur une <b>surface plus grande</b>. D'où l'inclinaison des panneaux vers le sud."),
dict(t="n", o="§4 Le laser",
 r="Pourquoi un laser de 1 mW est-il dangereux pour l'œil ?",
 v="Il est <b>directif</b> : sa puissance reste concentrée sur une section minuscule, donc son <b>irradiance</b> est énorme. Le danger vient de la <b>concentration</b>, pas de la puissance."),
dict(t="n", o="§5 Rendement d'un panneau",
 r="Rendement d'un panneau photovoltaïque ? Valeurs courantes ?",
 v="<b>η = P<sub>élec</sub> / (E × S)</b>, entre <b>15 et 20 %</b> en pratique. Le reste échauffe le panneau."),
dict(t="n", o="§6 Dimensionner",
 r="Surface de panneaux nécessaire pour une puissance électrique P<sub>élec</sub> ?",
 v="<b>S = P<sub>élec</sub> / (η × E)</b>"),
dict(t="n", o="§6 Sur une année",
 r="Énergie solaire reçue par an par une surface bien orientée en France ?",
 v="Environ <b>1200 kWh/m²</b> par an."),
# --- méthodes
dict(t="m", o="§3 Méthode 1",
 r="Toit de 40 m² sous E = 1000 W/m². Comment trouver la puissance reçue ?",
 v="1. P = E × S.<br>2. P = 1000 × 40 = <b>40 kW</b>.<br>3. C'est la puissance <b>reçue</b>, pas celle récupérée."),
dict(t="m", o="§4 Méthode 2",
 r="Pointeur laser 1 mW, faisceau de 1 mm². Comment trouver son irradiance ?",
 v="1. Convertir : P = 10<sup>−3</sup> W ; S = 1 mm² = <b>10<sup>−6</sup> m²</b>.<br>2. E = P/S = <b>1000 W/m²</b>.<br>3. Autant que le Soleil à midi → danger pour l'œil."),
dict(t="m", o="§5 Méthode 3",
 r="Panneau de 1,7 m² délivrant 300 W sous 1000 W/m². Comment trouver son rendement ?",
 v="1. Puissance reçue : E × S = 1000 × 1,7 = 1700 W.<br>2. η = 300/1700 ≈ <b>0,18</b> (18 %).<br>3. Commenter : valeur normale, le reste chauffe le panneau."),
dict(t="m", o="§6 Dimensionner une installation",
 r="Quelle surface pour 3 kW avec des panneaux à 18 % sous 1000 W/m² ? Production annuelle ?",
 v="1. S = 3000/(0,18 × 1000) ≈ <b>17 m²</b>.<br>2. Par an : 1200 kWh/m² × 17 × 0,18 ≈ <b>3700 kWh</b>."),
]

# =====================================================================
CARTES["ch12"] = [
dict(t="n", o="§1 Les familles de matériaux",
 r="Quelles sont les quatre familles de matériaux ? Qu'est-ce qu'un composite ?",
 v="<b>Métalliques</b>, <b>organiques</b>, <b>minéraux</b>, <b>composites</b>.<br>Un composite associe au moins deux matériaux de familles différentes (fibre de carbone : fibres + résine)."),
dict(t="n", o="§2 Les propriétés",
 r="Citer les six familles de propriétés d'un matériau.",
 v="<b>Mécaniques</b>, <b>électriques</b>, <b>thermiques</b>, <b>optiques</b>, <b>chimiques</b>, <b>environnementales</b>."),
dict(t="n", o="§2 Masse volumique",
 r="Définir la masse volumique. Unité SI ?",
 v="<b>ρ = m / V</b>, en <b>kg/m³</b>. Elle décide si une pièce est lourde ou légère."),
dict(t="n", o="§3 Cahier des charges",
 r="Qu'est-ce qu'un cahier des charges ? Quand élimine-t-on un matériau candidat ?",
 v="La liste des <b>critères</b> que la pièce doit satisfaire. <b>Un seul critère non respecté</b> suffit à éliminer un candidat."),
dict(t="n", o="§4 Résistivité",
 r="Résistance d'un conducteur de longueur L et section S ? Résistivité du cuivre ?",
 v="<b>R = ρ L / S</b> (ρ en Ω·m, S en m²).<br>Cuivre : <b>1,7 × 10<sup>−8</sup> Ω·m</b> ; un isolant comme le verre dépasse 10<sup>10</sup> Ω·m."),
dict(t="n", o="§4 Résistance thermique",
 r="Résistance thermique surfacique d'une paroi ? Comment se lit-elle ?",
 v="<b>R<sub>th</sub> = e / λ</b> (m²·K/W), e épaisseur, λ conductivité thermique. Plus elle est grande, mieux la paroi <b>isole</b>."),
dict(t="n", o="§4 Indice de réfraction",
 r="Définir l'indice de réfraction. Valeur pour le verre ?",
 v="<b>n = c / v</b> (vitesse dans le vide / vitesse dans le matériau). Verre : <b>n ≈ 1,50</b>."),
dict(t="n", o="§5 Couche externe",
 r="Quand un atome est-il stable ? Qu'est-ce qu'une liaison covalente ?",
 v="Quand sa couche externe contient <b>8 électrons</b> (2 pour H).<br>Liaison covalente : une <b>paire d'électrons mise en commun</b> entre deux atomes."),
dict(t="n", o="§5 À savoir par cœur",
 r="Nombre de liaisons formées par H, C, N, O, Cl ?",
 v="H : <b>1</b> ; C : <b>4</b> ; N : <b>3</b> ; O : <b>2</b> ; Cl : <b>1</b>."),
dict(t="n", o="§5 Schéma de Lewis",
 r="Qu'apporte le schéma de Lewis par rapport à la formule développée ?",
 v="Il ajoute les <b>doublets non liants</b> (électrons de valence qui ne forment pas de liaison). H<sub>2</sub>O : 2 sur O ; HCl : 3 sur Cl ; NH<sub>3</sub> : 1 sur N."),
dict(t="n", o="§6 Les quatre représentations",
 r="Formules brute, développée, semi-développée : que montre chacune ? (exemple de l'éthanol)",
 v="<b>Brute</b> : nombre d'atomes (C<sub>2</sub>H<sub>6</sub>O).<br><b>Développée</b> : toutes les liaisons.<br><b>Semi-développée</b> : liaisons avec H sous-entendues (CH<sub>3</sub>–CH<sub>2</sub>–OH)."),
dict(t="n", o="§7 Macromolécules",
 r="Qu'est-ce qu'une macromolécule ? Exemple ?",
 v="Une molécule géante formée de la <b>répétition d'un motif</b> des milliers de fois : les <b>polymères</b> (plastiques)."),
dict(t="n", o="§7 Groupes caractéristiques",
 r="Quel groupe caractérise un alcool ? un acide carboxylique ? Exemples.",
 v="<b>–OH</b> (hydroxyle) : alcool, ex. éthanol CH<sub>3</sub>–CH<sub>2</sub>–OH.<br><b>–COOH</b> (carboxyle) : acide carboxylique, ex. acide éthanoïque CH<sub>3</sub>–COOH."),
dict(t="n", o="§8 Recyclage",
 r="Quel est l'intérêt du recyclage ? Exemple de l'aluminium.",
 v="Il referme le cycle de vie et économise <b>ressources et énergie</b> : l'aluminium recyclé demande ≈ <b>20 fois moins d'énergie</b>."),
dict(t="n", o="§8 Pictogrammes CLP",
 r="Que signalent les pictogrammes CLP les plus courants ?",
 v="Losange rouge sur fond blanc : <b>inflammable</b>, <b>corrosif</b>, <b>toxique</b>, <b>nocif/irritant</b>, <b>dangereux pour l'environnement</b>."),
# --- méthodes
dict(t="m", o="§3 Méthode 1",
 r="Comment choisir un matériau sur cahier des charges ?",
 v="1. <b>Traduire</b> le besoin en critères mesurables.<br>2. <b>Confronter</b> chaque candidat, critère par critère.<br>3. <b>Éliminer</b> dès qu'un critère n'est pas satisfait.<br>4. <b>Conclure</b> : celui qui satisfait tout, au moindre coût."),
dict(t="m", o="§4 Méthode 2",
 r="Câble de cuivre de 50 m et 2,5 mm². Comment calculer sa résistance ?",
 v="1. S = 2,5 mm² = <b>2,5 × 10<sup>−6</sup> m²</b> (facteur 10<sup>−6</sup>).<br>2. R = ρ L/S = 1,7 × 10<sup>−8</sup> × 50 / 2,5 × 10<sup>−6</sup>.<br>3. R = <b>0,34 Ω</b>."),
dict(t="m", o="§6 Méthode 3",
 r="Comment passer de la formule brute NH<sub>3</sub> au schéma de Lewis ?",
 v="1. Compter les liaisons : N 3, H 1.<br>2. Atome central : celui qui en fait le plus (N).<br>3. Relier les 3 H au N (développée).<br>4. Doublets non liants : N a 5 électrons de valence, 3 liés → <b>1 doublet non liant</b>.<br>5. Vérifier : 8 électrons autour de N, 2 autour de H."),
]

# =====================================================================
CARTES["ch13"] = [
dict(t="n", o="§1 Conservation des atomes",
 r="Que se conserve-t-il au cours d'une transformation chimique ?",
 v="Les <b>atomes</b> : il y a autant d'atomes de chaque élément avant et après. D'où la nécessité d'<b>équilibrer</b> l'équation."),
dict(t="n", o="§2 Équilibrer",
 r="Pour équilibrer une équation, que modifie-t-on ? Que ne touche-t-on jamais ?",
 v="On place des <b>coefficients stœchiométriques</b> devant les formules. On ne modifie <b>jamais les indices</b> (CO<sub>3</sub> au lieu de CO<sub>2</sub> change la molécule)."),
dict(t="n", o="§2 Équilibrer une combustion",
 r="Dans quel ordre équilibre-t-on une combustion ? Pourquoi l'oxygène en dernier ?",
 v="<b>C</b>, puis <b>H</b>, puis <b>O</b>. O<sub>2</sub> ne contient que de l'oxygène : on l'ajuste sans rien déranger."),
dict(t="n", o="§3 Les carburants",
 r="Formules générales des alcanes et des alcènes ? Groupe des alcools ?",
 v="Alcanes : <b>C<sub>n</sub>H<sub>2n+2</sub></b>.<br>Alcènes : <b>C<sub>n</sub>H<sub>2n</sub></b> (une double liaison).<br>Alcools : groupe <b>–OH</b>."),
dict(t="n", o="§4 Réactif limitant",
 r="Qu'est-ce que le réactif limitant ?",
 v="Celui qui <b>s'épuise le premier</b>. Il fixe seul la quantité de produits formés ; les autres restent <b>en excès</b>."),
dict(t="n", o="§4 La mole",
 r="Qu'est-ce qu'une mole ? Valeur de la constante d'Avogadro ?",
 v="Un paquet de <b>N<sub>A</sub> = 6,02 × 10<sup>23</sup></b> entités. La quantité de matière n s'exprime en mol.<br>0,5 mol n'est pas « presque rien » : 3,01 × 10<sup>23</sup> molécules."),
dict(t="n", o="§4 Masse molaire",
 r="Relation entre masse et quantité de matière ? Masses molaires de H, C, N, O ?",
 v="<b>n = m / M</b> (M masse molaire en g/mol).<br>H <b>1</b> ; C <b>12</b> ; N <b>14</b> ; O <b>16</b> g/mol."),
dict(t="n", o="§6 Complète ou incomplète",
 r="Quand une combustion devient-elle incomplète ? Que produit-elle ?",
 v="Quand le <b>dioxygène est limitant</b>. Elle produit en plus du <b>CO</b> et des <b>suies</b>."),
dict(t="n", o="§6 Le CO2 d'un plein",
 r="Pourquoi la masse de CO<sub>2</sub> produite dépasse-t-elle celle du carburant brûlé ?",
 v="Les atomes d'<b>oxygène</b> du CO<sub>2</sub> viennent de l'<b>air</b> : leur masse s'ajoute à celle du carbone (37,5 kg d'essence → 116 kg de CO<sub>2</sub>)."),
# --- méthodes
dict(t="m", o="§2 Méthode 1",
 r="Comment équilibrer la combustion complète du butane C<sub>4</sub>H<sub>10</sub> ?",
 v="1. Squelette : C<sub>4</sub>H<sub>10</sub> + O<sub>2</sub> → CO<sub>2</sub> + H<sub>2</sub>O.<br>2. C : 4 CO<sub>2</sub>. 3. H : 5 H<sub>2</sub>O.<br>4. O : 13 atomes → 6,5 O<sub>2</sub>.<br>5. Doubler : <b>2 C<sub>4</sub>H<sub>10</sub> + 13 O<sub>2</sub> → 8 CO<sub>2</sub> + 10 H<sub>2</sub>O</b>.<br>6. Vérifier."),
dict(t="m", o="§4 Méthode 2",
 r="Quelle quantité de matière dans 92 g d'éthanol C<sub>2</sub>H<sub>6</sub>O ?",
 v="1. M = 2 × 12 + 6 × 1 + 16 = <b>46 g/mol</b>.<br>2. n = m/M = 92/46 = <b>2,0 mol</b>.<br>3. Sens inverse : m = n × M."),
dict(t="m", o="§5 Méthode 3",
 r="0,20 mol de CH<sub>4</sub> et 0,30 mol de O<sub>2</sub> (CH<sub>4</sub> + 2 O<sub>2</sub> → CO<sub>2</sub> + 2 H<sub>2</sub>O). Comment trouver le réactif limitant ?",
 v="1. Tester : brûler 0,20 mol de CH<sub>4</sub> demande 0,40 mol de O<sub>2</sub> &gt; 0,30 → <b>O<sub>2</sub> limitant</b>.<br>2. Avancement : 0,30/2 = 0,15 mol.<br>3. Formés : 0,15 mol CO<sub>2</sub> ; 0,30 mol H<sub>2</sub>O.<br>4. Reste : 0,05 mol de CH<sub>4</sub> en excès."),
dict(t="m", o="§6 Le CO2 d'un plein",
 r="Comment calculer la masse de CO<sub>2</sub> émise par la combustion d'une masse de carburant ?",
 v="1. Équation équilibrée (2 C<sub>8</sub>H<sub>18</sub> + 25 O<sub>2</sub> → 16 CO<sub>2</sub> + 18 H<sub>2</sub>O).<br>2. n(carburant) = m/M.<br>3. Proportions : n(CO<sub>2</sub>) = 8 × n(octane).<br>4. m(CO<sub>2</sub>) = n × 44 g/mol."),
]

# =====================================================================
CARTES["ch14"] = [
dict(t="n", o="§1 Solution",
 r="Qu'est-ce qu'une solution ? un soluté ? un solvant ?",
 v="Un mélange <b>homogène</b> obtenu en dissolvant un <b>soluté</b> dans un liquide, le <b>solvant</b>."),
dict(t="n", o="§1 Solution aqueuse",
 r="Qu'est-ce qu'une solution aqueuse ? Comment la note-t-on ?",
 v="Une solution dont le solvant est l'<b>eau</b>. On note <b>(aq)</b> derrière les espèces dissoutes."),
dict(t="n", o="§2 Concentration",
 r="Concentration en quantité de matière et concentration en masse : formules et unités ?",
 v="<b>c = n / V</b> en mol/L ; <b>c<sub>m</sub> = m / V</b> en g/L.<br>Lien : <b>c<sub>m</sub> = c × M</b>."),
dict(t="n", o="§2 Le volume est celui de la solution",
 r="Dans c = n/V, que représente V ?",
 v="Le volume <b>total de la solution</b> obtenue (en L), pas le volume de solvant ajouté. D'où la fiole jaugée complétée au trait."),
dict(t="n", o="§3 Ce que diluer ne change pas",
 r="Qu'est-ce qui se conserve lors d'une dilution ? Relation de dilution ?",
 v="La <b>quantité de soluté</b> : on n'ajoute que du solvant.<br><b>c<sub>0</sub> V<sub>0</sub> = c V</b>"),
dict(t="n", o="§3 Facteur de dilution",
 r="Qu'est-ce que le facteur de dilution ?",
 v="<b>F = c<sub>0</sub> / c = V / V<sub>0</sub></b> : la concentration est divisée par F, le volume multiplié par F."),
dict(t="n", o="§4 Choisir la bonne verrerie",
 r="Quelle verrerie est précise ? Laquelle est approximative ?",
 v="Précise : <b>fiole jaugée</b>, <b>pipette jaugée</b>.<br>Approximative : <b>bécher</b>, <b>éprouvette graduée</b>."),
dict(t="n", o="§4 Échelle de teintes",
 r="Qu'est-ce qu'une échelle de teintes ? À quoi sert-elle ?",
 v="Une série de solutions de concentrations connues (dilutions successives). On y compare une solution inconnue pour estimer sa concentration : <b>dosage par étalonnage</b>."),
# --- méthodes
dict(t="m", o="§3 Méthode 1",
 r="Comment préparer 250 mL de CuSO<sub>4</sub> à 0,10 mol/L par dissolution ?",
 v="1. n = c V = 0,10 × 0,250 = 0,025 mol.<br>2. M = 159,5 g/mol.<br>3. m = n M ≈ <b>4,0 g</b> à peser.<br>4. Fiole jaugée de 250 mL : introduire, rincer, dissoudre, compléter <b>au trait de jauge</b>."),
dict(t="m", o="§3 Méthode 2",
 r="Comment préparer 100 mL à 0,020 mol/L à partir d'une solution mère à 0,10 mol/L ?",
 v="1. c<sub>0</sub>V<sub>0</sub> = cV → V<sub>0</sub> = cV/c<sub>0</sub> = <b>20 mL</b>.<br>2. Vérifier : facteur 5.<br>3. Prélever 20 mL à la <b>pipette jaugée</b>, fiole jaugée de 100 mL, compléter au trait, homogénéiser."),
dict(t="m", o="§2 Concentration",
 r="Comment passer d'une concentration en mol/L à une concentration en g/L ?",
 v="1. Calculer la masse molaire M du soluté.<br>2. <b>c<sub>m</sub> = c × M</b>.<br>3. Inversement : c = c<sub>m</sub> / M."),
]

# =====================================================================
CARTES["ch15"] = [
dict(t="n", o="§1 Oxydant et réducteur",
 r="Définir un oxydant et un réducteur.",
 v="<b>Réducteur</b> : <b>cède</b> des électrons (il est oxydé).<br><b>Oxydant</b> : <b>capte</b> des électrons (il est réduit)."),
dict(t="n", o="§1 Erreur fréquente",
 r="Qui subit l'oxydation : l'oxydant ou le réducteur ?",
 v="Le <b>réducteur</b> subit l'oxydation ; l'oxydant subit la réduction."),
dict(t="n", o="§2 Couples",
 r="Qu'est-ce qu'un couple oxydant/réducteur ? une demi-équation ?",
 v="Un oxydant et le réducteur qu'il devient en captant des électrons (Cu<sup>2+</sup>/Cu).<br>La demi-équation fait apparaître les électrons : Cu<sup>2+</sup> + 2 e<sup>−</sup> = Cu."),
dict(t="n", o="§2 Rappel pH",
 r="Solution acide, neutre, basique : quelle valeur de pH ?",
 v="Acide : <b>pH &lt; 7</b> (beaucoup de H<sup>+</sup>).<br>Neutre : <b>pH = 7</b>.<br>Basique : <b>pH &gt; 7</b> (beaucoup de HO<sup>−</sup>)."),
dict(t="n", o="§3 Corrosion",
 r="Qu'est-ce que la corrosion ? Pourquoi le fer rouille-t-il en profondeur et pas l'aluminium ?",
 v="Une oxydation <b>subie</b> par le métal (O<sub>2</sub> + eau).<br>L'oxyde d'aluminium est <b>compact et adhérent</b> ; la rouille est <b>poreuse et s'effrite</b>."),
dict(t="n", o="§3 Protection",
 r="Citer les protections contre la corrosion. Qu'est-ce qu'un métal sacrificiel ?",
 v="<b>Barrière</b> (peinture), <b>galvanisation</b>, <b>métal sacrificiel</b>.<br>Un métal <b>plus réducteur</b> (zinc) placé au contact du fer s'oxyde à sa place ; il faut le remplacer."),
dict(t="n", o="§4 Anode et cathode",
 r="Dans une pile : anode et cathode, quelle réaction, quelle borne ?",
 v="<b>Anode</b> : <b>oxydation</b>, borne <b>−</b>.<br><b>Cathode</b> : <b>réduction</b>, borne <b>+</b>.<br>La <b>CA</b>thode <b>CA</b>pte les électrons."),
dict(t="n", o="§4 Les piles",
 r="Rôle du pont salin ? Sens du courant dans le circuit extérieur ?",
 v="Le <b>pont salin</b> ferme le circuit en laissant circuler les ions.<br>Le courant circule en <b>sens inverse des électrons</b>."),
dict(t="n", o="§4 Une pile s'use",
 r="Qu'est-ce qui fixe la durée de vie d'une pile ?",
 v="Le <b>réactif limitant</b> : la pile s'arrête quand le métal de l'anode ou l'oxydant est épuisé."),
# --- méthodes
dict(t="m", o="§2 Méthode 1",
 r="Lame de zinc dans une solution de Cu<sup>2+</sup>. Comment écrire l'équation ?",
 v="1. Zn réducteur (cède), Cu<sup>2+</sup> oxydant (capte).<br>2. Oxydation : Zn → Zn<sup>2+</sup> + 2 e<sup>−</sup>.<br>3. Réduction : Cu<sup>2+</sup> + 2 e<sup>−</sup> → Cu.<br>4. Égaliser les électrons, additionner : <b>Zn + Cu<sup>2+</sup> → Zn<sup>2+</sup> + Cu</b>."),
dict(t="m", o="§2 Méthode 2",
 r="Dans quel ordre équilibrer une demi-équation en milieu acide ?",
 v="1. Poser Ox = Red.<br>2. Élément caractéristique.<br>3. <b>O</b> avec <b>H<sub>2</sub>O</b>.<br>4. <b>H</b> avec <b>H<sup>+</sup></b>.<br>5. <b>Charges</b> avec <b>e<sup>−</sup></b>.<br>6. Vérifier atomes et charges."),
dict(t="m", o="§2 Combiner deux demi-équations",
 r="MnO<sub>4</sub><sup>−</sup> (5 e<sup>−</sup>) réagit avec Fe<sup>2+</sup> (1 e<sup>−</sup>). Comment écrire l'équation ?",
 v="1. Écrire les deux demi-équations.<br>2. <b>Égaliser les électrons</b> : multiplier celle du fer par 5.<br>3. Additionner : MnO<sub>4</sub><sup>−</sup> + 8 H<sup>+</sup> + 5 Fe<sup>2+</sup> → Mn<sup>2+</sup> + 4 H<sub>2</sub>O + 5 Fe<sup>3+</sup>.<br>4. Vérifier atomes et charges."),
dict(t="m", o="§4 Les piles",
 r="Comment identifier l'anode et la cathode d'une pile ?",
 v="1. Repérer où a lieu l'<b>oxydation</b> (le métal qui se dissout) : <b>anode</b>, borne −.<br>2. Où a lieu la <b>réduction</b> : <b>cathode</b>, borne +.<br>3. Électrons de l'anode vers la cathode dans le fil ; courant en sens inverse."),
]

# =====================================================================
CARTES["ch16"] = [
dict(t="n", o="§1 Onde",
 r="Qu'est-ce qu'une onde ? Que transporte-t-elle ?",
 v="La <b>propagation d'une perturbation</b> dans un milieu. Elle transporte de l'<b>énergie</b>, <b>jamais de matière</b> : les points du milieu oscillent sur place."),
dict(t="n", o="§2 Les deux familles",
 r="Onde mécanique et onde électromagnétique : différence ? Exemples ?",
 v="<b>Mécanique</b> : a besoin d'un <b>milieu matériel</b> (son, vagues, ondes sismiques).<br><b>Électromagnétique</b> : se propage <b>même dans le vide</b> (lumière, radio, Wi-Fi)."),
dict(t="n", o="§3 Longitudinale ou transversale",
 r="Onde longitudinale, onde transversale : définir et donner un exemple.",
 v="<b>Longitudinale</b> : oscillation <b>parallèle</b> à la propagation (le son).<br><b>Transversale</b> : oscillation <b>perpendiculaire</b> (corde, vagues, lumière)."),
dict(t="n", o="§4 Les grandeurs d'une onde",
 r="Définir la période T et la longueur d'onde λ. Sur quel graphe les lit-on ?",
 v="<b>T</b> : durée d'une oscillation <b>en un point</b> → graphe en fonction du <b>temps</b>.<br><b>λ</b> : distance entre deux motifs identiques <b>à un instant</b> → graphe en fonction de la <b>position</b>."),
dict(t="n", o="§4 La relation fondamentale",
 r="Relation entre célérité, longueur d'onde et fréquence ?",
 v="<b>v = λ / T = λ × f</b> (v en m/s, λ en m, f en Hz)."),
dict(t="n", o="§4 Ce qui dépend de quoi",
 r="Quand une onde change de milieu, que deviennent f, v et λ ?",
 v="<b>f</b> ne change pas (imposée par la <b>source</b>).<br><b>v</b> change (dépend du <b>milieu</b>).<br>Donc <b>λ change</b>."),
dict(t="n", o="§5 À la rencontre d'un obstacle",
 r="Que devient l'énergie d'une onde à la frontière entre deux milieux ?",
 v="Elle se répartit en <b>transmission</b>, <b>réflexion</b> et <b>absorption</b> (qui échauffe), toujours ensemble."),
dict(t="n", o="§6 Guide d'onde",
 r="Qu'est-ce qu'un guide d'onde ? Comment la fibre optique piège-t-elle la lumière ?",
 v="Un dispositif qui <b>confine</b> une onde et la conduit avec peu de pertes. Dans la fibre, la lumière reste dans le <b>cœur</b> par <b>réflexions totales</b> sur la gaine."),
dict(t="n", o="§7 Chaîne de transmission",
 r="Quels sont les maillons d'une chaîne de transmission d'information ?",
 v="<b>Émetteur</b> (code en modulant l'onde) → <b>onde modulée</b> → <b>récepteur</b> (décode), avec un <b>code partagé</b>."),
dict(t="n", o="§7 Une onde n'est qu'un support",
 r="Où se trouve l'information transportée par une onde ?",
 v="Dans la <b>façon dont on modifie l'onde</b> (modulation) et dans le <b>code commun</b> qui permet de l'interpréter."),
# --- méthodes
dict(t="m", o="§4 Méthode 1",
 r="Diapason à 440 Hz, son à 340 m/s dans l'air. Comment trouver λ ?",
 v="1. Isoler : λ = v / f.<br>2. λ = 340/440 = <b>0,77 m</b>.<br>3. Dans l'eau (1500 m/s), f ne change pas : λ = 3,4 m."),
dict(t="m", o="§5 Méthode 2",
 r="Un sonar reçoit l'écho 0,80 s après l'émission (v = 1500 m/s). Comment trouver la profondeur ?",
 v="1. L'onde fait l'<b>aller-retour</b> : elle parcourt 2d.<br>2. 2d = v Δt → <b>d = v Δt / 2</b>.<br>3. d = 1500 × 0,80/2 = <b>600 m</b>."),
dict(t="m", o="§7 Méthode 3",
 r="Comment analyser une chaîne de transmission (télécommande de TV) ?",
 v="1. <b>Nature de l'onde</b> (infrarouge : électromagnétique).<br>2. <b>Émetteur</b> (diode).<br>3. <b>Codage</b> (suite d'impulsions).<br>4. <b>Récepteur</b> (capteur du téléviseur).<br>5. <b>Code partagé</b> nécessaire."),
]

# =====================================================================
CARTES["ch17"] = [
dict(t="n", o="§1 Onde sonore",
 r="Quelle est la nature du son ?",
 v="Une onde <b>mécanique longitudinale</b> : propagation d'une variation de <b>pression</b> dans un milieu matériel. Pas de son dans le vide."),
dict(t="n", o="§1 Célérité du son",
 r="De quoi dépend la célérité du son ? Dépend-elle de la fréquence ?",
 v="Du <b>milieu</b> (plus rapide s'il est dense et rigide). <b>Pas de la fréquence</b> : graves et aigus arrivent ensemble. C'est λ qui change avec f."),
dict(t="n", o="§2 Domaines de fréquences",
 r="Domaine des sons audibles ? Infrasons ? Ultrasons ?",
 v="Audibles : <b>20 Hz à 20 kHz</b>.<br>Infrasons : <b>&lt; 20 Hz</b> (séismes).<br>Ultrasons : <b>&gt; 20 kHz</b> (sonar, échographie)."),
dict(t="n", o="§3 La hauteur",
 r="Quelle grandeur détermine la hauteur d'un son (grave/aigu) ?",
 v="La <b>fréquence</b> : plus elle est élevée, plus le son est <b>aigu</b> ; plus elle est basse, plus il est <b>grave</b>."),
dict(t="n", o="§4 Le timbre",
 r="Qu'est-ce que le timbre ? D'où vient-il ?",
 v="Ce qui permet de reconnaître la <b>source</b> d'un son de même hauteur. Il vient des <b>harmoniques</b> (multiples de la fréquence fondamentale) : la <b>forme</b> du motif."),
dict(t="n", o="§4 Le timbre",
 r="Signal d'un diapason et signal d'un instrument : quelle différence ?",
 v="Diapason : <b>sinusoïdal pur</b>.<br>Instrument : <b>périodique non sinusoïdal</b> (fondamental + harmoniques)."),
dict(t="n", o="§5 Intensité sonore",
 r="Définir l'intensité sonore. Formule pour une source qui rayonne dans toutes les directions ?",
 v="<b>I = P / S</b> en <b>W/m²</b>.<br>À la distance d : <b>I = P / (4π d²)</b> (surface d'une sphère)."),
dict(t="n", o="§6 L'atténuation avec la distance",
 r="Si la distance à la source double, que devient l'intensité sonore ?",
 v="Elle est <b>divisée par 4</b> (distance × 3 → intensité ÷ 9)."),
dict(t="n", o="§7 Exposition sonore",
 r="Pourquoi des écouteurs de 5 mW sont-ils plus dangereux qu'un concert de 100 W ?",
 v="Ils concentrent leur puissance sur une <b>surface minuscule</b> (le conduit auditif) : l'<b>intensité reçue</b> est bien plus grande. Le danger vient de la concentration."),
dict(t="n", o="§7 Exposition sonore",
 r="Quels sont les trois leviers pour réduire l'exposition sonore ?",
 v="1. <b>S'éloigner</b> (I en 1/d²).<br>2. <b>Réduire la durée</b>.<br>3. <b>S'isoler</b> (bouchons, casque)."),
# --- méthodes
dict(t="m", o="§3 Méthode 1",
 r="5 périodes occupent 12,5 ms sur un oscillogramme. Comment trouver f et dire si le son est audible ?",
 v="1. Mesurer sur plusieurs périodes : 5T = 12,5 ms.<br>2. T = 2,5 ms = 2,5 × 10<sup>−3</sup> s.<br>3. f = 1/T = <b>400 Hz</b>.<br>4. Entre 20 Hz et 20 kHz → <b>audible</b>."),
dict(t="m", o="§5 Méthode 2",
 r="Haut-parleur de 0,50 W. Comment calculer l'intensité reçue à 2,0 m ?",
 v="1. Surface : S = 4π d² = 4π × 2,0² = 50,3 m².<br>2. I = P/S = 0,50/50,3 = <b>9,9 × 10<sup>−3</sup> W/m²</b>."),
dict(t="m", o="§6 Méthode 3",
 r="On passe de 2,0 m à 4,0 m d'une source. Comment prévoir la nouvelle intensité ?",
 v="1. La distance <b>double</b>.<br>2. La surface 4π d² est multipliée par <b>4</b>.<br>3. L'intensité est <b>divisée par 4</b>."),
]

# =====================================================================
CARTES["ch18"] = [
dict(t="n", o="§1 Onde électromagnétique",
 r="Qu'est-ce qu'une onde électromagnétique ? A-t-elle besoin d'un milieu ?",
 v="La propagation d'une perturbation <b>électrique et magnétique</b>. Elle n'a besoin d'<b>aucun milieu</b> : elle se propage dans le vide."),
dict(t="n", o="§1 Célérité de la lumière",
 r="Célérité des ondes électromagnétiques dans le vide ? Et dans le verre ?",
 v="<b>c = 3,00 × 10<sup>8</sup> m/s</b>, identique pour tout le spectre (vitesse limite).<br>Dans le verre : ralentie, ≈ 2,0 × 10<sup>8</sup> m/s."),
dict(t="n", o="§2 Relation λ et f",
 r="Relation entre λ et f dans le vide ? Comment varient-elles l'une par rapport à l'autre ?",
 v="<b>c = λ × f</b>. c étant fixée, λ et f varient en <b>sens inverse</b>."),
dict(t="n", o="§3 Spectre électromagnétique",
 r="Domaines du spectre électromagnétique, des grandes vers les petites longueurs d'onde ?",
 v="<b>Radio</b> → <b>micro-ondes</b> → <b>infrarouge</b> → <b>visible</b> → <b>ultraviolet</b> → <b>rayons X</b> → <b>rayons γ</b>."),
dict(t="n", o="§3 Le visible",
 r="Domaine de longueurs d'onde du visible ? Quelle couleur à chaque extrémité ?",
 v="De <b>400 nm (violet)</b> à <b>800 nm (rouge)</b> : une fenêtre minuscule du spectre."),
dict(t="n", o="§3 Spectre électromagnétique",
 r="Bornes du domaine des micro-ondes ?",
 v="De <b>1 mm à 1 m</b> (Wi-Fi 2,4 GHz : λ = 12,5 cm)."),
dict(t="n", o="§4 Durée de propagation",
 r="Durée de propagation de la lumière : Soleil-Terre ? Terre-Lune ?",
 v="<b>d = c × t</b>.<br>Soleil-Terre : <b>8 min 20 s</b> (500 s).<br>Terre-Lune : <b>1,3 s</b>."),
dict(t="n", o="§5 Les sources de lumière",
 r="Source à spectre continu, source monochromatique : définir et donner un exemple.",
 v="<b>Spectre continu</b> (polychromatique) : toutes les longueurs d'onde du visible (Soleil, lampe à filament).<br><b>Monochromatique</b> : une seule longueur d'onde (laser). La LED : bande étroite."),
dict(t="n", o="§5 Le laser",
 r="Quelles sont les trois propriétés du laser ?",
 v="<b>Monochromatique</b>, <b>directif</b> (faisceau parallèle), <b>cohérent</b>."),
dict(t="n", o="§6 Classes de laser",
 r="Que signifie la classe d'un laser ? Classe d'un pointeur du commerce ?",
 v="Le niveau de risque, de <b>1 (sans danger)</b> à <b>4 (brûlures œil et peau)</b>. Pointeur : <b>classe 2</b>. Ne jamais viser un œil."),
dict(t="n", o="§7 Interaction avec la matière",
 r="Comment évolue la dangerosité d'une onde avec sa longueur d'onde ? Risques des IR, UV, X ?",
 v="Plus λ est <b>petite</b>, plus l'onde est <b>énergétique</b>.<br>IR : chauffent. UV : peau et yeux. X et γ : traversent les tissus (usage encadré)."),
# --- méthodes
dict(t="m", o="§2 Méthode 1",
 r="Radio FM à 100 MHz. Comment trouver la longueur d'onde ?",
 v="1. Convertir : f = 1,00 × 10<sup>8</sup> Hz.<br>2. λ = c / f.<br>3. λ = 3,00 × 10<sup>8</sup>/1,00 × 10<sup>8</sup> = <b>3,00 m</b>."),
dict(t="m", o="§3 Méthode 2",
 r="Comment situer une onde de 2,4 GHz dans le spectre ?",
 v="1. λ = c/f = 3,00 × 10<sup>8</sup>/2,4 × 10<sup>9</sup> = <b>12,5 cm</b>.<br>2. Comparer aux bornes : entre 1 mm et 1 m.<br>3. Conclure : <b>micro-onde</b>."),
dict(t="m", o="§4 Méthode 3",
 r="Soleil à 1,50 × 10<sup>11</sup> m. Comment trouver la durée de trajet de sa lumière ?",
 v="1. Isoler : t = d / c.<br>2. t = 1,50 × 10<sup>11</sup>/3,00 × 10<sup>8</sup> = <b>500 s</b>.<br>3. Convertir : <b>8 min 20 s</b>."),
]
