# -*- coding: utf-8 -*-
# Cartes de révision écrites à la main — BTS TSMA
FILIERE = "bts-tsma"
NIVEAU = "BTS TSMA"

CARTES = {}

# =====================================================================
CARTES["ch00"] = [
dict(t="n", o="§1 Grandeur, valeur et unité",
 r="À quelle condition un résultat sort-il automatiquement dans la bonne unité ?",
 v="Avoir converti <b>toutes les données en unités SI avant de calculer</b>."),
dict(t="n", o="§1 La règle qui donne le signe",
 r="On convertit vers une unité plus <b>petite</b>. Le nombre augmente ou diminue ? Et l'exposant ?",
 v="Le découpage est plus fin, il en faut <b>davantage</b> : le nombre <b>augmente</b>, exposant <b>positif</b>.<br>Vers une unité plus grande : le nombre diminue, exposant négatif."),
dict(t="n", o="§1 Le piège du kilogramme",
 r="Sur quelle unité s'appliquent les préfixes pour une masse ?",
 v="Sur le <b>gramme</b>, jamais sur le kilogramme (pas de « kilokilogramme »). Le kg est la seule unité de base qui porte déjà un préfixe."),
dict(t="n", o="§2 Les puissances de dix",
 r="Que valent 10<sup>a</sup> × 10<sup>b</sup> et 10<sup>a</sup> / 10<sup>b</sup> ?",
 v="10<sup>a</sup> × 10<sup>b</sup> = <b>10<sup>a+b</sup></b><br>10<sup>a</sup> / 10<sup>b</sup> = <b>10<sup>a−b</sup></b>"),
dict(t="n", o="§2 L'écriture scientifique",
 r="Quelle est la forme d'une écriture scientifique ?",
 v="<b>N = a × 10<sup>n</sup></b> avec <b>1 ≤ a &lt; 10</b>.<br>45 × 10<sup>5</sup> ou 0,45 × 10<sup>7</sup> ne sont <b>pas</b> des écritures scientifiques."),
dict(t="n", o="§2 C'est la même question que pour les conversions",
 r="Écriture scientifique : comment choisir le signe de l'exposant ?",
 v="On se demande si le nombre doit <b>grandir</b> (exposant <b>positif</b>) ou <b>rapetisser</b> (exposant <b>négatif</b>) pour revenir au nombre de départ. Aucune règle de déplacement de virgule."),
dict(t="n", o="§3 La règle du plus faible",
 r="Combien de chiffres significatifs pour un produit ou un quotient ? pour une somme ?",
 v="Produit, quotient : autant que la <b>donnée la moins précise</b>.<br>Somme, différence : c'est le <b>nombre de décimales</b> qui commande.<br>On n'arrondit <b>qu'à la fin</b>."),
dict(t="n", o="§3 Pourquoi 1200 est ambigu",
 r="Combien de chiffres significatifs a 1200 ? Comment lever le doute ?",
 v="On ne sait pas : <b>2, 3 ou 4</b>. Seule l'<b>écriture scientifique</b> le dit : 1,2 × 10<sup>3</sup> (2 c.s.), 1,20 × 10<sup>3</sup> (3), 1,200 × 10<sup>3</sup> (4)."),
dict(t="n", o="§3 Toutes les valeurs ne sont pas des mesures",
 r="Compte-t-on les chiffres significatifs de « batterie 12 V » ou « réseau d'air à 6 bar » ?",
 v="Non : ce sont des valeurs <b>nominales</b> (des noms de catégorie), pas des mesures."),
dict(t="n", o="§4 Convertir : compter les crans",
 r="Préfixes de kilo à milli, puis au-delà ? Que vaut un cran ?",
 v="Un cran = <b>un facteur 10</b>.<br>k, h, da, unité, d, c, m.<br>Puis par <b>3 crans</b> : M, G, T d'un côté ; µ, n, p de l'autre (« Mille Microbes Nagent Profondément »)."),
dict(t="n", o="§5 Le piège des unités composées",
 r="Que valent 1 cm² en m², et 1 L en m³ ?",
 v="<b>1 cm² = 10<sup>−4</sup> m²</b><br><b>1 L = 1 dm³ = 10<sup>−3</sup> m³</b><br>Aire : la puissance de 10 s'élève au carré ; volume : au cube."),
dict(t="n", o="§5 Conversions du métier",
 r="1 bar en Pa ? 1 tr/min en rad/s ? T (K) en fonction de θ (°C) ?",
 v="<b>1 bar = 10<sup>5</sup> Pa</b><br><b>1 tr/min = 2π/60 rad/s</b><br><b>T = θ + 273</b>"),
dict(t="n", o="§5 Un débit, trois écritures",
 r="Une pompe débite 60 L/min. Combien en m³/s, L/s et m³/h ?",
 v="60 × 10<sup>−3</sup> / 60 = <b>1,0 × 10<sup>−3</sup> m³/s</b> = <b>1,0 L/s</b> = <b>3,6 m³/h</b>.<br>Seule l'écriture en m³/s entre dans les formules."),
dict(t="n", o="§6 Durées",
 r="Combien valent 1,5 h et 2,25 h ? Comment passe-t-on des km/h aux m/s ?",
 v="1,5 h = <b>1 h 30 min</b> ; 2,25 h = <b>2 h 15 min</b> (partie décimale × 60).<br>km/h → m/s : <b>diviser par 3,6</b>."),
dict(t="n", o="§7 Proportionnalité",
 r="Deux grandeurs sont proportionnelles si… ? Et sur un graphique ?",
 v="Leur <b>quotient est constant</b>.<br>Graphique : une <b>droite passant par l'origine</b> — les deux conditions sont nécessaires."),
dict(t="n", o="§9 Lire une droite",
 r="Formule de la pente d'une droite ? Avec quelle unité ? Quels points choisir ?",
 v="<b>a = (y<sub>2</sub> − y<sub>1</sub>) / (x<sub>2</sub> − x<sub>1</sub>)</b><br>Unité : celle de y divisée par celle de x.<br>Deux points <b>éloignés</b> de la droite."),
dict(t="n", o="§9 La règle de trois n'est pas toujours valable",
 r="Quand a-t-on le droit d'utiliser une règle de trois sur une droite ?",
 v="Seulement si la droite <b>passe par l'origine</b>. Avec une ordonnée à l'origine (décalage de capteur, tare), doubler x ne double pas y."),
dict(t="n", o="§10 Transformer une formule",
 r="Sur quel principe repose la transformation d'une formule ?",
 v="Faire <b>la même opération sur les deux membres</b> de l'égalité. C'est la seule méthode qui marche aussi avec une somme."),
dict(t="n", o="§11 Trigonométrie",
 r="Dans un triangle rectangle, que valent cos α, sin α et tan α ?",
 v="<b>cos α = adjacent / hypoténuse</b><br><b>sin α = opposé / hypoténuse</b><br><b>tan α = opposé / adjacent</b><br>Vérifier le mode <b>degrés</b> de la calculatrice."),
dict(t="n", o="§12 Contrôler un ordre de grandeur",
 r="Que fait-on toujours avant d'écrire un résultat ?",
 v="On vérifie qu'il est <b>plausible</b> (ordre de grandeur). Repérer une erreur est évalué en CCF dans la compétence <b>Valider</b>."),
# --- méthodes
dict(t="m", o="§2 Méthode 1",
 r="Comment écrire 4 500 000 Pa et 0,000072 m en écriture scientifique ?",
 v="1. Écrire le nombre entre 1 et 10 : 4,5 et 7,2.<br>2. Compter les rangs pour revenir au nombre : 6 rangs en <b>agrandissant</b> ; 5 rangs en <b>rapetissant</b>.<br>3. p = <b>4,5 × 10<sup>6</sup> Pa</b> ; e = <b>7,2 × 10<sup>−5</sup> m</b>."),
dict(t="m", o="§3 Méthode 2",
 r="Vérin : S = 38,5 cm², p = 125 bar. Comment calculer F = p S au bon nombre de chiffres ?",
 v="1. SI : S = 38,5 × 10<sup>−4</sup> m² ; p = 1,25 × 10<sup>7</sup> Pa.<br>2. Calculer sans arrondir : 48 125 N.<br>3. Données à 3 c.s. → <b>F = 4,81 × 10<sup>4</sup> N</b>.<br>4. Contrôler : ~4,9 t, plausible."),
dict(t="m", o="§5 Unités composées",
 r="Comment convertir une section de 2,5 cm² en m² ?",
 v="1. Crans de cm à m : <b>2</b>, vers une unité plus grosse → 10<sup>−2</sup>.<br>2. Aire : élever <b>une fois</b> au carré → 10<sup>−4</sup>.<br>3. S = <b>2,5 × 10<sup>−4</sup> m²</b>."),
dict(t="m", o="§6 Méthode 3",
 r="Prise de force : 540 tr/min, couple 380 N·m. Comment calculer la puissance ?",
 v="1. Convertir : ω = 540 × 2π/60 = <b>56,5 rad/s</b>.<br>2. P = C ω = 380 × 56,5 = 21 470 W.<br>3. Arrondir : <b>P = 21,5 kW</b>.<br>Oublier la conversion donne 9,55 fois trop."),
dict(t="m", o="§8 Méthode 4",
 r="6,0 m de flexible pèsent 5,4 kg. Comment trouver la masse de 14 m ?",
 v="1. Vérifier la proportionnalité (flexible homogène).<br>2. <b>Passer à l'unité</b> : 1 m pèse 5,4 / 6,0 = 0,90 kg.<br>3. Multiplier : 14 × 0,90 = <b>12,6 kg</b>.<br>4. Contrôler : un peu plus du double."),
dict(t="m", o="§10 Méthode 5",
 r="Comment isoler Δθ dans Q = m c Δθ ?",
 v="1. Δθ est multiplié par m et c.<br>2. <b>Diviser les deux membres</b> par m c.<br>3. <b>Δθ = Q / (m c)</b>.<br>4. Contrôler l'unité : J / (kg × J·kg<sup>−1</sup>·K<sup>−1</sup>) = K."),
dict(t="m", o="§10 Quand la formule contient une somme",
 r="Comment isoler h dans p<sub>A</sub> = p<sub>B</sub> + ρ g h ?",
 v="1. <b>Déplacer le terme entier</b> : p<sub>A</sub> − p<sub>B</sub> = ρ g h.<br>2. <b>Diviser</b> par ρ g : <b>h = (p<sub>A</sub> − p<sub>B</sub>) / (ρ g)</b>."),
]

# =====================================================================
CARTES["ch01"] = [
dict(t="n", o="§1.1 Les deux natures d'erreur",
 r="Erreur aléatoire : comment se manifeste-t-elle ? Comment la réduire ?",
 v="Elle change de valeur et de signe d'une mesure à l'autre : elle <b>disperse</b> les résultats. On la réduit <b>en répétant les mesures et en les moyennant</b>."),
dict(t="n", o="§1.1 Les deux natures d'erreur",
 r="Erreur systématique : comment se manifeste-t-elle ? La répétition la corrige-t-elle ?",
 v="Elle se répète à l'identique et <b>décale</b> toutes les mesures dans le même sens. Répéter <b>ne la corrige jamais</b>."),
dict(t="n", o="§1.1 La conséquence pratique",
 r="Comment révéler une erreur systématique ?",
 v="Uniquement en <b>comparant à une valeur de référence</b>. Des mesures très groupées prouvent seulement que l'erreur aléatoire est faible."),
dict(t="n", o="§1.2 D'où viennent les erreurs",
 r="Quelles sont les trois occasions de s'écarter de la valeur vraie lors d'une mesure ?",
 v="L'<b>instrument</b>, l'<b>opérateur</b> et l'<b>environnement</b>."),
dict(t="n", o="§2 Évaluer l'incertitude",
 r="Quelle différence entre erreur et incertitude ?",
 v="L'<b>erreur</b> est inconnue par nature. L'<b>incertitude u</b> est ce que l'on sait de son ampleur ; elle s'exprime dans l'unité de la grandeur."),
dict(t="n", o="§2.1 Une mesure unique",
 r="Incertitude-type d'une lecture unique sur un instrument de résolution d ?",
 v="<b>u = d / (2√3) ≈ 0,29 d</b>"),
dict(t="n", o="§2.1 Une mesure unique",
 r="Incertitude-type d'un appareil analogique de classe c sur le calibre E ?",
 v="<b>u = c × E / (100 √3)</b>"),
dict(t="n", o="§2.1 Le piège du calibre",
 r="Appareil de classe : de quoi dépend l'incertitude ? Quel calibre choisir ?",
 v="Du <b>calibre</b>, pas de la valeur lue. Choisir toujours le <b>plus petit calibre compatible</b> avec la valeur attendue."),
dict(t="n", o="§2.2 Une série de mesures",
 r="Série de n mesures : incertitude-type sur la moyenne ?",
 v="<b>u = s / √n</b> (s : écart-type expérimental). s mesure la dispersion des mesures, u l'incertitude sur la moyenne."),
dict(t="n", o="§2.2 Une série de mesures",
 r="Augmenter le nombre n de mesures réduit-il s ? et u ?",
 v="<b>s ne diminue pas</b>. u diminue, mais en 1/√n : il faut <b>quadrupler</b> n pour diviser u par 2."),
dict(t="n", o="§2.2 Incertitude élargie",
 r="Incertitude élargie : formule, valeur de k, niveau de confiance ?",
 v="<b>U = k u</b> avec <b>k = 2</b> : niveau de confiance d'environ <b>95 %</b> (convention des sujets de BTS)."),
dict(t="n", o="§2.3 Composer",
 r="Comment se composent les incertitudes pour un produit ou un quotient ?",
 v="Les incertitudes <b>relatives</b> en quadrature :<br><b>u(y)/y = √[ (u(a)/a)² + (u(b)/b)² ]</b>"),
dict(t="n", o="§2.3 Composer",
 r="Comment se composent les incertitudes pour une somme ou une différence ?",
 v="Les incertitudes <b>absolues</b> en quadrature :<br><b>u(y) = √[ u(a)² + u(b)² ]</b>"),
dict(t="n", o="§2.3 La source dominante",
 r="Pour améliorer une mesure, sur quelle source d'erreur faut-il agir ?",
 v="Sur la <b>source dominante</b> : en quadrature, la plus grande contribution écrase les autres. Améliorer une source négligeable ne change rien."),
dict(t="n", o="§3.1 Écrire un résultat",
 r="Règles d'écriture d'un résultat de mesure (TSMA) ?",
 v="<b>valeur ± incertitude, unité</b>.<br>Incertitude à <b>1 ou 2 chiffres significatifs</b>, arrondie <b>vers le haut</b>.<br>Dernier chiffre de la valeur <b>au même rang</b>."),
dict(t="n", o="§3.1 Chiffres significatifs",
 r="Combien de chiffres significatifs dans 0,00250 et dans 25,0 ?",
 v="<b>3</b> dans les deux cas : on compte à partir du premier chiffre non nul."),
dict(t="n", o="§3.2 Précision relative",
 r="Qu'est-ce que la précision relative ? À quoi sert-elle ?",
 v="<b>U / x</b>, sans unité, souvent en %. Elle permet de <b>comparer la qualité</b> de mesures portant sur des grandeurs différentes."),
dict(t="n", o="§3.3 Ce qui ne vaut pas conclusion",
 r="« L'écart à la référence est de 4 kg/m³, c'est faible. » Pourquoi n'est-ce pas une conclusion ?",
 v="Faible <b>par rapport à quoi ?</b> Seule la comparaison de l'écart à l'<b>incertitude U</b> permet de trancher."),
# --- méthodes
dict(t="m", o="§2.2 Méthode — Traiter une série de mesures",
 r="Comment traiter une série de mesures répétées ?",
 v="1. Écarter les valeurs aberrantes selon le <b>critère de l'énoncé</b>.<br>2. Calculer la moyenne x̄.<br>3. Relever s, calculer <b>u = s/√n</b> (n = valeurs conservées).<br>4. <b>U = 2u</b>."),
dict(t="m", o="§2.1 L'incertitude d'une mesure unique",
 r="Pied à coulisse de résolution 0,02 mm, une seule lecture. Comment obtenir u et U ?",
 v="1. u = d / (2√3) = 0,02 / 3,46 = <b>0,0058 mm</b>.<br>2. U = 2u = <b>0,012 mm</b>, arrondi vers le haut."),
dict(t="m", o="§3.1 Du tableur à la copie",
 r="Tableur : ρ = 1078,9 et U = 12,94 (kg/m³). Comment écrire le résultat ?",
 v="1. Arrondir U <b>vers le haut</b> à 2 chiffres : <b>13</b>.<br>2. Aligner la valeur au même rang (unités) : <b>1079</b>.<br>3. ρ = <b>(1079 ± 13) kg/m³</b>."),
dict(t="m", o="§2.3 Composer deux incertitudes",
 r="y = a × b. Comment obtenir l'incertitude sur y ?",
 v="1. Calculer les incertitudes <b>relatives</b> u(a)/a et u(b)/b.<br>2. Les composer : u(y)/y = √[(u(a)/a)² + (u(b)/b)²].<br>3. Multiplier par y pour avoir u(y).<br>4. Repérer la source dominante."),
dict(t="m", o="§3.3 Méthode — Conclure en trois temps",
 r="Comment conclure sur la compatibilité avec une valeur de référence ?",
 v="1. Construire l'intervalle <b>[x − U ; x + U]</b>.<br>2. Dire si la référence y <b>appartient</b>.<br>3. Rédiger : oui → <b>compatible</b> ; non → erreur systématique probable, <b>citer une cause</b>."),
dict(t="m", o="§3.4 Améliorer la démarche",
 r="Comment proposer une amélioration de la mesure ?",
 v="Viser la <b>source dominante</b> :<br>1. l'<b>instrument</b> (calibre, classe, verrerie jaugée) ;<br>2. le <b>protocole</b> (répéter, élargir l'étendue) ;<br>3. le <b>systématique</b> (zéro, étalonnage, température)."),
]

# =====================================================================
CARTES["ch02"] = [
dict(t="n", o="§1.1 Puissance",
 r="Définir la puissance. Relation avec l'énergie ? Unités ?",
 v="Le quotient de l'énergie échangée par la durée : <b>P = E / t</b>, soit <b>E = P × t</b>.<br>E en J, t en s, P en W (1 W = 1 J/s)."),
dict(t="n", o="§1.2 Les unités du terrain",
 r="1 kWh en J ? 1 ch en W ? Énergie d'un litre de gazole ?",
 v="<b>1 kWh = 3,6 × 10<sup>6</sup> J = 3,6 MJ</b> ; <b>1 ch = 736 W</b> ; 1 L de gazole ≈ <b>36 MJ</b>."),
dict(t="n", o="§2.1 Rotation",
 r="Puissance en rotation ? Conversion de N (tr/min) en ω ? Couple ?",
 v="<b>P = C × ω</b>, <b>ω = 2π N / 60</b> (rad/s) ; couple <b>C = F × r</b>.<br>Oublier la conversion : erreur d'un facteur 9,55."),
dict(t="n", o="§2.2 Hydraulique et électricité",
 r="Puissance hydraulique ? Puissance électrique en continu ?",
 v="Hydraulique : <b>P = p × Q<sub>v</sub></b> (Pa, m³/s).<br>Électrique : <b>P = U × I</b>."),
dict(t="n", o="§2.2 Les conversions qui tuent",
 r="Comment convertir un débit en L/min et une pression en bar pour calculer une puissance ?",
 v="L/min → m³/s : <b>÷ 60 000</b>.<br>bar → Pa : <b>× 10<sup>5</sup></b>."),
dict(t="n", o="§2 Translation",
 r="Puissance en translation ?",
 v="<b>P = F × v</b> (N, m/s)."),
dict(t="n", o="§3.2 Le rendement",
 r="Définir le rendement d'un convertisseur. Valeurs possibles ?",
 v="<b>η = P<sub>utile</sub> / P<sub>absorbée</sub></b>, sans unité, <b>entre 0 et 1</b>. η &gt; 1 : erreur de calcul."),
dict(t="n", o="§3.2 Ce qui manque n'est pas perdu",
 r="Que vaut la puissance perdue ? Sous quelle forme part-elle ?",
 v="<b>P<sub>perdue</sub> = P<sub>absorbée</sub> − P<sub>utile</sub></b>, dissipée en <b>chaleur</b> (effet Joule, frottements, échappement). L'énergie se conserve, sa qualité se dégrade."),
dict(t="n", o="§3.3 Rendements en cascade",
 r="Rendement global de plusieurs convertisseurs en série ?",
 v="Les rendements se <b>multiplient</b> : η<sub>global</sub> = η<sub>1</sub> × η<sub>2</sub> × … Le plus bas offre la plus grande marge de progrès."),
dict(t="n", o="§4.1 Consommation spécifique",
 r="Définir la consommation spécifique d'un moteur. Unité ? Valeur d'un diesel moderne ?",
 v="La <b>masse de carburant par unité d'énergie mécanique</b> produite, en <b>g/kWh</b>. Diesel moderne : <b>200 à 260 g/kWh</b>."),
dict(t="n", o="§4.1 Ne pas juger sur la consommation horaire",
 r="Pourquoi la consommation horaire (L/h) ne permet-elle pas de comparer deux moteurs ?",
 v="Elle dépend de la <b>charge</b>. Seule la <b>consommation spécifique</b> rapporte la dépense au travail réellement fourni."),
# --- méthodes
dict(t="m", o="§2.1 La prise de force",
 r="Prise de force à 540 tr/min, couple 950 N·m. Comment calculer la puissance ?",
 v="1. ω = 2π × 540/60 = <b>56,5 rad/s</b>.<br>2. P = C ω = 950 × 56,5 = <b>53,7 kW</b>.<br>3. En ch : 53 700/736 ≈ <b>73 ch</b>."),
dict(t="m", o="§3.1 Méthode — Chaîne d'énergie",
 r="Comment construire une chaîne d'énergie ?",
 v="1. <b>Source</b> et nature de son énergie.<br>2. <b>Convertisseurs</b> dans l'ordre, nommés.<br>3. <b>Nature de l'énergie</b> entre chaque bloc.<br>4. <b>Pertes</b> : flèche descendante sous chaque bloc (chaleur)."),
dict(t="m", o="§4.1 Un moteur de tracteur",
 r="Moteur : 12,0 L/h de gazole (ρ = 0,84 kg/L), 42 kW utiles. Comment calculer la consommation spécifique ?",
 v="1. Masse : 12,0 × 0,84 = 10,08 kg/h.<br>2. CS = 10,08 / 42 = 0,240 kg/kWh = <b>240 g/kWh</b>.<br>3. Comparer : entre 200 et 260 → dans la norme."),
dict(t="m", o="§4.2 Méthode — Rendement au banc",
 r="Comment déterminer un rendement au banc ?",
 v="1. Établir la charge, attendre la <b>stabilisation</b>.<br>2. Relever <b>simultanément</b> entrée et sortie.<br>3. Calculer les deux puissances (conversions !).<br>4. η et incertitude relative composée.<br>5. Comparer à la valeur constructeur (intervalle)."),
]

# =====================================================================
CARTES["ch03"] = [
dict(t="n", o="§1.1 La pression",
 r="Définir la pression. Unités ?",
 v="<b>p = F / S</b> : force répartie perpendiculairement sur une surface. p en <b>Pa</b>, F en N, S en <b>m²</b> (1 Pa = 1 N/m²)."),
dict(t="n", o="§1.1 L'erreur qui coûte cher",
 r="Section d'un piston de diamètre D ? 1 cm² en m² ?",
 v="<b>S = π D² / 4</b>.<br><b>1 cm² = 10<sup>−4</sup> m²</b> (et non 10<sup>−2</sup>)."),
dict(t="n", o="§1.2 Les unités",
 r="Relations entre bar, pascal et mégapascal ?",
 v="<b>1 bar = 10<sup>5</sup> Pa = 0,1 MPa</b> ; <b>1 MPa = 10 bar</b>. On lit en bar, on calcule en Pa."),
dict(t="n", o="§2.1 Principe fondamental de l'hydrostatique",
 r="Énoncer le principe fondamental de l'hydrostatique.",
 v="Dans un liquide au repos et incompressible : <b>Δp = ρ g h</b> (Pa ; kg/m³ ; g = 9,81 N/kg ; m). La pression est plus grande <b>en bas</b>."),
dict(t="n", o="§2.2 Le paradoxe hydrostatique",
 r="La pression au fond d'une cuve dépend-elle de sa forme ? du volume de liquide ?",
 v="<b>Non</b> : seulement de la <b>hauteur</b> et de la <b>masse volumique</b>."),
dict(t="n", o="§2.3 Pression absolue, relative",
 r="Relation entre pression absolue et relative ? Laquelle affiche le manomètre ? Laquelle pour un gaz ?",
 v="<b>p<sub>abs</sub> = p<sub>atm</sub> + p<sub>rel</sub></b>. Le manomètre affiche la <b>relative</b>. Les calculs sur un <b>gaz</b> exigent la <b>absolue</b>."),
dict(t="n", o="§3.1 Théorème de Pascal",
 r="Énoncer le théorème de Pascal. Conséquence pour deux pistons ?",
 v="Une variation de pression dans un fluide incompressible enfermé <b>se transmet intégralement</b> partout.<br><b>F<sub>1</sub>/S<sub>1</sub> = F<sub>2</sub>/S<sub>2</sub></b> → F<sub>2</sub> = F<sub>1</sub> × S<sub>2</sub>/S<sub>1</sub>."),
dict(t="n", o="§3.2 Le prix de la multiplication",
 r="Que paie-t-on quand une presse multiplie la force ?",
 v="La <b>course</b> : S<sub>1</sub> d<sub>1</sub> = S<sub>2</sub> d<sub>2</sub>. On échange de la course contre de la force ; l'énergie se conserve."),
dict(t="n", o="§4.1 Les instruments",
 r="Manomètre et capteur de pression : que délivrent-ils ?",
 v="<b>Manomètre</b> : affiche une pression <b>relative</b> ; incertitude fixée par sa classe.<br><b>Capteur</b> : une <b>tension</b> proportionnelle à la pression, pour une acquisition."),
dict(t="n", o="§4.3 Incertitude relative",
 r="Si ρ = a / g avec g très précis, quelle incertitude relative sur ρ ?",
 v="<b>u(ρ)/ρ = u(a)/a</b> : 3 % sur la pente → 3 % sur ρ."),
# --- méthodes
dict(t="m", o="§2.1 Méthode — PFH dans les trois sens",
 r="Comment utiliser Δp = ρ g h selon l'inconnue ?",
 v="Pression : <b>Δp = ρ g h</b>.<br>Hauteur : <b>h = Δp / (ρ g)</b> (indicateur de niveau).<br>Fluide : <b>ρ = Δp / (g h)</b>.<br>h en m, hauteur de liquide <b>au-dessus du point</b>."),
dict(t="m", o="§3.1 Un ordre de grandeur d'atelier",
 r="Petit piston 2,0 cm² poussé par 200 N, grand piston 50 cm². Comment trouver p et F<sub>2</sub> ?",
 v="1. p = 200 / 2,0 × 10<sup>−4</sup> = <b>1,0 × 10<sup>6</sup> Pa</b> (10 bar).<br>2. F<sub>2</sub> = p × S<sub>2</sub> = 10<sup>6</sup> × 50 × 10<sup>−4</sup> = <b>5000 N</b>.<br>3. Force × 25, course ÷ 25."),
dict(t="m", o="§4.2 Méthode — ρ par la pente",
 r="Comment déterminer une masse volumique par la pente de p = f(h) ?",
 v="1. Zéro du capteur <b>à la surface</b>.<br>2. Au moins 6 couples (h ; p), h en m.<br>3. Tracer, vérifier l'alignement et l'origine.<br>4. Pente a = Δp/Δh sur deux points éloignés.<br>5. <b>ρ = a / g</b>."),
dict(t="m", o="§4.3 Conclure proprement",
 r="Pente a = 8,76 × 10<sup>3</sup> Pa/m, incertitude 3 %, référence 870 kg/m³. Comment conclure ?",
 v="1. ρ = 8760/9,81 = 893 kg/m³.<br>2. u = 3 % → 27, arrondi vers le haut à 30.<br>3. ρ = <b>(890 ± 30) kg/m³</b> → [860 ; 920].<br>4. 870 y est → <b>compatible</b>."),
]

# =====================================================================
CARTES["ch04"] = [
dict(t="n", o="§1.1 Débits",
 r="Définir le débit volumique et le débit massique. Formules et unités ?",
 v="<b>Q<sub>v</sub> = V / t = S × v</b> (m³/s) : volume traversant une section par seconde.<br><b>Q<sub>m</sub> = ρ × Q<sub>v</sub></b> (kg/s)."),
dict(t="n", o="§1.1 Les deux conversions",
 r="Comment convertir des L/min en m³/s ? Section d'une conduite de diamètre D ?",
 v="L/min → m³/s : <b>÷ 60 000</b>.<br><b>S = π D² / 4</b>, D converti en m <b>avant</b> d'élever au carré."),
dict(t="n", o="§2.1 Équation de continuité",
 r="Énoncer l'équation de continuité.",
 v="En écoulement permanent incompressible, le débit est le même dans toute section : <b>Q<sub>v</sub> = S<sub>1</sub> v<sub>1</sub> = S<sub>2</sub> v<sub>2</sub></b>."),
dict(t="n", o="§2.1 La conséquence à retenir",
 r="Où le fluide accélère-t-il ? Si le diamètre est divisé par 2 ?",
 v="Il <b>accélère dans les rétrécissements</b>, ralentit dans les élargissements. Diamètre ÷ 2 → vitesse <b>× 4</b>."),
dict(t="n", o="§3.1 Théorème de Bernoulli",
 r="Énoncer le théorème de Bernoulli et ses conditions.",
 v="<b>p + ½ ρ v² + ρ g z = constante</b> le long d'une ligne de courant, pour un fluide <b>parfait</b> (sans viscosité), <b>incompressible</b>, en écoulement <b>permanent</b>."),
dict(t="n", o="§3.1 Les trois termes",
 r="Nommer les trois termes de Bernoulli.",
 v="<b>p</b> : pression statique (manomètre) ; <b>½ρv²</b> : pression dynamique ; <b>ρgz</b> : pression de pesanteur. Tous en Pa."),
dict(t="n", o="§3.3 L'effet Venturi",
 r="Qu'est-ce que l'effet Venturi ? Relation en circuit horizontal ?",
 v="Là où le fluide va <b>plus vite</b>, la pression statique est <b>plus faible</b>.<br><b>p<sub>1</sub> − p<sub>2</sub> = ½ ρ (v<sub>2</sub>² − v<sub>1</sub>²)</b>."),
dict(t="n", o="§3.4 Vidange d'un réservoir",
 r="Vitesse de vidange par un orifice à une profondeur h ?",
 v="<b>v = √(2 g h)</b>, indépendante du liquide. Le débit diminue quand le niveau baisse."),
dict(t="n", o="§4 Bernoulli en circuit réel",
 r="Bernoulli généralisé : où placer le terme de la pompe et celui des pertes ?",
 v="Δp<sub>pompe</sub> <b>du côté où se trouve la pompe</b> ; Δp<sub>pertes</sub> <b>du côté de l'arrivée</b>."),
dict(t="n", o="§4 Haute pression",
 r="Dans un circuit haute pression (185 bar), quels termes de Bernoulli sont négligeables ?",
 v="Les termes <b>dynamique</b> et de <b>pesanteur</b> (&lt; 0,1 %). Ils comptent seulement en basse pression (aspiration, cuves, irrigation)."),
# --- méthodes
dict(t="m", o="§2.1 Circuit de refroidissement",
 r="60 L/min dans une conduite de 40 mm puis 25 mm. Comment trouver les deux vitesses ?",
 v="1. Q<sub>v</sub> = 60/60 000 = <b>1,0 × 10<sup>−3</sup> m³/s</b>.<br>2. S<sub>1</sub> = π × 0,040²/4 = 1,257 × 10<sup>−3</sup> m² → v<sub>1</sub> = <b>0,80 m/s</b>.<br>3. S<sub>2</sub> = 4,91 × 10<sup>−4</sup> m² → v<sub>2</sub> = <b>2,04 m/s</b>."),
dict(t="m", o="§3.2 Méthode — Appliquer Bernoulli",
 r="Comment appliquer Bernoulli entre deux points ?",
 v="1. Deux points <b>sur la même ligne de courant</b>, les plus connus.<br>2. Fixer <b>z = 0</b> (souvent le plus bas).<br>3. Écrire l'égalité, <b>barrer</b> : horizontal (z égaux), grand réservoir (v ≈ 0), air libre (p = 0 relatif).<br>4. Isoler, vérifier l'unité."),
dict(t="m", o="§3.4 Une cuve de gazole",
 r="Orifice de 15 mm à 1,80 m sous la surface. Comment trouver la vitesse et le débit de sortie ?",
 v="1. v = √(2 × 9,81 × 1,80) = <b>5,94 m/s</b>.<br>2. S = π × 0,015²/4 = 1,77 × 10<sup>−4</sup> m².<br>3. Q<sub>v</sub> = S v ≈ <b>63 L/min</b> (au début seulement)."),
]

# =====================================================================
CARTES["ch05"] = [
dict(t="n", o="§1.1 Viscosité dynamique",
 r="Que mesure la viscosité dynamique ? Symbole et unité ?",
 v="La <b>résistance au glissement</b> des couches de fluide les unes sur les autres. Symbole <b>η</b>, en <b>Pa·s</b>."),
dict(t="n", o="§1.1 Viscosité cinématique",
 r="Viscosité cinématique : formule et unités ?",
 v="<b>ν = η / ρ</b> en m²/s, en pratique en mm²/s : <b>1 mm²/s = 10<sup>−6</sup> m²/s</b>."),
dict(t="n", o="§1.1 Désignation d'une huile",
 r="Que signifie « ISO VG 46 » ?",
 v="Viscosité cinématique de <b>46 mm²/s à 40 °C</b>."),
dict(t="n", o="§1.2 Viscosité et température",
 r="Comment varie la viscosité d'une huile avec la température ? Conséquence ?",
 v="Elle <b>s'effondre quand la température monte</b> (÷ 90 entre 0 et 100 °C pour une VG 46). Tout calcul ou relevé doit <b>préciser la température</b>."),
dict(t="n", o="§2.1 Les deux régimes",
 r="Régime laminaire et régime turbulent : description ?",
 v="<b>Laminaire</b> : filets qui glissent sans se mélanger, profil parabolique.<br><b>Turbulent</b> : écoulement chaotique, tourbillons, profil aplati."),
dict(t="n", o="§2.2 Nombre de Reynolds",
 r="Formule du nombre de Reynolds ? Seuils (TSMA) ?",
 v="<b>Re = ρ v D / η = v D / ν</b>, sans unité.<br><b>Re &lt; 2000</b> : laminaire ; <b>Re &gt; 3000</b> : turbulent ; entre les deux : transition."),
dict(t="n", o="§3.1 Pertes de charge",
 r="Qu'est-ce qu'une perte de charge ? Où part l'énergie ?",
 v="La <b>chute de pression</b> du fluide entre deux points d'un circuit. L'énergie est <b>dissipée en chaleur</b>, irrécupérable."),
dict(t="n", o="§3.1 Régulières et singulières",
 r="Formules des pertes régulières et singulières ?",
 v="Régulières (longueurs droites) : <b>Δp = λ (L/D) ½ ρ v²</b>.<br>Singulières (coude, vanne, raccord, filtre) : <b>Δp = K ½ ρ v²</b>."),
dict(t="n", o="§3.1 Sur un engin",
 r="Sur un engin agricole, quelles pertes de charge dominent souvent ?",
 v="Les <b>singulières</b> : conduites courtes mais accessoires nombreux. Un raccord mal choisi peut coûter autant que 10 m de flexible."),
dict(t="n", o="§3.2 La ligne de charge",
 r="Comment évolue la charge le long d'un circuit ?",
 v="Elle <b>ne fait que décroître</b> dans le sens de l'écoulement ; seule une <b>pompe</b> la fait remonter."),
dict(t="n", o="§4.1 Loi de Poiseuille",
 r="Loi de Poiseuille ? Condition d'application ?",
 v="<b>Q<sub>v</sub> = π Δp D<sup>4</sup> / (128 η L)</b>, soit Δp = 128 η L Q<sub>v</sub> / (π D<sup>4</sup>).<br>Seulement en régime <b>laminaire</b>, conduite cylindrique droite : calculer Re d'abord."),
dict(t="n", o="§4.2 La puissance quatrième",
 r="À Δp et L fixés, comment le débit dépend-il du diamètre ?",
 v="Comme <b>D<sup>4</sup></b> : doubler D multiplie le débit par <b>16</b> ; D − 10 % → débit − 34 %."),
dict(t="n", o="§4.3 Laminaire et turbulent",
 r="Comment les pertes croissent-elles avec le débit en laminaire ? en turbulent ?",
 v="Laminaire : <b>Δp ∝ Q<sub>v</sub></b> (droite par l'origine).<br>Turbulent : <b>Δp ∝ Q<sub>v</sub><sup>1,75</sup></b> environ (débit × 2 → pertes × 3,4)."),
# --- méthodes
dict(t="m", o="§1.1 Lire une désignation d'huile",
 r="Huile ISO VG 46, ρ = 870 kg/m³. Comment calculer sa viscosité dynamique à 40 °C ?",
 v="1. ν = 46 mm²/s = <b>4,6 × 10<sup>−5</sup> m²/s</b>.<br>2. η = ν × ρ = 4,6 × 10<sup>−5</sup> × 870 = <b>4,0 × 10<sup>−2</sup> Pa·s</b>."),
dict(t="m", o="§2.2 Le fluide décide",
 r="Comment déterminer le régime d'écoulement dans une conduite ?",
 v="1. Convertir D en m, v en m/s, ν en m²/s.<br>2. <b>Re = v D / ν</b>.<br>3. Vérifier que Re est sans unité.<br>4. &lt; 2000 laminaire ; &gt; 3000 turbulent."),
dict(t="m", o="§4.2 Choisir un flexible",
 r="Pertes de 3,1 bar dans un flexible de 10 mm. Que deviennent-elles en 16 mm (même débit, laminaire) ?",
 v="1. Δp ∝ 1/D<sup>4</sup>.<br>2. Rapport (16/10)<sup>4</sup> = <b>6,6</b>.<br>3. Δp = 3,1/6,6 ≈ <b>0,47 bar</b>.<br>Passer au calibre supérieur rapporte plus qu'une pompe plus puissante."),
]

# =====================================================================
CARTES["ch06"] = [
dict(t="n", o="§1.1 La mole",
 r="Qu'est-ce qu'une mole ? Valeur de N<sub>A</sub> ?",
 v="La quantité de matière contenant <b>N<sub>A</sub> = 6,02 × 10<sup>23</sup></b> entités (atomes, molécules, ions). Symbole <b>mol</b>. On compte en pesant."),
dict(t="n", o="§1.2 Masse molaire",
 r="Définir la masse molaire. Comment la calcule-t-on pour une molécule ?",
 v="La masse d'<b>une mole</b>, en <b>g/mol</b>. On additionne les masses molaires atomiques, chacune <b>multipliée par son indice</b>."),
dict(t="n", o="§1.2 Deux pièges de lecture",
 r="Dans 2 Ca(OH)<sub>2</sub>, sur quoi porte l'indice 2 ? Le coefficient 2 entre-t-il dans M ?",
 v="L'indice porte sur <b>tout le groupe</b> entre parenthèses (2 O, 2 H). Le coefficient devant la formule <b>n'entre jamais</b> dans M."),
dict(t="n", o="§2 Les trois relations",
 r="Comment calculer n pour un solide ? un gaz ? une espèce en solution ?",
 v="Solide/liquide : <b>n = m / M</b>.<br>Gaz : <b>n = V / V<sub>m</sub></b>.<br>Solution : <b>n = C × V</b> (mol/L, L)."),
dict(t="n", o="§2 Le volume molaire",
 r="De quoi dépend le volume molaire V<sub>m</sub> ? Valeur à 20 °C ?",
 v="Seulement de la <b>température et de la pression</b>, pas du gaz. <b>24,0 L/mol</b> à 20 °C (22,4 à 0 °C)."),
dict(t="n", o="§3.1 Nombres stœchiométriques",
 r="Que représentent les nombres stœchiométriques ? Quand une équation est-elle ajustée ?",
 v="Les <b>proportions</b> dans lesquelles les espèces réagissent et se forment. Ajustée : <b>chaque élément</b> en même nombre des deux côtés."),
dict(t="n", o="§3.1 Ce qu'on n'a pas le droit de toucher",
 r="Pour ajuster une équation, que peut-on modifier ?",
 v="Seulement les <b>coefficients</b>. Changer un indice change l'espèce chimique."),
dict(t="n", o="§4.1 L'avancement",
 r="Qu'est-ce que l'avancement x ? Comment varient réactifs et produits ?",
 v="Le degré de progression de la réaction, en mol. Réactif : <b>− ν x</b> ; produit : <b>+ ν x</b>."),
dict(t="n", o="§4.2 Le réactif limitant",
 r="Comment trouver le réactif limitant ?",
 v="Comparer les quotients <b>n<sub>initial</sub> / ν</b> : le <b>plus petit</b> désigne le limitant et donne <b>x<sub>max</sub></b>. Jamais les n bruts."),
dict(t="n", o="§4.3 Mélange stœchiométrique",
 r="Qu'est-ce qu'un mélange stœchiométrique ?",
 v="Les quotients n/ν de tous les réactifs sont <b>égaux</b> : ils disparaissent <b>en même temps</b>, sans reste."),
# --- méthodes
dict(t="m", o="§2 Méthode — Aborder un énoncé de chimie",
 r="Comment aborder un énoncé de chimie ?",
 v="1. Repérer la <b>forme</b> de chaque espèce (masse, volume de gaz, solution).<br>2. Convertir (g, L, mol/L).<br>3. Calculer les <b>quantités de matière initiales</b> de tous les réactifs."),
dict(t="m", o="§4.2 Méthode — Bilan de matière",
 r="Comment établir un bilan de matière ?",
 v="1. Équation <b>ajustée</b>.<br>2. n initiales des réactifs.<br>3. Plus petit n/ν → limitant et <b>x<sub>max</sub></b>.<br>4. Restant = n<sub>i</sub> − ν x<sub>max</sub> ; formé = ν x<sub>max</sub>.<br>5. Revenir à m = n M ou V = n V<sub>m</sub>."),
dict(t="m", o="§4.2 Le décapage d'une pièce",
 r="2,80 g de fer et 80,0 mL de HCl à 1,00 mol/L (Fe + 2 HCl → FeCl<sub>2</sub> + H<sub>2</sub>). Comment trouver le limitant et le volume de H<sub>2</sub> ?",
 v="1. n(Fe) = 2,80/55,8 = 5,02 × 10<sup>−2</sup> mol ; n(HCl) = 8,00 × 10<sup>−2</sup> mol.<br>2. Quotients : 5,02 × 10<sup>−2</sup> et 4,00 × 10<sup>−2</sup> → <b>HCl limitant</b>.<br>3. V(H<sub>2</sub>) = x<sub>max</sub> × V<sub>m</sub> = 4,00 × 10<sup>−2</sup> × 24,0 = <b>0,96 L</b>."),
]

# =====================================================================
CARTES["ch07"] = [
dict(t="n", o="§1 Combustion",
 r="Qu'est-ce qu'une combustion ? Combustible et comburant dans un moteur ?",
 v="Une réaction entre un <b>combustible</b> et un <b>comburant</b> qui libère de l'énergie thermique. Moteur : le <b>carburant</b> et le <b>dioxygène de l'air</b>."),
dict(t="n", o="§1 Le triangle du feu",
 r="Comment éteindre un feu ? Pourquoi jamais d'eau sur un feu d'hydrocarbure ou électrique ?",
 v="Supprimer <b>un côté</b> du triangle (carburant, O<sub>2</sub>, chaleur). L'eau <b>projette le combustible</b> enflammé et <b>conduit le courant</b>."),
dict(t="n", o="§2.1 Combustion complète",
 r="Produits de la combustion complète d'un hydrocarbure ?",
 v="<b>CO<sub>2</sub> et H<sub>2</sub>O</b>, rien d'autre."),
dict(t="n", o="§2.2 Combustion incomplète",
 r="Quand une combustion est-elle incomplète ? Que produit-elle ? Effet sur l'énergie ?",
 v="Quand le <b>dioxygène est en défaut</b>. Elle produit en plus du <b>CO</b> et des <b>suies</b>, et libère <b>moins d'énergie</b>."),
dict(t="n", o="§2.2 Le monoxyde de carbone",
 r="Pourquoi le CO est-il si dangereux ? Règle à l'atelier ?",
 v="<b>Inodore, incolore</b>, il se fixe sur l'hémoglobine. <b>Jamais de moteur qui tourne en local fermé</b> : extraction ou ventilation."),
dict(t="n", o="§3.1 Pouvoir calorifique inférieur",
 r="Définir le PCI. Énergie libérée par une masse m ?",
 v="L'énergie libérée par la combustion complète de <b>1 kg</b> (eau formée en vapeur), en MJ/kg.<br><b>E = m × PCI</b>."),
dict(t="n", o="§3.1 Massique ou volumique",
 r="Comment passer du PCI massique au PCI volumique ?",
 v="<b>PCI<sub>vol</sub> = PCI × ρ</b> (gazole : 35,9 MJ/L)."),
dict(t="n", o="§3.1 Valeurs de PCI",
 r="PCI du gazole, de l'essence, du GNV, du B100, du bioéthanol ?",
 v="Gazole <b>42,7</b> ; essence <b>44,0</b> ; GNV <b>50,0</b> ; B100 <b>37,2</b> ; bioéthanol <b>26,8</b> MJ/kg."),
dict(t="n", o="§3.2 Ce montage ne donne pas le PCI",
 r="Que mesure-t-on en faisant chauffer de l'eau par une combustion ? Comment comparer deux combustibles ?",
 v="<b>Q = m c Δθ</b> = η × PCI (une partie de l'énergie se perd). Pour comparer : faire le <b>rapport</b> de deux essais identiques (η s'élimine)."),
dict(t="n", o="§4.1 Les rejets de CO2",
 r="Combien de CO<sub>2</sub> rejette un litre de gazole ? Pourquoi plus que sa masse ?",
 v="<b>≈ 2,6 kg</b>, plus de trois fois sa masse : l'<b>oxygène vient de l'air</b>."),
dict(t="n", o="§4.1 Comparer les carburants",
 r="Comment comparer les rejets de CO<sub>2</sub> de deux carburants ?",
 v="<b>À énergie égale</b> (g de CO<sub>2</sub> par MJ), pas par litre."),
dict(t="n", o="§4.2 Les critères de choix",
 r="Quels sont les trois critères de choix d'un carburant alternatif ?",
 v="Le <b>pouvoir calorifique</b>, l'<b>indice de cétane ou d'octane</b>, les <b>rejets de CO<sub>2</sub></b> à énergie égale sur le cycle complet."),
dict(t="n", o="§4.3 Octane et cétane",
 r="Que mesurent l'indice d'octane et l'indice de cétane ?",
 v="<b>Octane</b> : résistance à l'auto-inflammation (essence).<br><b>Cétane</b> : aptitude à s'enflammer (diesel). En sens contraire."),
dict(t="n", o="§5 Polluants",
 r="Quels sont les quatre polluants d'un moteur thermique ?",
 v="<b>CO</b> (combustion incomplète), <b>particules</b>, <b>NO<sub>x</sub></b> (haute température), <b>hydrocarbures imbrûlés</b>. Le CO<sub>2</sub> est un gaz à effet de serre."),
dict(t="n", o="§5 Dépollution d'un diesel",
 r="Rôle du FAP, de la SCR et de l'EGR ?",
 v="<b>FAP</b> : retient puis brûle les suies.<br><b>SCR</b> (AdBlue) : NO<sub>x</sub> → N<sub>2</sub> + H<sub>2</sub>O.<br><b>EGR</b> : abaisse la température de combustion → moins de NO<sub>x</sub>."),
# --- méthodes
dict(t="m", o="§2.1 Méthode — Ajuster une combustion",
 r="Comment ajuster l'équation de combustion complète d'un carburant ?",
 v="1. <b>C</b> : coefficient de CO<sub>2</sub> = nombre de C.<br>2. <b>H</b> : coefficient de H<sub>2</sub>O = H/2.<br>3. <b>O en dernier</b> : O à droite ÷ 2 (retirer l'O du carburant si alcool).<br>4. Demi-entier → <b>doubler</b> tout."),
dict(t="m", o="§3.2 Un ordre de grandeur",
 r="1,42 g d'éthanol chauffent 200,0 g d'eau de 26,5 K. Comment estimer l'énergie par gramme et le rendement du montage ?",
 v="1. Q = 0,2000 × 4185 × 26,5 = <b>2,22 × 10<sup>4</sup> J</b>.<br>2. Par gramme : 2,22 × 10<sup>4</sup>/1,42 = 1,56 × 10<sup>4</sup> J/g.<br>3. η = 1,56/2,68 ≈ <b>58 %</b>."),
dict(t="m", o="§4.1 Méthode — Rejets de CO2",
 r="Comment calculer la masse de CO<sub>2</sub> rejetée par un carburant ?",
 v="1. Équation ajustée de la combustion complète.<br>2. n(carburant) = m / M.<br>3. × rapport stœchiométrique → n(CO<sub>2</sub>).<br>4. m(CO<sub>2</sub>) = n × 44,0 g/mol."),
]

# =====================================================================
CARTES["ch08"] = [
dict(t="n", o="§1.1 Système",
 r="Qu'est-ce qu'un système en thermodynamique ? Convention de signe des échanges ?",
 v="La portion de matière étudiée, séparée du <b>milieu extérieur</b> par une <b>frontière</b>.<br>Ce que le système <b>reçoit</b> : <b>positif</b> ; ce qu'il <b>cède</b> : <b>négatif</b>."),
dict(t="n", o="§1.2 Intensif, extensif",
 r="Grandeur intensive et grandeur extensive : définir et donner des exemples.",
 v="<b>Intensive</b> : inchangée si l'on coupe le système en deux (T, p, ρ).<br><b>Extensive</b> : proportionnelle à la taille (V, m, n, U, H)."),
dict(t="n", o="§1.3 Les transformations",
 r="Isochore, isobare, isotherme, adiabatique : que signifient-elles ?",
 v="<b>Isochore</b> : V constant. <b>Isobare</b> : p constante. <b>Isotherme</b> : T constante. <b>Adiabatique</b> : Q = 0."),
dict(t="n", o="§2.1 Interprétation microscopique",
 r="Que traduisent la température et la pression d'un gaz à l'échelle des particules ?",
 v="<b>Température</b> : l'<b>agitation</b> des particules.<br><b>Pression</b> : les <b>chocs</b> des particules sur les parois."),
dict(t="n", o="§2.2 Loi des gaz parfaits",
 r="Loi des gaz parfaits et unités ?",
 v="<b>p V = n R T</b> : p en Pa (<b>absolue</b>), V en m³, n en mol, T en <b>K</b>, R = 8,314 J·mol<sup>−1</sup>·K<sup>−1</sup>."),
dict(t="n", o="§2.2 La pression est toujours absolue",
 r="Pneu gonflé « à 2 bar » au manomètre : quelle pression dans pV = nRT ?",
 v="La pression <b>absolue</b> : 2 + 1 = <b>3 bar</b> (3 × 10<sup>5</sup> Pa)."),
dict(t="n", o="§3.1 Premier principe",
 r="Énoncer le premier principe. Qu'est-ce qu'une fonction d'état ?",
 v="<b>ΔU = W + Q</b> (tout ce que le système reçoit).<br>U est une <b>fonction d'état</b> : ne dépend que de l'état, pas du chemin. W et Q en dépendent."),
dict(t="n", o="§3.2 Première loi de Joule",
 r="Énergie interne d'un gaz parfait : de quoi dépend-elle ?",
 v="Seulement de la <b>température</b> : <b>ΔU = n C<sub>v,m</sub> ΔT</b>, quelle que soit la transformation."),
dict(t="n", o="§3.3 Les quatre transformations",
 r="Que vaut W ou Q pour une isochore ? une isobare ? une isotherme ? une adiabatique ?",
 v="Isochore : <b>W = 0</b>, Q = ΔU.<br>Isobare : <b>W = −p ΔV</b>.<br>Isotherme : <b>ΔU = 0</b>, Q = −W.<br>Adiabatique : <b>Q = 0</b>, ΔU = W."),
dict(t="n", o="§3.3 Compression adiabatique",
 r="Température et pression après une compression adiabatique de taux τ ?",
 v="<b>T<sub>2</sub> = T<sub>1</sub> τ<sup>γ−1</sup></b> ; <b>p<sub>2</sub> = p<sub>1</sub> τ<sup>γ</sup></b> (T en K)."),
dict(t="n", o="§4.1 L'enthalpie",
 r="Définir l'enthalpie. Son intérêt ?",
 v="<b>H = U + p V</b>. À <b>pression constante</b> : <b>ΔH = Q</b>."),
dict(t="n", o="§4.2 Changements d'état",
 r="Quelle formule hors changement d'état ? pendant un changement d'état ?",
 v="Hors changement : <b>Q = m c Δθ</b> (θ varie).<br>Pendant : <b>Q = m L</b> (θ constante, L enthalpie massique de changement d'état)."),
# --- méthodes
dict(t="m", o="§2.2 Méthode — Gaz parfaits",
 r="Comment exploiter la loi des gaz parfaits entre deux états ?",
 v="1. Convertir : bar → Pa (× 10<sup>5</sup>, absolue), L → m³ (÷ 1000), °C → K (+ 273,15).<br>2. Repérer ce qui ne varie pas.<br>3. p<sub>1</sub>V<sub>1</sub>/T<sub>1</sub> = p<sub>2</sub>V<sub>2</sub>/T<sub>2</sub>, simplifier.<br>4. Pour n ou m : pV = nRT puis m = n M."),
dict(t="m", o="§3.3 La compression d'un diesel",
 r="Air à 20 °C, taux de compression 18, γ = 1,40. Comment trouver la température en fin de compression ?",
 v="1. Compression rapide → <b>adiabatique</b>.<br>2. T<sub>1</sub> = 293 K.<br>3. T<sub>2</sub> = 293 × 18<sup>0,40</sup> = <b>931 K</b> (658 °C).<br>4. &gt; 250 °C : le gazole s'enflamme sans bougie."),
dict(t="m", o="§4.3 Méthode — Calorimètre",
 r="Comment déterminer une température d'équilibre dans un calorimètre ?",
 v="1. Qui <b>cède</b>, qui <b>reçoit</b>.<br>2. <b>Vérifier la faisabilité</b> (assez d'énergie pour tout fondre ?).<br>3. Q<sub>cédé</sub> = Q<sub>reçu</sub> avec m c Δθ et m L.<br>4. Résoudre, vérifier θ<sub>f</sub> encadrée."),
]

# =====================================================================
CARTES["ch09"] = [
dict(t="n", o="§1.1 Le flux thermique",
 r="Définir le flux thermique. Unité ? Lien avec l'énergie Q ?",
 v="L'énergie transférée <b>par unité de temps</b> : <b>φ = Q / Δt</b>. C'est une <b>puissance</b>, en <b>W</b>. Q = φ Δt."),
dict(t="n", o="§1.2 Densité de flux",
 r="Qu'est-ce que la densité de flux ? Unité ?",
 v="Le flux rapporté à la surface : <b>φ / S</b>, en <b>W/m²</b>."),
dict(t="n", o="§1.3 Le sens du transfert",
 r="Dans quel sens se fait spontanément un transfert thermique ? Quand cesse-t-il ?",
 v="Toujours du <b>plus chaud vers le plus froid</b> ; il cesse quand les <b>températures sont égales</b>."),
dict(t="n", o="§1.4 Régime permanent",
 r="Comment savoir que le régime permanent est établi ?",
 v="Par un critère <b>chiffré</b> : les températures relevées (toutes les 2 min) ne varient plus de plus que la <b>résolution des sondes</b>."),
dict(t="n", o="§2 Les trois modes",
 r="Conduction, convection, rayonnement : définir et donner un exemple sur un engin.",
 v="<b>Conduction</b> : de proche en proche dans la matière immobile (le carter).<br><b>Convection</b> : par un fluide en mouvement (liquide de refroidissement).<br><b>Rayonnement</b> : par ondes, sans support (l'échappement chauffe le capot)."),
dict(t="n", o="§3.1 Loi de Fourier",
 r="Flux de conduction à travers une paroi ? Unités ?",
 v="<b>φ = λ S (T<sub>1</sub> − T<sub>2</sub>) / e</b> : λ en W·m<sup>−1</sup>·K<sup>−1</sup>, S en m², e en m, écart en K."),
dict(t="n", o="§3.2 Isolant ou conducteur",
 r="Qu'est-ce qu'un bon isolant ? Pourquoi laine de verre, polystyrène et liège se ressemblent-ils ?",
 v="Un λ <b>petit</b> (≈ 0,04 W·m<sup>−1</sup>·K<sup>−1</sup>, 10 000 fois moins que le cuivre). Tous emprisonnent de l'<b>air immobile</b> : tassé ou mouillé, l'isolant perd son pouvoir."),
dict(t="n", o="§4.1 Résistance thermique",
 r="Résistance thermique d'une paroi plane ? Expression du flux ?",
 v="<b>R<sub>th</sub> = e / (λ S)</b> en K/W ; <b>φ = ΔT / R<sub>th</sub></b>."),
dict(t="n", o="§4.2 Parois multicouches",
 r="Comment se combinent les résistances de couches successives ? Laquelle commande ?",
 v="Elles <b>s'ajoutent</b> (en série). La <b>plus grande</b> (l'isolant) impose le résultat."),
dict(t="n", o="§5.1 Convection",
 r="Flux de convection ? Convection naturelle et forcée ?",
 v="<b>φ = h S ΔT</b>, h coefficient de convection (W·m<sup>−2</sup>·K<sup>−1</sup>), qui dépend surtout de la vitesse du fluide.<br><b>Naturelle</b> : mouvement né de l'échauffement ; <b>forcée</b> : ventilateur, pompe."),
dict(t="n", o="§5.2 Résistance de surface",
 r="Résistance thermique d'un film de fluide ? Pourquoi l'oublier donne des résultats absurdes ?",
 v="<b>R<sub>th</sub> = 1 / (h S)</b>, en série avec les couches. Sur un vitrage, les films d'air portent <b>97 %</b> de la résistance."),
dict(t="n", o="§6.1 Fluide en écoulement",
 r="Puissance emportée par un fluide qui traverse un appareil ?",
 v="<b>φ = q<sub>m</sub> c ΔT</b> (q<sub>m</sub> en kg/s)."),
dict(t="n", o="§6.2 Bilan d'un échangeur",
 r="Dans un échangeur, comparer le flux cédé par le chaud et le flux reçu par le froid.",
 v="Flux cédé <b>≥</b> flux reçu ; la différence = <b>pertes vers l'extérieur</b>."),
# --- méthodes
dict(t="m", o="§4.1 Méthode — Flux à travers une paroi",
 r="Comment calculer le flux traversant une paroi multicouche ?",
 v="1. Convertir épaisseurs (m) et surfaces (m²).<br>2. <b>R<sub>th</sub> = e/(λS)</b> pour chaque couche (contrôler l'ordre de grandeur).<br>3. Ajouter les films : 1/(hS).<br>4. <b>R<sub>tot</sub></b> = somme.<br>5. <b>φ = ΔT / R<sub>tot</sub></b>."),
dict(t="m", o="§6.2 Méthode — Bilan d'un échangeur",
 r="Comment faire le bilan d'un échangeur liquide-liquide ?",
 v="1. Pour chaque circuit : φ = q<sub>m</sub> c ΔT.<br>2. Comparer : l'écart = pertes.<br>3. Retenir une valeur, calculer ΔT<sub>moy</sub> entre fluides.<br>4. <b>K = φ / (S ΔT<sub>moy</sub>)</b> en W·m<sup>−2</sup>·K<sup>−1</sup>."),
dict(t="m", o="§6.2 Bilan d'une enceinte",
 r="Comment mesurer la résistance thermique globale d'une cabine sans la démonter ?",
 v="1. Régime permanent : puissance de chauffage = flux perdu.<br>2. Mesurer P<sub>chauffage</sub> et ΔT intérieur/extérieur.<br>3. <b>R<sub>th</sub> = ΔT / P</b>."),
]

# =====================================================================
CARTES["ch10"] = [
dict(t="n", o="§1.1 Le second principe",
 r="Énoncer le second principe (forme évolution). Différence avec le premier principe ?",
 v="Un transfert thermique ne se fait <b>jamais spontanément du froid vers le chaud</b>.<br>Le premier <b>compte</b> l'énergie ; le second dit <b>dans quel sens</b> les choses se produisent."),
dict(t="n", o="§1.2 Réversible, irréversible",
 r="Qu'est-ce qu'une transformation réversible ? Les trois causes d'irréversibilité ?",
 v="Parcourable en sens inverse par les mêmes états, <b>sans trace</b> dans l'extérieur (idéal).<br>Causes : <b>frottements</b>, transferts sous <b>écart fini de température</b>, <b>détentes brusques</b>."),
dict(t="n", o="§2.1 Entropie échangée",
 r="Variation d'entropie lors d'un échange Q avec un thermostat à T ? Unité ? Signe ?",
 v="<b>ΔS = Q / T</b> (T en K), en <b>J/K</b>, du <b>signe de Q</b>."),
dict(t="n", o="§2.1 Second principe et entropie",
 r="Second principe écrit avec l'entropie ?",
 v="<b>ΔS<sub>total</sub> ≥ 0</b> ; égalité seulement si tout est réversible, <b>&gt; 0</b> pour toute transformation réelle."),
dict(t="n", o="§3.1 Machine ditherme",
 r="Qu'est-ce qu'une machine ditherme ? Premier principe sur un cycle ?",
 v="Une machine qui, par <b>cycles</b>, échange de la chaleur avec <b>deux sources</b> et du travail avec l'extérieur.<br><b>W + Q<sub>c</sub> + Q<sub>f</sub> = 0</b> (ΔU = 0 sur un cycle)."),
dict(t="n", o="§3.2 Rendement et efficacités",
 r="Rendement d'un moteur ? Efficacités d'une machine frigorifique et d'une PAC ?",
 v="Moteur : <b>η = |W| / Q<sub>c</sub> &lt; 1</b>.<br>Frigo : <b>e<sub>f</sub> = Q<sub>f</sub> / |W|</b>.<br>PAC : <b>e<sub>c</sub> = Q<sub>c</sub> / |W|</b> ; <b>e<sub>c</sub> = e<sub>f</sub> + 1</b>."),
dict(t="n", o="§3.2 Une efficacité &gt; 1",
 r="Un climatiseur d'efficacité 2,6 viole-t-il la conservation de l'énergie ?",
 v="<b>Non</b> : il <b>déplace</b> de la chaleur du froid vers le chaud, il n'en crée pas. Le froid ne se fabrique pas, il se déplace."),
dict(t="n", o="§4.1 Limite de Carnot",
 r="Rendement de Carnot d'un moteur ? Efficacités de Carnot (frigo, PAC) ?",
 v="<b>η<sub>C</sub> = 1 − T<sub>f</sub>/T<sub>c</sub></b> ; <b>e<sub>f,C</sub> = T<sub>f</sub>/(T<sub>c</sub> − T<sub>f</sub>)</b> ; <b>e<sub>c,C</sub> = T<sub>c</sub>/(T<sub>c</sub> − T<sub>f</sub>)</b>.<br>T en <b>kelvins</b> ; ce sont des <b>plafonds</b>."),
dict(t="n", o="§4.2 Diagramme entropique",
 r="Dans un diagramme (T, S), comment lit-on la chaleur échangée et le travail d'un cycle ?",
 v="<b>Q = T ΔS</b> : aire du rectangle. Le <b>travail</b> du cycle : <b>aire enfermée</b>."),
dict(t="n", o="§4.3 Inégalité de Clausius-Carnot",
 r="Énoncer l'inégalité de Clausius-Carnot.",
 v="<b>Q<sub>c</sub>/T<sub>c</sub> + Q<sub>f</sub>/T<sub>f</sub> ≤ 0</b> ; égalité dans le cas réversible (le plus performant)."),
dict(t="n", o="§5.2 Climatisation d'une cabine",
 r="Pourquoi une climatisation consomme-t-elle plus quand il fait très chaud dehors ?",
 v="e<sub>f,C</sub> = T<sub>f</sub>/(T<sub>c</sub> − T<sub>f</sub>) <b>diminue</b> quand l'écart de température augmente : c'est le second principe."),
# --- méthodes
dict(t="m", o="§2.2 Méthode — Variation d'entropie",
 r="Comment calculer une variation d'entropie et faire un bilan ?",
 v="1. Thermostat : <b>ΔS = Q/T</b> (T en K, Q signé).<br>2. Changement d'état : <b>ΔS = m L / T</b>.<br>3. <b>Additionner</b> pour tous les corps.<br>4. Le total doit être <b>≥ 0</b> (sinon erreur de signe)."),
dict(t="m", o="§3.1 Méthode — Reconnaître une machine",
 r="Comment reconnaître le type d'une machine thermique ?",
 v="1. Elle <b>fournit</b> du travail → <b>moteur</b> ; elle en <b>consomme</b> → récepteur.<br>2. Récepteur : on veut le <b>froid</b> (frigo) ou la <b>chaleur</b> (PAC).<br>3. Flèches signées (reçu = +).<br>4. Vérifier W + Q<sub>c</sub> + Q<sub>f</sub> = 0."),
dict(t="m", o="§4.1 Méthode — Situer une machine réelle",
 r="Comment situer une machine réelle par rapport à la limite de Carnot ?",
 v="1. Températures des sources en <b>K</b>.<br>2. Performance de <b>Carnot</b> du bon type.<br>3. Performance <b>réelle</b> mesurée.<br>4. <b>Rapport réel/Carnot &lt; 1</b> (sinon erreur)."),
]

# =====================================================================
CARTES["ch11"] = [
dict(t="n", o="§1.1 Oxydant et réducteur",
 r="Définir un oxydant et un réducteur. Qui se réduit, qui s'oxyde ?",
 v="<b>Oxydant</b> : capte des électrons, il <b>se réduit</b>.<br><b>Réducteur</b> : cède des électrons, il <b>s'oxyde</b>."),
dict(t="n", o="§1.1 Les électrons ne se promènent jamais seuls",
 r="Une oxydation peut-elle se produire seule ? Que contient une équation bilan ?",
 v="<b>Non</b> : toujours une réduction en face. L'équation bilan ne contient <b>plus aucun électron</b>."),
dict(t="n", o="§1.2 Couple",
 r="Comment note-t-on un couple oxydant/réducteur ? Exemple de demi-équation.",
 v="<b>ox/réd</b>, l'oxydant en premier.<br>Cu<sup>2+</sup> + 2 e<sup>−</sup> ⇌ Cu."),
dict(t="n", o="§3.1 Potentiel standard",
 r="Que mesure le potentiel standard E° ?",
 v="Il classe les couples : E° <b>grand</b> → oxydant <b>fort</b> ; E° <b>petit</b> → réducteur <b>fort</b> (métal qui se corrode)."),
dict(t="n", o="§3.2 Règle du gamma",
 r="Énoncer la règle du gamma.",
 v="La réaction spontanée met en présence l'<b>oxydant du couple le plus haut</b> et le <b>réducteur du couple le plus bas</b>. Dans l'autre sens : rien."),
dict(t="n", o="§4.1 Anode et cathode",
 r="Dans une pile : anode et cathode, quelle réaction, quel pôle ?",
 v="<b>Anode</b> : <b>oxydation</b>, pôle <b>−</b> (les électrons en partent).<br><b>Cathode</b> : <b>réduction</b>, pôle <b>+</b>."),
dict(t="n", o="§4.1 Force électromotrice",
 r="F.é.m. standard d'une pile ? Signe ?",
 v="<b>E°<sub>pile</sub> = E°<sub>cathode</sub> − E°<sub>anode</sub></b>, toujours <b>positive</b> (sinon électrodes inversées)."),
dict(t="n", o="§4.1 Le pont salin",
 r="Rôle du pont salin ?",
 v="Il <b>ferme le circuit</b> par les ions et maintient la <b>neutralité électrique</b>. Sans lui, le courant s'arrête."),
dict(t="n", o="§4.2 Loi de Nernst",
 r="Énoncer la loi de Nernst.",
 v="<b>E = E° + (0,059 / n) log([ox]/[réd])</b>, n électrons échangés. [ox] ÷ 10 → E baisse de 0,059/n V."),
dict(t="n", o="§5 Pile, accumulateur, pile à combustible",
 r="Différence entre pile, accumulateur et pile à combustible ?",
 v="<b>Pile</b> : réactifs enfermés, non réversible.<br><b>Accumulateur</b> : réversible, se recharge (batterie au plomb).<br><b>Pile à combustible</b> : réactifs apportés en continu (H<sub>2</sub>, seul rejet : l'eau)."),
dict(t="n", o="§6.1 Anode sacrificielle",
 r="Deux métaux en contact en milieu humide : lequel se corrode ? Principe de l'anode sacrificielle ?",
 v="Le <b>plus réducteur</b> (E° le plus petit). On accole à l'acier un métal <b>encore plus réducteur</b> (zinc) qui est <b>consommé à sa place</b>."),
dict(t="n", o="§6.2 Méthodes de protection",
 r="Citer des méthodes de protection contre la corrosion.",
 v="<b>Peinture</b>, <b>galvanisation</b>, <b>chromage</b>, <b>anodisation</b>, <b>anode sacrificielle</b>, <b>courant imposé</b>."),
# --- méthodes
dict(t="m", o="§2 Méthode — Équation bilan",
 r="Comment passer de deux couples à l'équation bilan d'oxydoréduction ?",
 v="1. Deux demi-équations équilibrées en charges.<br>2. Repérer le sens : réduction / oxydation.<br>3. <b>Multiplier</b> pour égaliser les électrons.<br>4. Additionner, vérifier : <b>aucun électron</b>, charges équilibrées."),
dict(t="m", o="§2 L'erreur qui coûte le plus",
 r="Ag<sup>+</sup>/Ag (1 e<sup>−</sup>) et Cu<sup>2+</sup>/Cu (2 e<sup>−</sup>) : comment écrire le bilan ?",
 v="1. Ag<sup>+</sup> + e<sup>−</sup> → Ag (× 2) ; Cu → Cu<sup>2+</sup> + 2 e<sup>−</sup>.<br>2. <b>2 Ag<sup>+</sup> + Cu → 2 Ag + Cu<sup>2+</sup></b>.<br>3. Vérifier les charges : +2 = +2."),
dict(t="m", o="§4.2 Méthode — Vérifier la loi de Nernst",
 r="Comment vérifier expérimentalement la loi de Nernst ?",
 v="1. Ne faire varier <b>qu'une</b> concentration.<br>2. Tracer <b>E = f(log c)</b> : une droite.<br>3. <b>Pente</b> comparée à 0,059/n (teste le modèle).<br>4. <b>Ordonnée à l'origine</b> comparée à E° (teste le montage)."),
dict(t="m", o="§3.2 Un raccord mal choisi",
 r="Raccord en cuivre sur un tuyau en acier en milieu humide : comment prévoir quel métal est attaqué ?",
 v="1. Placer les couples : Cu<sup>2+</sup>/Cu au-dessus de Fe<sup>2+</sup>/Fe.<br>2. Gamma : oxydant du haut (Cu<sup>2+</sup>) + réducteur du bas (<b>Fe</b>).<br>3. C'est l'<b>acier qui est attaqué</b>."),
]

# =====================================================================
CARTES["ch12"] = [
dict(t="n", o="§1 Période et fréquence",
 r="Définir période et fréquence d'un signal. Comment repérer correctement une période ?",
 v="<b>T</b> : durée du motif ; <b>f = 1/T</b> en Hz.<br>Entre deux points de <b>même valeur et même sens de variation</b>."),
dict(t="n", o="§2 La valeur moyenne",
 r="Définir la valeur moyenne. Quelle position du multimètre l'affiche ?",
 v="Le niveau constant qui donnerait <b>la même aire</b> sur une période. Position <b>continu (DC)</b>."),
dict(t="n", o="§2 Signal rectangulaire",
 r="Valeur moyenne d'un signal rectangulaire (U pendant αT, 0 sinon) ? Ce qu'elle fixe pour un moteur ?",
 v="<b>u<sub>moy</sub> = α U</b> (α rapport cyclique). Elle fixe la <b>vitesse</b> d'un moteur à courant continu (24 V, α = 0,60 → 14,4 V)."),
dict(t="n", o="§3.1 La valeur efficace",
 r="Définir la valeur efficace. Puissance dans une résistance ?",
 v="La tension <b>continue</b> qui produirait <b>le même échauffement</b> dans la même résistance.<br><b>P = U<sub>eff</sub>² / R</b>."),
dict(t="n", o="§3.1 Formes usuelles",
 r="Valeur efficace d'une sinusoïde, d'un créneau symétrique, d'un triangle symétrique ?",
 v="Sinusoïde : <b>U<sub>max</sub>/√2</b>.<br>Créneau : <b>U<sub>max</sub></b>.<br>Triangle : <b>U<sub>max</sub>/√3</b>."),
dict(t="n", o="§3.2 Les carrés s'ajoutent",
 r="Relation entre valeur efficace totale, valeur moyenne et composante alternative ?",
 v="<b>U<sub>eff</sub>² = U<sub>moy</sub>² + U<sub>alt,eff</sub>²</b> : les <b>carrés</b> s'ajoutent, jamais les valeurs."),
dict(t="n", o="§4 Ce que mesure un multimètre",
 r="Que mesure un multimètre ordinaire en position AC ? Sur quel signal est-il juste ?",
 v="1,11 × la valeur moyenne du signal redressé : juste <b>seulement sur une sinusoïde</b> (créneau : + 11 % ; triangle : − 3,8 %). Il faut un <b>TRMS</b> ou un oscilloscope."),
dict(t="n", o="§5 Régime transitoire",
 r="Définir le temps de montée et le temps d'établissement à 5 %.",
 v="<b>t<sub>m</sub></b> : de <b>10 à 90 %</b> de la valeur finale (rapidité).<br><b>t<sub>5%</sub></b> : à partir duquel le signal reste dans <b>± 5 %</b> de la valeur finale (stabilisation)."),
dict(t="n", o="§6.1 Fondamental et harmoniques",
 r="Qu'est-ce que le fondamental ? les harmoniques ? Que porte le spectre d'amplitude ?",
 v="<b>Fondamental</b> : sinusoïde de même fréquence que le signal. <b>Harmoniques</b> : fréquences multiples. Spectre : <b>fréquence</b> en abscisse, <b>amplitude</b> en ordonnée."),
dict(t="n", o="§6.1 Reconnaître une forme",
 r="Que dit un spectre à une seule raie ? Quels rangs pour un signal symétrique ? Décroissance d'un créneau, d'un triangle ?",
 v="Une raie : <b>sinusoïde pure</b>.<br>Symétrique : <b>rangs impairs</b> seulement.<br>Créneau : en <b>1/n</b> ; triangle : en <b>1/n²</b>."),
dict(t="n", o="§6.2 Du spectre à la valeur efficace",
 r="Valeur efficace d'un signal à partir de son spectre ?",
 v="<b>U<sub>eff</sub> = √(U<sub>0</sub>² + U<sub>1</sub>² + U<sub>3</sub>² + …)</b> (valeurs efficaces des raies). Une somme tronquée <b>sous-estime</b>."),
# --- méthodes
dict(t="m", o="§3.2 Une ondulation résiduelle",
 r="Alimentation : 3,0 V continus et ondulation sinusoïdale d'amplitude 0,80 V. Comment trouver la valeur efficace totale ?",
 v="1. U<sub>alt,eff</sub> = 0,80/√2 = 0,57 V.<br>2. U<sub>eff</sub>² = 3,0² + 0,57² = 9,32.<br>3. U<sub>eff</sub> = <b>3,05 V</b> (+ 1,8 % seulement)."),
dict(t="m", o="§6.1 Méthode — Identifier une forme d'onde",
 r="Comment identifier une forme d'onde à partir de son spectre ?",
 v="1. Raie la plus basse = <b>fondamental</b> (fréquence du signal).<br>2. Autres raies à des <b>multiples</b>.<br>3. Rangs <b>présents</b> (impairs → symétrique).<br>4. <b>Décroissance</b> : 1/n créneau, 1/n² triangle."),
dict(t="m", o="§5 Régime transitoire",
 r="Comment lire t<sub>m</sub> et t<sub>5%</sub> sur un enregistrement ?",
 v="1. Repérer la <b>valeur finale</b>.<br>2. t<sub>m</sub> : instants à 10 % et 90 % de la valeur finale, faire la différence.<br>3. t<sub>5%</sub> : dernier instant où le signal entre dans ± 5 % sans en ressortir."),
]

# =====================================================================
CARTES["ch13"] = [
dict(t="n", o="§1 Oscillateur",
 r="Qu'est-ce qu'un oscillateur ? Par quoi est-il caractérisé ?",
 v="Un système qui, écarté de l'équilibre, y revient <b>en le dépassant</b>. Caractérisé par sa <b>période propre T<sub>0</sub></b> et sa <b>fréquence propre f<sub>0</sub> = 1/T<sub>0</sub></b>."),
dict(t="n", o="§1 Masse-ressort",
 r="Fréquence propre d'un système masse-ressort ? Comment doubler f<sub>0</sub> ?",
 v="<b>f<sub>0</sub> = (1/2π) √(k/m)</b> : en √k et en 1/√m. Doubler f<sub>0</sub> → <b>quadrupler la raideur</b>."),
dict(t="n", o="§2 Les trois régimes",
 r="Quels sont les trois régimes d'oscillation selon l'amortissement ?",
 v="<b>Périodique</b> : sans amortissement (idéal).<br><b>Pseudopériodique</b> : oscille en perdant de l'amplitude.<br><b>Apériodique</b> : retour sans oscillation."),
dict(t="n", o="§2 Plus d'amortissement",
 r="Augmenter toujours l'amortissement accélère-t-il le retour à l'équilibre ?",
 v="<b>Non</b> : au-delà du seuil apériodique, il le <b>ralentit</b>. Un amortisseur est réglé près de ce seuil."),
dict(t="n", o="§3 L'amortissement",
 r="En régime pseudopériodique, comment évoluent les amplitudes ? la période ?",
 v="Les amplitudes décroissent dans un <b>rapport constant</b> ; la période reste <b>pratiquement inchangée</b>."),
dict(t="n", o="§4 Libres et forcées",
 r="À quelle fréquence vibre un système en oscillations libres ? forcées ?",
 v="<b>Libres</b> : à sa <b>fréquence propre</b>.<br><b>Forcées</b> : à la fréquence de l'<b>excitateur</b> ; seule l'amplitude dépend du système."),
dict(t="n", o="§5 La résonance",
 r="Qu'est-ce que la résonance ? Effet de l'amortissement ?",
 v="L'amplitude passe par un <b>maximum</b> quand la fréquence d'excitation approche <b>f<sub>0</sub></b>. Amortissement faible → pic <b>haut et étroit</b>."),
dict(t="n", o="§5 Recherchée ou redoutée",
 r="Où recherche-t-on la résonance ? Où la redoute-t-on ?",
 v="Recherchée : crible vibrant, compacteur, table vibrante. Redoutée : cabine, tôlerie, tuyauterie, échappement."),
dict(t="n", o="§6.1 Le balourd",
 r="À quelle fréquence excite un balourd ? Que signale un pic au double ?",
 v="À la <b>fréquence de rotation</b> : <b>f = N/60</b>. Un pic à <b>2f</b> oriente vers un <b>désalignement</b>."),
dict(t="n", o="§6.2 Règle de l'isolation",
 r="Quand des plots élastiques isolent-ils efficacement des vibrations ?",
 v="Seulement si <b>f &gt; √2 × f<sub>0</sub></b> (f<sub>0</sub> du système sur plots). En dessous, ils <b>amplifient</b>."),
dict(t="n", o="§6.2 Traiter une vibration",
 r="Dans quel ordre traiter une vibration ?",
 v="1. <b>Supprimer l'excitation</b> (équilibrer, aligner).<br>2. <b>Déplacer f<sub>0</sub></b> (raideur du support).<br>3. <b>Amortir</b> (dernier recours)."),
# --- méthodes
dict(t="m", o="§3 Méthode — Oscillations libres",
 r="Comment exploiter un enregistrement d'oscillations libres ?",
 v="1. Durée de <b>plusieurs</b> oscillations ÷ leur nombre → T<sub>0</sub>.<br>2. f<sub>0</sub> = 1/T<sub>0</sub>.<br>3. Amplitudes successives du même côté.<br>4. Rapports X<sub>2</sub>/X<sub>1</sub>, X<sub>3</sub>/X<sub>2</sub>… <b>égaux</b> → amortissement visqueux."),
dict(t="m", o="§5 Méthode — Courbe de résonance",
 r="Comment relever une courbe de résonance ?",
 v="1. Excitateur à <b>amplitude constante</b>.<br>2. Balayer par <b>pas réguliers</b>, attendre le régime établi.<br>3. Repérer le maximum, <b>balayage plus fin</b> autour.<br>4. Comparer à f<sub>0</sub> mesurée en libre."),
dict(t="m", o="§1 Ordre de grandeur",
 r="m = 0,200 kg, k = 120 N/m. Comment calculer f<sub>0</sub> et T<sub>0</sub> ?",
 v="1. f<sub>0</sub> = (1/2π) √(120/0,200) = <b>3,90 Hz</b>.<br>2. T<sub>0</sub> = 1/f<sub>0</sub> = <b>0,256 s</b>."),
]

# =====================================================================
CARTES["ch14"] = [
dict(t="n", o="§1 Onde acoustique",
 r="Qu'est-ce qu'une onde acoustique ? Quelle grandeur mesure-t-on ?",
 v="La propagation d'une suite de <b>compressions et dilatations</b> dans un milieu matériel. On mesure la <b>surpression</b> (écart à la pression atmosphérique)."),
dict(t="n", o="§1 Ce qui voyage",
 r="Un son transporte-t-il de la matière ?",
 v="<b>Non</b> : chaque tranche d'air va et vient sur place ; c'est la <b>perturbation</b> qui se déplace."),
dict(t="n", o="§1 Longueur d'onde",
 r="Relation entre λ, c et f ? Que devient chacune quand le son change de milieu ?",
 v="<b>λ = c / f</b>. <b>f ne change pas</b> (imposée par la source) ; <b>c change</b> (dépend du milieu), donc λ aussi."),
dict(t="n", o="§1 Célérités",
 r="Célérité du son dans l'air, l'eau, l'acier ?",
 v="Air <b>340 m/s</b> ; eau <b>1500 m/s</b> ; acier <b>5000 m/s</b> (plus le milieu est rigide, plus c'est rapide)."),
dict(t="n", o="§2 Puissance et intensité",
 r="Puissance et intensité acoustiques : différence ? Intensité en champ direct ?",
 v="<b>P</b> (W) caractérise la <b>source</b> ; <b>I</b> (W/m²) dépend aussi de la <b>distance</b>.<br><b>I = P / (4π r²)</b>."),
dict(t="n", o="§3 Le niveau en décibels",
 r="Formule du niveau sonore ? Valeur de I<sub>0</sub> ?",
 v="<b>L = 10 log(I / I<sub>0</sub>)</b> en dB ; <b>I<sub>0</sub> = 1,0 × 10<sup>−12</sup> W/m²</b> (seuil d'audition)."),
dict(t="n", o="§3 Échelle logarithmique",
 r="+10 dB et +3 dB : que devient l'intensité ?",
 v="<b>+10 dB</b> → intensité <b>× 10</b> ; <b>+3 dB</b> → <b>× 2</b>. Doubler les décibels ne double rien."),
dict(t="n", o="§4.1 Deux sources",
 r="Deux sources identiques fonctionnant ensemble : quel niveau ?",
 v="<b>+3 dB</b>, jamais le double. Formule : L = 10 log(10<sup>L<sub>1</sub>/10</sup> + 10<sup>L<sub>2</sub>/10</sup>)."),
dict(t="n", o="§4.2 La règle des 6 dB",
 r="En champ direct, que fait perdre le doublement de la distance ?",
 v="<b>6 dB</b>. C'est le <b>rapport</b> des distances qui compte, pas leur différence."),
dict(t="n", o="§5 Décibel pondéré A",
 r="Qu'est-ce que le dB(A) ? Pourquoi l'utilise-t-on ?",
 v="Le niveau corrigé de la <b>sensibilité de l'oreille selon la fréquence</b> (les graves sont moins perçus). C'est celui de la <b>réglementation</b>."),
dict(t="n", o="§6 Isoler, absorber",
 r="Que devient l'énergie d'une onde devant une paroi ? Différence entre isoler et absorber ?",
 v="<b>Réfléchie</b>, <b>absorbée</b> (échauffe), <b>transmise</b>.<br>Isoler : réduire ce qui <b>passe</b> ; absorber : réduire ce qui <b>revient</b>."),
dict(t="n", o="§6 Seuils réglementaires",
 r="Seuils réglementaires d'exposition au bruit ?",
 v="<b>80 dB(A)</b> : information, protections mises à disposition.<br><b>85 dB(A)</b> : valeur d'action, port obligatoire.<br><b>87 dB(A)</b> : valeur limite, sous protection."),
dict(t="n", o="§6 L'EPI en dernier",
 r="Dans quel ordre agir contre le bruit ?",
 v="1. <b>Source</b> (silencieux, capotage).<br>2. <b>Trajet</b> (cabine, écrans).<br>3. <b>Opérateur</b> (EPI)."),
# --- méthodes
dict(t="m", o="§4.1 Méthode — Additionner deux niveaux",
 r="Comment additionner deux niveaux sonores ?",
 v="1. Revenir aux intensités : <b>10<sup>L/10</sup></b> (en I<sub>0</sub>).<br>2. <b>Additionner</b>.<br>3. Reprendre <b>10 log</b>.<br>4. Contrôle : deux sources identiques → +3 dB."),
dict(t="m", o="§6 Méthode — Choisir une protection",
 r="Comment choisir une protection auditive ?",
 v="1. Mesurer au poste en <b>dB(A)</b>.<br>2. Niveau sous protection : <b>L − SNR</b>.<br>3. Vérifier <b>&lt; 85 dB(A)</b>.<br>4. Mais <b>&gt; 70 dB(A)</b> pour entendre alarmes et collègues."),
dict(t="m", o="§5 Ce qu'un écart révèle",
 r="Sonomètre : 96 dB en linéaire, 88 dB(A). Que conclure ?",
 v="Écart de 8 dB : bruit <b>riche en graves</b> (moteur diesel), énergétiquement fort mais moins perçu par l'oreille."),
]

# =====================================================================
CARTES["ch15"] = [
dict(t="n", o="§1 Réponse indicielle",
 r="Qu'est-ce que la réponse indicielle ? Où se trouve l'information sur le comportement du système ?",
 v="La sortie enregistrée quand l'entrée subit un <b>échelon</b>. Toute l'information est dans le <b>régime transitoire</b>."),
dict(t="n", o="§1 Transmittance statique",
 r="Définir la transmittance statique K. Dépend-elle de l'amortissement ?",
 v="<b>K = Δs / Δe</b> en régime permanent, avec unité (V/°C…). <b>Non</b> : c'est un contrôle de cohérence entre essais."),
dict(t="n", o="§2 Premier ordre",
 r="Constante de temps d'un premier ordre ? À 3τ ?",
 v="<b>τ</b> : instant où la sortie atteint <b>63 %</b> de sa valeur finale. À <b>3τ</b> : <b>95 %</b>."),
dict(t="n", o="§3.1 Reconnaître l'ordre",
 r="Comment reconnaître un système du second ordre ?",
 v="Un <b>dépassement</b> suffit (un premier ordre n'en a jamais). Sans dépassement : <b>tangente horizontale</b> au départ → second ordre amorti."),
dict(t="n", o="§3.2 Dépassement et temps de réponse",
 r="Formule du dépassement (TSMA) ? Définition du temps de réponse à 5 % ?",
 v="<b>D = (s<sub>max</sub> − s<sub>∞</sub>) / s<sub>∞</sub></b>.<br>t<sub>5%</sub> : depuis l'échelon jusqu'à la <b>dernière sortie</b> de la bande s<sub>∞</sub> ± 5 %."),
dict(t="n", o="§3 Temps de montée et temps de réponse",
 r="Temps de montée et temps de réponse classent-ils les réglages dans le même ordre ?",
 v="<b>Non</b>, souvent en sens inverse : pas de « plus rapide » sans critère choisi."),
dict(t="n", o="§4.1 Schéma fonctionnel",
 r="Éléments d'une boucle fermée ?",
 v="<b>Consigne</b> → <b>comparateur</b> (écart) → <b>correcteur</b> → <b>actionneur</b> → <b>système</b> → sortie ; <b>capteur</b> et chaîne de retour vers le comparateur."),
dict(t="n", o="§4.1 Ce qui distingue les deux montages",
 r="Qu'est-ce qui distingue une boucle fermée d'une boucle ouverte ?",
 v="La présence du <b>capteur</b> et du <b>comparateur</b>."),
dict(t="n", o="§4.2 Intérêt d'un asservissement",
 r="Quel est l'intérêt d'une boucle fermée ? Sa correction est-elle instantanée ?",
 v="Elle <b>compense les perturbations sans les connaître</b> et dépend moins du matériel. <b>Non</b> : il faut un écart pour réagir ; la sortie <b>revient</b> à la consigne."),
dict(t="n", o="§4.3 Jamais meilleur que son capteur",
 r="Que se passe-t-il si le capteur d'un asservissement est faux ?",
 v="La boucle asservit <b>ce qu'on lui donne à mesurer</b> : la sortie réelle reste décalée, sans que rien ne le signale."),
# --- méthodes
dict(t="m", o="§2 Méthode — Déterminer τ",
 r="Comment déterminer τ sur l'enregistrement d'un premier ordre ?",
 v="1. Lire la <b>valeur finale</b> s<sub>∞</sub>.<br>2. Calculer <b>63 %</b>, lire l'instant : <b>τ</b>.<br>3. Vérifier : instant à <b>95 %</b> ÷ 3.<br>4. Les deux concordent (sinon palier non atteint)."),
dict(t="m", o="§3.2 Second ordre",
 r="Comment exploiter la réponse indicielle d'un second ordre ?",
 v="1. Lire s<sub>∞</sub> et s<sub>max</sub>.<br>2. <b>D = (s<sub>max</sub> − s<sub>∞</sub>)/s<sub>∞</sub></b>.<br>3. Tracer la bande ± 5 %.<br>4. t<sub>5%</sub> : <b>dernière sortie</b> de la bande.<br>5. K = Δs/Δe."),
]

# =====================================================================
CARTES["ch16"] = [
dict(t="n", o="§1 La chaîne de mesure",
 r="Quels sont les quatre maillons d'une chaîne de mesure ?",
 v="<b>Capteur</b> (grandeur électrique) → <b>conditionneur</b> (tension exploitable) → <b>convertisseur</b> (nombre) → <b>calculateur</b> (exploite, affiche)."),
dict(t="n", o="§1 Aucun maillon n'améliore le précédent",
 r="Quel maillon fixe la qualité d'une chaîne de mesure ?",
 v="Le <b>maillon le plus faible</b> — presque toujours le <b>capteur</b>. Aucun étage n'améliore le précédent."),
dict(t="n", o="§1.1 Actif ou passif",
 r="Capteur actif et capteur passif : définir et donner des exemples sur un engin.",
 v="<b>Actif</b> : délivre lui-même une tension ou un courant (thermocouple, génératrice tachymétrique, piézo de cliquetis).<br><b>Passif</b> : fait varier R, C ou L, il faut une alimentation (CTN, jauge, potentiomètre)."),
dict(t="n", o="§2 Caractéristique d'un capteur",
 r="Sensibilité, étendue de mesure, linéarité : définir.",
 v="<b>Sensibilité</b> : la pente, <b>avec son unité</b> (V/bar, mV/K…).<br><b>Étendue</b> : plage utilisable.<br><b>Linéarité</b> : écart maximal à la droite, en % de l'étendue."),
dict(t="n", o="§2 Le zéro décalé",
 r="Pourquoi un capteur de pression délivre-t-il 0,50 V à 0 bar ?",
 v="Pour <b>distinguer une pression nulle d'un capteur débranché</b> : 0 V signale une panne."),
dict(t="n", o="§3.1 La CTN",
 r="Loi de la CTN ? Défaut principal ?",
 v="<b>R = R<sub>0</sub> e<sup>β(1/T − 1/T<sub>0</sub>)</sup></b>, T en <b>K</b>. Très sensible mais <b>très non linéaire</b> (R ÷ 30 entre 0 et 100 °C)."),
dict(t="n", o="§3.2 Le diviseur",
 r="Tension de mesure d'un conditionnement par diviseur avec une CTN ?",
 v="<b>V<sub>m</sub> = V<sub>cc</sub> × R<sub>1</sub> / (R<sub>1</sub> + R)</b>. R<sub>1</sub> décide de la plage où la réponse est droite, pas de la qualité de la mesure."),
dict(t="n", o="§4.1 Quantifier",
 r="Quantum d'un convertisseur ? Que rend-il réellement ?",
 v="<b>q = pleine échelle / 2<sup>N</sup></b> (10 bits, 5,00 V : 4,9 mV). Il rend la <b>partie entière de V/q</b> (le numéro de la marche). Un bit de plus divise q par 2."),
dict(t="n", o="§4.2 Résolution et précision",
 r="Différence entre résolution et précision ? Qu'améliore l'ajout de bits ?",
 v="<b>Résolution</b> : plus petit écart distingué, fixée par le <b>convertisseur</b>.<br><b>Précision</b> : écart à la vraie valeur, fixée par le <b>capteur</b>.<br>Ajouter des bits n'améliore que la <b>résolution</b>."),
dict(t="n", o="§5 Échantillonner",
 r="Condition de Shannon ? Que se passe-t-il si elle n'est pas respectée ?",
 v="<b>f<sub>éch</sub> &gt; 2 f<sub>max</sub></b>. Sinon <b>repliement</b> : un autre signal, plus lent, apparaît (120 Hz à 100 Hz → 20 Hz), et rien ne le signale."),
dict(t="n", o="§5 Deux remèdes",
 r="Comment éviter le repliement ?",
 v="1. <b>Filtrer avant de convertir</b> (filtre anti-repliement).<br>2. <b>Échantillonner assez vite</b>.<br>Filtrer après coup ne sert à rien."),
# --- méthodes
dict(t="m", o="§3.2 Méthode — Conditionnement par diviseur",
 r="Comment exploiter un conditionnement par diviseur ?",
 v="1. Calculer R à quelques températures de la plage.<br>2. En déduire V<sub>m</sub>.<br>3. <b>Écarts successifs</b> de V<sub>m</sub> voisins → linéaire.<br>4. Sensibilité de l'ensemble en mV/°C."),
dict(t="m", o="§4.2 Le dixième de degré",
 r="Résolution 0,15 °C, CTN à ± 1,8 °C. L'affichage 80,3 °C est-il justifié ?",
 v="1. Comparer : l'incertitude du capteur est <b>12 fois</b> la résolution.<br>2. La vraie valeur est entre 78,5 et 82,1 °C.<br>3. Le dixième affiché est du <b>bruit</b> : la précision vient du capteur."),
dict(t="m", o="§4.1 Quantifier",
 r="Convertisseur 10 bits, pleine échelle 5,00 V, tension 2,40 V. Quel nombre rend-il ?",
 v="1. q = 5,00/1024 = 4,9 mV.<br>2. V/q = 2,40/4,88 × 10<sup>−3</sup> ≈ 491,5.<br>3. Partie entière : <b>491</b>."),
]

# =====================================================================
CARTES["ch17"] = [
dict(t="n", o="§1 Le réseau triphasé",
 r="Tension simple et tension composée : entre quels conducteurs ? Relation ? Valeurs en France ?",
 v="<b>V</b> : phase-neutre ; <b>U</b> : entre deux phases.<br><b>U = √3 V</b> : 230 V et 400 V."),
dict(t="n", o="§2 Étoile ou triangle",
 r="Quelle tension voit chaque récepteur en étoile ? en triangle ?",
 v="<b>Étoile</b> : la tension simple <b>V</b>.<br><b>Triangle</b> : la tension composée <b>U</b> (√3 fois plus)."),
dict(t="n", o="§2 Lire la plaque",
 r="Que signifie une plaque moteur 230/400 V ?",
 v="<b>Triangle sous 230 V</b> entre phases, <b>étoile sous 400 V</b>. Une erreur triple la puissance ou laisse le moteur sans force : vérifier <b>avant</b> la mise sous tension."),
dict(t="n", o="§3 Les trois puissances",
 r="Puissances active, réactive, apparente : unités, rôles, formules ?",
 v="<b>P</b> (W) : travaille, payée. <b>Q</b> (var) : allers-retours. <b>S</b> (VA) : vue par câbles et disjoncteur.<br><b>S = √3 U I</b> ; P = S cos φ ; Q = S sin φ."),
dict(t="n", o="§3 Facteur de puissance",
 r="Que représente cos φ ? Valeurs typiques ?",
 v="<b>cos φ = P/S</b> : fraction du courant qui travaille. Radiateur : <b>1</b> ; moteur asynchrone en charge : ≈ <b>0,75</b>, bien moins à vide."),
dict(t="n", o="§3 On paie P, on dimensionne sur S",
 r="Pourquoi un mauvais facteur de puissance coûte-t-il cher ?",
 v="On <b>paie P</b>, mais disjoncteur, câbles et échauffement dépendent du courant donc de <b>S</b> : il coûte en <b>installation</b>."),
dict(t="n", o="§5 Le courant et le corps humain",
 r="Qu'est-ce qui est dangereux, la tension ou le courant ? Ordre des effets ?",
 v="Le <b>courant</b> (quelques dizaines de mA suffisent).<br>Perception → contraction → <b>tétanisation</b> → <b>fibrillation cardiaque</b>."),
dict(t="n", o="§6.1 Le différentiel",
 r="Que compare un dispositif différentiel ? Calibre usuel ?",
 v="Le <b>courant aller et le courant retour</b>. Si la différence dépasse <b>30 mA</b>, du courant s'échappe vers la terre : il coupe."),
dict(t="n", o="§6.2 Trois appareils, trois rôles",
 r="Rôles du disjoncteur, du différentiel et de la mise à la terre ?",
 v="<b>Disjoncteur</b> : protège les <b>biens</b> (surintensité, incendie).<br><b>Différentiel</b> : protège les <b>personnes</b>.<br><b>Terre</b> : chemin du courant de défaut, <b>pour que le différentiel le voie</b>."),
dict(t="n", o="§6.3 Consignation",
 r="Quelles sont les étapes de la consignation, dans l'ordre ?",
 v="<b>Séparer</b>, <b>condamner</b>, <b>identifier</b>, <b>vérifier</b> l'absence de tension (VAT, sur place, juste avant de toucher)."),
# --- méthodes
dict(t="m", o="§4 Méthode — Batterie de condensateurs",
 r="Comment dimensionner une batterie de condensateurs pour relever cos φ ?",
 v="1. <b>Q<sub>1</sub> = P tan φ<sub>1</sub></b> (actuel).<br>2. <b>Q<sub>2</sub> = P tan φ<sub>2</sub></b> (visé).<br>3. <b>Q<sub>C</sub> = Q<sub>1</sub> − Q<sub>2</sub></b>.<br>4. Triangle : <b>C = Q<sub>C</sub> / (3 ω U²)</b>.<br>5. Contrôler : P inchangée."),
dict(t="m", o="§3 Les trois puissances",
 r="Moteur : P = 7,5 kW, cos φ = 0,75, réseau 400 V. Comment trouver S et I ?",
 v="1. S = P / cos φ = 7500/0,75 = <b>10 000 VA</b>.<br>2. I = S / (√3 U) = 10 000/693 ≈ <b>14,4 A</b>."),
dict(t="m", o="§2 Lire la plaque",
 r="Moteur 230/400 V à brancher sur un réseau 230/400 V : quel couplage ?",
 v="1. Enroulement = <b>230 V</b>.<br>2. Réseau : U = 400 V entre phases.<br>3. L'enroulement doit voir 230 V = V → <b>étoile</b>."),
]
